use dynamic plugin for side panel and action provider for rhoas
openshift/console pull request #10035
Opened 2021-09-09 13:21 UTC by invincibleJai

**Fixes**: 
https://issues.redhat.com/browse/ODC-5846

Task: https://issues.redhat.com/browse/ODC-6113

**Solution Description**: 

- converts Rhoas kafka connection side panel to use dynamic extensions
- converts Rhoas kafka connection  actions to use dynamic extensions

**Screen shots / Gifs for design review**: 

![image](https://user-images.githubusercontent.com/5129024/132693429-b9aad193-b4c5-4a9d-89c3-ec16be6af835.png)

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2021-09-09 13:22 UTC, invincibleJai commented
/cc @sahil143  @wtrocki

2021-09-09 13:53 UTC, sahil143 commented on frontend/packages/rhoas-plugin/console-extensions.json
> +    }
These should have `RHOAS_FLAG` as well

2021-09-09 13:53 UTC, sahil143 commented on frontend/packages/rhoas-plugin/console-extensions.json
> +        "$codeRef": "rhoasTopologyComponents.getDetailsTabSectionForTopologySideBar"
we can move these under `rhoasTopologySidebar` as well

2021-09-09 13:53 UTC, sahil143 commented on frontend/packages/rhoas-plugin/console-extensions.json
> +        "$codeRef": "rhoasTopologyComponents.getResourceTabSectionForTopologySideBar"
same as above

2021-09-09 13:53 UTC, sahil143 commented on frontend/packages/rhoas-plugin/src/topology/components/kafka-connection-tab-section.tsx
> +  const resource = getResource(element) as KafkaConnection;
```suggestion
  const resource = getResource<KafkaConnection>(element);
```

2021-09-09 13:53 UTC, sahil143 commented on frontend/packages/rhoas-plugin/src/topology/components/kafka-connection-tab-section.tsx
> +  const resource = getResource(element) as KafkaConnection;
same as above

2021-09-09 13:58 UTC, wtrocki commented
Verified with Operator running! Additional verification needed to check if plugin is loaded without operator/flag missing etc.

2021-09-28 06:41 UTC, sahil143 requested changes
@invincibleJai alert is showing after sidepanel is closed and opened again
![Kapture 2021-09-28 at 12 06 45](https://user-images.githubusercontent.com/9278015/135035859-384349b5-afd4-4af9-8c2c-cba34b6b2085.gif)

2021-09-28 06:43 UTC, sahil143 commented
getting i18n error in console
![image](https://user-images.githubusercontent.com/9278015/135036383-b8cf54a7-fadb-4648-bdc6-abc41e87057b.png)

2021-09-29 09:02 UTC, sahil143 approved these changes
/lgtm
/label qe-approved

verified locally, works as expected

2021-09-29 09:43 UTC, invincibleJai commented
Propagate from epic:
/label docs-approved
/label px-approved

2021-09-29 11:29 UTC, merged