Bug 1928285: Display loading message when PVs are being provisioned.
openshift/console pull request #10348
Opened 2021-10-28 09:49 UTC by rexagod

Show a loading message when PVs are being provisioned to the selected
nodes.
***
### Loading message when PVs are being provisioned.
![2021-10-28-145105_2185x650_scrot](https://user-images.githubusercontent.com/33557095/139231670-1c8d7571-872e-48c0-a65b-351d99a141c1.png)
***
### Error message after PV provisioning fails.
![2021-10-28-151146_2175x586_scrot](https://user-images.githubusercontent.com/33557095/139231661-bff519f4-dc0f-4d30-92b5-87cbda8e7fd7.png)

2021-11-02 10:28 UTC, rexagod commented on frontend/packages/ceph-storage-plugin/src/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-and-nodes-step.tsx
> +        'ceph-storage-plugin~Failed to provision persistent volumes on the selected nodes. Please try again.',
Would "Error while loading PersistentVolumes" be okay?

2021-11-02 10:41 UTC, rexagod commented on frontend/packages/ceph-storage-plugin/src/components/create-storage-system/create-storage-system-steps/capacity-and-nodes-step/capacity-and-nodes-step.tsx
> +        'ceph-storage-plugin~Failed to provision persistent volumes on the selected nodes. Please try again.',
Is "Error while loading PersistentVolumes" okay? https://github.com/openshift/console/pull/10348/files#diff-d03ec5c051a2297edf66447c36fbcd791d09905439c58b9ab98691191a3c35a6R189

2021-11-02 10:51 UTC, rexagod commented
Removed the warning message on the loading screen.

> 1. PV getting provisioned screen is shown and then eventually loaded PV screen (cap and nodes step)

Verified.

![2021-11-02-155719_2560x1440_scrot](https://user-images.githubusercontent.com/33557095/139832333-85e15802-8361-43c7-8969-f79fcd6f6c73.png)
![2021-11-02-155458_2560x1440_scrot](https://user-images.githubusercontent.com/33557095/139832339-d3ae313c-cc2c-47b2-89cc-597d049a1cce.png)


> 2. PV getting provisioned -> close wizard -> come to wizard again -> choose existing sc-> choose just created sc -> PV getting provisioned screen is shown and then eventually loaded PVs

Partially verified.

![2021-11-02-162229_2560x1440_scrot](https://user-images.githubusercontent.com/33557095/139833255-f85a8165-d407-4d05-bb69-1bf760687424.png)

2021-11-02 15:17 UTC, afreen23 requested changes
Run yarn i18n.

2021-11-03 09:44 UTC, rexagod commented
/test e2e-gcp-console

2021-11-03 12:59 UTC, afreen23 approved these changes
/lgtm

2021-11-04 01:21 UTC, merged