Bug 1998378: Use reference to extension models instead of kind
openshift/console pull request #10369
Opened 2021-11-01 14:26 UTC by yaacov

Screenshots:
Before:
![screenshot-localhost_9000-2021 11 01-16_07_16](https://user-images.githubusercontent.com/2181522/139687495-8cbf4a13-6b01-41d2-9056-522bc4cb0b88.png)

After:
![screenshot-localhost_9000-2021 11 01-15_59_06](https://user-images.githubusercontent.com/2181522/139687507-ed857d1f-6613-4b25-9e1a-db5664432e1c.png)

2021-11-01 14:27 UTC, yaacov commented
@glekner @avivtur please review

2021-11-01 14:42 UTC, avivtur commented
/lgtm

2021-11-01 15:14 UTC, glekner requested changes

2021-11-01 15:14 UTC, glekner commented on frontend/packages/kubevirt-plugin/src/components/dashboards-page/overview-dashboard/health.ts
> +    kind: referenceForExtensionModel({
you can replace all of these with `kubevirtReferenceForModel`

e.g. `kubevirtReferenceForModel(VirtualMachineInstanceModel)`

2021-11-01 15:43 UTC, glekner commented
/lgtm

2021-11-02 13:46 UTC, yaacov commented
/retest

2021-11-02 18:41 UTC, pcbailey commented
/lgtm

2021-11-02 22:57 UTC, merged