Bug 2018264: Delete Export button doesn't work in topology sidebar (general issue with unknown CSV?)
openshift/console pull request #10457
Opened 2021-11-15 05:59 UTC by yozaam

**Fixes**: 

https://bugzilla.redhat.com/show_bug.cgi?id=2018264
https://issues.redhat.com/browse/OCPBUGSM-36630

**Analysis / Root cause**: 

`kind` was undefined as it was passed in the props as `kindObj` 

**Solution Description**: 

If `kind` is undefined, then search for `kindObj` and also double check if `kind` is not undefined when accessing its property label

**Screen shots / Gifs for design review**: 

![deleteModalExport](https://user-images.githubusercontent.com/20089340/141730099-067c45cd-3914-49ba-9aec-378a91e9a87a.gif)

**Unit test coverage report**: 

**Test setup:**

Steps to Reproduce:
1. Open Operator Hub and install the "Primer" GitOps Operator
2. Switch to developer perspective
3. Import at least one Application to enable the Export button in topology
4. If not opened yet, open the topology, and click the "Export Application" button
5. Wait until the export finishs and a new Deployment "primer-export-primer" was shown
6. Click on surrounding CSV Export "Primer" to open the sidebar
7. Click in the topology sidebar on Actions > Delete Export

**Browser conformance**: 

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2021-11-15 17:32 UTC, yozaam commented
/retest-required

2021-11-16 16:23 UTC, jerolimov requested changes
First of all, your PR works fine. :smile: But the new prop type confuses me.

This is not what the DeleteModalProps "allows". `kind` is not optional, it should be defined. And if I search for `deleteModal({` to get all code areas that want to open the delete modal, there is the only one that doesn't align with the other one.

(I believe) You can also fix this issue by changing `csv-actions.ts` to

```tsx
        deleteModal({
          kind: kindObj,
          resource,
          // ...
```

Similar to the other  `deleteModal({` calls.

Can you please check if the other changes here are then required if this caller aka the root cause is fixed? Maybe an additional null check is still worth it!

---

After this fix, I have still a general concern with the old code. This issue is introduced because the `deleteModal` AND ALL OTHER functions exported in `public/components/modals/index.ts` don't define an argument type.

It would be cool if you can check if build, tests, etc. works fine if you define the `deleteModal` like this:

```tsx
export const deleteModal = (props: DeleteModalProps) =>
  import('./delete-modal' /* webpackChunkName: "delete-modal" */).then((m) => m.deleteModal(props));
```

I have just quick checked this and notice multiple errors after adding `DeleteModalProps`

* csv-actions.ts doesn't set the `kind` prop as mentioned above.
* Some callers (csv-actions.ts and packages/operator-lifecycle-manager/src/components/operand/index.tsx) submits a `namespace` prop to the deleteModal function which is completely ignored! I think we can drop it from the caller code.
* DeleteModalProps `message` prop is optional, only one caller submits this prop.
* Some arguments are still missing, that happen because `DeleteModalProps` includes also `& ModalComponentProps & HandlePromiseProps`. For this, I would recommend just defining the `DeleteModalProps` with its own custom props.

```tsx
export type DeleteModalProps = {
  kind: K8sKind;
  kindObj?: K8sKind;
  resource: any;
  close?: () => void;
  redirectTo?: any;
  message?: JSX.Element;
  cancel?: () => void;
  btnText?: string;
};
```

And then using these props in the function call as union type, like this:

```tsx
const DeleteModal = withHandlePromise((props: DeleteModalProps & HandlePromiseProps) => {
```

ModalComponentProps is not used in this function, so I believe we can remove the import and ignore it as well.

---

Sorry, much longer than expected for an already working PR :+1: But I really think we should fix this without a new prop (which uses just another name) and I also would like to improve our TS strongly-type check quality here. Wdyt? :)

I also would like to create a tech dept story for the other missing modal props if this works fine for the delete modal.

2021-11-17 08:26 UTC, yozaam commented
Thank you @jerolimov 
 made the changes

2021-11-17 15:15 UTC, jerolimov approved these changes
Tested this locally and the code works fine for the broken as well as other known resources.

/lgtm
/approve

2021-11-17 15:16 UTC, jerolimov commented
/retest

2021-11-19 08:39 UTC, merged