Bug 2024262 - Sample catalog is not displayed when one API call to the backend fails
openshift/console pull request #10569
Opened 2021-11-29 10:04 UTC by gruselhaus

**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2024262
https://issues.redhat.com/browse/OCPBUGSM-37299

**Analysis / Root cause**: 
On the samples page when you try to add an application from a sample the catalog gets not rendered when one API Call fails but the catalog placeholder is rendered instead. I assume that there are multiple sources for those entries on the samples page.

**Solution Description**: 

As seen in the changes of this PR I removed the `loaded` check. I removed this because if a call fails the provider does not go into the `loaded=true` state. The logic wanted all providers to load successfully which was not the case when a call failed.

## Before
<img width="1393" alt="Bildschirmfoto 2021-11-29 um 10 57 49" src="https://user-images.githubusercontent.com/33380107/143846733-97fec538-799f-448f-961d-340f5ef51df0.png">

## After
<img width="1392" alt="Bildschirmfoto 2021-11-29 um 10 56 37" src="https://user-images.githubusercontent.com/33380107/143846763-03e10dd9-1ea1-4d03-a642-4bad99eb34eb.png">

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [x] Safari
- [ ] Edge

2021-11-29 10:05 UTC, gruselhaus commented
/bugzilla refresh

2021-11-29 10:05 UTC, gruselhaus commented
/bugzilla refresh

2021-12-07 12:54 UTC, jeff-phillips-18 commented
/lgtm

would be nice to show those services that loaded when only one failed and notify the user of any failures.

2021-12-07 13:39 UTC, jerolimov requested changes
> would be nice to show those services that loaded when only one failed and notify the user of any failures.

+1. This change shows an error but doesn't help the user to get the other samples (or other catalog entries). We should always expect that 1 of n calls can fail. Maybe it's possible to show the `LoadError` anyway, but more important is that the user see the non-failing samples.

Can you also please check the "Getting Started" section on the add page. It has the same issue, the placeholders shows forever when the Devfile samples call fail:

![image](https://user-images.githubusercontent.com/139310/145038800-9cd486c2-5d0d-44ac-b4a0-3fdd9e8c202c.png)

2021-12-09 12:38 UTC, gruselhaus commented
/test e2e-gcp-console

2021-12-09 19:54 UTC, gruselhaus commented
/bugzilla refresh

2021-12-09 20:02 UTC, jerolimov requested changes
I really like the direction. :+1: I have added some small improvement ideas. And I'm also looking forward to see what @jeff-phillips-18 is thinking on this change. Nico updated already the screenshots in the first comment!

Unluckily there are no tests yet for `status-box.tsx`, but can you please add some for these highly shared components?

2021-12-09 20:13 UTC, jerolimov commented
@openshift/team-devconsole-ux @beaumorley @serenamarie125 (and fyi @rohitkrai03 @debsmita1 @jeff-phillips-18)

Nico, our new intern if you doesn't meet him yet, fixed an issue when one or more of X network calls are failing while loading the catalog. The exact issue depends maybe also on the loader, the error, etc. But this happens. :)

In this case, the catalog never finishes loading and shows the placeholder boxes forever.

This PR doesn't just fix a loading issue, it changes the UX (that's the reason I want to have your ack on this) so that the catalog shows the rest of the data if some network calls fail and others load fine.

**TL;DR;** :smile:  See screenshots in the first comment. Are you fine with the new PF alert box (and its content) when one, but not all network calls in the catalog fails?

> Only 1 of 2 resources loaded. Some data might not be displayed.

2021-12-09 20:34 UTC, gruselhaus commented on frontend/packages/console-shared/src/components/catalog/service/CatalogServiceProvider.tsx
> +        );
Yeah, this makes sense. Thanks 🎉

2021-12-09 20:44 UTC, gruselhaus commented
/retest-required

2021-12-09 20:58 UTC, gruselhaus commented
/retest-required

2021-12-09 23:28 UTC, gruselhaus commented
/test e2e-gcp-console

2021-12-10 10:58 UTC, gruselhaus commented on frontend/packages/console-shared/src/components/catalog/service/CatalogServiceProvider.tsx
> +        );
Resolved.

2021-12-10 11:35 UTC, gruselhaus commented
I implemented the feedback from @jerolimov and this PR is ready to receive more comments now 🎉

2021-12-10 18:57 UTC, jerolimov requested changes
😏

2021-12-10 18:57 UTC, jerolimov commented on frontend/public/components/utils/__tests__/status-box.spec.tsx
> +    getByText('Timed out fetching new data. The data below is stale.');
```suggestion
    getByText('Timed out fetching new data. The data below is stale.');
    getByText('my-children');
```

2021-12-10 18:57 UTC, jerolimov commented on frontend/public/components/utils/__tests__/status-box.spec.tsx
> +  it('should render a patternfly alert together with its children when an IncomleteDataError occured', () => {
```suggestion
  it('should render a patternfly alert together with its children when an IncompleteDataError occured', () => {
```

2021-12-10 18:57 UTC, jerolimov commented on frontend/public/components/utils/__tests__/status-box.spec.tsx
> +  it("should render its children when not loaded and there's no error", () => {
```suggestion
  it("should render its children when loaded and there's no error", () => {
```

2021-12-13 22:25 UTC, gruselhaus commented
I've implemented @serenamarie125's feedback. Here's the updated screenshot
<img width="1693" alt="Bildschirmfoto 2021-12-13 um 23 12 26" src="https://user-images.githubusercontent.com/33380107/145898703-74951c52-d358-40b9-8df1-4ac026e4df1a.png">

2021-12-14 23:47 UTC, gruselhaus commented
/retest

2021-12-15 00:52 UTC, gruselhaus commented
/retest

2021-12-15 11:39 UTC, gruselhaus commented
/retest

2021-12-15 19:25 UTC, gruselhaus commented
<img width="1749" alt="Bildschirmfoto 2021-12-15 um 20 18 13" src="https://user-images.githubusercontent.com/33380107/146251779-b0c7e73e-0173-4ac2-9fd1-a1ce9e3a1039.png">

2021-12-15 22:38 UTC, gruselhaus commented
/retest

2021-12-16 09:34 UTC, gruselhaus commented
/retest

2021-12-16 10:30 UTC, gruselhaus commented
/bugzilla refresh

2021-12-16 11:23 UTC, jerolimov approved these changes
Tested this via blocking some network calls in chrome dev tools.

Works very well :+1: 

Esp. thanks for all these new tests. :tada: 

/lgtm
/approved
/woof

2021-12-16 12:21 UTC, gruselhaus commented
retest

2021-12-16 14:58 UTC, gruselhaus commented
/hold

2021-12-16 19:25 UTC, gruselhaus commented
/hold cancel

2021-12-16 19:25 UTC, gruselhaus commented
/retest

2021-12-16 23:01 UTC, gruselhaus commented
/retest

2021-12-17 13:33 UTC, jerolimov commented
/lgtm

2021-12-17 20:16 UTC, merged

2022-05-03 22:28 UTC, jerolimov commented
A customer reports a similar issue here https://bugzilla.redhat.com/show_bug.cgi?id=2068203, so I want to check if we can backport this fix

/cherry-pick release-4.9