Add Support information in the event source catalog side panel
openshift/console pull request #10585
Opened 2021-11-30 16:30 UTC by vikram-raj

**Story:** https://issues.redhat.com/browse/ODC-6439

**Descriptions:** 
Add information about support on catalog side panel under "Support" Section

**GIF:**
![Kapture 2021-11-30 at 21 58 19](https://user-images.githubusercontent.com/2561818/144087412-976b6473-7969-45fe-8847-9ee1d9fc59c3.gif)

2021-11-30 16:30 UTC, vikram-raj commented
/label feature

2021-11-30 16:31 UTC, vikram-raj commented
/cc @sahil143

2021-11-30 16:48 UTC, sahil143 requested changes

2021-11-30 16:48 UTC, sahil143 commented on frontend/packages/knative-plugin/src/catalog/utils.ts
> +      return 'Community';
I think we would need to translate these.

2021-12-02 15:47 UTC, karthikjeeyar reviewed
Overall looks good, I have added few nits. It would be helpful if you can add a sample Kamlet CR in the PR description.

2021-12-02 15:47 UTC, karthikjeeyar commented on frontend/packages/knative-plugin/src/catalog/utils.ts
> +export const getEventSourceSupport = (item: K8sResourceKind, t: TFunction) => {
We could avoid passing `t: TFunction` as a second argument and straight away import and use i18next.t
i.e i18next.t('knative-plugin~Tech Preview')

2021-12-02 15:47 UTC, karthikjeeyar commented on frontend/packages/knative-plugin/src/catalog/__tests__/utils.spec.ts
> +  it('should return Supported support', () => {
```suggestion
  it('should return Tech Preview support', () => {
```

2021-12-02 15:47 UTC, karthikjeeyar commented on frontend/packages/knative-plugin/src/catalog/__tests__/utils.spec.ts
> +  it('should return Supported support', () => {
```suggestion
  it('should return Community support', () => {
```

2021-12-02 15:47 UTC, karthikjeeyar commented on frontend/packages/knative-plugin/src/catalog/__tests__/utils.spec.ts
> +  it('should return Community support', () => {
nit
```suggestion
  it('should return Community support if the label is not present', () => {
```

2021-12-08 11:53 UTC, debsmita1 requested changes

2021-12-08 11:53 UTC, debsmita1 commented on frontend/packages/knative-plugin/src/catalog/__tests__/utils.spec.ts
> +  it('should return Supported support', () => {
```suggestion
  it('should return `Supported` support type', () => {
```

2021-12-08 11:54 UTC, debsmita1 commented
verified the changes locally, looks good to me

2021-12-08 13:06 UTC, vikram-raj commented
Propagate from epic:
/label docs-approved
/label px-approved

2021-12-08 14:02 UTC, debsmita1 commented
/lgtm

2021-12-08 14:33 UTC, rohitkrai03 requested changes
@vikram-raj Is this field for support information needed for all catalog items? If not then there's a way to send extra details panel information using `details` property of `CatalogItem`. Check helm catalog items how it is sending extra information to details panel properties. That should solve this issue without introducing a new property to CatalogItem.

2021-12-09 09:03 UTC, vikram-raj commented
@rohitkrai03 I thought the same to make use of `details` property. But the requirement is a bit different here, currently, we have `Support` property but we can only add a link using `supportURL` property. But in this story, we need plain text under `Support`. And if I make use of the `details` property then we have a duplicate entry for `Support` title.

2021-12-13 12:06 UTC, rohitkrai03 commented
> @rohitkrai03 I thought the same to make use of `details` property. But the requirement is a bit different here, currently, we have `Support` property but we can only add a link using `supportURL` property. But in this story, we need plain text under `Support`. And if I make use of the `details` property then we have a duplicate entry for `Support` title.

@vikram-raj You can send any custom detail property for event sources only. We do that for helm charts. It could be simple string, url or even a react node. SupportURL is something that is supported by the catalog by default but the custom properties can be used for anything else.

2021-12-14 13:49 UTC, vikram-raj commented
@rohitkrai03 Updated the PR, PTAL again.

2021-12-14 17:56 UTC, rohitkrai03 approved these changes
/approve

2021-12-15 07:48 UTC, karthikjeeyar commented
/lgtm

2021-12-16 12:06 UTC, karthikjeeyar commented
/label qe-approved

2021-12-16 12:43 UTC, jerolimov commented
> /label qe-approved

Damn. I have done this at the same moment. qe-approved +1 :)

2021-12-16 14:20 UTC, merged