Bug 2033044: Shift invalid devfile alert down
openshift/console pull request #10688
Opened 2021-12-17 15:26 UTC by rottencandy

**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-38513

**Analysis / Root cause**: 
The "edit strategy" button is shifted upwards.

**Solution Description**: 
Shift invalid devfile alert down to offset the overlap.

**Screen shots / Gifs for design review**: 
![0](https://user-images.githubusercontent.com/20013884/146567528-2df724fd-7777-44b0-bab7-0d0815ea1103.png)

**Unit test coverage report**: 
(Unchanged)

**Test setup:**
Use a repo with multiple an invalid devfile and multiple import strategies, eg. https://github.com/rottencandy/devfile-python-invalid

**Browser conformance**: 

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

/kind bug

2021-12-17 15:31 UTC, rottencandy commented
/cc @divyanshiGupta

2021-12-22 08:01 UTC, rottencandy commented
/bugzilla refresh

2021-12-28 09:25 UTC, divyanshiGupta commented
/lgtm

2021-12-28 09:25 UTC, divyanshiGupta approved these changes

2021-12-28 10:52 UTC, rottencandy commented
/cc @rohitkrai03

2021-12-28 15:54 UTC, rohitkrai03 requested changes
@rottencandy Can you also add some margin at the bottom? And maybe it makes sense to keep the alert only half width similar to the one above.

2021-12-29 07:25 UTC, rottencandy commented
@rohitkrai03 updated.
![0](https://user-images.githubusercontent.com/20013884/147637408-c8caaafa-73f4-486a-aadc-55125b5480a7.png)

2021-12-29 16:40 UTC, rohitkrai03 approved these changes
/lgtm
/approve

2021-12-29 19:54 UTC, merged

2022-01-04 09:12 UTC, rottencandy commented
/cherrypick release-4.9