Show binding secret in service binding sidebar
openshift/console pull request #10683
Opened 2021-12-16 17:59 UTC by divyanshiGupta

**Fixes:** https://issues.redhat.com/browse/ODC-6449

**Description:**
In this PR we have added the functionality to show binding secret in service binding sidebar's resource tab when the user clicks on service binding connector in topology view.

**Demo:**

https://user-images.githubusercontent.com/20724543/146423915-eaa98a21-ae61-4e5f-81d8-2c8753eabbe3.mov

/kind feature

2021-12-16 17:59 UTC, divyanshiGupta commented
cc: @serenamarie125 @beaumorley

2021-12-17 11:14 UTC, debsmita1 requested changes

2021-12-17 11:14 UTC, debsmita1 commented on frontend/packages/topology/src/components/side-bar/TopologyEdgeResourcesPanel.tsx
> +                kind={referenceForModel(SecretModel)}
can you use `referenceForGroupVersionKind` instead of  `referenceForModel` ?

2021-12-17 11:15 UTC, debsmita1 commented
can you please add some tests for `TopologyEdgeResourcesPanel` component ?

2021-12-23 16:59 UTC, debsmita1 commented
Thank you adding the tests
/lgtm
I will verify this on a cluster and add he qe-approved label

2021-12-27 07:17 UTC, debsmita1 commented
verified this on a cluster
/label qe-approved

2021-12-27 09:22 UTC, rohitkrai03 approved these changes
/approve

2021-12-27 09:22 UTC, rohitkrai03 commented
/label docs-approved
/label px-approved

2021-12-27 23:30 UTC, merged