Migrate KebabOption to the SDK
openshift/console pull request #10792
Opened 2022-01-07 14:05 UTC by fhlavac

Migrate KebabOption component to the SDK as a part of ListPage migration effort
https://issues.redhat.com/browse/HAC-311

@andrewballantyne @invincibleJai

2022-01-07 14:43 UTC, andrewballantyne commented
/cc

2022-01-07 20:34 UTC, fhlavac commented
/retest

2022-01-10 11:49 UTC, invincibleJai commented
/cc

2022-01-10 11:58 UTC, invincibleJai requested changes
this PR just migrated one type `KebabOption`, this doesn't look like a big change could have been incorporated into original PR as well.

2022-01-10 11:58 UTC, invincibleJai commented on frontend/public/components/utils/kebab.tsx
> +export { KebabOption } from '@console/dynamic-plugin-sdk';
Duplicate imports `KebabOption`

2022-01-10 11:58 UTC, invincibleJai commented on frontend/packages/console-dynamic-plugin-sdk/src/app/components/utils/kebab.tsx
> +import * as React from 'react';
do we need this?

2022-01-10 12:01 UTC, invincibleJai commented on frontend/packages/console-dynamic-plugin-sdk/src/app/components/utils/kebab.tsx
> +export type KebabOption = {
if this is just one type, then we don't need to have `kebab.tsx` here, we do have `console-types.ts` and `common-types.ts`

2022-01-10 12:11 UTC, invincibleJai commented on frontend/public/components/utils/kebab.tsx
> +export { KebabOption } from '@console/dynamic-plugin-sdk';
ah it's export, now issues

2022-01-10 12:33 UTC, closed without merging

2022-01-10 12:34 UTC, fhlavac commented
Closing this and moving the changes to https://github.com/openshift/console/pull/10515