Bug 2033098: Conjunction in the ProgressiveListFooter is now translatable
openshift/console pull request #10790
Opened 2022-01-07 12:41 UTC by gruselhaus

**Fixes**: 
[BZ2033098](https://issues.redhat.com/browse/OCPBUGSM-38517)

**Analysis / Root cause**: 
In https://github.com/openshift/console/blob/master/frontend/packages/dev-console/src/components/progressive-list/ProgressiveListFooter.tsx#L22-L29 we use an approach that does not allow the rendered text to be translated.

**Expected results**: 
The text should be translatable. We should use the internationalization API provided by the browser. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat.

**Screen shots / Gifs for design review**: 
## English
<img width="684" alt="english" src="https://user-images.githubusercontent.com/33380107/148545476-83cf964c-5799-445f-890a-98e2141260b5.png">

## Mandarin
<img width="421" alt="chinese" src="https://user-images.githubusercontent.com/33380107/148545466-53514bee-da27-48f2-8a1b-a599ed056af0.png">

## Korean
<img width="538" alt="korean" src="https://user-images.githubusercontent.com/33380107/148545470-e9eb4787-0356-40a5-9a49-fe92e0e48fb1.png">

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [x] Safari
- [ ] Edge

2022-01-07 15:20 UTC, jerolimov commented
/cc
/assign

2022-01-12 18:59 UTC, jerolimov requested changes
Unfortunately, this breaks the option to click on one of the adv. list items. Looks like a rerender loop, can you please check or ping me if we should take a look together.

2022-01-12 20:28 UTC, gruselhaus commented
Thanks @jerolimov 🎉 I'll take a deeper look into this 👍

2022-01-19 07:51 UTC, jerolimov commented on frontend/packages/dev-console/src/components/import/advanced/AdvancedSection.tsx
> +          Click on the names to access advanced options for{' '}
When using this string with the space included, the i18n tools export can export the same string for all three cases.

```suggestion
          {'Click on the names to access advanced options for '}
```

2022-01-19 07:54 UTC, jerolimov commented on frontend/packages/dev-console/src/components/buildconfig/BuildConfigFormEditor.tsx
> +const List: React.FC<{ namespace: string }> = ({ namespace }) => {
In both other components you reused the parent component props. Not required, but for consistency you can do this here as well

```suggestion
const List: React.FC<BuildConfigFormEditorProps> = ({ namespace }) => {
```

2022-01-19 23:50 UTC, jerolimov approved these changes
Works really well now :+1:  Thanks again for the extra round and cleaning up the components.

/lgtm
/approve

2022-01-20 10:25 UTC, merged