Bug 2011368: fix PipelineRun visualization tooltip to show duration
openshift/console pull request #10806
Opened 2022-01-10 17:45 UTC by debsmita1

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2011368

**Root analysis:**
Tooltip for tasks in pipeline visualization shows when the task ran instead of how long it ran.

**Solution description:**
- pipeline run duration now shows how long the tasks ran
- the duration is shown for tasks that have terminated

**Screenshot:**
![Screenshot from 2022-01-10 17-27-51](https://user-images.githubusercontent.com/22490998/148812729-bc69c443-ec1f-4788-8b5e-5d22c23cd619.png)
![Screenshot from 2022-01-10 17-10-10](https://user-images.githubusercontent.com/22490998/148812738-0591a7b0-8e31-4fa7-9158-f0776a20ff3f.png)
![Screenshot from 2022-01-10 17-04-46](https://user-images.githubusercontent.com/22490998/148812750-a76cfcf5-b53d-4373-9b52-4d175494a557.png)
![pr](https://user-images.githubusercontent.com/22490998/148813306-6cfdfc36-a523-4d61-af9d-5b125d8cd7b0.png)

2022-01-10 17:45 UTC, debsmita1 commented
/kind bug

2022-01-10 17:46 UTC, debsmita1 commented
/assign @karthikjeeyar 
/assign @jerolimov

2022-01-12 15:14 UTC, debsmita1 commented
/cc @serenamarie125 
/cc @siamaksade

2022-01-12 19:55 UTC, jerolimov requested changes
Hey, nice PR. :+1:

Unluckily the [Intl.RelativeTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat) doesn't match our requirements here.

Also if we have a translation for the "hour(s)" it's not perfect, but I think the old version was not translated at all. So this is also a win here.

But I would suggest showing the duration also if the step or pipeline is still running ("running since"). Everything else is fine from my side.

2022-01-12 19:55 UTC, jerolimov commented on frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/pipeline-metrics-utils.ts
> +import i18n from '@console/internal/i18n';
There is already an import `import i18next from 'i18next';`, all other translation code here uses `i18next.t(`, could we reuse this here as well?

2022-01-12 19:55 UTC, jerolimov commented on frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/pipeline-metrics-utils.ts
> +export const getDuration = (seconds: number, list?: boolean): string => {
I would suggest a name that is independent of the use case "list" or "detail page" and use a more generic term like "short" or "long" here. Wdyt?

```suggestion
export const getDuration = (seconds: number, long: boolean): string => {
```

2022-01-12 19:55 UTC, jerolimov commented on frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/pipeline-step-utils.ts
>    }
We should also show a duration if the pipeline step is running. This gives the user a creat indicator if its need 10%, 50% or 90% complete.

```suggestion
  if (matchingStep.terminated) {
    return calculateDuration(matchingStep.terminated.startedAt, matchingStep.terminated.finishedAt);
  }
  if (matchingStep.running) {
    return calculateDuration(matchingStep.running.startedAt, new Date() /* or make the second parameter optional and do this in calcDuration? */);
  }
```

2022-01-12 19:55 UTC, jerolimov commented on frontend/packages/pipelines-plugin/src/utils/pipeline-utils.ts
> +export const calculateDuration = (startTime: string, completionTime: string, list?: boolean) => {
To calculate a duration without an end date it's maybe easier to switch to Date here and then parse the strings in calling functions? But that's not required.

```suggestion
export const calculateDuration = (startTime: Date, endTime: Date, long: boolean) => {
```

2022-01-13 17:34 UTC, jerolimov reviewed
Looks good to me! :+1: Would like that @karthikjeeyar to add lgtm as well. :)

/approve

2022-01-13 17:34 UTC, jerolimov approved these changes

2022-01-13 17:38 UTC, jerolimov commented
/retest

2022-01-17 13:43 UTC, karthikjeeyar commented
Thanks @debsmita1 for this PR, duration field now shows correct representation of the data.
/lgtm

2022-01-17 13:59 UTC, jerolimov commented
/retest

2022-01-18 07:20 UTC, merged