Remove tech preview badge for web terminal
openshift/console pull request #11012
Opened 2022-02-08 19:09 UTC by vikram-raj

**Fixes:** https://issues.redhat.com/browse/OCPBUGSM-40405

**Descriptions:**
Remove Tech preview badge from web terminal drawer.

**Screenshot:**
![image](https://user-images.githubusercontent.com/2561818/153057681-19621a2f-7ae1-454c-a9ff-f1e2ea5cb3e5.png)

2022-02-09 06:35 UTC, sahil143 requested changes
@vikram-raj Please remove the badge from `CloudShellTab.tsx` as well.
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/9278015/153134825-671a2ca1-0bd3-40a3-aca9-804c755306a1.png">

2022-02-09 08:14 UTC, vikram-raj commented
> @vikram-raj Please remove the badge from `CloudShellTab.tsx` as well.

Removed the badge from the `Terminal` page as well.

2022-02-14 12:09 UTC, sahil143 approved these changes
/lgtm

verified works as expected

2022-02-14 12:53 UTC, invincibleJai commented
/approve

2022-02-14 18:42 UTC, merged

2022-03-10 16:36 UTC, christianvogt commented
/cherry-pick release-4.10