[WIP] service binding discoverability labels in dev catalog
openshift/console pull request #11035
Opened 2022-02-10 17:05 UTC by christianvogt

POC for https://issues.redhat.com/browse/ODC-6467

Enhance the dev catalog extensions to allow for contributing extra metadata to other catalog item contributions.

Operator backed services are contributed to the dev catalog by OLM.
Service binding will eventually become it's own plugin.

Created a new extension `console.catalog/item-metadata` which would allow SB to enhance the CSV catalog items by adding a `bindable` label. 

New metadata extensions allow for addition of `tags`, `attributes`, and `labels` to catalog items.

Added labels to quick search.

TODO
Confirm labels and filters with UX.

**Screen shots / Gifs for design review**: 

![image](https://user-images.githubusercontent.com/14068621/153457668-5831b8f5-3e6e-44d9-b9f4-6e605e1e88e0.png)

![image](https://user-images.githubusercontent.com/14068621/153280308-eafad2cf-ad7d-4972-a741-c411b0165928.png)

![image](https://user-images.githubusercontent.com/14068621/153281377-9e57f906-0fc2-449a-b584-b111bcfdebab.png)

**Unit test coverage report**: 

**Test setup:**

**Browser conformance**: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [x] Edge

cc @serenamarie125

2022-02-15 20:16 UTC, christianvogt commented on frontend/packages/dev-console/src/components/catalog/providers/useBindableItemMetadataProvider.ts
> +    fetchBindableServices()
TODO use a watcher instead of `k8sGet`

2022-02-24 11:37 UTC, divyanshiGupta commented
@beaumorley can you PTAL at this PR and approve if the labels and filters looks good to you?

2022-02-24 11:41 UTC, divyanshiGupta commented
@christianvogt can you add a few unit tests and fix the ones that are failing? Also please remove WIP.

2022-02-24 12:15 UTC, divyanshiGupta commented
Created a followup story https://issues.redhat.com/browse/ODC-6491 for the remaining todos.

2022-02-25 10:35 UTC, divyanshiGupta requested changes
@christianvogt code looks good to me and I also ran it locally and it works as expected. Apart from that I think there is 1 issue that is when there are no bindable services the filters on the sidepanel are not shown
<img width="1784" alt="Screenshot 2022-02-25 at 4 00 29 PM" src="https://user-images.githubusercontent.com/20724543/155700331-20be77ff-fcd7-40b6-a921-1f42c523b858.png">
IMO the filters should be shown so that the user knows that there are no bindable services at the moment.

cc: @beaumorley 

WDYT?

2022-02-25 10:36 UTC, divyanshiGupta commented
/retitle service binding discoverability labels in dev catalog

2022-02-25 16:23 UTC, christianvogt commented
@divyanshiGupta the filter mechanism is same across all catalog pages. ie if all items match a single filter then that filter is not shown.

If @beaumorley wants to change this, I suggest creating a separate issue to track this.

2022-02-25 17:06 UTC, divyanshiGupta commented
> @divyanshiGupta the filter mechanism is same across all catalog pages. ie if all items match a single filter then that filter is not shown.
> 
> If @beaumorley wants to change this, I suggest creating a separate issue to track this. But this was the decision made by UX at that time of implementing filters.

@christianvogt Thanks for clarifying. Will create another issue if required.

2022-02-25 17:07 UTC, divyanshiGupta commented
/retest

2022-03-01 22:14 UTC, christianvogt commented
Addressed comments and added tests.
Remainder of TODOs to be completed as followup work.

2022-03-02 10:14 UTC, divyanshiGupta commented
/retest

2022-03-03 12:04 UTC, divyanshiGupta approved these changes
Tested the PR and it works as expected.
/lgtm

2022-03-03 12:08 UTC, divyanshiGupta commented
/label px-approved
/label qe-approved

2022-03-03 12:16 UTC, rishumehra commented
/label docs-approved

2022-03-03 13:35 UTC, divyanshiGupta commented
/retest

2022-03-03 15:08 UTC, divyanshiGupta commented
/retest

2022-03-04 02:34 UTC, merged