[WIP] ODC-4474: Show "project not found" error if a namespace selected via an URL doesn't exist
openshift/console pull request #11098
Opened 2022-02-24 11:05 UTC by jerolimov

**Fixes**: 
https://issues.redhat.com/browse/ODC-4474

**Analysis / Root cause**: 
todo

**Solution Description**: 
todo

**Screen shots / Gifs for design review**: 
todo

**Unit test coverage report**: 
todo

**Test setup:**
todo

**Browser conformance**: 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2022-02-25 15:03 UTC, jerolimov commented
/retest

2022-02-25 16:11 UTC, jerolimov commented
Set this on hold to get feedback here also from Sam and Serena.

Can you please take a look if this solution makes sense to you?

Tl;dr-summary: Checking the namespace and showing an error if the namespace doesn't exist. This new check happens only if the user opens a URL **with a namespace.**

If the user opens just the console, or /add as URL the browser navigates to the latest (or preferred) namespace. If the latest or preferred namespace was removed in the mean time, the user was redirected to "all namespaces" as before.

/cc @spadgett @serenamarie125 
/hold

2022-02-25 16:19 UTC, jerolimov commented
/cc @sspeiche

2022-02-28 10:27 UTC, jerolimov commented
/bugzilla refresh

2022-03-02 09:15 UTC, jerolimov commented
/cc @debsmita1

2022-03-03 16:05 UTC, spadgett requested changes
It looks to me like this will break deep-linking to resources in namespaces that aren't in your project list. We can't assume that just because the namespace isn't in your project list that you can't see resources in that namespace. (We've had this bug a few times in the past and rejected fixing it for this reason.)

/hold

2022-03-03 19:09 UTC, jerolimov commented
> It looks to me like this will break deep-linking to resources in namespaces that aren't in your project list. We can't assume that just because the namespace isn't in your project list that you can't see resources in that namespace. (We've had this bug a few times in the past and rejected fixing it for this reason.)

OK, that's the reason I want your review. I wasn't aware that this was possible and expected. But totally makes sense to me. Thanks for sharing that.

So, @spadgett @serenamarie125, do you think we should check for the current namespace on this pages

* "Create forms" as shown in https://bugzilla.redhat.com/show_bug.cgi?id=2000073
    * `.../~new` and `..../~new/...` URLs (includes also pipeline builder)
* And on the add page for https://issues.redhat.com/browse/ODC-4474
    * `/add/ns/...` (Add page)
    * `/catalog/ns/...` (Add > Catalog pages)
    * `/samples/ns/...` (Add > Samples)
    * `/import/ns/...` (Add > Import from git)
    * `/deploy-image/ns/...` (Add > Container images)
    * `/upload-jar/ns/...` (Add > Upload JAR flow)
    * `/channel/ns/...` (Add > kn Channel)
    * `/broker/ns/...` (Add > kn Broker)

And then show such a "404 Project not found" page  -OR- should we just show a warning box at the top of the form? :thinking: 

I would still add this check to the individual called page. I just added the URLs to that the pages are clear and just to confirm that this 2nd approach goes into right direction.

Wdyt?

2022-08-01 01:24 UTC, closed without merging