Sort catalog filters and other enhancements
openshift/console pull request #11161
Opened 2022-03-09 08:59 UTC by divyanshiGupta

**Fixes:** https://issues.redhat.com/browse/ODC-6491

This PR adds the fix for sorting catalog filters alphabetically and 
uses useK8sWatchResource instead of k8sGet for fetching the bindable-services.

**Screenshots:**
<img width="1784" alt="Screenshot 2022-03-08 at 11 13 24 PM" src="https://user-images.githubusercontent.com/20724543/157407728-a191931a-4039-4da8-a440-ee8d947733ad.png">

<img width="1784" alt="Screenshot 2022-03-08 at 11 13 40 PM" src="https://user-images.githubusercontent.com/20724543/157407734-eda2f729-8015-4f1a-aeed-1e4ae1b46448.png">

/kind feature

2022-03-09 09:00 UTC, divyanshiGupta commented
@beaumorley can you PTAL at this PR and approve if the badge and filters looks good to you?

2022-03-09 11:07 UTC, divyanshiGupta commented
/cc: @christianvogt 
/cc: @invincibleJai

2022-03-09 11:07 UTC, divyanshiGupta commented
/cc @christianvogt 
/cc @invincibleJai

2022-03-09 13:11 UTC, divyanshiGupta commented
/retest

2022-03-09 14:24 UTC, christianvogt commented
/approve

2022-03-09 14:33 UTC, christianvogt commented
@beaumorley you'll see how there is a `bindable` as well as `not bindable` filter in the catalog list. This is the way the filters currently work in that all items must be covered by at least one filter. If we want to change this for boolean type filters, then we should raise a new issue with the details and not hold up this one.

2022-03-09 14:49 UTC, jerolimov requested changes
Get this react error and then a white page when open the OperatorBackedService catalog with this PR. Can you take a look?

```
Error
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
Call Stack
 checkForNestedUpdates
  vendors~main-fde4aab59bedd45747de.js:465232:15
 scheduleUpdateOnFiber
  vendors~main-fde4aab59bedd45747de.js:463264:3
```

/hold

2022-03-09 14:58 UTC, jerolimov requested changes
Some more requests to add some missing types.

2022-03-09 14:58 UTC, jerolimov commented on frontend/packages/console-shared/src/components/catalog/catalog-view/CatalogFilters.tsx
> +    .reduce((acc, groupName) => {
"I like types" :smirk: without defining it at the reduce or the initial parameter of the reduce its just `{}`

```suggestion
    .reduce<CatalogFilters>((acc, groupName) => {
```

2022-03-09 14:58 UTC, jerolimov commented on frontend/packages/console-shared/src/components/catalog/catalog-view/CatalogFilters.tsx
> +  const renderFilterGroup = (filterGroup, groupName) => {
Types please :)

2022-03-09 14:58 UTC, jerolimov commented on frontend/packages/console-shared/src/components/catalog/catalog-view/CatalogFilters.tsx
>    const renderFilterItem = (filter, filterName, groupName) => {
Can you add types here? :)

2022-03-09 16:21 UTC, serenamarie125 commented
Couple comments here

1. I think we need to reconsider the filter "text" here.  Let's cover it in the Friday call?  (this shouldn't hold up merging this PR though, we can have a follow PR for text as needed)
1. Shouldn't there be more spacing under the `Service Binding` title?

Otherwise looks great! FYI @slemeur

2022-03-10 11:25 UTC, divyanshiGupta commented
> Get this react error and then a white page when open the OperatorBackedService catalog with this PR. Can you take a look?
> 
> ```
> Error
> Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
> Call Stack
>  checkForNestedUpdates
>   vendors~main-fde4aab59bedd45747de.js:465232:15
>  scheduleUpdateOnFiber
>   vendors~main-fde4aab59bedd45747de.js:463264:3
> ```
> 
> /hold

@jerolimov I couldn't reproduce this issue. Can you share the steps to reproduce this?


https://user-images.githubusercontent.com/20724543/157652299-88389415-733b-46a3-9421-b716f817e60a.mov

2022-03-10 12:53 UTC, divyanshiGupta commented
/retest

2022-03-10 19:20 UTC, divyanshiGupta commented
/retest

2022-03-10 22:04 UTC, serenamarie125 reviewed
great work!

2022-03-11 11:58 UTC, jerolimov commented
/retest

2022-03-11 11:59 UTC, jerolimov commented
The updated flags names fix the crash when the operator is not installed.
/unhold

2022-03-11 12:08 UTC, jerolimov approved these changes
Tested it locally and the code looks good to me. The broken tests are not related to this PR.

/lgtm

2022-03-11 12:38 UTC, invincibleJai commented
/retest

2022-03-11 12:44 UTC, invincibleJai commented
@divyanshiGupta something looks off with test, PTAL

2022-03-11 12:54 UTC, divyanshiGupta commented
/retest-required

2022-03-11 13:19 UTC, divyanshiGupta commented
/restes

2022-03-11 13:22 UTC, jerolimov commented
/lgtm

2022-03-14 04:23 UTC, invincibleJai commented
/label docs-approved
/label px-approved

propagating above labels based on ACKs on epic

cc @rishumehra

2022-03-14 09:14 UTC, jerolimov commented
> 2. Shouldn't there be more spacing under the `Service Binding` title?

@divyanshiGupta FYI: I created this issue and PR for the PF catalog extension.

* https://github.com/patternfly/patternfly-react/issues/7059
* https://github.com/patternfly/patternfly-react/pull/7060

2022-03-14 09:59 UTC, jerolimov commented
/label qe-approved

2022-03-15 11:27 UTC, merged