Bug 2063756: - User Preferences - Applications - Insecure traffic : i18n misses
openshift/console pull request #11213
Opened 2022-03-21 21:19 UTC by cyril-ui-developer

@jhadvig /assign

### Before:
![Screen Shot 2022-03-21 at 5 17 44 PM](https://user-images.githubusercontent.com/15249132/159365455-d791290e-97cb-43a6-9aa0-0a95ff1a14d0.png)
![Screen Shot 2022-03-21 at 5 17 52 PM](https://user-images.githubusercontent.com/15249132/159365461-21e1d61e-6cbb-40dc-89d5-1140d26cfff8.png)

### After:
![Screen Shot 2022-03-21 at 5 15 02 PM](https://user-images.githubusercontent.com/15249132/159365526-302c0d86-4d17-43ed-a46f-41bd6248f13a.png)
![Screen Shot 2022-03-21 at 5 15 12 PM](https://user-images.githubusercontent.com/15249132/159365533-aa4bf237-618d-4897-9663-2f21b11b8e81.png)

2022-03-21 21:21 UTC, cyril-ui-developer commented
/bugzilla refresh

2022-03-22 07:21 UTC, jhadvig requested changes
Looks like we are missing locales for some of the strings

2022-03-22 07:21 UTC, jhadvig commented on frontend/packages/dev-console/src/components/import/import-types.ts
> +  // t('devconsole~Redirect')
Dont see `Allow` and `Redirect` translations in the devconsole locales. We should be adding them.

2022-03-22 12:50 UTC, cyril-ui-developer commented
/bugzilla refresh

2022-03-22 13:57 UTC, jhadvig approved these changes
@cyril-ui-developer thank you for the fix!
/lgtm
/approve

2022-03-22 21:10 UTC, cyril-ui-developer commented
/retest-required

2022-03-22 22:21 UTC, merged

2022-04-04 17:11 UTC, andrewballantyne commented
@cyril-ui-developer There is a bug on this PR. When we translate the enums backing the dropdown items, we need to translate them using qualified namespaces otherwise it defaults to `public` translations. Pseudo translations only interact on the usage of `t` and not actually verify the translations are in the right qualified namespace.

Current Error on 4.11.0-0.nightly-2022-04-01-172551
![image](https://user-images.githubusercontent.com/8126518/161596174-8975788d-865c-4995-a736-5681a75a05de.png)

I quickly hacked in an update to your code... 
The diff:
```
diff --git a/frontend/packages/dev-console/src/components/import/import-types.ts b/frontend/packages/dev-console/src/components/import/import-types.ts
index 0c1c5c77c4..4207b5bde6 100644
--- a/frontend/packages/dev-console/src/components/import/import-types.ts
+++ b/frontend/packages/dev-console/src/components/import/import-types.ts
@@ -305,27 +305,27 @@ export interface ImportData {

 export enum TerminationTypes {
   // t('devconsole~Edge')
-  edge = 'Edge',
+  edge = 'devconsole~Edge',
   // t('devconsole~Passthrough')
-  passthrough = 'Passthrough',
+  passthrough = 'devconsole~Passthrough',
   // t('devconsole~Re-encrypt')
-  reencrypt = 'Re-encrypt',
+  reencrypt = 'devconsole~Re-encrypt',
 }

 export enum InsecureTrafficTypes {
   // t('devconsole~None')
-  None = 'None',
+  None = 'devconsole~None',
   // t('devconsole~Allow')
-  Allow = 'Allow',
+  Allow = 'devconsole~Allow',
   // t('devconsole~Redirect')
-  Redirect = 'Redirect',
+  Redirect = 'devconsole~Redirect',
 }

 export enum PassthroughInsecureTrafficTypes {
   // t('devconsole~None')
-  None = 'None',
+  None = 'devconsole~None',
   // t('devconsole~Redirect')
-  Redirect = 'Redirect',
+  Redirect = 'devconsole~Redirect',
 }

 export interface AutoscaleWindowType {
```