Bug 2060329: show Limit exceeded state for large number of nodes in topology
openshift/console pull request #11334
Opened 2022-04-13 15:35 UTC by sahil143

**Fixes**: https://issues.redhat.com/browse/OCPBUGSM-41289

**Analysis / Root cause**: topology view lags with large number of nodes

**Solution Description**: if number of filtered nodes exceed 100 we will show a LimitExceeded state which suggests user to use the search page 

**Screen shots / Gifs for design review**: 

![image](https://user-images.githubusercontent.com/9278015/163217008-bb9e5308-68a0-4cbe-8e79-792ab301111f.png)

![Kapture 2022-04-13 at 20 54 07](https://user-images.githubusercontent.com/9278015/163216321-8c9b27de-7cff-46a5-92c4-481f2b12aeb6.gif)

**Unit test coverage report**: 

**Test setup:**

**Browser conformance**: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2022-04-13 15:37 UTC, sahil143 commented
/cc @jerolimov @christianvogt

2022-04-13 15:42 UTC, sahil143 commented on frontend/packages/topology/src/components/page/LimitExceededState.tsx
> +        </Button>
Dummy text is used here. Need UX/PM input on the final text for the state.

2022-04-13 21:59 UTC, jerolimov requested changes
Please define a const for the current max number of nodes. We can expect that we will change it over time.

2022-04-14 14:07 UTC, christianvogt commented on frontend/packages/topology/src/components/page/LimitExceededState.tsx
> +      </Button>
Use semantic HTML. Navigational links shouldn't be buttons that push to history. Use react-router with the button. See patternfly docs for example code.

2022-04-14 14:07 UTC, christianvogt commented on frontend/packages/topology/src/components/page/TopologyView.tsx
> +  const nodesLength = filteredModel?.nodes?.length;
```suggestion
  const nodesLength = filteredModel?.nodes?.length ?? 0;
```

2022-04-14 14:07 UTC, christianvogt commented on frontend/packages/topology/src/components/page/TopologyView.tsx
> +      nodesLength && (nodesLength < 100 || (nodesLength > 99 && showTopologyAnyway)) ? (
```suggestion
      nodesLength < 100 || showTopologyAnyway ? (
```

Use a const for the max nodes.

Also, do we really want to render `null` if 0 nodes? old code didn't

2022-04-14 14:07 UTC, christianvogt commented on frontend/packages/topology/src/components/page/TopologyView.tsx
> +                    {nodesLength && nodesLength > 99 && !showTopologyAnyway ? (
Use a const for max nodes.
```suggestion
                    {nodesLength >= MAX_NODES && !showTopologyAnyway ? (
```

2022-04-18 12:43 UTC, sahil143 commented on frontend/packages/topology/src/components/page/LimitExceededState.tsx
> +        </Button>
/cc @serenamarie125 @beaumorley 

Need proper text for this state.

2022-04-19 17:49 UTC, christianvogt commented on frontend/packages/topology/src/components/page/TopologyView.tsx
> +      nodesLength < MAX_NODES_LIMIT || showTopologyAnyway ? (
you use `nodesLength > MAX_NODES_LIMIT` when checking if the limit is exceeded, therefore you need to use `<=` here

2022-04-26 12:45 UTC, serenamarie125 requested changes
@sahil143 - worked with Beau and Allison Wolfe (content writer).  Please change to the following recommendations:

**Loading is taking longer than expected**

We noticed that it is taking a long time to visualize your application Topology. You can use Search to find specific resources or click Continue to keep waiting.

[Go to Search]
[Continue]

2022-04-27 11:22 UTC, jerolimov requested changes
@sahil143 Can you please also check the dark mode of this?

The empty state looks like this:

![image](https://user-images.githubusercontent.com/139310/165507235-a8acf711-e8f7-44ee-a084-c5b873533a4c.png)

But your empty state looks like this:

![image](https://user-images.githubusercontent.com/139310/165507288-86875389-a364-43f1-bce6-cdaac83cb22f.png)

You might want to take a look into @vikram-raj PR #11393 that solves this for the empty state above.

2022-04-27 14:55 UTC, sahil143 commented
@jerolimov fixed dark mode and added icon for the state
![image](https://user-images.githubusercontent.com/9278015/165546954-b70781f3-f783-4e22-a6c9-de26246d83ea.png)

2022-05-09 08:49 UTC, jerolimov commented
/assign

2022-05-09 10:51 UTC, jerolimov approved these changes
Change works fine and contains the recommendation text from Serena.

/lgtm
/approve

2022-05-09 18:06 UTC, merged

2022-05-17 08:47 UTC, sahil143 commented
/cherry-pick release-4.10