Stop disabling extensions with non-existing `disallowed` flags
openshift/console pull request #11344
Opened 2022-04-14 13:15 UTC by glekner

As of now, If flags in `disallowed` do not exist e.g. `"disallowed": ["KUBEVIRT_DYNAMIC"]`, the extension is disabled.

The extension should only be disabled if the flag exists and it is set to `true`.

2022-04-14 13:46 UTC, yaacov commented
/lgtm
@vojtechszocs PTAL

2022-04-14 14:04 UTC, glekner commented on frontend/packages/console-plugin-sdk/src/store.ts
> +  e.flags.disallowed.every((f) => !(f in flags) || flags[f] === false);
@spadgett yes it can. changed

2022-04-14 15:15 UTC, vojtechszocs requested changes

2022-04-14 15:15 UTC, vojtechszocs commented on frontend/packages/console-plugin-sdk/src/__tests__/store.spec.ts
> +    // undefined disallowed flags (flags that can be created at runtime by dynamic plugins) should not disable the extension
```suggestion
    // When the flag value is undefined, having the flag in `disallowed` array should keep the extension in use
```

2022-04-14 15:15 UTC, vojtechszocs commented on frontend/packages/console-plugin-sdk/src/__tests__/store.spec.ts
> +
```ts
// When the flag value is undefined, having the flag in `required` array should put the extension out of use
expect(isExtensionInUse(gatedExtension, flags(undefined, undefined, false, false))).toBe(false);
```

2022-04-14 15:19 UTC, vojtechszocs commented
/lgtm

2022-04-15 04:39 UTC, yaacov commented
/retest

2022-04-15 19:02 UTC, merged