Console 3113: Support ordering of plugin nav sections in admin perspective
openshift/console pull request #11401
Opened 2022-04-26 18:39 UTC by TheRealJon

Migrate admin nav items to dynamic plugn extensions
Refactor nav components to remove admin nav special cases and address tech debt

2022-04-28 17:13 UTC, TheRealJon commented
/woof

2022-05-05 09:33 UTC, glekner commented
/retest

2022-05-05 14:08 UTC, andrewballantyne requested changes
Is there anyway we can move the nav into `console-app`? Framework for building the navigation sounds very `console-app`.

2022-05-05 20:52 UTC, TheRealJon commented
@andrewballantyne I've addressed the easiest of your comments, but haven't moved the nav components into the console-app package yet. That's going to involve a little bit of refactoring to address some cyclical imports.

2022-05-05 23:32 UTC, andrewballantyne commented
> @andrewballantyne I've addressed the easiest of your comments, but haven't moved the nav components into the console-app package yet. That's going to involve a little bit of refactoring to address some cyclical imports.

@TheRealJon We don't **have to** move them with this work, but we always need to ask the natural follow up question... "if not now, when?", so I just asked it of you here. Let me know if you think it's too much.

As for your cyclical imports -- that's likely the curse of our `index` files. If you're hitting these issues, go directly to the file instead of stopping at an index file. Usually that will solve your issue.

2022-05-06 13:05 UTC, TheRealJon commented
QE Approver
/assign @yapei

Docs Approver:
/assign @opayne1

PX Approver:
/assign @RickJWagner

2022-05-06 13:07 UTC, TheRealJon commented
@andrewballantyne I think for the sake of moving this story along, we should try to get this merged and create a follow-on story to move the nav component into console-app.

2022-05-06 13:35 UTC, RickJWagner commented
/label px-approved

2022-05-06 16:34 UTC, andrewballantyne requested changes
Can you also move the translations for the other extensions in the other packages.

2022-05-06 16:34 UTC, andrewballantyne commented on frontend/packages/knative-plugin/console-extensions.json
> +      "name": "%public~Serverless%",
here

2022-05-06 16:34 UTC, andrewballantyne commented on frontend/packages/kubevirt-plugin/console-extensions.json
> +      "name": "%public~Virtualization%",
here

2022-05-06 16:34 UTC, andrewballantyne commented on frontend/packages/pipelines-plugin/console-extensions.json
> +      "name": "%public~Pipelines%",
here

2022-05-06 16:37 UTC, andrewballantyne requested changes
Looks like you also have a test failure around a CSS variable... `NavHeader.tsx` now imports the CSS file and thus probably lost some context of the global variables it had before. Should probably just be an import in your SCSS file

The error:
```
ERROR in ./public/components/nav/NavHeader.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
  ╷
5 │   @media screen and (min-width: $pf-global--breakpoint--xl) {
  │                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  public/components/nav/NavHeader.scss 5:33  root stylesheet
    at /go/src/github.com/openshift/console/frontend/node_modules/webpack/lib/NormalModule.js:316:20
    at /go/src/github.com/openshift/console/frontend/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /go/src/github.com/openshift/console/frontend/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/go/src/github.com/openshift/console/frontend/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /go/src/github.com/openshift/console/frontend/node_modules/sass-loader/dist/index.js:62:7
    at Function.call$2 (/go/src/github.com/openshift/console/frontend/node_modules/sass/sass.dart.js:95825:16)
    at _render_closure1.call$2 (/go/src/github.com/openshift/console/frontend/node_modules/sass/sass.dart.js:83882:12)
    at _RootZone.runBinary$3$3 (/go/src/github.com/openshift/console/frontend/node_modules/sass/sass.dart.js:28060:18)
    at _FutureListener.handleError$1 (/go/src/github.com/openshift/console/frontend/node_modules/sass/sass.dart.js:26590:21)
    at _Future__propagateToListeners_handleError.call$0 (/go/src/github.com/openshift/console/frontend/node_modules/sass/sass.dart.js:26889:49)
    at Object._Future__propagateToListeners (/go/src/github.com/openshift/console/frontend/node_modules/sass/sass.dart.js:12505:77)
    at _Future._completeError$2 (/go/src/github.com/openshift/console/frontend/node_modules/sass/sass.dart.js:26735:9)
    at _AsyncAwaitCompleter.completeError$2 (/go/src/github.com/openshift/console/frontend/node_modules/sass/sass.dart.js:26404:12)
    at Object._asyncRethrow (/go/src/github.com/openshift/console/frontend/node_modules/sass/sass.dart.js:12308:17)
    at /go/src/github.com/openshift/console/frontend/node_modules/sass/sass.dart.js:1822:20
    at _wrapJsFunctionForAsync_closure.$protected (/go/src/github.com/openshift/console/frontend/node_modules/sass/sass.dart.js:12333:15)
 @ ./public/components/nav/NavHeader.tsx 20:0-26
 @ ./public/components/nav/index.tsx
 @ ./public/components/app.jsx
```

2022-05-06 17:23 UTC, opayne1 commented
/label docs-approved

2022-05-06 22:20 UTC, TheRealJon commented
@andrewballantyne Addressed additional comments and fixed the build error. I'll just need to squash whenever we're ready. @zherman0 If you have any comments to add before I squash, just let me know.

2022-05-07 11:04 UTC, yapei commented
@TheRealJon tested the changes by updating our console-demo-plugin top level nav menu `Demo Plugin` order with following json
  {
    "type": "console.navigation/section",
    "properties": {
      "id": "admin-demo-section",
      "perspective": "admin",
      "name": "%plugin__console-demo-plugin~Demo Plugin%",
      "insertAfter": "workloads",
      "insertBefore": "networking",
      "dataAttributes": {
        "data-test": "nav-demo-plugin"
      }
    }
  }

`Demo Plugin` nav menu is reordered correctly however I didn't the `data-test` value in `dataAttributes` applied successfully to the element
<img width="350" alt="Screen Shot 2022-05-07 at 19 01 53" src="https://user-images.githubusercontent.com/12692381/167251477-009d3ab4-c86c-4bb6-b262-82374bd9dbc1.png">

2022-05-09 20:07 UTC, TheRealJon commented
@yapei I found a typo in my original implementation that was causing the data attributes to be committed from dynamic plugin nav section extensions. It should be fixed now.

@andrewballantyne I squashed and rebased. This should be ready for a final review.

2022-05-09 20:35 UTC, andrewballantyne approved these changes
/lgtm

2022-05-10 11:34 UTC, yapei commented
tested again and no issues found
/label qe-approved

2022-05-10 17:13 UTC, andrewballantyne approved these changes
/lgtm

2022-05-12 05:15 UTC, TheRealJon commented
/label tide/merge-method-squash

2022-05-18 15:24 UTC, TheRealJon commented
/retest

2022-05-18 19:21 UTC, andrewballantyne commented
/lgtm

2022-05-19 15:30 UTC, merged