Bug 1989610: Don't render empty div for invalid descriptors.
openshift/console pull request #11433
Opened 2022-05-03 20:03 UTC by TheRealJon

- Move div wrapper for descriptor details items down to SpecDescriptorDetailsItem and StatusDescriptorDetailsItem components so that the div itself is also conditionally rendered based on descriptor validation.
- Move duplicate Secret components out of status and spec descriptor index files and into the common component file.

2022-05-10 14:17 UTC, TheRealJon commented
/bugzilla refresh

2022-05-10 19:19 UTC, andrewballantyne requested changes

2022-05-10 19:19 UTC, andrewballantyne commented on frontend/packages/operator-lifecycle-manager/src/components/descriptors/spec/index.tsx
> +  return !Component ? null : (
Not a big deal, but you could write this as 
```suggestion
  return Component && (
```

2022-05-10 21:04 UTC, TheRealJon commented
/label tide/merge-method-squash

2022-05-10 21:05 UTC, TheRealJon commented
@andrewballantyne I've made some updates to address your comments

2022-05-11 14:38 UTC, andrewballantyne approved these changes
/lgtm

2022-05-11 20:07 UTC, merged