Bug 1973077: add warning alert when selecting an encrypted storageclass
openshift/console pull request #11691
Opened 2022-06-13 06:21 UTC by weirdwiz

2022-06-15 06:06 UTC, bipuladh commented
/ok-to-test

2022-06-15 06:12 UTC, bipuladh requested changes

2022-06-15 06:12 UTC, bipuladh commented on frontend/packages/console-app/src/components/modals/restore-pvc/restore-pvc-modal.tsx
> +            {warningComponent}
```suggestion
 {isEncrypted && (
   <Alert
       className="co-alert"
       variant="warning"
        title={t('console-app~Encrypted snapshots cannot be restored with a non-encrypted storage class')}
       isInline
    />
 );
}
```

2022-06-15 06:12 UTC, bipuladh commented on frontend/packages/console-app/src/components/modals/restore-pvc/restore-pvc-modal.tsx
> +    const [isEncrypted, setEncrypted] = React.useState(false);
```suggestion
    const isEncrypted = pvcSc?.parameters?.['encrypted'] === 'true';
```
This can be derived from pvcSC state value.

2022-06-15 06:12 UTC, bipuladh commented on frontend/packages/console-app/src/components/modals/restore-pvc/restore-pvc-modal.tsx
> +      setEncrypted(updatedStorageClass?.parameters['encrypted'] === 'true' ?? false);
```suggestion
```

2022-06-15 06:12 UTC, bipuladh commented on frontend/packages/console-app/src/components/modals/restore-pvc/restore-pvc-modal.tsx
> +    }
```suggestion
```

2022-08-16 08:21 UTC, weirdwiz commented
/test e2e-gcp-console

2022-09-02 08:36 UTC, SanjalKatiyar commented
/test e2e-gcp-console

2022-09-02 08:36 UTC, SanjalKatiyar commented
@weirdwiz please squash the commits and add screenshots.

2023-03-19 00:01 UTC, closed without merging