Bug 2093593: Updated selected strategy file as devfile when devfile is selected
openshift/console pull request #11719
Opened 2022-06-16 12:04 UTC by lokanandaprabhu

**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-45090

**Analysis / Root cause**: 
import type was not considered while rendering other components

**Solution Description**: 
Added import type as a condition 

**Screen shots / Gifs for design review**: 
-----Before----

https://user-images.githubusercontent.com/102503482/174065535-ab0bad08-c7da-4d5e-95f7-a60c50f5bfeb.mov

-----After------

https://user-images.githubusercontent.com/102503482/174065556-88c68cfc-a489-45c3-8514-b4b79a4264c9.mov

**Unit test coverage report**: 
NA

**Test setup:**
1. Navigate to the Add page > All services
2. Select Devfiles as type
3. Select the "Basic Node.js" example and press Create

**Browser conformance**: 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2022-06-17 04:29 UTC, lokanandaprabhu commented
/test e2e-gcp-console

2022-06-20 20:05 UTC, jerolimov requested changes

2022-06-20 20:05 UTC, jerolimov commented on frontend/packages/dev-console/src/components/import/GitImportForm.tsx
> +            {importType !== 'devfile' &&
Please use the ImportTypes enum. Please also replace the other 'devfile' below.

```suggestion
            {importType !== ImportTypes.devfile &&
```

2022-06-21 07:32 UTC, invincibleJai commented
/retest

2022-06-21 08:54 UTC, lokanandaprabhu commented
/retest

2022-06-21 14:23 UTC, lokanandaprabhu commented
/retest

2022-07-05 07:46 UTC, invincibleJai commented
/lgtm
/approve

Verified the changes , works as expected

2022-07-05 07:47 UTC, invincibleJai commented
/kind bug

2022-07-06 00:19 UTC, merged