Bug 2093597: Added the spacing between advanced options
openshift/console pull request #11739
Opened 2022-06-21 11:23 UTC by lokanandaprabhu

**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-45092

**Analysis / Root cause**: 
Since the component was not included in div, grid spacing was not added in between a advanced option and the message showing "Click on the names to access advanced options for"

**Solution Description**: 
Added margin bottom styling after expanding an advanced option and made changes to handle "When importing a component from git or from a container image, and open one or more advanced options, the sentence "Click on the names to access advanced options for ..." is split into two parts".  

**Screen shots / Gifs for design review**: 
--------Build config edit page-------

BEFORE:
<img width="419" alt="Advanced options" src="https://user-images.githubusercontent.com/102503482/174777920-b504958b-43ab-48f3-b3a1-a1cccd2397d1.png">

AFTER:
<img width="581" alt="Advanced options" src="https://user-images.githubusercontent.com/102503482/174777946-be930ccd-ad6b-44a6-963e-95de846023ea.png">

-------Edit deployment page--------

BEFORE:
<img width="608" alt="Advanced options" src="https://user-images.githubusercontent.com/102503482/174777986-d9fc7b50-faef-4778-b610-9c821b5dfe74.png">

AFTER:
<img width="585" alt="Advanced options" src="https://user-images.githubusercontent.com/102503482/174778002-21d36e1b-1d5b-47e1-b1a8-dc91b088b924.png">

---------Container Images add page-----

BEFORE:
<img width="723" alt="Health checks" src="https://user-images.githubusercontent.com/102503482/174778046-70da9632-7645-4c6e-8c81-c68c14ee1b51.png">

AFTER:
<img width="761" alt="Health checks" src="https://user-images.githubusercontent.com/102503482/174778061-8f16d3f2-c62c-4ce6-9e57-45fd11c2557a.png">

**Unit test coverage report**: 
NA

**Test setup:**
Steps to Reproduce:

CASE1:

1. Switch to dev perspective
2. Navigate to the add page > Import from container
3. Scroll down and open one or more of the advanced options

CASE2:

1. Create application using container images
2. Go to topology
3. Edit deployment
4. Scroll down and open one or more of the advanced options

CASE3:

1. Create a BuildConfig
2. Edit BuildConfig
3. Scroll down and open one or more of the advanced options

**Browser conformance**: 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2022-06-21 16:14 UTC, divyanshiGupta commented
/lgtm

2022-06-22 07:47 UTC, lokanandaprabhu commented
/retest

2022-06-22 21:24 UTC, jerolimov requested changes

2022-06-22 21:24 UTC, jerolimov commented on frontend/packages/dev-console/locales/en/devconsole.json
> -  "Click on the names to access advanced options for <1></1>.": "Click on the names to access advanced options for <1></1>.",
Please let us keep this translation and don't add a dot somewhere else in the code. Not all languages use a dot at the end of a sentence.

2022-06-22 21:24 UTC, jerolimov commented on frontend/packages/dev-console/src/components/progressive-list/ProgressiveListFooter.tsx
> +        }
That's not correct in all languages.

2022-06-22 21:33 UTC, jerolimov requested changes
@lokanandaprabhu @divyanshiGupta we need a fix for the current version, but also a version that works for all languages we support. I believe a <Trans> is still the right way, but maybe you need to think about how we composite all these List, ProgressiveList, and ProgressiveListFooter components.

2022-06-23 07:12 UTC, jerolimov commented
/hold

2022-06-27 10:27 UTC, lokanandaprabhu commented
PR is updated to test a bug. This PR is not completely worked on. Please don't consider for testing/review. 

cc: @jerolimov

2022-07-14 13:28 UTC, jerolimov approved these changes
This looks really good now! Thanks!

Please let us backport this to 4.11 and 4.10 as well.

As we discussed in Slack, it would be cool if you can do the change in `frontend/packages/dev-console/locales/en/devconsole.json` also in the other languages (updating `<1>` to `<0>`) so that we don't lose the translation here!

/unhold
/approve

2022-07-14 13:29 UTC, jerolimov requested changes

2022-07-14 13:29 UTC, jerolimov commented on frontend/packages/dev-console/locales/en/devconsole.json
> +  "Click on the names to access advanced options for <0></0>.": "Click on the names to access advanced options for <0></0>.",
Please do a similar change for the other language files so that we don't lose our translation ere.

2022-07-15 07:53 UTC, lokanandaprabhu commented
/cherry-pick release-4.11

2022-07-15 08:09 UTC, jerolimov approved these changes
Thanks for updating the translation files as well. That is helpful for the backports.

Tested it again and works great. And the fullstop **is** part of the translation. :partying_face: 

/lgtm

2022-07-17 02:56 UTC, merged