Bug 2091542: - Error Loading/404 not found page shown after clicking "Current namespace only"
openshift/console pull request #11743
Opened 2022-06-21 19:57 UTC by cyril-ui-developer

2022-06-21 20:09 UTC, cyril-ui-developer commented
/bugzilla refresh

2022-06-24 14:28 UTC, TheRealJon requested changes
We should remove `csv` from OperandListProps and OperandTableRowProps types since they are no longer used in those components.

2022-06-24 14:28 UTC, TheRealJon commented on frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
>    csv?: ClusterServiceVersionKind;
```suggestion
```

2022-06-24 15:26 UTC, cyril-ui-developer commented on frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
>    csv?: ClusterServiceVersionKind;
> 

@TheRealJon Changed this to `obj` .

2022-06-24 15:47 UTC, cyril-ui-developer commented on frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx
>    csv?: ClusterServiceVersionKind;
> > 
> 
> @TheRealJon Changed this to `obj` .

Never mind. Remove it.

2022-06-24 16:00 UTC, TheRealJon approved these changes
/lgtm

2022-07-13 12:14 UTC, cyril-ui-developer commented
/retest

2022-07-13 16:50 UTC, cyril-ui-developer commented
/test e2e-gcp-console

2022-07-14 00:17 UTC, merged

2022-07-14 14:17 UTC, TheRealJon commented
/bugzilla refresh

2022-07-14 14:22 UTC, TheRealJon commented
@cyril-ui-developer For future reference, if a PR addresses multiple bugs, you can add all the bugs in the title as a comma-separated list like this: "Bug 1234567, Bug 1234568: Fixes two bugs".

2022-07-14 14:28 UTC, cyril-ui-developer commented
> @cyril-ui-developer For future reference, if a PR addresses multiple bugs, you can add all the bugs in the title as a comma-separated list like this: "Bug 1234567, Bug 1234568: Fixes two bugs".

Thanks. 
@TheRealJon This needs to be backported to the release branch, right?

2022-07-21 21:18 UTC, cyril-ui-developer commented
/cherry-pick release-4.11