Bug 2100666: Use BuildConfig form also when pressing create
openshift/console pull request #11757
Opened 2022-06-23 23:02 UTC by jerolimov

**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2100666

**Analysis / Root cause**: 
BuildConfig form was only used for edit yet.

**Solution Description**: 
Set the right URL as `createProps` similar to Deployments, DeploymentConfigs, etc.

**Test setup:**
1. Switch to dev perspective
2. Navigate to build
3. Click on create
4. Opens a YAML editor to create a BuildConfig in admin and dev perspective

**Browser conformance**: 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2022-06-23 23:02 UTC, jerolimov commented
/cc @debsmita1

2022-06-24 05:38 UTC, jerolimov commented
/retest

2022-06-24 08:22 UTC, debsmita1 commented
Got the below error when saving the form

![Peek 2022-06-21 16-05](https://user-images.githubusercontent.com/22490998/175494883-fe9b7374-becb-4ebe-985b-0fa7f8ebd30f.gif)

2022-06-24 08:46 UTC, vikram-raj commented
/hold

2022-06-24 08:57 UTC, vikram-raj commented
I am able to create a build after providing the Image stream data. but After creating for redirect to Edit build config form. It should take us to the BuildConfig list page. 
 /hold cancel
/lgtm cancel

2022-07-27 18:30 UTC, jerolimov commented
/retest

2022-07-27 19:37 UTC, jerolimov commented
> Got the below error when saving the form [...]

@debsmita1 Thanks, I've made "Source" > "Source Type" and "Images" > "Build from" dropdown now required by expecting a specific type value. You can select Image Stream Tag `openshift`/`nodejs`/`latest` for example, but it depends on your git repo.



>  After creating it redirect to Edit build config form. It should take us to the BuildConfig list page.

@vikram-raj Agree that switching to the edit page was unexpected. I changed this now but it opens the details view page and not the list page similar to other pages. That's fine, right?

> One more observation. When I click on Create BuildConfig in the Devconsole Build list page, the namespace always changes to the default.

This is fixed as well.

Here is a recording but please take a fresh look. Thanks.

https://user-images.githubusercontent.com/139310/181357312-ec730cdb-bdf1-4f5b-8ec8-29acc3e50c4d.mp4

> /hold cancel

/unhold

2022-07-27 19:43 UTC, jerolimov commented
/bugzilla refresh

2022-07-28 08:18 UTC, vikram-raj commented
/retest

2022-07-28 09:11 UTC, vikram-raj commented
After editing the BuildConfig it stays on the form page. Isn't It should redirect to the details/list page as we do for other edit flow in devConsole.

![Kapture 2022-07-28 at 14 38 24](https://user-images.githubusercontent.com/2561818/181468038-f0303cf3-8205-439b-a537-5a2f9c2b42dd.gif)

2022-07-28 12:20 UTC, jerolimov commented
> After editing the BuildConfig it stays on the form page. Isn't It should redirect to the details/list page as we do for other edit flow in devConsole.

@vikram-raj Good point! Was maybe too much time on the Project > Project access page, :smirk: 

[Updated it](https://github.com/openshift/console/compare/b678a29e7d8559974679b0ee0aef67672c5821a9..b55bc541a0e3c6bb3c117c8fde355361e800ec61), it now always redirects to the details page when the create or update call was successfully.

2022-07-28 13:10 UTC, vikram-raj commented
@jerolimov Looks like you need to run `yarn i18n` frontend tests are failing because of that.

2022-07-28 14:17 UTC, vikram-raj requested changes

2022-07-28 14:17 UTC, vikram-raj commented on frontend/public/components/build-config.tsx
> +  const namespace = props.match.params.ns;
Looks like props is undefined here. The search page is crashing when I select the `BuildConfig` resource from the dropdown.
![Kapture 2022-07-28 at 19 44 38](https://user-images.githubusercontent.com/2561818/181531302-9d8f9cca-2b53-4391-9ff9-0b13f2dc9144.gif)

2022-07-28 14:24 UTC, vikram-raj commented on frontend/public/components/build-config.tsx
> +  const namespace = props.match.params.ns;
You will get the namespace here.

```suggestion
  const namespace = props?.namespace;
```

2022-07-28 14:25 UTC, vikram-raj commented on frontend/public/components/build-config.tsx
> +  match: Rmatch<{ ns?: string }>;
```suggestion
  namespace: string;
```

2022-12-09 14:13 UTC, jerolimov commented
/remove-lifecycle rotten

2023-01-19 18:02 UTC, debsmita1 commented
cherry-picked this commit in this PR https://github.com/openshift/console/pull/12400
So closing this PR

2023-01-19 18:02 UTC, debsmita1 commented
/close

2023-01-19 18:02 UTC, closed without merging