OCPBUGS-548: Changes to the application menu with search and favorite options so it is consistent with PatternFly menu and aligns with Project selection menu
openshift/console pull request #11985
Opened 2022-08-24 17:34 UTC by sg00dwin

The application dropdown menu uses a custom component with a configuration to favorite applications, like the Project selection menu favorites projects, but its UX is inconsistent in the way it looks and behaves. The Project selection UI element uses the PatternFly Menu component. This PR modifies the relevant parts of our custom dropdown component to mimic the look and feel of the PF Menu component.

**_Specific changes for consistency_**
1. Add magnify glass icon in search input
2. Add `<Divider />` below search input
3. Add Favorites section heading when there are favorited apps
4. Use `<StarIcon />` to signify favorited
5. Use `<CheckIcon />` to signify current selection
6. Apply correct menu item spacing and positioning of icons
7. Apply correct `hover` `focus` background color

### Visual comparison
**Before**
<img width="1047" alt="Menus-bug" src="https://user-images.githubusercontent.com/1874151/186465765-f00a5551-6cae-4f5c-8580-3afae1c55c94.png">

**After**
<img width="1047" alt="Menus-bug-good" src="https://user-images.githubusercontent.com/1874151/186469810-a5817e0c-3207-409a-860d-1a0e989148ec.png">

### Behavior comparison
**Before**

![app-select-dark-before](https://user-images.githubusercontent.com/1874151/186456195-8eaad898-f12d-4792-99c5-ece66457c6f7.gif)

**After**
![app-select-dark-after](https://user-images.githubusercontent.com/1874151/186456158-67f89771-19a8-46ca-aa5d-90a64a38f95f.gif)

2022-08-24 17:36 UTC, sg00dwin commented
/jira refresh

2022-08-24 18:07 UTC, rhamilto reviewed
Nice work, @sg00dwin.  Always great to see more custom CSS going away.

LGTM, but will let @jerolimov give the final approval since this is in the Developer perspective.

2022-08-24 20:06 UTC, sg00dwin commented
> LGTM, but will let @jerolimov give the final approval since this is in the Developer perspective.

I did see the application selector is now accessible in the Admin perspective under Project details > Workloads

<img width="901" alt="Screen Shot 2022-08-24 at 3 57 33 PM" src="https://user-images.githubusercontent.com/1874151/186512828-035b0fea-5e86-4544-b147-75abb70d6845.png">

2022-08-29 20:22 UTC, sg00dwin commented
/retest-required

2022-08-30 15:07 UTC, sg00dwin commented
/retest

2022-08-30 20:43 UTC, sg00dwin commented
/retest

2022-08-31 13:37 UTC, sg00dwin commented
@jerolimov can you review these changes to the Application menu

2022-09-01 22:51 UTC, jerolimov requested changes
Implementation and result look almost good :+1: 

But I found one issue the generated dom shows an `h1` for the Favorites title and an `hr` for the Divider in a `ul`. You can fix this with these changes and it looks almost the same. Wdyt?

![image](https://user-images.githubusercontent.com/139310/188025651-348ea3c2-8448-4156-8b90-02e58b2d1349.png)

![image](https://user-images.githubusercontent.com/139310/188025707-bf17ea32-a648-49cc-978e-923b80d97d60.png)

2022-09-01 22:51 UTC, jerolimov commented on frontend/public/components/utils/dropdown.jsx
> +                      <h1 className="pf-c-menu__group-title pf-u-pb-sm">Favorites</h1>
```suggestion
                      <li className="pf-c-menu__group-title pf-u-pb-sm">Favorites</li>
```

2022-09-01 22:51 UTC, jerolimov commented on frontend/public/components/utils/dropdown.jsx
> +          <Divider />
```suggestion
          <Divider component="li" />
```

2022-09-01 22:52 UTC, jerolimov commented on frontend/public/components/utils/dropdown.jsx
> +                    {_.size(bookMarkRows) && _.size(rows) ? <Divider /> : null}
Here as well:

```suggestion
                    {_.size(bookMarkRows) && _.size(rows) ? <Divider component="li" /> : null}
```

2022-09-01 22:53 UTC, jerolimov commented on frontend/public/components/utils/dropdown.jsx
> +                      <Divider />
This is fine because its before the `ul`

```suggestion
                      <Divider />
```

2022-09-06 19:48 UTC, sg00dwin commented on frontend/public/components/utils/dropdown.jsx
> +          <Divider />
Updated

2022-09-06 19:49 UTC, sg00dwin commented on frontend/public/components/utils/dropdown.jsx
> +                    {_.size(bookMarkRows) && _.size(rows) ? <Divider /> : null}
updated

2022-09-06 19:49 UTC, sg00dwin commented on frontend/public/components/utils/dropdown.jsx
> +                      <h1 className="pf-c-menu__group-title pf-u-pb-sm">Favorites</h1>
updated

2022-09-06 20:09 UTC, sg00dwin commented
> But I found one issue the generated dom shows an `h1` for the Favorites title and an `hr` for the Divider in a `ul`. You can fix this with these changes and it looks almost the same. Wdyt?

Thanks @jerolimov I've updated the pr with those changes.

2022-09-08 15:27 UTC, jerolimov approved these changes
Works fine and dom looks also good now. :+1: 

/lgtm
/approve

2022-09-08 19:02 UTC, merged