OCPBUGS-193: Corrected kebab action overlapping issue in Helm page
openshift/console pull request #11980
Opened 2022-08-24 06:15 UTC by lokanandaprabhu

**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-193

**Analysis / Root cause**: 
Different kebab component was used.

**Solution Description**: 
Replaced LazyActionMenu component with ResourceKebab component

**Screen shots / Gifs for design review**: 
----BEFORE----
https://issues.redhat.com/secure/attachment/12751774/Screencast%20from%2008-06-2022%20061155PM.webm

----AFTER----
![helm-chart-repo-kebab](https://user-images.githubusercontent.com/102503482/186344100-457e127d-e1cc-4cf2-9e40-501e37dd96ca.gif)

**Unit test coverage report**: 
NA

**Test setup:**
Steps to Reproduce:
1. Create some helm chart repository
2. Go to the Helm page and switch to the repositories tab
3. Open kebab menu for different repos

**Browser conformance**: 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2022-09-02 07:29 UTC, invincibleJai commented
/jira refresh

2022-09-02 07:29 UTC, invincibleJai commented
/jira refresh

2022-09-05 11:36 UTC, invincibleJai commented
/approve

/cc @debsmita1

2022-09-06 16:48 UTC, debsmita1 commented
This issue exists for all the resources that use the dynamic extension for action menu items. We should refrain from using the ResourceKebab component for rendering the action menu. LazyActionMenu uses the dynamic extensions and the PF components for rendering the menu items.

2022-09-09 07:14 UTC, jerolimov commented
I would also expect that we need `LazyActionMenu` for dynamic plugins. Please find a test case for this and see if there is a way to fix just the CSS/layer issue.

/approved cancel
/hold

2022-09-09 07:33 UTC, invincibleJai commented
/approve cancel

2022-10-03 04:39 UTC, lokanandaprabhu commented
/retest

2022-10-04 20:24 UTC, jerolimov requested changes
Hey @lokanandaprabhu,

thanks for this fix. It works fine but with a detailed look into this, I would like to make a suggestion.

The main reason is that the new solutions use a state similar to `isOpen`, and it also feels a like a (working!) workaround instead of fixing the underlying issue.

And by adding another state it rerenders the component one more time. It might not matter in this small component, but on bigger components, this could impact our performance. In this case, I mainly want to suggest another approach for maintainability.

Previously, `MenuToggle` adds an `onClick` callback to a `button`, and another `click` handler to the `window` that closes the menu if the user clicks outside or on another button. Because the button click handler was called first, the code `stopPropagation` so that the 2nd handler isn't called.

This logic doesn't work anymore when changing this to `mousedown`. It works for the user, but it keeps code that "doesn't make sense" anymore. (For another dev, in a year or so...)

For this I take a deeper look into the change and believe we can implement this without adding a new state and change the code so that the original idea works:

For this we should:

1. Add the listeners to the window only if the menu `isOpen`.
    
    The state for this exists already (as a prop) and the `useEffect` was already called every time this prop changes. We should just not add the listener if it's not necessary. We also don't need to check isOpen then in the handlers, because they are only called if its open.
    
2. Don't call `ev.stopPropagation()` anymore
    
    The old implementation cancels **_all_** click propagations. So `handleClickOutside` of another `ActionMenuToggle` isn't called and doesn't close their menu. The real bug. ;)
    
    Then `handleClickOutside` of this other instance needs to ignore clicks on the "current button". For this you need to check `toggleRef.current` instead of `menuRef` - or as well.

I added more below. PTAL and let me know if this makes sense to you. :smile:

2022-10-12 10:04 UTC, lokanandaprabhu commented
Thanks @jerolimov for the detailed explanation. Updated the PR. PTAL.

2022-10-14 19:29 UTC, jerolimov commented
/retest

2022-10-15 23:08 UTC, jerolimov approved these changes
Tested this locally and works fine. :+1:

/unhold
/lgtm
/approve

2022-10-16 06:03 UTC, merged