[WIP] add list of enabled/disabled perspectives to server flags
openshift/console pull request #11993
Opened 2022-08-26 18:07 UTC by debsmita1

**Story:**
https://issues.redhat.com/browse/ODC-6783

Add dev catalog types customization API based on https://github.com/openshift/enhancements/pull/1205

**TODO:**
- Add tests

2022-08-29 09:20 UTC, debsmita1 commented
/assign @jerolimov

2022-09-06 18:49 UTC, debsmita1 commented
/kind feature

2022-09-19 18:13 UTC, debsmita1 commented
/retest

2022-09-20 05:36 UTC, debsmita1 commented
/retest

2022-09-23 09:49 UTC, jerolimov requested changes
Small nits:

2022-09-23 09:49 UTC, jerolimov commented on pkg/serverconfig/validate.go
> +		if perspective.ID != "" && reflect.DeepEqual(perspective.Visibility, PerspectiveVisibility{}) {
ID is already checked, so we can focus on visibility here and keep it simple:

```suggestion
		if perspective.Visibility.State == "" {
```

2022-09-23 10:20 UTC, jerolimov approved these changes
Tested this locally with `-perspective` and this works fine. :+1: 

Will test this later also on cluster bot together with https://github.com/openshift/console-operator/pull/676

/lgtm

2022-09-23 11:33 UTC, debsmita1 commented
/label px-approved
/label docs-approved

2022-09-25 21:17 UTC, jerolimov requested changes
Tested this locally, and it works fine  :+1:

But there should be no update to the vendor folder without a change in the `go.sum`, can you pls revert `vendor/k8s.io/api/core/v1/types.go`?

2022-09-26 05:25 UTC, debsmita1 commented
rebased

2022-09-26 07:12 UTC, jerolimov approved these changes
Tested it locally and it still works fine. Started a cluster bot to verify it there as well...

/lgtm

2022-09-26 08:21 UTC, jerolimov commented
> Tested it locally and it still works fine. Started a cluster bot to verify it there as well...

Tested this now successfully also on a cluster bot instance.

/label qe-approved

2022-09-26 09:25 UTC, merged