OCPBUGS-943: Use the Deployment as resource kind and label also when importing a Devfile
openshift/console pull request #12022
Opened 2022-09-06 12:03 UTC by jerolimov

**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-943

**Analysis / Root cause**: 
The selected resource type can not be changed for Devfiles.

But `getPodLabels` used this to create the right labels. If the resource was unknown it creates a invalid label for the Deployment (not the selected resource!)

```ts
"": app
```

**Solution Description**: 
Use a "hard coded" (based on the calling function name) DeploymentModel or DeploymentConfigModel instead of the selected resource type when creating the Pod labels.

**Screen shots / Gifs for design review**: 
Before 4.11:

https://user-images.githubusercontent.com/139310/188630347-efcab895-1429-4def-a84c-9145a14abb87.mp4

Before 4.12:

https://user-images.githubusercontent.com/139310/188630364-ff294028-29b6-4a12-8af4-a3543cddd54e.mp4

With this PR:

https://user-images.githubusercontent.com/139310/188630385-c8eed582-ae95-4555-a6bf-91ac36d55e8d.mp4

Labels for a Devfile, Deployment and DeploymentConfig:

https://user-images.githubusercontent.com/139310/188630397-2eabce34-a50b-41ec-90f1-28d20ddd0c93.mp4

**Unit test coverage report**: 
Unchanged

**Test setup:**
1. Install and setup Serverless operator
1. Switch to dev perspective, navigate to add > import from git
3. Enter a non-Devfile git URL like https://github.com/jerolimov/nodeinfo
4. On 4.11 select resource type Serverless (on 4.12 this should be selected automatically)
5. Update the git URL to a repo with a Devfile like https://github.com/nodeshift-starters/devfile-sample
6. Press create

**Browser conformance**: 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2022-09-06 12:04 UTC, jerolimov commented
/jira refresh

2022-09-06 12:06 UTC, jerolimov commented
/cc @divyanshiGupta

2022-09-07 09:45 UTC, divyanshiGupta requested changes
@jerolimov `getPodLabels` is also used in `shared-submit-utils` as well.

2022-09-07 09:46 UTC, divyanshiGupta commented
/retest

2022-09-09 06:38 UTC, invincibleJai commented
/lgtm

2022-09-09 11:30 UTC, divyanshiGupta commented
/retest

2022-09-09 13:37 UTC, divyanshiGupta commented
/retest

2022-09-10 07:23 UTC, jerolimov commented
/retest

2022-09-12 07:14 UTC, jerolimov commented
/retest

2022-09-15 19:13 UTC, jerolimov commented
remove auto hold after CI job fails 3 times (unrelated to this PR)

/unhold

2022-09-16 03:13 UTC, merged