Bug 2115424: Helm chart Nodejs Ex K could not be installed via Form view
openshift/console pull request #12050
Opened 2022-09-14 17:45 UTC by Lucifergene

**Fixes**: 

https://issues.redhat.com/browse/OCPBUGSM-47478

**Analysis / Root cause**: 

Helm Chart "Nodejs Ex K" could not be installed via form mode.

**Solution Description**: 

The `formData` was being passed into a `Prune` function, which was used to remove all the empty and null objects and their keys. This caused the issue since for the form to be successfully executed, some of these deleted keys were required.

As the solution, the call to the `Prune` function is cancelled.

**Screen shots / Gifs for design review**: 

https://user-images.githubusercontent.com/47265560/190225629-d8852d8c-ecb1-46ce-9114-28d27fb72c66.mp4

**Unit test coverage report**: 

No Changes

**Test setup:**

1. Switch to Developer perspective
2. Navigate to Add > Helm Chart (catalog)
3. Search for nodejs and select "Nodejs Ex K"
4. Click on "Install Helm Chart"
5. Ensure the form view is opened (as yaml works fine)
6. Press Install

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

2022-09-14 17:46 UTC, Lucifergene commented
/cc @jerolimov @rottencandy

2022-09-15 06:07 UTC, Lucifergene commented
/retest

2022-09-15 10:21 UTC, rottencandy reviewed
Looks like pruning was added in https://github.com/openshift/console/pull/9897 as a bugfix
Would removing it cause [ODC-6225](https://issues.redhat.com/browse/ODC-6225) to happen again?

2022-09-15 14:37 UTC, Lucifergene commented
I verified the setup defined in [ODC-6225](https://issues.redhat.com/browse/ODC-6225).
The error is not recurring anymore.
(Verified in OpenShift version: 4.12.0-0.ci-2022-09-14-225342)


https://user-images.githubusercontent.com/47265560/190432520-dd315096-4e81-4a47-a505-5bea73e0c737.mp4

2022-09-16 08:17 UTC, rottencandy commented
I think the problem happens when switching before changing values.

https://user-images.githubusercontent.com/20013884/190591176-05244085-6ed1-43c6-a089-5bd9763dd58c.mp4

2022-12-19 10:25 UTC, Lucifergene commented
/remove-lifecycle stale

2023-03-31 07:21 UTC, jerolimov commented
/remove-lifecycle stale

2023-03-31 07:22 UTC, jerolimov commented
/retitle OCPBUGS-9447: Helm chart Nodejs Ex K could not be installed via Form view

2023-03-31 14:19 UTC, jerolimov requested changes
Hey Avik, this PR needs a rebase, after that I would like to take a fresh look

2023-04-06 12:10 UTC, closed without merging

2023-04-06 12:15 UTC, Lucifergene commented
Continuing the work on another PR. Attaching Link here once the new PR is up