Bug 2115265: Search page: LazyActionMenus are shown below Add/Remove from navigation button
openshift/console pull request #12187
Opened 2022-10-19 07:17 UTC by lokanandaprabhu

Fixes:
https://issues.redhat.com/browse/OCPBUGSM-47470

Analysis / Root cause:
In LazyActionMenu component, Popper is appended to parent, so the z-index was in-effective. 

Solution Description:
Detached popper component from parent like in ResourceKebab component 

Screen shots / Gifs for design review:

-------------- Before -------

<img width="1399" alt="Screenshot 2022-10-19 at 12 35 15 PM" src="https://user-images.githubusercontent.com/102503482/196621982-88e0e0f0-8e80-4b9f-a27d-a81da240258b.png">

<img width="415" alt="Screenshot 2022-10-19 at 12 35 37 PM" src="https://user-images.githubusercontent.com/102503482/196622001-f9e2bd84-501e-46b3-981b-cb36fbd1189c.png">

-------After-----------------

<img width="1387" alt="Screenshot 2022-10-19 at 12 33 51 PM" src="https://user-images.githubusercontent.com/102503482/196621974-05079e97-a36a-4e27-9369-adcb55e4fc85.png">

<img width="347" alt="Screenshot 2022-10-19 at 12 35 54 PM" src="https://user-images.githubusercontent.com/102503482/196622029-2a572cc5-75fa-40e9-99b6-2b6fbf93eb55.png">

**Unit test coverage report:**
NA

**Test setup:**
1. Navigate to the search
2. Open the resource selector and search for HelmChartRepo, select HelmChartRepositories and ProjectHelmChartRepositories
3. HCR should have at least one repo. Click on the action menu of the first table.

**Browser conformance**: 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2022-10-20 10:15 UTC, vikram-raj requested changes
There are multiple scrollbars if the dropdown goes out of the screen. See the GIF.
![Peek 2022-10-20 15-42](https://user-images.githubusercontent.com/2561818/196922169-c9d4fe23-cdb9-471a-9436-b2534518c552.gif)

2022-11-08 05:37 UTC, lokanandaprabhu commented
Hi @vikram-raj / @invincibleJai ,

The scrollbar issue is exists in all places where Popper component is used. There is already an issue for multiple scroll bar in user preference, https://issues.redhat.com/browse/OCPBUGSM-36604 , may be we can generalise this issue to correct multiple scroll bar in all the places where Popper component is used. 

Attached the video about multiple scrollbar issue in master branch,

https://user-images.githubusercontent.com/102503482/200483502-34ba3723-c3f7-4928-85fe-afa3a0cfb041.mov

2022-11-17 08:30 UTC, invincibleJai commented
@jerolimov WDYT about it?

2022-12-12 09:30 UTC, lokanandaprabhu commented
Hi @jerolimov / @vikram-raj ,

Need you review on this.

2023-02-03 15:15 UTC, jerolimov requested changes
This change works fine and I've tested different list views and didn't find any issue.

But since this `containerRef` was only used in a state in this component (in `LazyActionMenu` and `LazyMenuRenderer`) it would be great if we can remove it completely. There is no need to save it and pass it as a prop when we don't use it anymore.

You can also replace the `<div ref{containerRef}>...</div>` with just a Fragment: `<>...</>`.

2023-02-06 06:36 UTC, lokanandaprabhu commented
Hi @jerolimov ,

Updated the PR based on suggestion. PTAL. Thanks.

2023-02-06 08:53 UTC, jerolimov approved these changes
Tested it locally and works for me :+1:

/lgtm
/approve

2023-02-06 21:41 UTC, jerolimov commented
/retest

2023-02-13 05:37 UTC, lokanandaprabhu commented
/retest

2023-02-13 16:50 UTC, jerolimov commented
/retest

2023-02-14 22:05 UTC, jerolimov commented
/unhold

2023-02-15 07:00 UTC, merged

2023-02-16 18:50 UTC, jerolimov commented
/cherry-pick release-4.12