CONSOLE-3077: Promote ConsolePlugins API version to v1 in console repository
openshift/console pull request #12248
Opened 2022-11-07 12:51 UTC by jhadvig

Console should be using v1 version of the ConsolePlugin model rather then the old v1alpha1.

[CONSOLE-3077](https://issues.redhat.com/browse/CONSOLE-3077) was updating this version, but did not made the cut for the 4.12 release. Based on discussion with @spadgett  we should be backporting to 4.12.

The risk should be minimal since we are only updating the model itself + validation + Readme

2022-11-07 12:55 UTC, jhadvig commented
/jira refresh

2022-11-08 15:31 UTC, spadgett requested changes
/label backport-risk-assessed

2022-11-08 15:31 UTC, spadgett commented on frontend/public/module/k8s/types.ts
>  export type ConsolePluginKind = K8sResourceCommon & {
I believe a number of these fields should be optional, but don't have a `?` in the type definition.

2022-11-08 15:31 UTC, spadgett commented on dynamic-demo-plugin/README.md
> +`spec.proxy` array field. Each entry needs to specify ednpoint and alias of the proxy, under the `endpoint` and `alias` field. For the `Service` proxy type, endpoint's `type` field will need to be se
```suggestion
`spec.proxy` array field. Each entry needs to specify an endpoint and alias of the proxy under the `endpoint` and `alias` fields. For the `Service` proxy type, the endpoint's `type` field will need to be set to `Service` and the `service` must include a `name`, `namespace` and `port`.
```

2022-11-08 15:31 UTC, spadgett commented on dynamic-demo-plugin/README.md
> +needs to contain logged-in user's OpenShift access token, the `authorization`
```suggestion
needs to contain the logged-in user's OpenShift access token, the `authorization`
```

2022-11-08 15:31 UTC, spadgett commented on dynamic-demo-plugin/README.md
> +OpenShift access token, the `authorization` field needs to be set to `None`.
```suggestion
If the service proxy request shouldn't contain the logged-in user's
OpenShift access token, set the `authorization` field to `None`.
```

2022-11-08 15:31 UTC, spadgett commented on dynamic-demo-plugin/README.md
> +set `spec.i18n.loadType` field based on needed behavior. `Preload` will
```suggestion
set the `spec.i18n.loadType` field based on needed behavior. `Preload` will
```

2022-11-08 15:31 UTC, spadgett commented on dynamic-demo-plugin/README.md
> +instead will leave their loading to runtime's lazy-loading.
```suggestion
If set to `Lazy`, the plugin's localization resources won't be preloaded.
They will be lazy-loaded instead.
```

2022-11-08 15:32 UTC, spadgett commented
@jhadvig I know this is the backport. Can we make the above changes in master as well?

2022-11-11 14:43 UTC, jhadvig commented
@spadgett updated

2022-11-11 14:45 UTC, spadgett approved these changes
/lgtm

2022-11-14 12:42 UTC, jhadvig commented
/test e2e-gcp-console

2022-11-22 03:54 UTC, yapei commented
/label qe-approved
/label cherry-pick-approved

2022-11-28 09:54 UTC, jhadvig commented
/hold cancel
/retest

2022-11-29 07:54 UTC, jhadvig commented
/retest

2022-11-29 12:46 UTC, merged