OCPBUGS-2480: Task delete icon is not align properly on the Pipeline builder page
openshift/console pull request #12266
Opened 2022-11-14 11:39 UTC by Lucifergene

**Fixes**: 

https://issues.redhat.com/browse/OCPBUGS-2480

**Analysis / Root cause**: 

Delete task icon is not align properly on the Pipeline builder page

**Solution Description**: 

Added the `noVerticalAlign` parameter to the `TrashIcon` Component. 

**Screenshots / Gifs for design review**: 

Before:
![Screenshot from 2022-11-14 17-03-29](https://user-images.githubusercontent.com/47265560/201650647-dd7be66a-a43c-416b-aa2a-00725fddd4d6.png)

After:
![Screenshot from 2022-11-14 17-06-28](https://user-images.githubusercontent.com/47265560/201650672-0f2b7dbf-9f14-4541-944f-c19f3f5d75e0.png)

**Unit test coverage report**: 

Not Changed

**Test setup:**

1. Navigate to the Pipeline builder page.
2. click on Add task button and add a task
3. hover over the task and click on plus(+)
4. Hover over the Add task button and see the delete button in the corner

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2022-11-14 11:42 UTC, Lucifergene commented
/jira refresh

2022-11-15 09:05 UTC, vikram-raj requested changes

2022-11-16 10:44 UTC, Lucifergene commented on frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-topology/RemoveNodeDecorator.tsx
> +            <TrashIcon color="white" noVerticalAlign />
Thanks. Have updated the code

2022-11-16 20:01 UTC, Lucifergene commented
/retest

2022-11-23 13:05 UTC, vikram-raj approved these changes
/approve

/lgtm

2022-11-23 16:53 UTC, merged