OCPBUGS-2666: Add RBAC check on Create a Project link in all-namespaces pages
openshift/console pull request #12279
Opened 2022-11-18 11:12 UTC by vikram-raj

Fixes: https://issues.redhat.com/browse/OCPBUGS-2666

Descriptions: Add RBAC check on Create a Project link in all-namespaces pages in dev console

2022-11-24 15:42 UTC, vikram-raj commented
/cc @jerolimov

2022-12-05 09:28 UTC, vikram-raj commented
/test e2e-gcp-console

2023-01-26 20:31 UTC, jerolimov commented
/retest

2023-01-26 21:04 UTC, jerolimov commented on frontend/packages/dev-console/src/components/projects/CreateProjectListPage.tsx
> +
Below in `CreateProjectListPage` the `openProjectModal` callback is created and passed to the `CreateProjectListPage` `children`...

Just an idea, don't know if this works fine. You might be also can check the flag here and pass the button as optional the child? Wdyt?

```tsx
const canCreateProject = useFlag(FLAGS.CAN_CREATE_PROJECT);
const orProjectButton = canCreateProject && (
    <Trans t={t} ns="devconsole">
      {' or '}
      <Button isInline variant="link" onClick={openProjectModal}>
        create a Project
      </Button>
    </Trans>
)
```

and then:

```tsx
  return (
    <ProjectListPage {...props} title={title}>
      {children({ orProjectButton })}
    </ProjectListPage>
  );
```

Just an idea. If you prefer the current impl. that's fine for me. But we need to address the translation issues. (Unnecessary space and the full stop should be part of the translations.)

2023-01-26 21:06 UTC, jerolimov commented on frontend/packages/dev-console/src/components/builds/BuildsTabListPage.tsx
> +            )}
I believe you missed using your new component here, or is there a difference that I didn't see?

2023-01-26 21:06 UTC, jerolimov commented on frontend/packages/dev-console/src/components/catalog/CatalogPage.tsx
> +                </Trans>
I believe you missed using your new component here, or is there a difference that I didn't see?

2023-01-26 21:06 UTC, jerolimov commented on frontend/packages/dev-console/src/components/import/SamplesCatalog.tsx
> +                  </Trans>
I believe you missed using your new component here, or is there a difference that I didn't see?

2023-01-27 20:59 UTC, jerolimov commented
/retest

2023-01-27 23:29 UTC, jerolimov requested changes
Tested it with a cluster bot and removed the create project permission from `ClusterRole` `self-provisioner`, works fine.

But sorry, there is one S missing. :see_no_evil:

2023-01-27 23:29 UTC, jerolimov commented on frontend/packages/dev-console/src/components/ProjectSelectPage.tsx
> +            elect a Project to view the list of {{ projectLabelPlural }}
Nit :smirk: 

```suggestion
            Select a Project to view the list of {{ projectLabelPlural }}
```

2023-01-28 03:31 UTC, vikram-raj commented on frontend/packages/dev-console/src/components/ProjectSelectPage.tsx
> +            elect a Project to view the list of {{ projectLabelPlural }}
My bad. fixed it

2023-01-28 09:51 UTC, jerolimov approved these changes
/lgtm
/cherry-pick release-4.12

2023-01-28 14:42 UTC, merged

2023-01-28 17:01 UTC, vikram-raj commented
/cherry-pick release-4.12

2023-01-29 03:17 UTC, vikram-raj commented
Manual cherry-pick https://github.com/openshift/console/pull/12489