ODC-7177: Add SBO label selector support for Topology page
openshift/console pull request #12283
Opened 2022-11-21 11:30 UTC by PatAKnight

Fixes: [ODC-7177](https://issues.redhat.com/browse/ODC-7177)

**Description:**
This PR adds support for service binding resources that defines a label to bind to in the labelSelector field. This is the first implementation that focuses on drawing the connection between the workload that contains the label specified in the service binding resource to a service. This PR also includes an updated deletion message specifically for service binding resources using label selector to explicitly notify the user that deletion of the resource will remove all connections to other resources. 

This PR also updates some of the e2e tests that were failing. [RedisSecrets](https://github.com/redhat-developer/service-binding-operator/issues/1088) are optional with Redis and a recent update with SBO made it so that the binding will not throw an error. I also went in and updated some of the tests that use the Crunchy Postgres for Kubernetes operator. [Crunchy Postgress for Kubernetes 5.2.0](https://github.com/CrunchyData/postgres-operator/issues/3365) isn't currently compatible with Kubernetes 1.25, so the tests will fail when running on an Openshift 4.12 cluster.

**Screenshots / Video:**

https://user-images.githubusercontent.com/82788581/203034924-0aedff8c-0ec9-4c27-b251-1bbd849ab3f3.mp4

![7177-delete](https://user-images.githubusercontent.com/82788581/203035103-22deb892-6aac-4a31-8958-7cd7c79713df.png)

**Unit Test Coverage:**
![7177-test](https://user-images.githubusercontent.com/82788581/203035222-6f6de956-b3a3-4102-8ce7-6a3f681eea82.png)

**Test Setup:**
Install Service Binding operator
Install an operator that supports SBO (above video uses the Redis operator as an example)
Import from git (ensure there is a label defined in the resource, the above video uses "app=nodejs-ex-git)
Navigate to Add > Operator Backed, select "Bindable" 
Create Redis using default name "redis-standalone"
Navigate to Import YAML
Create CR
```
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: test-connector
spec:
  services:
    - group: redis.redis.opstreelabs.in
      version: v1beta1
      kind: Redis
      name: redis-standalone
  application:
    labelSelector:
      matchLabels:
        app: nodejs-ex-git
    group: apps
    version: v1
    resource: deployments
```

2022-11-21 14:09 UTC, jerolimov commented
/cc @divyanshiGupta @jerolimov @sanketpathak 
/assign @jerolimov

2022-11-21 14:19 UTC, PatAKnight commented
/cc @beaumorley 
/cc @serenamarie125

2022-11-21 14:41 UTC, PatAKnight commented
/retest

2022-11-21 17:24 UTC, PatAKnight commented
/retest

2022-11-28 12:35 UTC, PatAKnight commented
/retest

2022-11-29 11:18 UTC, divyanshiGupta requested changes

2022-12-02 16:04 UTC, divyanshiGupta commented
@PatAKnight  Please run `yarn i18n` to update the i18n files and push the changes.

2022-12-02 16:54 UTC, PatAKnight commented on frontend/packages/console-app/src/actions/creators/common-factory.ts
> +    _relatedResource: undefined,
Updated with the fix

2022-12-02 21:12 UTC, PatAKnight commented
/retest

2022-12-05 12:31 UTC, PatAKnight commented
/retest

2022-12-05 18:43 UTC, PatAKnight commented
/retest

2022-12-06 06:51 UTC, sanketpathak commented
@PatAKnight Can you remove the broken-test tag [here](https://github.com/openshift/console/blob/3ea52056b9f8e486599353fc044336eae4c2a6c0/frontend/packages/topology/integration-tests/features/topology/topology-chart-area-visual.feature#L428)
And remove the installation steps for Red Hat OpenShift distributed tracing platform operator [here](https://github.com/openshift/console/blob/3ea52056b9f8e486599353fc044336eae4c2a6c0/frontend/packages/topology/integration-tests/features/topology/topology-chart-area-visual.feature#L448) as you have changed the operator name

2022-12-06 13:41 UTC, PatAKnight commented
@sanketpathak updated the PR based on your suggestions.

2022-12-07 13:07 UTC, PatAKnight commented
/retest

2022-12-07 17:29 UTC, PatAKnight commented
/retest

2022-12-07 20:30 UTC, PatAKnight commented
/retest

2022-12-08 01:19 UTC, PatAKnight commented
/retest

2022-12-08 12:39 UTC, PatAKnight commented
/retest

2022-12-08 18:21 UTC, PatAKnight commented
/retest

2022-12-13 15:16 UTC, sanketpathak commented
@PatAKnight Last two test cases are failing on my system
![Screenshot from 2022-12-13 20-45-02](https://user-images.githubusercontent.com/10252230/207371686-ed41d24f-4fa3-4185-8d2f-be2948c703ed.png)

2022-12-14 00:50 UTC, PatAKnight commented
/retest

2022-12-14 06:50 UTC, divyanshiGupta commented
/label docs-approved
/label px-approved

2022-12-14 07:21 UTC, divyanshiGupta commented
@PatAKnight The PR looks good and working as expected. 
/lgtm

2022-12-15 03:57 UTC, merged