Introduction of multi cluster menu filter capability
openshift/console pull request #12366
Opened 2022-12-13 19:15 UTC by sg00dwin

Convert existing cluster `Dropdown` to use PatternFly `MenuToggle` and `Menu` components, which includes filtering with search input option, along with built in capabilities to support grouping, isSelected and favoriting functionality. 

https://issues.redhat.com/browse/CONSOLE-3120

![cluster-menu-selector](https://user-images.githubusercontent.com/1874151/207424097-e0b6e1b1-d831-49bd-aa4d-2f3b11327176.gif)

2022-12-14 16:39 UTC, TheRealJon requested changes
A couple of adjustments, but it looks good so far! One recommendation I have would be to break out a new ClusterDropdown component. We have a lot of dropdown management logic in the NavHeader component that arguably doesn't belong here.

2023-01-04 22:13 UTC, sg00dwin commented on frontend/packages/console-app/src/components/nav/NavHeader.tsx
> +            disabled={false}
If I remove this it give the following error `Property 'disabled' is missing in type`

2023-01-05 14:07 UTC, sg00dwin commented
/retest

2023-01-05 17:48 UTC, TheRealJon requested changes
Some adjustments and a couple of concerns:
- "All Clusters" might not show a selected state when it is the currently selected item
- "All Clusters" item seems to be excluded from filtering

2023-01-16 13:51 UTC, jhadvig commented
@sg00dwin we need to rebase this one.

2023-01-18 02:56 UTC, jcaianirh requested changes
Aside from the changes requested, theres a bug with this code as follows:
When viewing a workload in a namespace on the hub cluster, then change the cluster to a spoke (or vice versa) the namespace value becomes the string undefined causing errors on the page. The undefined string also appears in the url for the page. I haven't found why/where that code change is but I can try and help find it.

2023-01-18 02:56 UTC, jcaianirh commented on frontend/packages/console-app/src/components/nav/ClusterMenu.tsx
> +          >
data-test-id="cluster-dropdown-item"

add this for e2e tests to access the menu item. if you want a better name, then the test id used here should match the one in nav.ts...ie cluster-menu-item 

cc: @TheRealJon

2023-01-18 02:56 UTC, jcaianirh commented on frontend/packages/console-app/src/components/nav/ClusterMenuToggle.tsx
> +    >
data-test-id="cluster-dropdown-toggle"

same as previous data-test-id comment wrt id name value

2023-01-20 18:39 UTC, sg00dwin commented
/test frontend

2023-01-23 21:07 UTC, jcaianirh commented
/test frontend

2023-01-25 12:15 UTC, jcaianirh commented
/retest

2023-01-26 22:01 UTC, jcaianirh approved these changes

2023-01-27 05:53 UTC, jcaianirh commented
QE Approver:
/assign @yapei

Docs Approver:
/assign @opayne1

PX Approver:
/assign @RickJWagner

Console Approver:
/assign @rhamilto

2023-01-27 14:13 UTC, spadgett commented
@rhamilto FYI since you're working on the masthead changes.

2023-01-27 14:57 UTC, opayne1 commented
/label docs-approved

2023-01-27 16:20 UTC, RickJWagner commented
/label px-approved

Thank you for providing the screen capture in this issue.

2023-02-01 12:46 UTC, rhamilto commented
/label tide/merge-method-squash

2023-02-01 19:37 UTC, rhamilto commented
/lgtm

2023-02-04 08:09 UTC, yapei commented
1. it looks like the cluster filter menu boundary will be enlarged when no results match the filter criteria
<img width="305" alt="no-clusters-found" src="https://user-images.githubusercontent.com/12692381/216756517-a046b527-0425-4741-8854-798f34acbd32.png">

2023-02-04 08:41 UTC, yapei commented
tested and no medium above issue found, clusters are ordered correct in filter dropdown
/label qe-approved

2023-02-04 14:51 UTC, merged