[WIP] ODC-7226: update helm install and upgrade flow
openshift/console pull request #12437
Opened 2023-01-17 17:59 UTC by debsmita1

**JIRA story:**
https://issues.redhat.com/browse/ODC-7226

**Solution description:**
- Using the api `/api/helm/release/async` for installing and upgrading helm charts
- When creating a Helm Release, if there are no workloads to be generated by a release's chart then navigate the user to the Helm Release details page otherwise navigating the user to the topology page with the release notes(if exists) tab opened in the side panel
- Added helm release grouping with installation status
- Disable "Upgrade" and "Rollback" options from the context menu and action dropdown on the side panel when the install/upgrade/rollback is in progress

**GIF:**

2023-01-18 09:45 UTC, lokanandaprabhu commented on frontend/packages/console-dynamic-plugin-sdk/src/app/components/status/Status.tsx
>        return <StatusIconAndText {...statusProps} icon={<BanIcon />} />;
Can you add "Uninstalled" status as well?

2023-01-19 05:13 UTC, lokanandaprabhu commented on frontend/packages/console-dynamic-plugin-sdk/src/app/components/status/Status.tsx
>        return <StatusIconAndText {...statusProps} icon={<BanIcon />} />;
`export const OtherReleaseStatuses = ['unknown', 'uninstalled', 'superseded', 'uninstalling'];`

In `OtherReleaseStatuses`, we added `uninstalled` as well. So I thought better to add it.

Let's not consider if it is not necessary.

2023-01-23 16:38 UTC, debsmita1 commented
/cc @serenamarie125

2023-01-24 17:28 UTC, serenamarie125 commented
Looks great @debsmita1 - just commenting that I did confirm that the recordings were done when running locally, thus does not reflect expected performance! 

Could you also confirm that if you hit Create - you could navigate to another page to perform another task, without interrupting the creation (this is implied, but want to confirm)

2023-01-25 15:04 UTC, jerolimov requested changes
Works fine. :+1:

I found small some code improvements. But we can also merge this and follow up with a small improvement PR. At least if the CI passes before you're back from PTO. :man_facepalming: 

/lgtm
/approve

2023-01-25 15:40 UTC, jerolimov commented
Propagating docs and px acks from the Epic
/label docs-approved
/label px-approved

If this passes the CI we will fix the mentioned issues in #12432, if not we will go with the other PR first and this will need some rework.
/approve
/retest

2023-01-30 08:24 UTC, jerolimov commented on frontend/packages/helm-plugin/src/utils/helm-utils.ts
> +    .join('');
@lokanandaprabhu in your PR I understand that this is just to calculate an internal status string, not the label. Then this is fine!

2023-01-31 15:27 UTC, jerolimov commented
Thanks @debsmita1 for the initial work. @lokanandaprabhu picked this up in PR #12502

/close

2023-01-31 15:27 UTC, closed without merging