ODC-7225: Update Helm Releases list page and the details page
openshift/console pull request #12432
Opened 2023-01-16 06:04 UTC by lokanandaprabhu

**JIRA story:**
https://issues.redhat.com/browse/ODC-7225

**Description**:
Users should able to see the correct status on the list page and on the details page when a helm release is installed.
1) Showing the status of the helm release in the correct format on the helm releases list page and on the details page next to the release name and on the revision history page
2) Added status information under the details tab
3) Showing an empty state for the Resources tab when the installation is pending
4) Disabled the "Upgrade" and "Rollback" options in the kebab menu in the list page and Actions dropdown on the details page when the installation/upgrade/rollback is in pending

**Demo:**

https://user-images.githubusercontent.com/102503482/212607235-f25f884e-5c37-438f-b070-3710d0dc5dc7.mov

**Tests:**
<img width="570" alt="Screenshot 2023-01-16 at 11 25 19 AM" src="https://user-images.githubusercontent.com/102503482/212608771-f2e51b93-cb07-4c1d-8e5e-5d57774a0fc8.png">

**How to test:**
Install gitlab helm chart to test pending-install, pending-upgrade and pending-rollback status.

2023-01-16 06:04 UTC, lokanandaprabhu commented
/assign @debsmita1

2023-01-17 16:19 UTC, debsmita1 requested changes

2023-01-19 18:34 UTC, debsmita1 commented
/cc @serenamarie125

2023-01-24 17:19 UTC, serenamarie125 approved these changes
LGTM!

2023-01-25 07:07 UTC, debsmita1 commented
/lgtm
/cc @sanketpathak

2023-01-27 13:02 UTC, hemantsaini-7 commented
tested using cluster-bot

https://user-images.githubusercontent.com/65410551/215092771-9e3cfe51-d78c-4e85-bb11-2cc482904673.mov




tests are green
<img width="571" alt="Screenshot 2023-01-27 at 5 41 02 PM" src="https://user-images.githubusercontent.com/65410551/215091865-eb7cf4ae-6c3f-4e29-8abb-0ed36d050afa.png">

/label qe-approved

2023-01-27 15:43 UTC, jerolimov approved these changes
I think we could add i18n for the helm status. But since we don't do this before I don't want block this PR for this.

/lgtm
/approve

2023-01-27 15:43 UTC, jerolimov commented
Propagating docs and px acks from the Epic
/label docs-approved
/label px-approved

2023-01-27 16:24 UTC, merged