k8sResourcePrefix x-descriptor labelSelector filtering support
openshift/console pull request #12525
Opened 2023-02-02 17:10 UTC by eduardo-at

Closes #11747

Adds an optional label selector to the k8sResourcePrefix x-descriptor,
The syntax follows the URI standards so the character '?' is used to begin the query and '+' to encode spaces, the label query is a standard Kubernetes label selector and can be equity based or set based. https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/

So when combined with spec descriptors, 
the syntax `urn:alm:descriptor:io.kubernetes:ServiceAccount?label!=test,level=production` should render a dropdown listing only the ServiceAccounts that match the equity based label selector, 
while the syntax  `urn:alm:descriptor:io.kubernetes:ServiceAccount?environment+in+(production,qa)` should list the ServiceAccounts that match the set-based label selector.

2023-02-21 19:20 UTC, ivandov commented
What is needed to get this PR into testing?

2023-04-05 19:24 UTC, spadgett commented
/assign @TheRealJon 
/ok-to-test

2023-04-21 21:00 UTC, TheRealJon requested changes
Overall this feature looks good! Just some implementation details that need attention. Alos, @tlwu2013 made the point that we should probably indicate to the user in some way that the dropdown is being filtered to prevent confusion.

2023-04-21 21:00 UTC, TheRealJon commented on frontend/packages/operator-lifecycle-manager/src/components/operand/utils.ts
> +  }
If we capture all tokens with one regex expression, we should be able to simplify this.
```suggestion
  const [, groupVersionKindToken, selectorToken] = capability.match(REGEXP_K8S_RESOURCE_SUFFIX) ?? [];
  const groupVersionKind = groupVersionKindToken?.replace(/:/g, '~');
  const selector = selectorFromString(selectorToken?.replace(/\+/g, ' '));
```

2023-04-21 21:00 UTC, TheRealJon commented on frontend/public/components/utils/list-dropdown.jsx
> +      selector: PropTypes.string,
This type conflicts with the Firehose type
```suggestion
      selector: PropTypes.object,
```

2023-04-24 18:47 UTC, eduardo-at commented on frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/k8s-resource.ts
> +      }
Understood, thanks for reviewing and adding comments, this was very helpful, I've removed this logic and implemented the proposed changes.

2023-04-24 18:48 UTC, eduardo-at commented on frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/k8s-utils.ts
> +export const requirementFromString = (string: string) => {
Noted, I've removed the function and implemented your previous suggestion.

2023-04-24 19:19 UTC, eduardo-at commented
@TheRealJon Great feedback, I appreciate the code suggestions, are those required to be commited individually with the "Commit suggestion" prompt? I pushed everything in a new commit to avoid writing commit messages but I can reset the commit and merge the suggestions if that is the process to follow.

As for @tlwu2013 comment, That's up for discussion, I present the following suggestion:
<img width="825" alt="image" src="https://user-images.githubusercontent.com/117455270/234093391-1235a8ce-fb9c-4be1-8f6b-11c6a5fe68ad.png">

2023-04-24 22:25 UTC, eduardo-at commented
/retest

2023-04-25 20:30 UTC, TheRealJon requested changes
A couple of other things I caught when looking over this one more time.
We also need to update the [API reference](https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md) to document this new feature.

2023-04-25 20:30 UTC, TheRealJon commented on frontend/packages/console-dynamic-plugin-sdk/src/utils/k8s/__tests__/k8s-resource.spec.ts
All changes in this file can be removed.

2023-04-25 20:30 UTC, TheRealJon commented on frontend/packages/operator-lifecycle-manager/src/components/operand/utils.spec.ts
> +    expect(uiSchema['ui:options'].selector).toEqual('label!=test,level=production');
These test cases need to be updated. A Selector object is expected now:
```suggestion
    expect(uiSchema['ui:options'].selector).toEqual(
      selectorFromString('label!=test,level=production')
    );
```

2023-04-25 20:30 UTC, TheRealJon commented on frontend/packages/operator-lifecycle-manager/src/components/operand/utils.ts
> +  const selector = selectorFromString(selectorToken?.replace(/\+/g, ' '));
On a second glance, we probably don't need to encode/decode space characters using '+'. An x-descriptor with spaces in it is perfectly valid.
```suggestion
  const selector = selectorFromString(selectorToken);
```

2023-04-27 14:14 UTC, TheRealJon approved these changes
Thanks for your contribution! This was a nice improvement!
/lgtm

2023-04-27 18:52 UTC, RickJWagner commented
Looks like a useful change.  Thanks for this.

/label px-approved

2023-04-27 19:52 UTC, opayne1 commented
/label docs-approved

2023-05-02 14:50 UTC, rhamilto commented
@eduardo-at, QE found a bug in this PR.  See https://issues.redhat.com/browse/OCPBUGS-12891.  Do you want to look at fixing it, or shall I?  cc: @jhadvig

2023-05-02 19:43 UTC, eduardo-at commented
@rhamilto Thank you, I'll take a look but I don't want to be a blocker so if you happen to spot the issue you're more than welcome to fix it.
Where is this "Component trace" I see in the bug report coming from? is it the Javascript console? or some other tool?
I haven't been able to replicate this, but I've just requested access to the "mock-crd-and-csv.yaml and screenshot" files so I can investigate further.

2023-05-02 20:47 UTC, rhamilto commented
Thanks @eduardo-at!

> Where is this "Component trace" I see in the bug report coming from? is it the Javascript console? 

Yeah, it's from the console. It's not super helpful since the error is from a production build where the component names are obfuscated.

> I haven't been able to replicate this, but I've just requested access to the "mock-crd-and-csv.yaml and screenshot" files so I can investigate further.

The screenshot isn't any more helpful than what's in the bug already.  I'll include the yaml here so you're not blocked as I believe QE is on holiday.

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mock-k8s-dropdown-resources.test.tectonic.com
spec:
  group: test.tectonic.com
  scope: Namespaced
  names:
    plural: mock-k8s-dropdown-resources
    singular: mock-k8s-dropdown-resource
    kind: MockK8sDropdownResource
    listKind: MockK8sDropdownResources
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            type: object
            properties:
              k8sResourcePrefix:
                type: string
              k8sResourcePrefixNoFilter:
                type: string
              k8sResourcePrefixEquityFilter:
                type: string
              k8sResourcePrefixSetFilter:
                type: string
              k8sResourcePrefixNone:
                type: string
        required:
        - spec
        type: object
    served: true
    storage: true
---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: mock-k8s-resource-dropdown-operator
  labels:
    automatedTestName: uiautotest
  annotations:
    alm-examples: '[{"apiVersion":"test.tectonic.com/v1","kind":"MockK8sDropdownResource","metadata":{"name":"mock-k8s-dropdown-resource-instance", namespace: "uiautotest"}}]'
spec:
  displayName: Mock K8sResourcePrefixOperator
  install:
    strategy: deployment
    spec:
      permissions: []
      deployments:
        - name: test-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: test-operator-alm-owned
            template:
              metadata:
                name: test-operator-alm-owned
                labels:
                  name: test-operator-alm-owned
              spec:
                serviceAccountName: test-operator
                containers:
                  - name: test-operator
                    image: nginx
  customresourcedefinitions:
    owned:
      - name: mock-k8s-dropdown-resources.test.tectonic.com
        version: v1
        kind: MockK8sDropdownResource
        displayName: Mock Resource
        description: Mock resource instance for testing descriptors
        resources: []
        specDescriptors:
          - path: k8sResourcePrefix
            description: Spec descriptor for k8sResourcePrefix
            displayName: Descriptor Generated K8s Resource Prefix
            x-descriptors:
              - "urn:alm:descriptor:io.kubernetes:test.tectonic.com:v1:MockK8sDropdownResource"
          - path: k8sResourcePrefixNoFilter
            description: k8sResourcePrefix without filter
            displayName: Generated K8s Resource Prefix without filters
            x-descriptors:
              - "urn:alm:descriptor:io.kubernetes:Secret"
          - path: k8sResourcePrefixEquityFilter
            description: k8sResourcePrefix with filters
            displayName: K8s Resource Prefix with equity based label selector filtering
            x-descriptors:
              - "urn:alm:descriptor:io.kubernetes:Secret?test=true,level!=production"
          - path: k8sResourcePrefixSetFilter
            description: k8sResourcePrefix with filters
            displayName: K8s Resource Prefix with set-based label selector filtering
            x-descriptors:
              - "urn:alm:descriptor:io.kubernetes:Secret?level+in+(production,staging)"
          - path: k8sResourcePrefixNone
            description: k8sResourcePrefix with filters
            displayName: K8s Resource Prefix with selector filtering no resources found
            x-descriptors:
              - "urn:alm:descriptor:io.kubernetes:Secret?testlabel"
 ```

2023-05-02 22:12 UTC, eduardo-at commented
@rhamilto Thank you for posting the yaml file, I think I found the issue,
we chose to allow spaces instead of encoding them with '+', so

` - "urn:alm:descriptor:io.kubernetes:Secret?level+in+(production,staging)"`
should be: 
`- "urn:alm:descriptor:io.kubernetes:Secret?level in (production,staging)"
`

I was able to replicate it and this fixed the error.

2023-05-05 06:31 UTC, yapei commented
@eduardo-at Shall we avoid invalid filters blocking operand creation? with that being said I mean shall we still show the operand creation form instead of error page even invalid filter syntax exist?

2023-05-09 01:12 UTC, yapei commented
about whether we should prevent console from completely failing when there is invalid x-descriptor is a general issue, will address in separate JIRA, approving this PR since no issues found
/label qe-approved

2023-05-09 11:43 UTC, rhamilto commented
@eduardo-at, you have all the necessary approvals, but the merge queue is currently frozen and will re-open on or around  May 29th (if not sooner for just the console).  No further action is required at this time, but wanted to give you the heads up in the event you were wondering why the PR hasn't merged.  The PR will automatically merge once the queue is re-opened.

2023-05-09 18:54 UTC, merged