ODC-7198: Show type of sample on the samples view
openshift/console pull request #12548
Opened 2023-02-08 16:04 UTC by Lucifergene

**Fixes**: 
https://issues.redhat.com/browse/ODC-7198

**Solution Description**: 
Added a condition in the CatalogTileBadge component which will check the href of the item to decide whether its a Builder Image/Devfile and show it in the Badge. 
The condition also checks that the DeveloperCatalog Page, which also uses the same component, does not get affected by this change.

**Screen shots / Gifs for design review**: 

**Before:**
![sssss](https://user-images.githubusercontent.com/47265560/217583636-3ad22359-00ce-4e0e-a892-c3d563bcca3e.png)

**After:**
![asdasdddd](https://user-images.githubusercontent.com/47265560/217582761-9346af6b-c3c5-43dd-b410-c9034bbecd1b.png)

**Unit test coverage report**: 
No changes.

**Test setup:**
1. Go to the Samples Page from the Add Page.
2. Check the Badges displayed on the right of each tile. 

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

2023-02-08 16:06 UTC, Lucifergene commented
/cc @jerolimov

2023-02-08 16:11 UTC, Lucifergene commented
/label component/dev-console

2023-02-13 10:29 UTC, Lucifergene commented
/retest

2023-02-13 15:59 UTC, debsmita1 commented
@Lucifergene can you check if we need this in the QuickSearchList ?

2023-02-13 18:08 UTC, debsmita1 commented
/lgtm

2023-02-14 08:37 UTC, Lucifergene commented
/label px-approved
/label docs-approved

2023-02-14 09:59 UTC, Lucifergene commented
/jira refresh

2023-02-14 10:00 UTC, Lucifergene commented
/jira refresh

2023-02-14 10:01 UTC, jerolimov requested changes
The catalog data are created via an extension mechanism.

The items are loaded via an item provider, you can search for `console.catalog/item-provider"`  to find the implementation or `console.catalog/item-provider` to find also the extension definition.

Both, the developer catalog and the samples use different provider sets.

For the devfiles:

```json
  {
    "type": "console.catalog/item-provider",
    "properties": {
      "catalogId": "dev-catalog",
      "type": "Devfile",
      "title": "%devconsole~Devfiles%",
      "provider": { "$codeRef": "catalog.devfileProvider" }
    },
    "flags": {
      "required": ["OPENSHIFT"]
    }
  },
```

and

```json
  {
    "type": "console.catalog/item-provider",
    "properties": {
      "catalogId": "samples-catalog",
      "type": "Sample",
      "title": "%devconsole~Devfiles%",
      "provider": { "$codeRef": "catalog.devfileSamplesProvider" }
    },
    "flags": {
      "required": ["OPENSHIFT"]
    }
  },
```

When you search then for `devfileProvider` and `devfileSamplesProvider` you will find two different implementations.

I think its more clear to change the `type` in `devfileSamplesProvider` then. Similar for Builder images.

2023-02-14 14:21 UTC, jerolimov commented
/remove-label docs-approved
/remove-label px-approved

2023-02-14 22:55 UTC, jerolimov approved these changes
Tested it locally and works fine :+1:

/lgtm
/approve

2023-02-15 19:46 UTC, Lucifergene commented
/test e2e-gcp-console

2023-02-16 09:41 UTC, Lucifergene commented
/unhold

2023-02-16 09:42 UTC, Lucifergene commented
/retest

2023-02-16 13:11 UTC, Lucifergene commented
/retest

2023-02-16 23:15 UTC, jerolimov commented
@Lucifergene some tests fails with this error, can you check if you need to update some e2e tests here?

```
  1) Create the different workloads from Add page
       Create Sample Application from Add page: GS-03-TC05 (example #1):
     AssertionError: Timed out retrying after 40000ms: Expected to find element: `a[data-test="Sample-Httpd"] .catalog-tile-pf-title`, but never found it.
```

/hold

2023-02-17 11:49 UTC, Lucifergene commented
/unhold

2023-02-17 13:48 UTC, Lucifergene commented
/test e2e-gcp-console

2023-02-22 09:36 UTC, invincibleJai commented
/retest

2023-02-22 09:53 UTC, jerolimov approved these changes
/lgtm

2023-02-24 06:07 UTC, invincibleJai commented
/unhold
/retest

2023-02-25 17:48 UTC, jerolimov commented
/retest

2023-02-26 21:57 UTC, jerolimov commented
/unhold
/retest

2023-02-28 03:09 UTC, invincibleJai commented
/unhold
/retest

2023-03-03 00:58 UTC, jerolimov requested changes
/lgtm cancel

The CI - and UX - issue is that the topology quick search shows now "Builder Images" instead of "Samples" as well.

CI issue could be found in topology-ci.feature:

![image](https://user-images.githubusercontent.com/139310/222604159-020d8469-87bf-472a-a649-33880d9e6202.png)

Before:

![image](https://user-images.githubusercontent.com/139310/222604002-548db022-6ae6-401f-81f6-34723b632bda.png)

With this PR:

![image](https://user-images.githubusercontent.com/139310/222604047-eeb5f699-d056-482e-a2ee-91946bbd3dee.png)


We reuse the same Samples catalog here. On the add page, the Samples list and the Developer catalog are splitted, so we can (and should) show there "BuilderImages" and "Devfiles" because the user knows the context.

But technically we use the same catalog in the topology quick search as well. But showing BuilderImages (for S2I)  BuilderImages (for a Sample) is confusing.

We should check the exact expectations with @serenamarie125 first.

2023-03-06 14:26 UTC, Lucifergene commented
/test e2e-gcp-console

2023-03-07 07:03 UTC, jerolimov approved these changes
:+1:

/lgtm
/unhold

2023-03-07 07:06 UTC, merged

2023-03-09 14:55 UTC, Lucifergene commented
/jira refresh

2023-03-13 07:30 UTC, Lucifergene commented
/cherry-pick release-4.13