Fixes card sizes not even issue when commit info is not available on Environments page
openshift/console pull request #12550
Opened 2023-02-09 00:15 UTC by ciiay

Fixes [[gitops-2476: [UI] Card size is not the same when commit information is not available](https://issues.redhat.com/browse/GITOPS-2476).

signed by: [yicai@redhat.com](mailto:yicai@redhat.com)

Screenshot after fix:
![Screenshot 2023-02-08 at 7 02 26 PM](https://user-images.githubusercontent.com/26255262/217680537-07f68488-c2e1-4845-8c38-83cb6d337e2e.png)

2023-02-09 19:37 UTC, ciiay commented
/test e2e-gcp-console

2023-02-10 16:19 UTC, ciiay commented
/test e2e-gcp-console

2023-02-13 14:24 UTC, ciiay commented
/test e2e-gcp-console

2023-03-10 16:30 UTC, debsmita1 requested changes

2023-03-10 16:30 UTC, debsmita1 commented on frontend/packages/gitops-plugin/src/components/details/GitOpsDetails.tsx
> +                              <span>{t('gitops-plugin~Commit message not available')}</span>
```suggestion
                              {t('gitops-plugin~Commit message not available')}
```

2023-03-10 18:55 UTC, ciiay commented
/test e2e-gcp-console

2023-03-13 12:35 UTC, lokanandaprabhu commented on frontend/packages/gitops-plugin/locales/ja/gitops-plugin.json
>  }
No need to add the translation other than English at this time.

2023-03-13 12:35 UTC, lokanandaprabhu commented on frontend/packages/gitops-plugin/locales/ko/gitops-plugin.json
>  }
No need to add the translation other than English at this time.

2023-03-13 12:35 UTC, lokanandaprabhu commented on frontend/packages/gitops-plugin/locales/zh/gitops-plugin.json
> +  "Last deployed time not available": "最后部署的时间不可用"
No need to add the translation other than English at this time.

2023-03-13 12:36 UTC, lokanandaprabhu commented on frontend/packages/gitops-plugin/src/components/details/GitOpsDetails.tsx
> +                        </StackItem>
{t('gitops-plugin~Last deployed time not available')}

2023-03-13 20:11 UTC, ciiay commented
/test e2e-gcp-console

2023-03-14 09:27 UTC, lokanandaprabhu commented
I cloned your ticket as https://issues.redhat.com/browse/OCPBUGS-10230 to follow our bug tracking and merge process.


/retitle OCPBUGS-10230: Fixes card sizes not even issue when commit info is not available on Environments page

2023-03-14 09:46 UTC, lokanandaprabhu commented
Tested locally. 

<img width="1240" alt="Screenshot 2023-03-13 at 7 08 41 PM" src="https://user-images.githubusercontent.com/102503482/224961729-cd1f5bbd-73c6-4221-b95b-625964e7ad7c.png">

/lgtm

2023-03-14 09:47 UTC, lokanandaprabhu commented
/retest

2023-03-14 10:23 UTC, jerolimov approved these changes
/approve

2023-03-14 10:27 UTC, lokanandaprabhu commented
/jira refresh

2023-03-14 14:01 UTC, ciiay commented
/cherry-pick release-4.13

2023-03-14 23:21 UTC, merged