OCPBUGS-7620: Edit Deployment (and DC) form doesn't enable Save button when changing strategy type
openshift/console pull request #12608
Opened 2023-02-27 08:27 UTC by aneeshmbhat

**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-7620

**Analysis / Root cause**: 
Initial Formik value is set to final formik value on change of dropdown items so the save button doesn't get enabled since there is no difference between initial & final formik value

**Solution Description**: 
Removed setting of initial formik value on change of dropdown item

**Screen shots / Gifs for design review**: 

--Before fix--

https://user-images.githubusercontent.com/122968482/221510829-d91dfd63-5302-4a74-a6b9-d0e4592c9327.mp4

\
--After fix--
  
https://user-images.githubusercontent.com/122968482/221510842-24baacca-282f-4a77-9c7d-6ad5b267f0fe.mp4

\
**Unit test coverage report**: 
NA

**Test setup:**
1. go to developer's perspective
2. create deployment or deployment config
3. click on edit deployment or deployment config
4. change deployment strategy type

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2023-02-28 03:50 UTC, invincibleJai commented
/ok-to-test
/cc @lokanandaprabhu

2023-03-09 18:20 UTC, Lucifergene reviewed
@aneeshmbhat When I am creating a deployment from an ImageStream, upon editing the deployment, I cannot save the changes made to the Deployment Strategy from the Form View. Instead, I have to switch to the YAML View to save the strategy change. 

Attached is a video: 

https://user-images.githubusercontent.com/47265560/224118897-257bf703-ddd7-4dba-89db-55fce4ede967.mp4

2023-03-10 08:06 UTC, debsmita1 commented on frontend/packages/dev-console/src/components/deployments/deployment-strategy/DeploymentStrategySection.tsx
> +      initialValues.formData.deploymentStrategy.type = oldType;
I think you won't need to set the initial values like this, 'cause we are already doing 
`setFieldValue('formData.deploymentStrategy', strategyData);`

Test the code after removing the usage of "initialValues" in this callback func

2023-03-13 06:10 UTC, aneeshmbhat commented
@Lucifergene @debsmita1 I've updated the PR, PTAL

2023-03-16 15:52 UTC, aneeshmbhat commented
> @aneeshmbhat When I am creating a deployment from an ImageStream, upon editing the deployment, I cannot save the changes made to the Deployment Strategy from the Form View. Instead, I have to switch to the YAML View to save the strategy change.
> 
> Attached is a video:

Regarding this a new issue has been made, https://issues.redhat.com/browse/OCPBUGS-10411
I'm looking into it

2023-03-16 15:54 UTC, aneeshmbhat commented
@Lucifergene @debsmita1 I've updated the PR, PTAL

2023-03-17 17:13 UTC, debsmita1 requested changes

2023-03-20 06:25 UTC, aneeshmbhat commented on frontend/packages/dev-console/src/components/import/image-search/ImageStreamTagDropdown.tsx
> +  const { name: resourceName, imageStream, application, formType, isi: isiValues } =
isi is already defined, so I kept another name for it here

2023-03-20 06:25 UTC, aneeshmbhat commented on frontend/packages/dev-console/src/components/import/image-search/ImageStreamTagDropdown.tsx
> +  const isiPorts = isiValues?.ports;
isi is already defined, so I kept another name for it here

2023-03-20 15:56 UTC, Lucifergene commented
/retest

2023-03-21 06:37 UTC, merged