ODC-7281: Provide Column management option for the TaskRuns list page
openshift/console pull request #12689
Opened 2023-03-30 10:02 UTC by aneeshmbhat

**Story**: 
https://issues.redhat.com/browse/ODC-7281

**Description**: 
Added Button with associated Modal for handling Column Management

**Screen shots / Gifs for design review**: 

https://user-images.githubusercontent.com/122968482/228800792-9fb5a256-40b5-4ba4-81f6-355654a08cf9.mp4

\
**Unit test coverage report**: 
WIP

**Test setup:** 
- Install Pipelines Operator
- Create a TaskRun

**Browser conformance**: 

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2023-03-30 11:41 UTC, aneeshmbhat commented
/retest

2023-03-30 11:45 UTC, vikram-raj commented
@aneeshmbhat  Frontend tests are failing because the Translation file is not up to date. Please Run `yarn i18n` locally and update the PR.

2023-03-30 13:45 UTC, vikram-raj requested changes

2023-03-30 13:45 UTC, vikram-raj commented on frontend/packages/pipelines-plugin/src/components/taskruns/list-page/TaskRunsListPage.tsx
> +      additional: true,
Translation namespace should be `pipelines-plugin`

```suggestion
  const getColumns = (): TableColumn<TaskRunKind>[] => [
    {
      title: t('pipelines-plugin~Name'),
      id: 'name',
    },
    {
      title: t('pipelines-plugin~Namespace'),
      id: 'namespace',
    },
    {
      title: t('pipelines-plugin~Pipeline'),
      id: 'pipeline',
    },
    {
      title: t('pipelines-plugin~Task'),
      id: 'task',
    },
    {
      title: t('pipelines-plugin~Pod'),
      id: 'pod',
    },
    {
      title: t('pipelines-plugin~Status'),
      id: 'status',
    },
    {
      title: t('pipelines-plugin~Started'),
      id: 'started',
    },
    {
      title: t('pipelines-plugin~Duration'),
      id: 'duration',
      additional: true,
```

2023-03-30 13:45 UTC, vikram-raj commented on frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipeline-task-runs-display.feature
> +             Then user does not see Duration column
nit: add a new line here.

2023-03-30 13:45 UTC, vikram-raj commented on frontend/packages/pipelines-plugin/src/components/taskruns/list-page/TaskRunsListPage.tsx
> +import { TableColumn } from 'packages/console-dynamic-plugin-sdk/dist/core/lib/extensions';
```suggestion
import { TableColumn } from '@console/dynamic-plugin-sdk';
```

2023-03-30 13:45 UTC, vikram-raj commented on frontend/packages/pipelines-plugin/src/components/taskruns/list-page/TaskRunsListPage.tsx
> +import { TaskRunKind } from 'packages/pipelines-plugin/src/types';
Use a relative path if importing from the same package

```suggestion
import { TaskRunKind } from '../../../types/taskRun';
```

2023-03-30 13:45 UTC, vikram-raj commented on frontend/packages/pipelines-plugin/src/components/taskruns/list-page/TaskRunsList.tsx
> +import { ColumnLayout } from 'packages/console-dynamic-plugin-sdk/dist/core/lib/extensions';
```suggestion
import { ColumnLayout } from '@console/dynamic-plugin-sdk';
```

2023-03-30 17:01 UTC, vikram-raj commented
On the first load of the console TaskRuns columns value are empty and Duration Column is visible but the Duration column is not checked.

![Peek 2023-03-30 22-28](https://user-images.githubusercontent.com/2561818/228910801-fcb71b7a-99bf-4252-bd42-8f74339cf377.gif)

2023-03-30 18:06 UTC, vikram-raj commented on frontend/packages/pipelines-plugin/src/components/taskruns/list-page/TaskRunsListPage.tsx
> +  const getColumns = (): TableColumn<TaskRunKind>[] => [
Can we make use of `TaskRunsHeader` instead of defining this new one?

2023-03-31 15:06 UTC, vikram-raj reviewed
Works as expected.

![Peek 2023-03-31 20-34](https://user-images.githubusercontent.com/2561818/229158218-1e9f9c22-5c0a-4342-ba35-cb165093ea3b.gif)


/lgtm
/approve

2023-03-31 15:07 UTC, vikram-raj commented
Propagating docs and px acks from the Epic
/label docs-approved
/label px-approved

2023-04-03 08:59 UTC, hemantsaini-7 commented on frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipeline-task-runs-display.feature
> +              And user enables Duration column
Duration column has been already enabled here, so no need to check duration option again, instead we can check for duration option already checked.

2023-04-03 09:00 UTC, hemantsaini-7 commented on frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipeline-task-runs-display.feature
> +        Scenario: Check for Duration column when enabled
Give test cases number accordingly. (P-05-TC07)

2023-04-04 13:56 UTC, merged