[release-4.11] OCPBUGS-10708: delete application should delete all part-of resources
openshift/console pull request #12772
Opened 2023-04-25 17:53 UTC by debsmita1

Manual cherry-pick of https://github.com/openshift/console/pull/12604

/kind bug

2023-04-25 17:54 UTC, debsmita1 commented
/cc @lokanandaprabhu 
/assign @jerolimov

2023-04-28 09:07 UTC, vikram-raj commented
/retest

2023-04-28 11:40 UTC, vikram-raj requested changes
Tests are failing because of error in `application-utils.spec.ts`

`ERROR in /go/src/github.com/openshift/console/frontend/packages/topology/src/utils/__tests__/application-utils.spec.ts
ERROR in /go/src/github.com/openshift/console/frontend/packages/topology/src/utils/__tests__/application-utils.spec.ts(155,5):
TS2554: Expected 2 arguments, but got 1.`

2023-04-28 11:42 UTC, vikram-raj commented on frontend/packages/topology/src/utils/__tests__/application-utils.spec.ts
> +    cleanUpWorkload(nodeModel.resource)
Expected 2 arguments, but got 1 in `cleanUpWorkload`.

2023-04-28 15:29 UTC, vikram-raj reviewed
Verified it on the cluster bot.

https://user-images.githubusercontent.com/2561818/235189035-abc8bc9e-4c12-4bae-96f4-4fc8c9c2dbc4.mov

/lgtm

2023-04-28 19:53 UTC, jerolimov commented
/label backport-risk-assessed
/approve

2023-05-02 07:25 UTC, vikram-raj commented
/lgtm

2023-05-03 06:16 UTC, sanketpathak commented
/label cherry-pick-approved

2023-05-03 06:42 UTC, debsmita1 commented
/retest

2023-05-03 08:07 UTC, vikram-raj commented
/retest

2023-05-05 17:46 UTC, debsmita1 commented
/retest

2023-05-05 22:40 UTC, jerolimov commented
/retest

2023-05-10 13:17 UTC, jerolimov approved these changes
Tested the latest version and still works fine.

/lgtm

2023-05-11 04:26 UTC, debsmita1 commented
/retest

2023-05-11 08:42 UTC, merged