ODC-7316: Add discoverability of the IDE extensions from Create Serverless form
openshift/console pull request #12846
Opened 2023-05-24 09:12 UTC by lokanandaprabhu

**Story**: https://issues.redhat.com/browse/ODC-7316

**Description**:

Added below IDE extensions in create serverless form,

VSCode Knative IDE extension: https://marketplace.visualstudio.com/items?itemName=redhat.vscode-knative
IntelliJ Knative Plugin: https://plugins.jetbrains.com/plugin/16476-knative--serverless-functions-by-red-hat

**Screenshots**:
<img width="1418" alt="Screenshot 2023-05-24 at 2 37 05 PM" src="https://github.com/openshift/console/assets/102503482/45e83748-c2e9-44a9-83a0-fd027cf51938">

2023-05-25 07:20 UTC, Lucifergene commented
@lokanandaprabhu Can you please share a video demonstrating the effect of the cards on gently reducing the screen's width? 
For this, you can adjust the width of the Chrome Dev Tools Side Panel.

I think this will help to understand the alignments and positions of the cards on different screens.

2023-05-25 07:24 UTC, Lucifergene commented
/retest

2023-05-25 09:19 UTC, lokanandaprabhu commented
Hi @Lucifergene ,

Added the video. The cards can be visible only for 'lg' and 'xl'.

2023-05-29 08:14 UTC, Lucifergene commented
Imo, this looked good as the position wouldn't change much on resizing the screen:

![image](https://github.com/openshift/console/assets/47265560/8c11c334-dcd4-47ef-ad39-f3864457a807)

But, if the current design is finalized, it's still okay :+1:

2023-05-29 08:49 UTC, Lucifergene commented
/lgtm

2023-05-30 06:07 UTC, vikram-raj commented
font-weight of `provided by` text is more than the title. Can you please change it to a normal font-weight?
<img width="501" alt="image" src="https://github.com/openshift/console/assets/2561818/88daca58-283d-4f4f-b3ba-d438fbcfc54a">

2023-05-31 05:21 UTC, lokanandaprabhu commented
/test e2e-gcp-console

2023-05-31 07:45 UTC, vikram-raj commented
@lokanandaprabhu `Create` and `Cancel` buttons are hanging in between the screen which looks odd. Can we move it to the bottom or remove the extra spaces between the input field and buttons? 

And the `Provided by` text still looks similar to the title, need to remove the title font family. See the recording. 

Check Operator hub cards for reference.

https://github.com/openshift/console/assets/2561818/bf7ebf92-c2b8-4f87-a466-55c889a70d73

2023-06-01 13:33 UTC, vikram-raj commented
@lokanandaprabhu 
- Font style now looks good
- I am not sure if we can go with the non-sticky footer. It will become inconsistent with other forms we have in the console.  wdyt @jerolimov ?

2023-06-02 15:05 UTC, jerolimov requested changes

2023-06-02 15:05 UTC, jerolimov commented on frontend/public/imgs/intellij.png
File should be at least part of the imgs/logos folder, or in the same folder as the card component.

2023-06-02 15:05 UTC, jerolimov commented on frontend/public/components/catalog/catalog-item-icon.tsx
> +import * as intellijImg from '../../imgs/intellij.png';
The other logos was part of the logos folder. I'm also unsure if we want add these both to the catalog list.. Its not wrong, but also not necessary.

2023-06-02 15:05 UTC, jerolimov commented on frontend/packages/dev-console/src/components/import/serverless-function/AddServerlessFunctionForm.tsx
> +  const imgScrIntelliJ = getImageForIconClass('icon-intellij');
You can import logos also like this:

```ts
import * as vscodeIcon from './icon-vscode.png';
```

and use it like this:

```ts
<img src={vscodeIcon} 
```

The `getImageForIconClass` is to get dynamic images.

2023-06-02 15:07 UTC, jerolimov commented
> @lokanandaprabhu
> 
>     * Font style now looks good
> 
>     * I am not sure if we can go with the non-sticky footer. It will become inconsistent with other forms we have in the console.  wdyt @jerolimov ?

I agree with Vikram, we should accept that its non sticky just because we add two icons on the right hand side.

2023-06-15 07:23 UTC, jerolimov requested changes
Hi, this looks overall good to me. But I have some small issues I hope you can address:

1. Avoid `!important` and use PF variables instead of hard coded px sizes.
2. The spacing around the cards looks could be improved (see comments below)
3. There are some small optional improvements in the scss file.

2023-06-15 07:23 UTC, jerolimov commented on frontend/packages/dev-console/src/components/import/serverless-function/AddServerlessFunctionForm.tsx
> +              <span className="co-catalog-item-icon__bg">
Please don't reuse classes from other plugins.

2023-06-15 07:23 UTC, jerolimov commented on frontend/packages/dev-console/src/components/import/serverless-function/AddServerlessFunctionForm.tsx
> +        <FlexItem flex={{ default: 'flex_1' }} alignSelf={{ default: 'alignSelfFlexStart' }}>
![Screenshot from 2023-06-15 09-10-16](https://github.com/openshift/console/assets/139310/2bde8a23-1734-457b-9976-844c88c5fc75)

Esp. with the light theme I notice these different gaps between the boxes.

You can remove the default spacing from the Flex components with the `spaceItems` props:

```suggestion
      <Flex direction={{ default: 'column', sm: 'row' }} spaceItems={{ default: 'spaceItemsNone' }}>
        <FlexItem flex={{ default: 'flex_1' }} alignSelf={{ default: 'alignSelfFlexStart' }}>
```

Wdyt?

2023-06-16 04:47 UTC, lokanandaprabhu commented
Propagate labels from the epic:

/label docs-approved
/label px-approved

2023-06-16 09:45 UTC, lokanandaprabhu commented
/retest

2023-06-16 12:40 UTC, jerolimov commented
/retest

2023-06-16 15:23 UTC, jerolimov approved these changes
Propage labels from the epic:

/label docs-approved
/label px-approved

Thanks for adding one additional e2e test.

/label qe-approved

2023-06-16 15:23 UTC, jerolimov approved these changes
/lgtm
/approve

2023-06-17 06:22 UTC, jerolimov commented
/retest

2023-06-17 12:30 UTC, jerolimov commented
/retest

2023-06-17 21:09 UTC, merged