Fix operator backed catalog page when copied CSVs disabled
openshift/console pull request #12932
Opened 2023-06-23 15:38 UTC by vikram-raj

Fixes: https://issues.redhat.com/browse/OCPBUGS-14907

Descriptions: 
Show catalog items in operator backed even if copied to CSVs is disabled.

2023-06-23 19:36 UTC, TheRealJon reviewed
There are two main cases we need to cover when listing CSVs and copied CSVs are disabaled:

1. **Listing in a namespaced context:** We are currently in a namespace other than 'openshift', 'openshift-operators', or 'All Namespaces'.
2. **We are listing in a global context:** we are in one of the three excluded namespaces from (1). 



### **Namespaced context** 
List CSVs from the current namespace and copied CSVs from the 'openshift' namespace

### **Global Context**
 a. **All Namespaces:** List CSVs from all namespaces, but filter out copied CSVs. (This is probably already covered since this is not a new case).
 b. **'openshift-operators' namespace:** List all operators in this namespace only and they are all available in all namespaces (they have copies in the 'openshift' namespace).
 c. **'openshift' namespace:** List all operators in this namespace only. Copied CSVs are available in all namespaces, otherwise, they are only available in the current namespace.
 
@tlwu2013 Could you help confirm this logic? Mainly with (b). Are all CSVs in the 'openshift-operators' namespace considered global or can namespaced operators be installed their as well?

2023-06-23 21:52 UTC, vikram-raj commented
/jira refresh

2023-06-26 17:53 UTC, tlwu2013 commented
https://github.com/openshift/console/pull/12932#pullrequestreview-1495809640

> @tlwu2013 Could you help confirm this logic? Mainly with (b). Are all CSVs in the 'openshift-operators' namespace considered global or can namespaced operators be installed their as well?


> Are all CSVs in the ‘openshift-operators’ namespace considered global

yes, all Operators in `openshift-operators` namespace are global.
(but global Operators can exist somewhere else, like Serverless does)

> or can namespaced operators be installed their as well?

no, they cannot. 

--
if users tried to install an Operator as namespaced scope in `openshift-operators` namespace, they got blocked by this:
> **Namespace does not support installation mode**
> The openshift-operators Namespace is reserved for global Operators that watch all Namespaces. To install an Operator in a single Namespace, select a different Namespace where the operand should run.

2023-06-26 18:13 UTC, TheRealJon commented
Thanks @tlwu2013!

@vikram-raj As Tony mentioned, we also need to handle the case where an operator is installed globally, but not in the default `openshift-operators` namespace. He used Serverless as an example. By default, that operator is installed globally in the `openshift-serverless` namespace. This means the source CSV will be in that namespace, while a copy will be made in the 'openshift' namespace. Therefore, when listing CSVs in the 'openshift-serverless' namespace, the source CSV should be listed and not the copied CSV from 'openshift'. I believe this case is handled in the admin perspective, we just need to make sure it's consistent in the dev perspective too.

2023-07-10 09:32 UTC, vikram-raj commented
@TheRealJon I updated the can you PTAL again. Thanks.

2023-07-13 15:23 UTC, TheRealJon requested changes

2023-07-14 09:34 UTC, vikram-raj commented on frontend/packages/operator-lifecycle-manager/src/utils/useClusterServiceVersions.tsx
> +      : namespacesResourceSelector;
Updated it PTAL again. Thanks

2023-07-14 14:12 UTC, TheRealJon approved these changes
/lgtm

2023-07-14 14:13 UTC, vikram-raj commented
/retest

2023-07-14 14:40 UTC, vikram-raj commented
/cherry-pick release-4.13

2023-07-15 14:28 UTC, merged