OCPBUGS-9714: Any namespace after deletion is still visible on UI if it is the default selection in namespace dropdown
openshift/console pull request #13411
Opened 2023-12-05 08:41 UTC by Lucifergene

**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-9714

**Analysis / Root cause**: 

- [ ] Any namespace after deletion is still visible on UI if it is the default selection in the namespace dropdown.
- [ ] If there is an ns mentioned in the URL, that does not exist, it is still shown in the namespace dropdown.

**Solution Description**: 
I have added a check in the Projects Dropdown to ensure the activeNamespace is present in the cluster. If not, the dropdown autoselects "All Projects" and shows the Project List.

_Note: If you delete an ns from a different tab or via CLI, ensure to refresh the actual page._

**Screen shots / Gifs for design review**: 

https://github.com/openshift/console/assets/47265560/47ce3e66-bb9c-41b7-a3a6-e385ad2b2a52

**Unit test coverage report**: 
Not Changed

**Test setup:**
1. Open 2 tabs: 
      a. Namespace in Admin View - TAB 1
      b. Topology Page in Dev View - TAB 2
2. Create a ns in the TAB 1.
3. In TAB 2, select that ns in the dropdown.
4. In TAB 1, delete the ns.
5. In TAB 2, refresh the page. You will see that the Dropdown is changed to "All Projects" and the Project list is shown.
6. In TAB 2, select some other project to verify that the ns is changed in the Project dropdown.
7. Now in the TAB 2 URL, change the namespace to something else that does not exist and press ENTER.
8. You will see that the Project Dropdown changes to "All Projects" and you see the Project List again.

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2023-12-05 08:44 UTC, Lucifergene commented
/cc @lokanandaprabhu @jerolimov 
/uncc @rhamilto @zherman0

2023-12-07 12:23 UTC, jerolimov requested changes

2024-01-09 08:03 UTC, Lucifergene commented on frontend/public/components/namespace-bar.tsx
> +  }, [nsErr]);
Thanks. Have updated the code.

2024-01-16 09:59 UTC, Lucifergene commented
/retest
/cc @vikram-raj

2024-01-17 12:44 UTC, vikram-raj commented
/retest

2024-01-18 14:26 UTC, vikram-raj commented
/retest

2024-01-19 06:25 UTC, vikram-raj commented
@Lucifergene e2e is failing because of the change in PR. Please take a look.

2024-01-24 08:28 UTC, Lucifergene commented on frontend/packages/integration-tests-cypress/tests/crud/namespace-crud.cy.ts
> -    projectDropdown.shouldContain(allProjectsDropdownLabel);
When we click on a list item with a namespace set in the URL, the project dropdown will automatically select that ns, as it continuously monitors the ns in the URL. 
So, I've removed this line from the test.

2024-01-24 14:54 UTC, vikram-raj commented
/retest

2024-01-25 11:29 UTC, vikram-raj commented
@Lucifergene still one e2e test is failing.

`Nav and breadcrumbs restores last selected "All Projects" when navigating from details to list view: Namespace Nav and breadcrumbs restores last selected "All Projects" when navigating from details to list view `

2024-02-06 13:52 UTC, vikram-raj reviewed
Tested it on the cluster bot and noticed an issue. All project is selected and when I create a new project it should select the new project but it is not get selected at once. See the recording.

https://github.com/openshift/console/assets/2561818/8b2dde67-ba58-4e4a-b54f-83fc3c8d7f8e

2024-02-07 04:46 UTC, Lucifergene commented
@vikram-raj This seems a legitimate issue as it takes time to get created on the cluster when you create the new namespace. But the console does not wait for that and directly changes the URL to the new ns. But since it's not created initially, the All Projects gets shown and after some time, when the ns is finally created in the cluster, the dropdown changes to it.

I am trying to approach this so that when you create the namespace, it waits for it to get created and then changes the route.

2024-02-08 05:25 UTC, Lucifergene commented
/retest

2024-02-08 11:21 UTC, vikram-raj reviewed
/lgtm

2024-02-08 17:01 UTC, merged

2024-02-11 14:00 UTC, Lucifergene commented
/cherry-pick release-4.15