[WIP] OCPBUGS-26236: VolumeSnapshots data not displayed in PVC >  VolumeSnapshots tab
openshift/console pull request #13485
Opened 2024-01-05 21:52 UTC by cyril-ui-developer

2024-01-08 16:32 UTC, cyril-ui-developer commented
Hi @bipuladh, This PR change is intended to fix this [Jira issue](https://issues.redhat.com/browse/OCPBUGS-26236). 
Since you worked on this code in the past, I wanted to double check with you on this change. I removed `snapshotStatusFilters` since the VolumeSnapshots tab should be displaying only matched PVC VolumeSnapshots,
 and  I am not sure why the `{ 'Snapshot Content': !canListVSC }` logic is use [here](https://github.com/openshift/console/blame/master/frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot.tsx#L206). PTAL, thanks.

PTAL, thanks in advance.

2024-01-24 14:56 UTC, TheRealJon requested changes
We shouldn't merge this without figuring out the missing column header.

2024-01-24 16:17 UTC, cyril-ui-developer commented
> We shouldn't merge this without figuring out the missing column header.

I don't think so. Only if this issue is fixed before the other issue would be visible. 
So I prefer to address the missing col as a separate issue since it can be traced back to 4.10 version.

2024-01-24 16:22 UTC, cyril-ui-developer commented
/jira refresh

2024-01-25 19:44 UTC, cyril-ui-developer commented
/retest

2024-01-26 13:33 UTC, cyril-ui-developer commented on frontend/packages/console-app/src/components/volume-snapshot/volume-snapshot.tsx
> +  const rowFilters = [
> Why are we redefining `volumeSnapshotStatus` ?

Not sure I understood what you meant here. I am not redefining `volumeSnapshotStatus`  but using it in the `rowFilter`. Pls explain further.

2024-01-30 17:36 UTC, cyril-ui-developer commented
/assign @jhadvig

2024-01-31 15:41 UTC, jhadvig approved these changes
/lgtm

2024-01-31 15:41 UTC, jhadvig commented
/label acknowledge-critical-fixes-only,

2024-01-31 15:42 UTC, jhadvig commented
/label acknowledge-critical-fixes-only

2024-01-31 16:02 UTC, jhadvig commented
/approve

2024-01-31 23:02 UTC, merged

2024-02-02 13:38 UTC, cyril-ui-developer commented
/cherry-pick release-4.15