[WIP] OCPBUGS-30567: Remove wrong arguments in K8sCreate method instance for Create YAML editor
openshift/console pull request #13658
Opened 2024-03-07 21:20 UTC by cyril-ui-developer

2024-03-08 15:03 UTC, cyril-ui-developer commented
/jira refresh

2024-03-08 16:39 UTC, TheRealJon requested changes
This will likely introduce a regression. `k8sUpdate` needs namespace and name args to know which resource to update. We should split this into two separate callbacks, one for update actions and one for create actions.

2024-03-08 17:14 UTC, cyril-ui-developer commented
> This will likely introduce a regression. `k8sUpdate` needs namespace and name args to know which resource to update. We should split this into two separate callbacks, one for update actions and one for create actions.

Oops! I overlooked that. Good catch, thanks.

2024-03-11 18:05 UTC, TheRealJon requested changes
IMO the `updateYAML` function has too many responsibilities. It should be broken into at least three functions: a dispatcher, a create handler, and an update handler. The dispatcher directs calls to the handlers based on the create bool, and the handlers execute create or update behaviors accordingly.

2024-03-11 18:05 UTC, TheRealJon commented on frontend/public/components/edit-yaml.jsx
>        let redirect = false;
We don't need another boolean for this. It will always be the same as `create`.

2024-03-11 18:05 UTC, TheRealJon commented on frontend/public/components/edit-yaml.jsx
> +        ? ((redirect = true), delete obj.metadata.resourceVersion, k8sCreate(model, obj))
not new, but we shouldn't mutate `obj`. Instead, we should use a copy, omitting the unwanted properties:
```suggestion
        ? k8sCreate(model, _.omit(obj, ['metadata', 'resourceVersion']))
```

2024-03-12 12:59 UTC, cyril-ui-developer commented
> IMO the `updateYAML` function has too many responsibilities. It should be broken into at least three functions: a dispatcher, a create handler, and an update handler. The dispatcher directs calls to the handlers based on the create bool, and the handlers execute create or update behaviors accordingly.

@TheRealJon This suggested change looks like a tech-debt to me. IMO, the code looks tricky to modify, although I am not familiar with the create/edit-yaml editor code. I would rather prefer to open a tech-debt to address code improvements of the create/edit-yaml code which would include refactoring to TS.

2024-03-12 14:29 UTC, cyril-ui-developer commented
/retest

2024-03-12 14:59 UTC, bbethell-1 approved these changes

2024-03-12 17:55 UTC, cyril-ui-developer commented
@TheRealJon Updated, PTAL.

2024-03-12 19:20 UTC, TheRealJon approved these changes
/lgtm

See https://issues.redhat.com/browse/CONSOLE-3975 for tech-debt story

2024-03-13 10:24 UTC, merged