OCPBUGS-31685: Revert - terminal: use username if uid is not present
openshift/console pull request #13719
Opened 2024-04-03 09:51 UTC by jhadvig

Reverts https://github.com/openshift/console/commit/e87dc6fc852d23e8fca211cd0d3862b07cefa79e
/assign @stlaz

2024-04-03 09:53 UTC, jhadvig commented
/jira refresh

2024-04-03 10:34 UTC, stlaz requested changes

2024-04-03 10:34 UTC, stlaz commented on pkg/terminal/proxy.go
> +			// uid is missing. it must be kube:admin
this breaks oidc where UID does not have to be set and username is not going to be `kube:admin`

2024-04-03 10:34 UTC, stlaz commented
/hold
we can't do this

2024-04-12 07:34 UTC, stlaz commented
/close

2024-06-17 08:35 UTC, jhadvig commented
Re-opening the PR so QE can tests if the change in the devworkspace pkg is actually breaking the external OIDC setup.

2024-06-28 11:14 UTC, jhadvig commented
/retest

2024-06-28 11:15 UTC, jhadvig commented
/jira refresh

2024-06-28 11:15 UTC, jhadvig commented
/jira refresh

2024-06-28 11:19 UTC, jhadvig commented
/lgtm

2024-07-02 15:01 UTC, jhadvig commented
/hold cancel

2024-07-02 15:04 UTC, jhadvig commented
Based on the testing with [YaDan Pei](https://issues.redhat.com/secure/ViewProfile.jspa?name=rhn-support-yapei) reverting the commit is fixing only the standard OCP setup, without external OIDC. Based on chat with [Ilya Buziuk](https://issues.redhat.com/secure/ViewProfile.jspa?name=ibuziuk%40redhat.com) the webterminal is not working for the external OIDC setup with or without the PR in place.

Reverting the commit in order to unblock the webterminal team.

2024-07-02 15:07 UTC, TheRealJon approved these changes
/lgtm

2024-07-02 23:22 UTC, merged

2024-07-03 09:20 UTC, jhadvig commented
/cherry-pick release-4.16