Update i18n docs with how to enable additional supported languages
openshift/console pull request #13730
Opened 2024-04-04 17:51 UTC by cyril-ui-developer

2024-04-10 12:06 UTC, cyril-ui-developer commented
/assign @jhadvig

2024-04-10 12:06 UTC, cyril-ui-developer commented
/retest

2024-04-10 12:44 UTC, jhadvig requested changes
Thanks @cyril-ui-developer for the PR.
Adding couple of comments.
@opayne1 PTAL as well.

2024-04-10 12:44 UTC, jhadvig commented on INTERNATIONALIZATION.md
> +4. Update the OCP UI Project Template to include the new laguage(s) in the Phrase TMS portal. Refer to the [Phrase Project Templates ](https://support.phrase.com/hc/en-us/articles/5709647439772-Proje
```suggestion
4. Update the OCP UI Project Template to include the new laguage(s) in the Phrase TMS portal. Refer to the [Phrase Project Templates ](https://support.phrase.com/hc/en-us/articles/5709647439772-Project-Templates-TMS) on how to update Project Template. Please note that you must have Phrase project owner permissions to perform this task.
```

2024-04-10 12:44 UTC, jhadvig commented on INTERNATIONALIZATION.md
> +The languages that are supported are represented using the ISO 639-1 Code, as defined in `frontend/packages/console-app/src/components/user-preferences/language/const.ts`. An exception is made for Ch
```suggestion
Supported languages are represented using the ISO 639-1 Code, as defined in `frontend/packages/console-app/src/components/user-preferences/language/const.ts`. An exception is made for Chinese, where the region code is included to distinguish the supported traditional Chinese from other variants. However, the locale directories for Chinese still follow the ISO 639-1 Code format.
```

2024-04-10 12:58 UTC, cyril-ui-developer commented
@jhadvig Updated, PTAL

2024-04-10 15:08 UTC, opayne1 commented on INTERNATIONALIZATION.md
> +Supported languages are represented using the ISO 639-1 Code, as defined in `frontend/packages/console-app/src/components/user-preferences/language/const.ts`. An exception is made for Chinese, where
It should probably be "There is an exception for Chinese" or "with the exception of Chinese". What do you think of this re-write?

```suggestion
Supported languages are represented using the ISO 639-1 Code defined in `frontend/packages/console-app/src/components/user-preferences/language/const.ts` with the exception of Chinese. While locale directories for Chinese still follow the ISO 639-1 Code format, the region code is also included to distinguish the supported traditional Chinese from other variants.
```

2024-04-10 15:09 UTC, opayne1 commented on INTERNATIONALIZATION.md
> +4. Update the OCP UI Project Template to include the new laguage(s) in the Phrase TMS portal. Refer to the [Phrase Project Templates ](https://support.phrase.com/hc/en-us/articles/5709647439772-Proje
```suggestion
4. Update the OCP UI Project Template to include the new laguage(s) in the Phrase TMS portal. Refer to the [Phrase Project Templates ](https://support.phrase.com/hc/en-us/articles/5709647439772-Project-Templates-TMS) on how to update the Project Template. You must have Phrase project owner permissions to perform this task.
```

2024-04-10 15:32 UTC, cyril-ui-developer commented on INTERNATIONALIZATION.md
> +Supported languages are represented using the ISO 639-1 Code, as defined in `frontend/packages/console-app/src/components/user-preferences/language/const.ts`. An exception is made for Chinese, where
@opayne1 @jhadvig I think the ""with the exception of Chinese"" looks and sound better.

2024-04-10 16:44 UTC, jhadvig approved these changes
/lgtm
/approve
/retest

2024-04-10 16:44 UTC, jhadvig commented
hmmm looks like CI is down

2024-04-10 18:00 UTC, cyril-ui-developer commented
/retest

2024-04-11 02:34 UTC, cyril-ui-developer commented
/retest

2024-04-11 06:55 UTC, merged