CONSOLE-4068: Break down public/components/secrets/create-secret.tsx into smaller files
openshift/console pull request #13945
Opened 2024-06-07 14:02 UTC by nitin-dhevar

2024-06-07 15:44 UTC, TheRealJon requested changes
A few small adjustments, but overall this looks great!

2024-06-07 15:44 UTC, TheRealJon commented on frontend/public/components/secrets/create-secret/KeyValueEntryForm.tsx
> +export const DroppableFileInput = (props) => (
No need to export this. 

Also, we should leave a TODO comment on this component to create a shared LazyDroppableFileInput component. This lazy-loaded DroppableFileInput pattern is repeated in multiple places in our codebase.

2024-06-10 19:23 UTC, nitin-dhevar commented
/retest

2024-06-12 13:50 UTC, nitin-dhevar commented
/retest

2024-06-12 18:23 UTC, nitin-dhevar commented
/label tide/merge-method-squash

2024-06-17 13:54 UTC, TheRealJon approved these changes
/lgtm

2024-06-18 19:03 UTC, nitin-dhevar commented
QE Approver
/assign @yapei

Docs Approver:
/assign @opayne1

PX Approver:
/assign @RickJWagner

2024-06-19 08:01 UTC, yapei commented
@XiyunZhao will help test the PR

2024-06-20 07:26 UTC, XiyunZhao commented
This PR has been tested via manual and regression test, no issue was found
/label qe-approved

2024-06-20 16:25 UTC, opayne1 commented
/label docs-approved

2024-06-21 04:24 UTC, merged