CONSOLE-4069: Refactor secret form util functions into React components
openshift/console pull request #13996
Opened 2024-06-21 13:41 UTC by nitin-dhevar

2024-06-21 14:58 UTC, TheRealJon requested changes
Looks really good! Just a couple of minor nits.

2024-06-21 14:58 UTC, TheRealJon commented on frontend/public/components/secrets/create-secret/SecretFormTitle.tsx
> +    case 'generic':
Use enum constant instead of "magic strings":
```suggestion
    case SecretTypeAbstraction.generic:
```

2024-06-21 14:58 UTC, TheRealJon commented on frontend/public/components/secrets/create-secret/SecretFormTitle.tsx
> +    case 'image':
```suggestion
    case SecretTypeAbstraction.image:
```

2024-06-21 14:58 UTC, TheRealJon commented on frontend/public/components/secrets/create-secret/SecretFormTitle.tsx
> +            : t('public~Edit {{secretType}} secret', { secretType: typeAbstraction })}{' '}
Remove extra space:
```suggestion
            : t('public~Edit {{secretType}} secret', { secretType: typeAbstraction })}
```

2024-06-21 14:58 UTC, TheRealJon commented on frontend/public/components/secrets/create-secret/SecretSubForm.tsx
> +};
nit, usually we define types at the bottom of the file.

2024-06-21 14:58 UTC, TheRealJon commented on frontend/public/components/secrets/create-secret/SecretFormTitle.tsx
> +type SecretFormTitleProps = {
nit, define types at the bottom of the file

2024-06-21 14:58 UTC, TheRealJon commented on frontend/public/components/secrets/create-secret/SecretFormDescription.tsx
> +};
nit, define types at the bottom of the file

2024-06-21 20:50 UTC, TheRealJon approved these changes
/lgtm

2024-06-21 20:51 UTC, TheRealJon commented
@nitin-dhevar You just need to run `yarn i18n` and commit those changes to fix the frontend test failure.

2024-06-21 21:04 UTC, nitin-dhevar commented
/label tide/merge-method-squash

2024-06-24 13:45 UTC, TheRealJon approved these changes
/lgtm

2024-06-24 14:26 UTC, nitin-dhevar commented
QE Approver
/assign @yapei

Docs Approver:
/assign @opayne1

PX Approver:
/assign @RickJWagner

2024-06-24 17:40 UTC, RickJWagner commented
/label px-approved

2024-06-26 01:18 UTC, yapei commented
@XiyunZhao will help test the PR

2024-06-28 19:21 UTC, nitin-dhevar commented
/jira refresh

2024-07-01 12:10 UTC, TheRealJon approved these changes
/lgtm

2024-07-01 17:15 UTC, merged