OU-251: Remove alerts list from console codebase
openshift/console pull request #14014
Opened 2024-06-27 19:33 UTC by PeterYurkovich

This PR is apart of a pair of PR's (along with [this](https://github.com/openshift/monitoring-plugin/pull/125) one in the monitoring-plugin) which look to move the alerting list page from the console codebase over to the monitoring one. This PR needs to wait for the other PR in the monitoring-plugin codebase to merge before it can merge. I would further prefer if both could be merged at the same time, by receiving approval on both before either merges.

This set of PR's change the UI of the developer perspective to be consistent with the admin perspective. The overall functionality stays the same, but there are some changes to the workflows required. For example to silence the alert you can't do so directly from the table anymore, instead you will click the ellipsis and then select the "Silence alert" option.

<img width="1393" alt="Screenshot 2024-06-27 at 1 36 14 PM" src="https://github.com/openshift/monitoring-plugin/assets/47438010/cb9307ba-1aa4-46c4-8ab8-7e8b8f149d0a">

In addition, the tab control is done manually in the console block, with new additions being added at the end. So until the rest of the monitoring tabs are moved over the tabs will be out of their typical order as seen in the image above.

2024-06-27 19:33 UTC, PeterYurkovich commented
/hold

2024-06-27 19:33 UTC, PeterYurkovich commented
After the other PR is merged, I will un-hold this one

2024-06-27 19:36 UTC, PeterYurkovich commented
/jira refresh

2024-07-08 07:51 UTC, jgbernalp requested changes

2024-07-08 07:51 UTC, jgbernalp commented on frontend/packages/dev-console/src/components/monitoring/__tests__/MonitoringPage.spec.tsx
> +  it('should not render the Sileences tab if user has no access to get prometheousRule resource', () => {
```suggestion
  it('should not render the Silences tab if user has no access to get prometheousRule resource', () => {
```

2024-07-08 14:05 UTC, PeterYurkovich commented on frontend/packages/dev-console/src/components/monitoring/__tests__/MonitoringPage.spec.tsx
> +  it('should not render the Sileences tab if user has no access to get prometheousRule resource', () => {
Fixed in latest commit

2024-07-08 15:27 UTC, jgbernalp commented
/lgtm

2024-07-08 19:29 UTC, PeterYurkovich commented
/retest

2024-07-09 02:02 UTC, PeterYurkovich commented
/retest

2024-07-09 06:59 UTC, jgbernalp commented
/test e2e-gcp-console

2024-07-09 09:27 UTC, juzhao commented
https://github.com/openshift/monitoring-plugin/pull/125 is merged
/hold cancel

2024-07-09 09:58 UTC, juzhao commented
/test e2e-gcp-console

2024-07-09 14:29 UTC, PeterYurkovich commented
Approval:
/assign @vikram-raj
Docs Approver: 
/assign @opayne1
PX Approver:
/assign @RickJWagner

2024-07-09 18:30 UTC, RickJWagner commented
/label px-approved

2024-07-09 19:08 UTC, opayne1 commented
/label docs-approved

2024-07-10 09:48 UTC, vikram-raj reviewed
Getting error `No Alert found` error when I try to see the Alert details page. 


https://github.com/openshift/console/assets/2561818/f076414d-9390-444f-80d8-d5c10e6b2437

2024-07-10 18:39 UTC, PeterYurkovich commented
The monitoring-plugin was adding the rules labels onto the alerts labels, so when the labels got encoded into the url there were additional labels from the rules, causing the alerts detail page to fail to match.

I've prevented the rules labels from being added onto the alerts in the developer perspective in a separate for the monitoring-plugin [PR](https://github.com/openshift/monitoring-plugin/pull/132) and will update this one once that has merged

2024-07-10 22:24 UTC, PeterYurkovich commented
The monitoring-plugin PR has been merged and the `No Alert found` issue has been fixed with it

2024-07-11 10:35 UTC, vikram-raj reviewed
/approve

2024-07-11 15:14 UTC, vikram-raj commented
@PeterYurkovich you need to create and link CONSOLE or ODC jira ticket to get it merged.

2024-07-11 15:26 UTC, PeterYurkovich commented
Based on the tide results I believe this PR is waiting on the qe-approved tag from @juzhao once they finish their testing. Is there another reason, such as tracking, that another ticket would be needed?

2024-07-11 17:47 UTC, jgbernalp commented
@vikram-raj  it seems we already have the `jira/valid-reference`. Do we still need to create a jira ticket on those projects?

2024-07-12 06:19 UTC, juzhao commented
/label qe-approved

2024-07-12 06:31 UTC, jgbernalp commented
/jira refresh

2024-07-12 06:33 UTC, jgbernalp commented
/jira refresh

2024-07-12 06:47 UTC, vikram-raj commented
> @vikram-raj it seems we already have the `jira/valid-reference`. Do we still need to create a Jira ticket on those projects?

Yes, CONSOLE / ODC ticket is required to get it in. As CONSOLE / ODC ticket is not attached to it so bot is looking for jira/valid-bug label. once you attach CONSOLE / ODC ticket then it will gone and the tide will be green as you have all the required labels.

2024-07-12 06:51 UTC, jgbernalp commented
/retitle ODC-7639: Remove alerts list from dev console codebase

2024-07-12 14:57 UTC, merged