Console 4075
openshift/console pull request #14065
Opened 2024-07-15 16:13 UTC by nitin-dhevar

2024-07-15 16:47 UTC, nitin-dhevar commented
/hold

Depends on https://github.com/openshift/console/pull/14064

2024-07-15 16:47 UTC, nitin-dhevar commented
/label tide/merge-method-squash

2024-07-15 16:48 UTC, nitin-dhevar commented
/assign @TheRealJon

2024-07-17 14:35 UTC, TheRealJon requested changes
Just a couple of nits.

2024-07-17 14:35 UTC, TheRealJon commented on frontend/public/components/secrets/create-secret/WebHookSecretForm.tsx
> +    </div>
Not new, but we are using 'webhook secret key' terminology here, when in reality this form controls the *value* of the webhook secret. The key is a static string: "WebhookSecretKey". We should update the wording.

2024-07-17 14:35 UTC, TheRealJon commented on frontend/public/components/secrets/create-secret/WebHookSecretForm.tsx
> +    onChange({ stringData: { ...stringData, WebHookSecretKey: newSecret }, base64StringData: {} });
To keep this DRY, we could separate the onChange call into it's own handler, then the text input and generator button will just pass values into it.

2024-11-21 15:56 UTC, jhadvig commented
Closing in favour of https://github.com/openshift/console/pull/14454

2024-11-21 15:56 UTC, closed without merging