[WIP] CONSOLE-4176: Add support for GCP Workload Identity / Federated identity operator installs
openshift/console pull request #14086
Opened 2024-07-23 17:15 UTC by cyril-ui-developer

…tall

2024-07-24 14:08 UTC, jhadvig reviewed
Very nice and fast progress on the work @cyril-ui-developer 👍 
Hope you dont mind adding a review even if the PR is WIP. Just couple of nits.

2024-07-24 14:08 UTC, jhadvig commented on frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx
> +          <STSWarningAlert
I know it not new, but lets swap the Alerts above with the new `STSWarningAlert`.

2024-07-24 14:08 UTC, jhadvig commented on frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx
> +                      'olm~The GCP PRoject Number required for the operator to access the cloud API.',
```suggestion
                      'olm~The GCP Project Number required for the operator to access the cloud API.',
```

2024-07-24 14:08 UTC, jhadvig commented on frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-item-details.tsx
> +                  <Alert
lets use `STSWarningAlert`

2024-07-24 14:08 UTC, jhadvig commented on frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx
> +              'olm~This cluster is using GCP Workload Identity / Federated Identity to reach the cloud API. In order for this operator to take the actions it requires directly with the cloud API, pro
The GCP WIF will have different variable names:

Project ID
Pool ID
Provider ID
Service Account Email

2024-07-26 15:22 UTC, cyril-ui-developer commented
/retest

2024-07-29 11:50 UTC, cyril-ui-developer commented
/retest

2024-07-29 17:09 UTC, cyril-ui-developer commented
/retest

2024-07-29 20:39 UTC, cyril-ui-developer commented
/retest

2024-07-30 07:50 UTC, jhadvig requested changes
Thanks @cyril-ui-developer the PR looks good 👍 
Adding two comments, otherwise I think its good to go :)

2024-07-30 07:50 UTC, jhadvig commented on frontend/packages/operator-lifecycle-manager/locales/en/olm.json
> +  "GCP Tenant ID": "GCP Tenant ID",
Tenant ID is only needed for Azure WIF. We dont need it for GCP.

2024-07-30 07:50 UTC, jhadvig commented on frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx
> +                    label={t('olm~GCP Tenant ID')}
```suggestion
                    label={t('olm~GCP Pool ID')}
```

2024-07-30 16:52 UTC, jhadvig approved these changes
/lgtm
/approve

2024-07-31 11:35 UTC, reestr commented
/label px-approved

2024-08-05 08:59 UTC, XiyunZhao commented
Working on this Pr, still need sometime to check

2024-08-06 00:45 UTC, XiyunZhao commented
@cyril-ui-developer could you help to double-check if following issues need a bug to track?
1. The Warning message is missing on Operator installation page 
2. The update approval strategy should be set to 'Manual' by default
Here are the details:
![Console4176_warningmissing](https://github.com/user-attachments/assets/a1836173-0c33-421c-9c54-9ae884f2b1f8)

2024-08-06 01:38 UTC, cyril-ui-developer commented
> @cyril-ui-developer could you help to double-check if following issues need a bug to track?
> 
> 1. The Warning message is missing on Operator installation page
> 2. The update approval strategy should be set to 'Manual' by default
>    Here are the details:
>    ![Console4176_warningmissing](https://private-user-images.githubusercontent.com/78589509/355274904-a1836173-0c33-421c-9c54-9ae884f2b1f8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MDg0MTIsIm5iZiI6MTcyMjkwODExMiwicGF0aCI6Ii83ODU4OTUwOS8zNTUyNzQ5MDQtYTE4MzYxNzMtMGMzMy00MjFjLTljNTQtOWFlODg0ZjJiMWY4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAxMzUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3NGYzZmQwOTgxNWEwNmQwOWY1NjdlYWZjMDE2YzQzYzlkYjVlNTVkNWFjODNkZGYxZjIwMzIzZTQyNTEzYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zVI_z4ZY8jxeQUqPqdduVEtKr8M5l2pYcNlo756A7X0)
>          
>            [
>              
>            
>                ![Console4176_warningmissing](https://private-user-images.githubusercontent.com/78589509/355274904-a1836173-0c33-421c-9c54-9ae884f2b1f8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MDg0MTIsIm5iZiI6MTcyMjkwODExMiwicGF0aCI6Ii83ODU4OTUwOS8zNTUyNzQ5MDQtYTE4MzYxNzMtMGMzMy00MjFjLTljNTQtOWFlODg0ZjJiMWY4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAxMzUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3NGYzZmQwOTgxNWEwNmQwOWY1NjdlYWZjMDE2YzQzYzlkYjVlNTVkNWFjODNkZGYxZjIwMzIzZTQyNTEzYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zVI_z4ZY8jxeQUqPqdduVEtKr8M5l2pYcNlo756A7X0)
>              ](https://private-user-images.githubusercontent.com/78589509/355274904-a1836173-0c33-421c-9c54-9ae884f2b1f8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MDg0MTIsIm5iZiI6MTcyMjkwODExMiwicGF0aCI6Ii83ODU4OTUwOS8zNTUyNzQ5MDQtYTE4MzYxNzMtMGMzMy00MjFjLTljNTQtOWFlODg0ZjJiMWY4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAxMzUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3NGYzZmQwOTgxNWEwNmQwOWY1NjdlYWZjMDE2YzQzYzlkYjVlNTVkNWFjODNkZGYxZjIwMzIzZTQyNTEzYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zVI_z4ZY8jxeQUqPqdduVEtKr8M5l2pYcNlo756A7X0)
>            
>            
>              
>                
>                  
>                
>                
>                  
>                  
>                
>              
>              [
>                
>                  
>                
>              ](https://private-user-images.githubusercontent.com/78589509/355274904-a1836173-0c33-421c-9c54-9ae884f2b1f8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MDg0MTIsIm5iZiI6MTcyMjkwODExMiwicGF0aCI6Ii83ODU4OTUwOS8zNTUyNzQ5MDQtYTE4MzYxNzMtMGMzMy00MjFjLTljNTQtOWFlODg0ZjJiMWY4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAxMzUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3NGYzZmQwOTgxNWEwNmQwOWY1NjdlYWZjMDE2YzQzYzlkYjVlNTVkNWFjODNkZGYxZjIwMzIzZTQyNTEzYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zVI_z4ZY8jxeQUqPqdduVEtKr8M5l2pYcNlo756A7X0)

Actually, I tested this with mock data because we couldn't reproduce the environment locally. Could I get access to the cluster you used for verification?

2024-08-06 02:19 UTC, XiyunZhao commented
@cyril-ui-developer Let me know when you need the cluster, I will prepare one for you

2024-08-06 08:42 UTC, cyril-ui-developer commented
> @cyril-ui-developer Let me know when you need the cluster, I will prepare one for you

8 a.m. (ET). Thank you.

> @cyril-ui-developer Let me know when you need the cluster, I will prepare one for you



> @cyril-ui-developer Let me know when you need the cluster, I will prepare one for you

8

2024-08-06 11:09 UTC, cyril-ui-developer commented
> @cyril-ui-developer could you help to double-check if following issues need a bug to track?
> 
> 1. The Warning message is missing on Operator installation page
> 2. The update approval strategy should be set to 'Manual' by default
>    Here are the details:
>    ![Console4176_warningmissing](https://private-user-images.githubusercontent.com/78589509/355274904-a1836173-0c33-421c-9c54-9ae884f2b1f8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDA4MDcsIm5iZiI6MTcyMjk0MDUwNywicGF0aCI6Ii83ODU4OTUwOS8zNTUyNzQ5MDQtYTE4MzYxNzMtMGMzMy00MjFjLTljNTQtOWFlODg0ZjJiMWY4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDEwMzUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMjU3MmY5ZDkzZWFmNTU0NjUyYzc5YzJkNTI3ZWE3NDBhNjdiMDBkYWMyNTc1NjgzY2JmNDc1NDBjNjZkMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.01x0zFUiwtbK-QYcfevwxljamkpueLzn-EUjmWPg0cY)
>          
>            [
>              
>            
>                ![Console4176_warningmissing](https://private-user-images.githubusercontent.com/78589509/355274904-a1836173-0c33-421c-9c54-9ae884f2b1f8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDA4MDcsIm5iZiI6MTcyMjk0MDUwNywicGF0aCI6Ii83ODU4OTUwOS8zNTUyNzQ5MDQtYTE4MzYxNzMtMGMzMy00MjFjLTljNTQtOWFlODg0ZjJiMWY4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDEwMzUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMjU3MmY5ZDkzZWFmNTU0NjUyYzc5YzJkNTI3ZWE3NDBhNjdiMDBkYWMyNTc1NjgzY2JmNDc1NDBjNjZkMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.01x0zFUiwtbK-QYcfevwxljamkpueLzn-EUjmWPg0cY)
>              ](https://private-user-images.githubusercontent.com/78589509/355274904-a1836173-0c33-421c-9c54-9ae884f2b1f8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDA4MDcsIm5iZiI6MTcyMjk0MDUwNywicGF0aCI6Ii83ODU4OTUwOS8zNTUyNzQ5MDQtYTE4MzYxNzMtMGMzMy00MjFjLTljNTQtOWFlODg0ZjJiMWY4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDEwMzUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMjU3MmY5ZDkzZWFmNTU0NjUyYzc5YzJkNTI3ZWE3NDBhNjdiMDBkYWMyNTc1NjgzY2JmNDc1NDBjNjZkMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.01x0zFUiwtbK-QYcfevwxljamkpueLzn-EUjmWPg0cY)
>            
>            
>              
>                
>                  
>                
>                
>                  
>                  
>                
>              
>              [
>                
>                  
>                
>              ](https://private-user-images.githubusercontent.com/78589509/355274904-a1836173-0c33-421c-9c54-9ae884f2b1f8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDA4MDcsIm5iZiI6MTcyMjk0MDUwNywicGF0aCI6Ii83ODU4OTUwOS8zNTUyNzQ5MDQtYTE4MzYxNzMtMGMzMy00MjFjLTljNTQtOWFlODg0ZjJiMWY4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDEwMzUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMjU3MmY5ZDkzZWFmNTU0NjUyYzc5YzJkNTI3ZWE3NDBhNjdiMDBkYWMyNTc1NjgzY2JmNDc1NDBjNjZkMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.01x0zFUiwtbK-QYcfevwxljamkpueLzn-EUjmWPg0cY)

@XiyunZhao This is happening because the value of `tokenizedAuth` is `null` for the cert-manager operator. The conditions for displaying the warning on the modal are slightly different from those on the subscription page. As mentioned earlier, we were unable to verify this with actual data. Are you able to verify the same behavior for Azure or AWS using your environment? That might help us figure out what is missing. cc: @jhadvig

2024-08-06 13:14 UTC, cyril-ui-developer commented
Docs Approver:
/assign @opayne1

2024-08-06 15:19 UTC, opayne1 reviewed
One small suggestion but otherwise lgtm!

/label docs-approved

2024-08-06 15:19 UTC, opayne1 commented on frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-item-details.tsx
> +                      'olm~This cluster is using AWS Security Token Service to reach the cloud API. In order for this operator to take the actions it requires directly with the cloud API, you will ne
Small wording suggestion
```suggestion
                      'olm~This cluster is using AWS Security Token Service to reach the cloud API. In order for this operator to take the actions it requires directly with the cloud API, you must provide a role ARN (with an attached policy) during installation. Please see the operator description for more details.',
```

2024-08-07 07:47 UTC, XiyunZhao commented
@cyril-ui-developer I checked on the AWS cluster, it's working as normal, so could you help to check the issue on this PR. also just a notice that we are nearing the branching date
Here is the correct behavior for STS mode :
![CONSOLE4176_aws](https://github.com/user-attachments/assets/f52f78d1-2c3b-4be9-8760-6383fb63c6f6)

2024-08-07 15:35 UTC, cyril-ui-developer commented
> @cyril-ui-developer could you help to double-check if following issues need a bug to track?
> 
> 1. The Warning message is missing on Operator installation page
> 2. The update approval strategy should be set to 'Manual' by default
>    Here are the details:
>    ![Console4176_warningmissing](https://private-user-images.githubusercontent.com/78589509/355274904-a1836173-0c33-421c-9c54-9ae884f2b1f8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNDUxMjUsIm5iZiI6MTcyMzA0NDgyNSwicGF0aCI6Ii83ODU4OTUwOS8zNTUyNzQ5MDQtYTE4MzYxNzMtMGMzMy00MjFjLTljNTQtOWFlODg0ZjJiMWY4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDE1MzM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3NjE4ZjYxYjkwMjcyNmQwYWE3MzI3MGZhNGE1N2U2OGFmMmFmMWIyZDU2MDllMTQ4ZmRlNDAwNTVmNDVmNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q1hRKMtj23tF37Lop5nUclchZ9uhgNIzHAyF4pF7DKw)
>          
>            [
>              
>            
>                ![Console4176_warningmissing](https://private-user-images.githubusercontent.com/78589509/355274904-a1836173-0c33-421c-9c54-9ae884f2b1f8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNDUxMjUsIm5iZiI6MTcyMzA0NDgyNSwicGF0aCI6Ii83ODU4OTUwOS8zNTUyNzQ5MDQtYTE4MzYxNzMtMGMzMy00MjFjLTljNTQtOWFlODg0ZjJiMWY4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDE1MzM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3NjE4ZjYxYjkwMjcyNmQwYWE3MzI3MGZhNGE1N2U2OGFmMmFmMWIyZDU2MDllMTQ4ZmRlNDAwNTVmNDVmNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q1hRKMtj23tF37Lop5nUclchZ9uhgNIzHAyF4pF7DKw)
>              ](https://private-user-images.githubusercontent.com/78589509/355274904-a1836173-0c33-421c-9c54-9ae884f2b1f8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNDUxMjUsIm5iZiI6MTcyMzA0NDgyNSwicGF0aCI6Ii83ODU4OTUwOS8zNTUyNzQ5MDQtYTE4MzYxNzMtMGMzMy00MjFjLTljNTQtOWFlODg0ZjJiMWY4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDE1MzM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3NjE4ZjYxYjkwMjcyNmQwYWE3MzI3MGZhNGE1N2U2OGFmMmFmMWIyZDU2MDllMTQ4ZmRlNDAwNTVmNDVmNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q1hRKMtj23tF37Lop5nUclchZ9uhgNIzHAyF4pF7DKw)
>            
>            
>              
>                
>                  
>                
>                
>                  
>                  
>                
>              
>              [
>                
>                  
>                
>              ](https://private-user-images.githubusercontent.com/78589509/355274904-a1836173-0c33-421c-9c54-9ae884f2b1f8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNDUxMjUsIm5iZiI6MTcyMzA0NDgyNSwicGF0aCI6Ii83ODU4OTUwOS8zNTUyNzQ5MDQtYTE4MzYxNzMtMGMzMy00MjFjLTljNTQtOWFlODg0ZjJiMWY4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDE1MzM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3NjE4ZjYxYjkwMjcyNmQwYWE3MzI3MGZhNGE1N2U2OGFmMmFmMWIyZDU2MDllMTQ4ZmRlNDAwNTVmNDVmNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q1hRKMtj23tF37Lop5nUclchZ9uhgNIzHAyF4pF7DKw)

@XiyunZhao Fixed and updated. PTAL.
Good catch :). Thank you.

2024-08-07 15:36 UTC, cyril-ui-developer commented
cc: @jhadvig PTAL and tag again.

2024-08-07 16:31 UTC, jhadvig commented
/lgtm

2024-08-08 08:11 UTC, XiyunZhao commented
@cyril-ui-developer Thanks for the quick fix, I need a confirmation about the customized field on the installation page.
The field 'PROJECT_ID' is missing on the installation page, which does not satisfy the description of our design. Is there any design change on this part? Kindly help to take a look~
![image](https://github.com/user-attachments/assets/419b5107-c5cb-43eb-b00f-b48028e7b648)

2024-08-08 09:01 UTC, jhadvig commented
@XiyunZhao yes the PROJECT_ID is missing on purpose, there was a change in the design, which was communicated by @dlom, that only Pool_ID, Provider_ID and SAEmail are required.

2024-08-08 09:06 UTC, XiyunZhao commented
@jhadvig Thanks for the quick reply, no other issue was found on this PR
/label qe-approved

2024-08-08 13:10 UTC, jhadvig approved these changes
/lgtm

2024-08-08 13:36 UTC, cyril-ui-developer commented
@XiyunZhao I rebased this PR due to recent changes upstream. I verified with mock data, but ideally it would be good to retest the changes with real data. If possible, could you please retest?

2024-08-08 16:51 UTC, dlom commented
@jhadvig the document has been updated again: we have combined all fields (except email) into a single AUDIENCE field, which is made up of the 3 original parts (pool, provider, and project)

2024-08-08 17:41 UTC, jhadvig commented
/lgtm

2024-08-08 17:43 UTC, jhadvig commented
/lgtm cancel

2024-08-08 23:13 UTC, cyril-ui-developer commented
/retest

2024-08-15 02:01 UTC, XiyunZhao commented
/test e2e-gcp-console

2024-08-15 02:52 UTC, XiyunZhao commented
@cyril-ui-developer @jhadvig Kindly help to check the failure, and hope this PR can be merged

2024-08-15 14:43 UTC, cyril-ui-developer commented
/retest

2024-08-15 14:50 UTC, rhamilto commented
/lgtm

2024-08-15 19:53 UTC, cyril-ui-developer commented
/jira refresh

2024-08-15 19:55 UTC, cyril-ui-developer commented
/jira refresh

2024-08-15 19:56 UTC, cyril-ui-developer commented
/retest

2024-08-15 22:28 UTC, rhamilto commented
/approve

2024-08-16 05:47 UTC, merged

2024-08-16 12:38 UTC, cyril-ui-developer commented
/cherrypick release-4.17