OCPBUGS-43830: Expand "Rollback Helm Release" status width
openshift/console pull request #14448
Opened 2024-10-29 17:46 UTC by logonoff

**Fixes**: 

https://issues.redhat.com/browse/OCPBUGS-43830

**Analysis / Root cause**: 

Status text was too long for the width so it overlapped with the content in the next column

**Solution Description**: 

Expand width of status header

**Screen shots / Gifs for design review**: 

Before:
![Screenshot From 2024-11-20 10-16-38](https://github.com/user-attachments/assets/5189978b-1fbf-4c0e-b657-768b676201be)

After:
![Screenshot From 2024-11-20 10-16-34](https://github.com/user-attachments/assets/79d2eaa4-8f0a-45e7-9e18-c163cf56cc42)

**Unit test coverage report**: 

n/a

**Test setup:**

Create a helm release, then upgrade it, then go to "Rollback Helm Release"

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari

2024-10-29 19:26 UTC, logonoff commented
/retest

2024-10-29 19:30 UTC, logonoff commented
/jira refresh

2024-10-29 23:31 UTC, logonoff commented on frontend/packages/console-dynamic-plugin-sdk/src/app/components/status/Status.tsx
> +export type StatusProps = StatusIconAndTextProps & {
all paths of this component end up returning a `StatusIconAndText` so this is fine to do

2024-11-20 09:11 UTC, lokanandaprabhu requested changes
Hi @logonoff ,

Instead of this change, we can achieve this by just changing status classname from

`  status: 'pf-m-hidden pf-m-visible-on-lg pf-v5-u-w-8-on-xl pf-v5-u-w-16-on-lg',
`  
  to
  
`    status: 'pf-m-hidden pf-m-visible-on-lg pf-v5-u-w-16-on-xl pf-v5-u-w-16-on-lg',
`

I am adding the result of the above change, 

https://github.com/user-attachments/assets/a2d85629-b6b0-453f-b727-a13a4b8fabf2

2024-11-20 17:57 UTC, logonoff commented
/retest

2024-11-20 21:07 UTC, logonoff commented
/label acknowledge-critical-fixes-only

2024-11-22 06:00 UTC, lokanandaprabhu approved these changes
/lgtm

2024-11-22 12:54 UTC, logonoff commented
/retest

2024-11-22 16:31 UTC, logonoff commented
/retest

2024-11-23 00:38 UTC, logonoff commented
/retest

2024-11-29 15:09 UTC, merged