OCPBUGS-44800: Add Dynamic Plugins nav item
openshift/console pull request #14521
Opened 2024-11-20 14:42 UTC by rhamilto

![localhost_9000_k8s_cluster_operator openshift io~v1~Console_cluster_console-plugins](https://github.com/user-attachments/assets/c2debaeb-ad90-4a09-885b-ebe8f1898e86)

2024-11-20 14:57 UTC, rhamilto commented
We use the label `Dynamic plugins` in the Overview and the about modal (screenshots below), but I think `Console Plugins` is the proper choice for the nav item since that aligns with the tab label, but it is odd we have this discrepancy.  Maybe we need to revisit?  @jhadvig, @spadgett, @vojtechszocs, WDYT?
<img width="391" alt="Screenshot 2024-11-20 at 9 53 05 AM" src="https://github.com/user-attachments/assets/91bbf3b0-3fe4-4305-9eba-826506f31301">
<img width="644" alt="Screenshot 2024-11-20 at 9 53 15 AM" src="https://github.com/user-attachments/assets/94ca5314-b734-48ec-8966-fefe7c496dc1">

2024-11-20 19:44 UTC, rhamilto commented
/retest

2024-11-21 13:00 UTC, rhamilto commented
/retest

2024-11-21 15:01 UTC, rhamilto commented
/test okd-scos-e2e-aws-ovn

2024-11-21 15:13 UTC, rhamilto commented
> We use the label `Dynamic plugins` in the Overview and the About modal (screenshots below), but I think `Console Plugins` is the proper choice for the nav item since that aligns with the tab label, but it is odd we have this discrepancy. Maybe we need to revisit? @jhadvig, @spadgett, @vojtechszocs, WDYT?

In the light of a new day, I realized the nav item label should be `Dynamic Plugins`, so I've updated this PR.

2024-11-21 19:48 UTC, rhamilto commented
/label acknowledge-critical-fixes-only

2024-11-21 19:51 UTC, vojtechszocs requested changes

2024-11-21 19:51 UTC, vojtechszocs commented on frontend/packages/console-app/src/consts.ts
> +export const FLAG_CAN_GET_CONSOLE_OPERATOR_CONFIG = 'FLAG_CAN_GET_CONSOLE_OPERATOR_CONFIG';
```suggestion
export const FLAG_CAN_GET_CONSOLE_OPERATOR_CONFIG = 'CAN_GET_CONSOLE_OPERATOR_CONFIG';
```

2024-11-21 20:00 UTC, rhamilto commented on frontend/packages/console-app/src/consts.ts
> +export const FLAG_CAN_GET_CONSOLE_OPERATOR_CONFIG = 'FLAG_CAN_GET_CONSOLE_OPERATOR_CONFIG';
Good catch, @vojtechszocs.  Thanks.  Updated.

2024-11-21 20:01 UTC, vojtechszocs commented
/lgtm

2024-11-21 20:56 UTC, rhamilto commented
> > We use the label `Dynamic plugins` in the Overview and the About modal (screenshots below), but I think `Console Plugins` is the proper choice for the nav item since that aligns with the tab label, but it is odd we have this discrepancy. Maybe we need to revisit? @jhadvig, @spadgett, @vojtechszocs, WDYT?
> 
> IMO it should be "Console Plugins" everywhere. That's the only kind of plugin we've ever had an external API for. "Static plugins" were always an internal thing, so there's not a need to differentiate between them for users. I think putting "Dynamic" in the label raises more questions than it answers for most users. Also "Console Plugin" matches the CRD kind.

IIRC, we went with Dynamic Plugins so as not to conflate the functionality with the resource.  One could argue that subtlety is lost on users however...

2024-11-21 21:13 UTC, spadgett commented
> IIRC, we went with Dynamic Plugins so as not to conflate the functionality with the resource. One could argue that subtlety is lost on users however...

To me, this could create more confusion because it sounds like they're two different things. There are also other kinds of plugins on the platform (for instance, network plugins or CLI plugins). The most important differentiator is that it's a _console_ plugin.
 
> Docs uses "Dynamic Plugins": https://docs.openshift.com/container-platform/4.17/web_console/dynamic-plugin/overview-dynamic-plugin.html

I'd update the docs as well to use "Console Plugins."

2024-11-21 22:01 UTC, rhamilto commented
> https://docs.openshift.com/container-platform/4.17/web_console/dynamic-plugin/overview-dynamic-plugin.html

I added [a story for 4.19](https://issues.redhat.com/browse/CONSOLE-4364).

2024-11-26 22:14 UTC, rhamilto commented
/jira refresh

2024-11-29 19:49 UTC, merged