Bug 1797766:  Resource Requirements" specDescriptor fields - CPU and Memory injects empty string YAML editor
openshift/console pull request #5525
Opened 2020-05-21 19:13 UTC by cyril-ui-developer

/assign @TheRealJon
/cc @benjaminapetersen @spadgett

2020-06-05 13:37 UTC, benjaminapetersen commented on frontend/packages/operator-lifecycle-manager/src/components/descriptors/spec/resource-requirements.tsx
> +    const [cpu, setCPU] = React.useState<string>(_.get(obj.spec, `${path}.${type}.cpu`));
Is this a candidate for the typescript syntax instead? `obj.spec?.path?.type?.cpu`

2020-08-19 20:19 UTC, spadgett commented
@TheRealJon PTAL
@cyril-ui-developer Sorry, needs rebase :/

2020-08-20 13:13 UTC, cyril-ui-developer commented
@spadgett Rebased. Thanks

2020-09-11 13:19 UTC, cyril-ui-developer commented
@spadgett Just rebase this PR -https://github.com/openshift/console/pull/5525 again. Please take a look when you have a chance. Thanks

2021-01-21 20:34 UTC, TheRealJon requested changes
This is untested, but I would think something like this would work:

```tsx
const submit = (e) => {
  e.preventDefault();
  const newObj = _.set(_.clone(obj), `spec.${path}`, {
    ...(memory && { memory }),
    ...(cpu && { cpu }),
    ...(storage && { 'ephemeral-storage': storage }),
  });
  return props.handlePromise(k8sUpdate(model, newObj), props.close);
};
```

2021-02-02 12:43 UTC, cyril-ui-developer reviewed
> This is untested, but I would think something like this would work:
> 
> ```tsx
> const submit = (e) => {
>   e.preventDefault();
>   const newObj =
>     cpu || memory || storage
>       ? _.set(_.cloneDeep(obj), `spec.${path}.${type}`, {
>           ...(cpu && { cpu }),
>           ...(memory && { memory }),
>           ...(storage && { 'ephemeral-storage': storage }),
>         })
>       : obj;
>   return props.handlePromise(k8sUpdate(model, newObj), props.close);
> };
> ```

@TheRealJon Looks cleaner! Works with small tweak. 
PTAL.  Thanks

2021-02-03 18:45 UTC, TheRealJon approved these changes
/lgtm

2021-02-03 20:59 UTC, merged