Remove Snapshot related components from OCS Plugin
openshift/console pull request #5968
Opened 2020-07-13 17:15 UTC by bipuladh

2020-07-14 05:51 UTC, a2batic commented
@bipuladh please remove following files as well
```
frontend/packages/ceph-storage-plugin/src/utils/snapshot-workflow.ts
frontend/packages/ceph-storage-plugin/src/utils/delete-snapshot-workflow.ts
frontend/packages/ceph-storage-plugin/src/components/volume-snapshot/volume-snapshot.tsx
frontend/packages/ceph-storage-plugin/src/components/volume-snapshot/_volume-snapshot.scss
frontend/packages/ceph-storage-plugin/src/components/modals/volume-snapshot-modal/volume-snapshot-modal.tsx
frontend/packages/ceph-storage-plugin/src/components/modals/volume-snapshot-modal/_volume-snapshot-modal.scss
frontend/packages/ceph-storage-plugin/src/__tests__/volume-snapshot.spec.tsx
frontend/packages/ceph-storage-plugin/src/__tests__/volume-snapshot-modal.spec.tsx
frontend/packages/ceph-storage-plugin/src/__tests__/restore-pvc-modal.spec.tsx
frontend/packages/ceph-storage-plugin/src/__tests__/__snapshots__/volume-snapshot.spec.tsx.snap
frontend/packages/ceph-storage-plugin/src/__mocks__/volume-snapshot-data.tsx

```

2020-07-14 06:39 UTC, a2batic commented
@bipuladh please do following changes as well.
1. Remove Snapshot flag from features.ts
2. Remove VolumeSnapshot model
```
diff --git a/frontend/packages/ceph-storage-plugin/src/features.ts b/frontend/packages/ceph-storage-plugin/src/features.ts
index e05e393d9..fae01c82e 100644
--- a/frontend/packages/ceph-storage-plugin/src/features.ts
+++ b/frontend/packages/ceph-storage-plugin/src/features.ts
@@ -23,7 +23,6 @@ export const CEPH_FLAG = 'CEPH';
 
 /* Key and Value should be same value received in CSV  */
 export const OCS_SUPPORT_FLAGS = {
-  SNAPSHOT: 'SNAPSHOT',
   EXTERNAL: 'EXTERNAL',
 };
 
diff --git a/frontend/packages/ceph-storage-plugin/src/models.ts b/frontend/packages/ceph-storage-plugin/src/models.ts
index 172262560..4612aa478 100644
--- a/frontend/packages/ceph-storage-plugin/src/models.ts
+++ b/frontend/packages/ceph-storage-plugin/src/models.ts
@@ -25,16 +25,3 @@ export const OCSServiceModel: K8sKind = {
   id: 'ocscluster',
   crd: true,
 };
-
-export const VolumeSnapshotModel: K8sKind = {
-  label: 'Volume Snapshot',
-  apiVersion: 'snapshot.storage.k8s.io/v1beta1',
-  apiGroup: '',
-  plural: 'volumesnapshots',
-  abbr: 'VS',
-  namespaced: true,
-  kind: 'VolumeSnapshot',
-  id: 'volumesnapshot',
-  labelPlural: 'Volume Snapshots',
-  crd: true,
-};

```

2020-09-04 09:30 UTC, bipuladh commented
/hold
for 4.7

2020-10-05 06:04 UTC, cloudbehl commented
/hold cancel

2020-10-05 07:48 UTC, a2batic requested changes
Remove `VolumeSnapshotModel` in models.ts
```
diff --git a/frontend/packages/ceph-storage-plugin/src/models.ts b/frontend/packages/ceph-storage-plugin/src/models.ts
index 172262560..4612aa478 100644
--- a/frontend/packages/ceph-storage-plugin/src/models.ts
+++ b/frontend/packages/ceph-storage-plugin/src/models.ts
@@ -25,16 +25,3 @@ export const OCSServiceModel: K8sKind = {
   id: 'ocscluster',
   crd: true,
 };
-
-export const VolumeSnapshotModel: K8sKind = {
-  label: 'Volume Snapshot',
-  apiVersion: 'snapshot.storage.k8s.io/v1beta1',
-  apiGroup: '',
-  plural: 'volumesnapshots',
-  abbr: 'VS',
-  namespaced: true,
-  kind: 'VolumeSnapshot',
-  id: 'volumesnapshot',
-  labelPlural: 'Volume Snapshots',
-  crd: true,
-};
```

2020-10-05 17:39 UTC, a2batic commented
/lgtm

2020-10-06 04:19 UTC, merged