Fix style, behavior and appearance uniformity issues of the drop-downs in OCS
openshift/console pull request #6351
Opened 2020-08-18 11:22 UTC by bipuladh

Converts dropdowns in all the capacity dropdowns(Persistent Storage in both Modes) to Select
Clicking the Single Select item will close the dropdown at once
Stop items from stretching outside of the viewport(Performance card in Object Storage)
Screenshots: 
Before:
![Screenshot from 2020-08-18 16-51-52](https://user-images.githubusercontent.com/54092533/90507214-2535e880-e173-11ea-898a-10887f87f5a3.png)
![Screenshot from 2020-08-18 16-52-11](https://user-images.githubusercontent.com/54092533/90507233-2ebf5080-e173-11ea-994e-e3170d893a20.png)

After:
![Screenshot from 2020-08-18 16-45-05](https://user-images.githubusercontent.com/54092533/90507034-d8eaa880-e172-11ea-9d13-20d705744214.png)
![Screenshot from 2020-08-18 16-44-17](https://user-images.githubusercontent.com/54092533/90507085-f15ac300-e172-11ea-837e-b4ca66d94fb3.png)

2020-08-18 11:23 UTC, bipuladh commented
Needs a BZ

2020-08-24 05:12 UTC, cloudbehl commented
Tests are failing.

2020-08-24 09:14 UTC, bipuladh commented
@cloudbehl they are passing now

2020-08-24 10:30 UTC, cloudbehl approved these changes

2020-08-24 13:10 UTC, afreen23 requested changes

2020-08-24 13:14 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/src/__tests__/independent-dashboard-breakdown-card.spec.tsx
> +import { Select } from '@patternfly/react-core';
Preferences

2020-08-24 20:40 UTC, a2batic requested changes
nit: The Data-consumption drop-down changes width on switching from `Providers` to `Account` and vice-versa. Adding following class will prevent this.
```
.nb-data-consumption-card__options-menu > div {
  width: 14rem;
}
```

2020-08-25 05:10 UTC, afreen23 approved these changes

2020-08-25 05:18 UTC, bipuladh commented
> nit: The Data-consumption drop-down changes width on switching from `Providers` to `Account` and vice-versa. Adding following class will prevent this.
> 
> ```
> .nb-data-consumption-card__options-menu > div {
>   width: 14rem;
> }
> ```
It changes slightly I don't want to enforce width settings as this hampers responsiveness. I can address this in another BZ that will target mobile views. 

> nb-data-consumption-card__options-menu

@a2batic the selected component is a pattern fly component and I do not want to alter its width. In the long run, I will have to fix it across multiple breakpoints which is not an ideal solution. I would like to keep it as it is for now.

2020-08-25 05:26 UTC, bipuladh commented
/retest

2020-08-25 05:36 UTC, a2batic commented
/lgtm

2020-08-25 05:46 UTC, a2batic commented
/lgtm

2020-08-25 07:34 UTC, merged