Bug 1860985:  Update the minimum requirement for OCS
openshift/console pull request #6486
Opened 2020-09-01 05:28 UTC by gnehapk

![Screenshot from 2020-09-01 14-20-48](https://user-images.githubusercontent.com/5517376/91798237-693ee800-ec5f-11ea-80a5-0f8e747f50f4.png)

2020-09-01 07:49 UTC, gnehapk commented
/hold 
Message needs to be updated

2020-09-02 16:01 UTC, bipuladh requested changes
Everything else looks good.

2020-09-02 16:01 UTC, bipuladh commented on frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/types.ts
> +export enum DiskMechanicalProperties {
```suggestion
```
Since it can only have one property of either SSD or HDD I find it perfect as it is (in singular)

2020-09-03 02:29 UTC, gnehapk commented
/hold cancel
Message updated

2020-09-03 07:55 UTC, bipuladh approved these changes
/lgtm

2020-09-03 12:17 UTC, merged