[release-4.5] Bug 1840253: Tighten cipher usage to library-go
openshift/console pull request #6503
Opened 2020-09-03 08:38 UTC by jhadvig

Manual backport of https://github.com/openshift/console/pull/6292

/assign @spadgett

2020-09-09 09:40 UTC, jhadvig commented
/cherry-pick release-4.4

2020-09-17 16:25 UTC, spadgett approved these changes
/lgtm

2020-09-17 16:26 UTC, spadgett commented
/hold

2020-09-17 16:29 UTC, spadgett requested changes
/lgtm cancel
/hold cancel

2020-09-17 16:29 UTC, spadgett commented on cmd/bridge/main.go
>  			CipherSuites: crypto.DefaultCiphers(),
I think we can remove `crypto.DefaultCiphers()` now and associated module since we have library-go.

2020-09-18 12:39 UTC, jhadvig commented
@spadgett comment addressed. Thanks for noticing!
PTAL

2020-09-18 16:27 UTC, spadgett approved these changes
/lgtm

2020-09-18 18:03 UTC, merged