Bug 1875878: Move pipelinerun log scroll handler to parent element
openshift/console pull request #6535
Opened 2020-09-04 15:40 UTC by rottencandy

**Fixes**: 
https://issues.redhat.com/browse/ODC-4517

**Analysis / Root cause**: 
The scroll event listener was attached to a div that did not have the `overflow-y` property, hence no events were being fired.

**Solution Description**: 
Move the event listener to it's parent element, which had the `overflow-y` property set to `scroll`. It is likely that a CSS change introduced this bug.

**Screen shots / Gifs for design review**: 
![rec](https://user-images.githubusercontent.com/20013884/92257126-52fc8a80-eef2-11ea-9546-830ae0d3c427.gif)
@openshift/team-devconsole-ux 

**Unit test coverage report**: 
Unchanged.

**Browser conformance**: 

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

2020-09-04 15:46 UTC, andrewballantyne commented
/cc @sahil143

2020-09-04 15:52 UTC, sahil143 commented
/assign

2020-09-07 12:45 UTC, sahil143 approved these changes
/lgtm

verified changes locally

2020-09-07 12:53 UTC, jerolimov approved these changes
Tested it locally works as expected.

/lgtm

2020-09-07 13:08 UTC, rottencandy commented
/assign @andrewballantyne

2020-09-22 16:35 UTC, rohitkrai03 requested changes
/approve

2020-09-22 18:33 UTC, merged