Bug 1873326: Adding accessibility alt to icons within overview status and activity sections
openshift/console pull request #6556
Opened 2020-09-08 18:57 UTC by sg00dwin

Currently `aria-hidden="true"` are on these icons, a label isn't required since it's not accessible to a screen reader. Including `alt` attribute to be consistent with https://github.com/openshift/console/pull/6497#issuecomment-686546767
Fix bug https://bugzilla.redhat.com/show_bug.cgi?id=1873326

2020-09-08 18:58 UTC, sg00dwin commented
/bugzilla refresh

2020-09-08 19:18 UTC, spadgett requested changes
@sg00dwin We should only use `alt=""` if there is other text in the UI describing the icon status. If the only status is the icon, we need a real value for `alt`.

cc @jessiehuff

2020-09-09 15:19 UTC, sg00dwin commented
@spadgett included descriptive text for health states and status icons

2020-09-10 18:08 UTC, jessiehuff reviewed
So this one took a little more thought because these icons seem to have a function. Since these icons act as a communication of the status, it seems that this information should be communicated to assistive technology. Right now, because it has `aria-hidden` on it, nothing will be read by the screen reader. The reason that gets added is in the [create icon file](https://github.com/patternfly/patternfly-react/blob/master/packages/react-icons/src/createIcon.tsx), when a title is not provided, the `aria-hidden` is added since it's assumed to be decorative. We can keep the alt, but I suggest adding a title as well. This will remove the `aria-hidden` and allow for the icon to communicate that status information. I also suggest taking off the "icon" text. It will then read out in VO as "Ok health state, image". If we keep the icon text, it would read as "Ok health state icon, image" which is a little unnecessary. However, to add this, I believe you'll need to add title to the icons.tsx file. So essentially I recommend something like this `icon: <GreenCheckCircleIcon alt="Ok health state" title="Ok health state" />` I think we could continue to investigate if there's a better way to associate these items, but I think adding that title alone would be an improvement.

2020-09-11 15:14 UTC, sg00dwin commented
Updated pr to include `title` with `svg`

2020-09-11 17:06 UTC, spadgett commented
@jessiehuff Instead of "Ok health state," would it be better to use something like "Healthy"?

2020-09-11 17:09 UTC, spadgett commented on frontend/packages/console-shared/src/components/dashboard/activity-card/EventItem.tsx
> +                  title="Warning alert"
These are events, not alerts. But I feel like the noun is unnecessarily verbose. Can this just be "Warning"? @jessiehuff ?

```suggestion
                  alt="Warning"
                  title="Warning"
```

If @jessiehuff disagrees, we'd need to change "alert" to "event."

2020-09-11 17:09 UTC, spadgett commented on frontend/packages/console-shared/src/components/dashboard/status-card/AlertItem.tsx
> +        <Icon alt="Status alert" title="Status alert" />
We need to put a real status in the alt here for whatever icon is passed. I believe you can move this into `getSeverityIcon` above.

```tsx
const CriticalIcon = <RedExclamationCircleIcon alt="Critical" title="Critical" />;
const WarningIcon = <YellowExclamationTriangleIcon alt="Warning" title="Warning" />;
const getSeverityIcon = (severity: string) => {
  switch (severity) {
    case 'critical':
      return CriticalIcon;
    case 'warning':
    default:
      return WarningIcon;
  }
};
```

2020-09-11 17:09 UTC, spadgett commented on frontend/packages/console-shared/src/components/dashboard/status-card/states.tsx
> +    icon: <InProgressIcon alt="Progress health state" title="Progress health state" />,
```suggestion
    icon: <InProgressIcon alt="In progress" title="In progress" />,
```

2020-09-11 17:09 UTC, spadgett commented on frontend/packages/console-shared/src/components/dashboard/status-card/states.tsx
> +    icon: <GreenCheckCircleIcon alt="Ok health state" title="Ok health state" />,
```suggestion
    icon: <GreenCheckCircleIcon alt="Healthy" title="Healthy" />,
```

2020-09-11 17:09 UTC, spadgett commented on frontend/packages/console-shared/src/components/dashboard/status-card/states.tsx
> +    icon: <GrayUnknownIcon alt="Unknown health state" title="Unknown health state" />,
```suggestion
    icon: <GrayUnknownIcon alt="Unknown status" title="Unknown status" />,
```

2020-09-11 17:09 UTC, spadgett commented on frontend/packages/console-shared/src/components/dashboard/status-card/states.tsx
> +    icon: <BlueSyncIcon alt="Updating health state" title="Updating health state" />,
```suggestion
    icon: <BlueSyncIcon alt="Updating" title="Updating" />,
```

2020-09-11 17:09 UTC, spadgett commented on frontend/packages/console-shared/src/components/dashboard/status-card/states.tsx
> +    icon: <YellowExclamationTriangleIcon alt="Warning health state" title="Warning health state" />,
```suggestion
    icon: <YellowExclamationTriangleIcon alt="Warning" title="Warning" />,
```

2020-09-11 17:09 UTC, spadgett commented on frontend/packages/console-shared/src/components/dashboard/status-card/states.tsx
> +    icon: <RedExclamationCircleIcon alt="Error health state" title="Error health state" />,
```suggestion
    icon: <RedExclamationCircleIcon alt="Error" title="Error" />,
```

2020-09-11 17:09 UTC, spadgett commented on frontend/packages/console-shared/src/components/dashboard/status-card/states.tsx
> +    icon: <GrayUnknownIcon alt="Not available health state" title="Not available health state" />,
```suggestion
    icon: <GrayUnknownIcon alt="Not available" title="Not available" />,
```

2020-09-11 18:16 UTC, jessiehuff commented
> @jessiehuff Instead of "Ok health state," would it be better to use something like "Healthy"?

Yeah, I could see that working and potentially sounding better. It would essentially say "Healthy, image" then when you navigate to the next item it would read whatever that is. Picking a label can be subjective and tricky, but I agree with your comments. I think "Healthy" and "Warning" communicate what you're trying to say in a concise way so those are definite possibilities. I also wonder if adding context to the label will help make things more clear. Perhaps we could do something like "Status: Healthy", "Status: Warning", etc. to provide more meaning in this context? What do you think @spadgett? I'm ok with either approach. 🙂

2020-09-11 20:43 UTC, spadgett approved these changes
/lgtm

Thanks @sg00dwin and @jessiehuff! Let's go ahead with the fix as-is for now so that it makes 4.6.

2020-09-12 08:29 UTC, merged