Bug 1877441: Watch for changes to Tasks & ClusterTasks when in pipeline builder
openshift/console pull request #6578
Opened 2020-09-09 16:17 UTC by rottencandy

**Fixes**: 
https://issues.redhat.com/browse/ODC-3171

**Analysis / Root cause**: 
List of Tasks and ClusterTasks is only fetched once when the pipeline builder page is loaded.

**Solution Description**: 
Watch for changes in Tasks and ClusterTasks in the pipeline builder.

**Screen shots / Gifs for design review**: 
![demo](https://user-images.githubusercontent.com/20013884/92625125-ec0e1580-f2e5-11ea-8426-adf1fc4ba600.gif)

**Unit test coverage report**: 
Unchanged

**Browser conformance**: 

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

2020-09-09 16:19 UTC, rottencandy commented
/kind bug

2020-09-09 16:20 UTC, rottencandy commented
/cc @andrewballantyne

2020-09-10 10:59 UTC, divyanshiGupta requested changes

2020-09-10 10:59 UTC, divyanshiGupta commented on frontend/packages/dev-console/src/components/pipelines/pipeline-builder/hooks.ts
> +  if (tasks.loaded && tasks.loadError) {
```suggestion
  if (tasks.loadError) {
```

2020-09-10 10:59 UTC, divyanshiGupta commented on frontend/packages/dev-console/src/components/pipelines/pipeline-builder/hooks.ts
> +  if (clusterTasks.loaded && clusterTasks.loadError) {
```suggestion
  if (clusterTasks.loadError) {
```

2020-09-10 10:59 UTC, divyanshiGupta commented on frontend/packages/dev-console/src/components/pipelines/pipeline-builder/hooks.ts
> +    clusterTasks: clusterTasks.loaded ? clusterTasks.data : null,
```suggestion
    namespacedTasks: tasks.loaded && !tasks.loadError ? tasks.data : null,
    clusterTasks: clusterTasks.loaded && !clusterTasks.loadError ? clusterTasks.data : null,
```

2020-09-11 10:54 UTC, debsmita1 commented
this works fine
/lgtm

2020-09-11 10:55 UTC, rottencandy commented
/retest

2020-09-15 16:15 UTC, andrewballantyne approved these changes

2020-09-15 21:11 UTC, merged