Bug 1872972: Make efficiency cards consistent
openshift/console pull request #6608
Opened 2020-09-14 06:00 UTC by a2batic

Signed-off-by: Kanika Murarka <a2batic@localhost.localdomain>

2020-09-14 06:01 UTC, a2batic commented
/bugzilla refresh

2020-09-14 06:05 UTC, a2batic commented
/assign @afreen23

2020-09-14 07:26 UTC, afreen23 commented
Please attach screenshots for the change.
Thanks!

2020-09-14 09:47 UTC, a2batic commented
/test e2e-gcp-console

2020-09-14 09:50 UTC, a2batic commented
@afreen23 updated the description, please review.

2020-09-14 09:58 UTC, a2batic commented
/test e2e-gcp-console

2020-09-14 11:17 UTC, a2batic commented
/test e2e-gcp-console

2020-09-15 04:09 UTC, afreen23 requested changes
We need to rename `efficiency` variables to `compressionRatio` , alongwith changing filename and changes in `queries.ts` file of noobaa plugin.

2020-09-15 07:43 UTC, a2batic commented
@afreen23 addressed review comments, please review.

2020-09-15 09:40 UTC, afreen23 commented
Nit: As per convention , we name the files and folders of cards by the name of card. So `object-storage-effiiciency-card` would be `storage-efficiency-card`

2020-09-15 15:30 UTC, afreen23 requested changes
We had this check for data reduction card previously, we need to consider this

2020-09-15 15:30 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/components/dashboard-page/storage-dashboard/storage-efficiency-card/storage-efficiency-card-item.tsx
> +    } else if (error || stats === 0) {
Noobaa compresion ratio can be negative certain times
```suggestion
    } else if (error || stats <= 0) {
```

2020-09-15 19:17 UTC, afreen23 approved these changes
/lgtm

2020-09-15 21:11 UTC, merged