Bug 1877728: Fixes bug attaching block storage to pods, deployments in attach-storage page
openshift/console pull request #6609
Opened 2020-09-14 08:50 UTC by vbnrh

Using  block storage provisioners with RWX access mode incorrectly attaches the path as volumeMount in PodSpec instead of volumeDevice. This caused the pods to be in a state of ContainerCreation indefinitely. This  commit fixes this by  sending the object with the right configuration for block storage.

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1877728

Signed-off-by: Vineet Badrinath <vbadrina@redhat.com>

2020-09-14 09:02 UTC, vbnrh commented
/assign clouldbehl

2020-09-15 10:18 UTC, cloudbehl requested changes

2020-09-15 11:08 UTC, vbnrh commented on frontend/public/components/storage/attach-storage.tsx
> -};
I had added that for the type checks. I have reverted to use this itself. Thanks

2020-09-24 09:17 UTC, cloudbehl approved these changes

2020-09-24 09:17 UTC, cloudbehl commented
@spadgett Please review.

2020-10-01 14:25 UTC, ashcrow commented
Will review once approved

2020-10-02 12:27 UTC, spadgett approved these changes
/lgtm

2020-10-02 12:27 UTC, spadgett commented
@ashcrow PR is approved, thanks!

2020-10-02 17:34 UTC, merged