Fix timeout issue in ceph test suite
openshift/console pull request #6790
Opened 2020-09-30 09:27 UTC by ebondare

2020-09-30 10:11 UTC, ebondare commented
/assign @gnehapk

2020-09-30 16:31 UTC, shyRozen approved these changes

2020-10-01 08:40 UTC, bipuladh requested changes

2020-10-01 08:40 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/integration-tests/tests/2-tests/ocp-dashboard-card-healthcheck.scenario.ts
>      await browser.wait(until.presenceOf(mainHealtGreenSvg));
```suggestion
    await browser.wait(until.presenceOf(mainHealtGreenSvg), 60 * SECOND);
```

2020-10-01 08:40 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/integration-tests/tests/2-tests/ocp-dashboard-card-healthcheck.scenario.ts
> +    jasmine.DEFAULT_TIMEOUT_INTERVAL += 30 * SECOND;
```suggestion
```

2020-10-01 08:40 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/integration-tests/tests/2-tests/ocp-dashboard-card-healthcheck.scenario.ts
> +    jasmine.DEFAULT_TIMEOUT_INTERVAL -= 30 * SECOND;
```suggestion
```

2020-10-01 11:59 UTC, bipuladh approved these changes
/lgtm

2020-10-01 15:22 UTC, ebondare commented
/test e2e-gcp-console

2020-10-01 16:55 UTC, merged