adds serving in admin to show services, revisions, routes as tab views
openshift/console pull request #6848
Opened 2020-10-06 11:44 UTC by invincibleJai

**Fixes**: 
https://issues.redhat.com/browse/ODC-4880

**Analysis / Root cause**: 
Admin should see Serving under Serverless and all resources (services, revisions, routes) under it

**Solution Description**: 
- moved Serving under Serverless and all resources (services, revisions, routes) under it

**Screen shots / Gifs for design review**: 

**Unit test coverage report**: 

**Test setup:**

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2020-10-07 05:43 UTC, karthikjeeyar commented on frontend/packages/knative-plugin/src/plugin.tsx
> +            './components/overview/serving-list/ServingListsPage' /* webpackChunkName: "admin-pipeline" */
```suggestion
            './components/overview/serving-list/ServingListsPage' /* webpackChunkName: "serving-list-page" */
```

2020-10-07 05:47 UTC, karthikjeeyar commented on frontend/packages/knative-plugin/src/components/overview/serving-list/ServingListsPage.tsx
> +  match: Rmatch<any>;
nit:
```suggestion
  match: Rmatch<{ ns: string }>;
```

2020-10-07 12:44 UTC, sahil143 requested changes

2020-10-07 12:44 UTC, sahil143 commented on frontend/packages/dev-console/src/components/pipelines-lists/PipelinesListsPage.tsx
> +import MultiTabListPage from '@console/shared/src/components/multi-tab-list/MultiTabListPage';
should import from `@console/shared`
```suggestion
import {
  MenuAction,
  MenuActions,
  MultiTabListPage
} from '@console/shared';
```

2020-10-07 15:59 UTC, bmignano commented
LGTM!

2020-10-08 03:40 UTC, sahil143 approved these changes
/lgtm

2020-10-08 11:01 UTC, vikram-raj reviewed
I notice one issue, clicking on the details page breadcrumb should redirect back to the same tabbed list page. But currently, it is redirected back to the default list page.

2020-10-08 15:58 UTC, invincibleJai commented
> I notice one issue, clicking on the details page breadcrumb should redirect back to the same tabbed list page. But currently, it is redirected back to the default list page.

@vikram-raj thanks for highlighting, have updated PTAL

2020-10-08 16:08 UTC, vikram-raj reviewed
Thanks @invincibleJai.

/lgtm

2020-10-15 10:54 UTC, invincibleJai commented
/assign @rohitkrai03

2020-10-15 11:52 UTC, rohitkrai03 reviewed
Code looks good to me but found this bug that may not be related to this PR. Please take a look - 

![Peek 2020-10-15 17-15](https://user-images.githubusercontent.com/6041994/96119672-f639ba00-0f0a-11eb-8242-1db61986dfa2.gif)

2020-10-19 14:26 UTC, invincibleJai commented
> Code looks good to me but found this bug that may not be related to this PR. Please take a look -
> 

Thanks @rohitkrai03 Similar behaviour is there for other flows but yes there was an issue should show `create Service`. Have fixed it PTAL

![Oct-19-2020 19-52-25](https://user-images.githubusercontent.com/5129024/96464100-0e7c4280-1245-11eb-92e0-4995960da704.gif)

2020-10-20 10:46 UTC, rohitkrai03 approved these changes
/approve

2020-10-20 11:30 UTC, sahil143 approved these changes
/lgtm

2020-10-20 16:28 UTC, merged