feature flag Helm based on HelmRepository CRs
openshift/console pull request #7035
Opened 2020-10-29 18:29 UTC by debsmita1

**JIRA Story:**
https://issues.redhat.com/browse/ODC-5024

**Root Analysis:**
Need a way to enable/disable helm specific navigation items from the console if there are no helm repositories configured 

**Solution Description:**
- sets the FLAG_OPENSHIFT_HELM flag when there are no HelmChartRepository configured &
- hides the Helm nav item
- hides the Helm catalog item from the Add page
- hides Helm Charts from the Dev catalog
- the helm URLs shows 404

**GIF/Sceenshot:**
will be adding soon

2020-10-29 18:29 UTC, debsmita1 commented
/kind feature

2020-10-30 10:50 UTC, debsmita1 commented
/assign @rohitkrai03

2020-11-03 19:30 UTC, rohitkrai03 requested changes
Even after helm flag is disabled catalog has a type filter for Helm Charts. Its probably better if we remove that filter item as well when Helm is disabled. @serenamarie125 thoughts on this?

![Screenshot from 2020-11-04 00-59-59](https://user-images.githubusercontent.com/6041994/98031858-205f0780-1e39-11eb-84eb-529859e17bb5.png)

2020-11-05 17:28 UTC, debsmita1 commented
/cc @rachael-phillips

2020-11-09 21:13 UTC, rohitkrai03 requested changes

2020-11-09 21:13 UTC, rohitkrai03 commented on frontend/packages/dev-console/src/components/topology/helm/helmTopologyPlugin.tsx
> +      required: [FLAG_OPENSHIFT_HELM],
No need to remove topology visualization if helm is disabled.

2020-11-30 13:55 UTC, jeff-phillips-18 commented
We should also add the flag to the Helm Topology plugin: https://github.com/openshift/console/blob/6062e7e96baff020679764676655a8b54d46eb59/frontend/packages/topology/src/helm/helmTopologyPlugin.tsx

2020-11-30 14:00 UTC, rohitkrai03 requested changes
@debsmita1 Tested the PR locally. Everything works as expected except the catalog. You need to feature flag the catalog extensions for Helm as well. Update the file `/catalog/catalog-plugin.ts` in components folder and add the Helm feature flag in helm extensions.

2020-11-30 14:32 UTC, rohitkrai03 commented
@jeff-phillips-18 Based on the chats from this [thread](https://coreos.slack.com/archives/CRDPF7YS2/p1604943507073800?thread_ts=1604934392.072500&cid=CRDPF7YS2) it seems we would want to show the topology visualization for helm charts regardless of helm flag. Maybe @serenamarie125 can confirm it here as well.

2020-11-30 14:33 UTC, rohitkrai03 commented
> We should also add the flag to the Helm Topology plugin: https://github.com/openshift/console/blob/6062e7e96baff020679764676655a8b54d46eb59/frontend/packages/topology/src/helm/helmTopologyPlugin.tsx

@jeff-phillips-18 Based on the chats from this [thread](https://coreos.slack.com/archives/CRDPF7YS2/p1604943507073800?thread_ts=1604934392.072500&cid=CRDPF7YS2) it seems we would want to show the topology visualization for helm charts regardless of helm flag. Maybe @serenamarie125 can confirm it here as well.

2020-11-30 15:35 UTC, rohitkrai03 approved these changes
/approve
/lgtm

2020-11-30 15:36 UTC, rohitkrai03 commented
/retest

2020-11-30 19:30 UTC, rohitkrai03 commented
/retest

2020-12-01 06:49 UTC, merged