Add Encryption workflow for storage cluster creation
openshift/console pull request #7062
Opened 2020-11-01 20:07 UTC by a2batic

JIRA: https://issues.redhat.com/browse/RHSTOR-1445
Signed-off-by: Kanika Murarka <kmurarka@redhat.com>

2020-11-02 05:35 UTC, afreen23 requested changes

2020-11-03 08:51 UTC, a2batic commented on frontend/packages/ceph-storage-plugin/src/components/kms-config/kms-config.tsx
> +    </>
There will be more `FormGroup` to be added https://github.com/openshift/console/pull/7062/files#diff-ae3d56459b2491d83b6fe9502d3c74b3910fc605496fef5d596dcf713a097af6R12

2020-11-03 09:12 UTC, a2batic commented on frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/install-lso-sc.tsx
> -};
ack

2020-11-03 10:39 UTC, a2batic commented on frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/configure.tsx
> +            />
ack

2020-11-03 11:13 UTC, a2batic commented on frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/configure.tsx
> +              aria-label="Checkbox with Cluster-wide encryption"
ack

2020-11-03 11:13 UTC, a2batic commented on frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/configure.tsx
> +              aria-label="Checkbox with Cluster-wide encryption"
ack

2020-11-03 11:15 UTC, a2batic commented on frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/reducer.ts
> +  modeType: string;
ack

2020-11-03 11:27 UTC, a2batic commented on frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/configure.tsx
> +              id="pv-encryption"
ya, internally its encryption PVs, so I kept PV encryption. Will change it to storage class encyption for better understanding.

2020-11-18 11:03 UTC, a2batic commented
@cloudbehl ack, will add these changes in KMS related PR https://github.com/openshift/console/pull/7153

2020-11-19 05:34 UTC, afreen23 commented
/lgtm

okay to take https://github.com/openshift/console/pull/7062#discussion_r519565433
in the other PR

2020-11-19 07:31 UTC, a2batic commented
/retest

2020-11-19 08:17 UTC, merged