Gherkin Scripts for scenarios in ODC-4419
openshift/console pull request #7101
Opened 2020-11-04 12:57 UTC by gajanan-more

Fixes: https://issues.redhat.com/browse/ODC-4805

Problem: Gherkin Scripts for scenarios in ODC-4419

Solution: These are the gherkin scripts designed covering all the scenarios related to epic ODC-4419

2020-11-05 06:53 UTC, sanketpathak commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-operator-backed-service.feature
> +        And user clicks on the Jargar card
*Jaeger

2020-11-05 06:53 UTC, sanketpathak commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-operator-backed-service.feature
> +        And user clicks on the Jargar card
Same as above

2020-11-05 06:57 UTC, sanketpathak commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-options.feature
> +    As a user, I want to add things in context from topology
```suggestion
    As a user, I want to add things in the context in topology
```

2020-11-05 06:58 UTC, sanketpathak commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-operator-backed-service.feature
> +    As a user, I want to add things in context from topology
```suggestion
    As a user, I want to add things in the context in topology
```

2020-11-05 07:00 UTC, sanketpathak commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-options.feature
> +        And use clicks on Add to Project
```suggestion
        And user clicks on Add to Project
```

2020-11-05 07:00 UTC, sanketpathak commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-options.feature
> +        And use clicks on Add to Application
Same as above

2020-11-05 07:01 UTC, sanketpathak commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-options.feature
> +        And use clicks on Delete Application
Same as above

2020-11-05 07:04 UTC, sanketpathak commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-options.feature
> +        Given user at topology page
```suggestion
        Given user is at topology page
```

2020-11-05 07:05 UTC, sanketpathak commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-options.feature
> +        Given user at topology page
Change the others as well

2020-11-05 07:26 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-operator-backed-service.feature
> +        And user clicks on the Jargar card
Updated

2020-11-05 07:26 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-operator-backed-service.feature
> +        And user clicks on the Jargar card
Updated

2020-11-05 07:26 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-options.feature
> +    As a user, I want to add things in context from topology
Updated

2020-11-05 07:26 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-operator-backed-service.feature
> +    As a user, I want to add things in context from topology
Updated

2020-11-05 07:26 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-options.feature
> +        And use clicks on Add to Project
Updated

2020-11-05 07:27 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-options.feature
> +        Given user at topology page
Updated

2020-11-05 07:27 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-options.feature
> +        And use clicks on Delete Application
Updated

2020-11-05 10:36 UTC, sanketpathak commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-options.feature
> +    Scenario: Add to Application in Context
I think it would be delete

2020-11-05 10:38 UTC, sanketpathak commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-operator-backed-service.feature
> +        And user has created "hello-openshift" workload
```suggestion
        And user has created a workload named "hello-openshift"
```

2020-11-05 12:00 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-options.feature
> +    Scenario: Add to Application in Context
Updated

2020-11-05 12:00 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-operator-backed-service.feature
> +        And user has created "hello-openshift" workload
Updated

2020-11-05 12:02 UTC, sanketpathak commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-options.feature
> +    Scenario: Delete Application from in Context options
```suggestion
    Scenario: Delete Application from the Context options
```

2020-11-05 12:28 UTC, sanketpathak commented
/lgtm

2020-11-05 12:35 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-options.feature
> +    Scenario: Delete Application from in Context options
Updated

2020-11-05 15:51 UTC, sahil143 requested changes

2020-11-05 15:51 UTC, sahil143 commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-options.feature
> +        Then user can see in context options Samples, From Git, Container Image, From Dockerfile, From Catalog, Database, Operator Backed, Helm Chart, Event Source, Channel
```suggestion
        Then user can see in context options From Git, Container Image, From Dockerfile, Event Source, Channel
```

2020-11-06 09:59 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-options.feature
> +        Then user can see in context options Samples, From Git, Container Image, From Dockerfile, From Catalog, Database, Operator Backed, Helm Chart, Event Source, Channel
Updated

2020-11-09 03:58 UTC, sahil143 commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-options.feature
> +        And user has created "knative-demo" workload
this step should be reversed user can not create a grouping without a workload

2020-11-09 04:14 UTC, sahil143 commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-operator-backed-service.feature
> +        And user has created application grouping "aut-operator-backed"
same here.. user can not create grouping without a workload

2020-11-09 04:25 UTC, sahil143 approved these changes
/lgtm

2020-11-09 14:02 UTC, makambalaji reviewed
If all scenarios has same given statement, Then add that statement to Background section
In this type of case, Given is not mandate for scenarios

2020-11-11 04:47 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-operator-backed-service.feature
> +        Given user is at developer perspecitve
Updated

2020-11-11 04:47 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-operator-backed-service.feature
> +        Given user is at topology page
Updated

2020-11-11 04:47 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-operator-backed-service.feature
> +        Given user is at topology page
Updated

2020-11-11 04:47 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-operator-backed-service.feature
> +        Given user is on topology page
Updated

2020-11-11 04:47 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-options.feature
> +        Given user is at topology page
Updated

2020-11-11 04:48 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-options.feature
> +        Given user is at topology page
same as above

2020-11-11 04:48 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-options.feature
> +        Given user is at topology page
same as above

2020-11-11 06:22 UTC, makambalaji commented on frontend/packages/dev-console/integration-tests/features/topology/topology-in-context-add-options.feature
> +        Given user is at topology page
Background is nothing but given statements, So it works pretty well.. No issues with the immediate action

2020-11-11 07:05 UTC, makambalaji commented
/lgtm
/approve

2020-11-11 09:34 UTC, merged