add support for customSchema in resource sidebar for helm charts
openshift/console pull request #7154
Opened 2020-11-09 06:41 UTC by sahil143

**Fixes**: https://issues.redhat.com/browse/ODC-5041

**Analysis / Root cause**: missing schema sidebar for Helm charts install form

**Solution Description**: added support for custom schema in the sidebar

**Screen shots / Gifs for design review**: 

<img width="1496" alt="Screenshot 2020-11-09 at 12 07 58 PM" src="https://user-images.githubusercontent.com/9278015/98507774-472b9c80-2284-11eb-8602-07517f695518.png">
<img width="1491" alt="Screenshot 2020-11-09 at 12 08 14 PM" src="https://user-images.githubusercontent.com/9278015/98507801-56aae580-2284-11eb-9ffe-c025c4c1aa3c.png">

**Unit test coverage report**:

**Test setup:**

**Browser conformance**: 

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2020-11-09 06:41 UTC, sahil143 commented
/cc @rohitkrai03 
/assign @rohitkrai03 
/kind bug

2020-11-09 21:21 UTC, rohitkrai03 approved these changes
/approve

Tried it locally. Works as expected.

2020-11-09 21:43 UTC, rohitkrai03 commented
/approve cancel

2020-11-09 21:44 UTC, rohitkrai03 requested changes
You also need to pass `schema` prop on line 128 as it is a required prop of ResourceSchema component. `<ResourceSchema kindObj={kindObj} schema={schema} />`

2020-11-10 06:53 UTC, rohitkrai03 approved these changes
/lgtm
/approve

2020-11-10 06:54 UTC, rohitkrai03 commented
/cherrypick release-4.6

2020-11-10 23:26 UTC, merged

2020-11-12 07:08 UTC, rohitkrai03 commented
/retitle Bug 1886861: add support for customSchema in resource sidebar for helm charts

2020-11-26 07:38 UTC, andrewballantyne commented on frontend/packages/console-shared/src/components/formik-fields/field-types.ts
> +  schema?: any;
@sahil143 please avoid `any` types at any and all changes you get. I think this is supposed to be `JSONSchema6` based on the singular usage here of `formSchema` in `frontend/packages/dev-console/src/components/helm/form/HelmInstallUpgradeForm.tsx`... please confirm.

cc @rohitkrai03