Add Cypress OperatorHub test
openshift/console pull request #7244
Opened 2020-11-17 16:53 UTC by rhamilto

Resolves https://issues.redhat.com/browse/CONSOLE-2484

2020-11-17 19:00 UTC, rhamilto commented
/retest

2020-11-17 20:50 UTC, dtaylor113 requested changes
Looks pretty good to me, just a couple of concerns.  -thanks

2020-11-17 20:50 UTC, dtaylor113 commented on frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-hub.spec.ts
> +    const firstOperatorWithRHFilterApplied = cy
I'm not sure this is working the way you expect.  Pls see: https://docs.cypress.io/guides/references/best-practices.html#Assigning-Return-Values.   You'll probably want to use closures as descripted [here](https://docs.cypress.io/guides/core-concepts/variables-and-aliases.html#Return-Values).

2020-11-17 20:50 UTC, dtaylor113 commented on frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-hub.spec.ts
> +      .eq(2)
This seems somewhat prone to changing/breaking.  Anyway to find the tab/a more deterministacally?

2020-11-17 21:43 UTC, dtaylor113 commented on frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/operator-hub.spec.ts
> +    const firstOperatorWithRHFilterApplied = cy
I think something like:
```
cy.get('.catalog-tile-pf').first().find('.catalog-tile-pf-title').then(($catalogTitle => {
    cy.log('diable the Red Hat filter');
    cy.byTestID('providerType-red-hat').click();
    cy.log('enable the Certified filter');
    cy.byTestID('providerType-certified').click();
    cy.log('more than one tile should be present');
    cy.get('.catalog-tile-pf')
      .its('length')
      .should('be.gt', 0);
    cy.log('the first tile for Certified should not be the same as Red Hat');
    cy.get('.catalog-tile-pf')
      .first()
      .find('.catalog-tile-pf-title')
      .should('not.equal', catalogTitle);  // maybe catalogTitle.text or something
})
```

2020-11-18 14:53 UTC, rhamilto commented
Thanks for the helpful feedback, @dtaylor113.  Feedback incorporated.  PTAL.

2020-11-18 15:14 UTC, dtaylor113 approved these changes
/lgtm

2020-11-18 18:37 UTC, merged