Updated test-prow-e2e file to accommodate ceph
openshift/console pull request #7308
Opened 2020-11-24 09:54 UTC by cloudbehl

Signed-off-by: Ankush Behl <cloudbehl@gmail.com>

2020-11-24 13:36 UTC, bipuladh commented
/retest

2020-11-24 14:05 UTC, spadgett approved these changes
/lgtm

2020-11-24 18:37 UTC, a2batic commented
/test e2e-gcp-console

2020-11-24 20:42 UTC, spadgett commented
/hold

2020-11-24 20:43 UTC, spadgett requested changes
/lgtm cancel

2020-11-24 20:43 UTC, spadgett commented on test-prow-e2e.sh
> +if [ "$SCENARIO" != "login" ] || ["$SCENARIO" != "ceph"] ; then
Doesn't this need to be `&&`?

2020-11-25 05:03 UTC, cloudbehl commented on test-prow-e2e.sh
> +if [ "$SCENARIO" != "login" ] || ["$SCENARIO" != "ceph"] ; then
Ahh right!

2020-11-25 15:48 UTC, spadgett approved these changes
/lgtm

2020-11-25 16:28 UTC, bipuladh commented
/hold cancel

2020-11-25 16:29 UTC, bipuladh commented
/retest

2020-11-25 23:10 UTC, jerolimov commented
/retest

2020-11-26 01:33 UTC, bipuladh commented
/retest

2020-11-26 06:33 UTC, bipuladh commented
/retest

2020-11-26 08:56 UTC, merged