Metal3 i18n form
openshift/console pull request #7333
Opened 2020-11-25 20:26 UTC by yaacov

More Metal3 plugin i18n strings.

Missing from this PR - Actions, Menu Items and Tabs from `plugin.json` file.

![screenshot-localhost_9000-2020 11 25-20_58_07](https://user-images.githubusercontent.com/2181522/100278144-0c588280-2f6d-11eb-9b62-b7fd4c48d05f.png)
![screenshot-localhost_9000-2020 11 25-20_59_47](https://user-images.githubusercontent.com/2181522/100278150-0d89af80-2f6d-11eb-960e-5a5684e30dee.png)
![screenshot-localhost_9000-2020 11 25-21_00_46](https://user-images.githubusercontent.com/2181522/100278151-0e224600-2f6d-11eb-921c-9f511be615f2.png)
![screenshot-localhost_9000-2020 11 25-22_24_09](https://user-images.githubusercontent.com/2181522/100278152-0f537300-2f6d-11eb-9656-8dc8b59bf6f1.png)

2020-11-25 20:27 UTC, yaacov commented
@pcbailey @rawagner @glekner @metalice please review

2020-11-26 04:40 UTC, yaacov commented
/retest

2020-11-26 06:48 UTC, yaacov commented
/retest

2020-11-26 07:09 UTC, yaacov commented on frontend/packages/metal3-plugin/src/components/baremetal-hosts/add-baremetal-host/AddBareMetalHost.tsx
> +          t('metal3-plugin~Name ${value} is already taken.'), // eslint-disable-line no-template-curly-in-string
```suggestion
          t('metal3-plugin~Name "${value}" is already taken.'), // eslint-disable-line no-template-curly-in-string
```

2020-11-26 10:39 UTC, yaacov commented on frontend/packages/metal3-plugin/locales/en/metal3-plugin.json
> +  "Are you sure you want to stop maintenance <1>{reason ? ` (${reason}) ` : ''}</1>on node <3>{nodeName}</3>?": "Are you sure you want to stop maintenance <1>{reason ? ` (${reason}) ` : ''}</1>on nod
```suggestion
  "Are you sure you want to stop maintenance <1>{reason ? ` (${reason}) ` : ''}</1>on node <3>{nodeName}</3>?": "Are you sure you want to stop maintenance <1>{reason}</1>on node <3>{nodeName}</3>?",
```

2020-11-30 14:43 UTC, jtomasek approved these changes

2020-11-30 15:12 UTC, rawagner requested changes

2020-11-30 15:12 UTC, rawagner commented on frontend/packages/metal3-plugin/src/components/baremetal-nodes/dashboard/StatusCard.tsx
> +  const POWER_MGMT_MSG = t(
can you inline this ?

2020-11-30 15:12 UTC, rawagner commented on frontend/packages/metal3-plugin/src/components/baremetal-nodes/dashboard/StatusCard.tsx
> +  const POWER_MGMT_ALERT = () => ({
why is this a function ? 
Can you also use camelcase ?

2020-11-30 15:12 UTC, rawagner commented on frontend/packages/metal3-plugin/src/components/baremetal-nodes/dashboard/StatusCard.tsx
> +  const BMO_DISABLED_ALERT = {
i'd use camelcase here too

2020-11-30 15:12 UTC, rawagner commented on frontend/packages/metal3-plugin/src/components/baremetal-nodes/dashboard/StatusCard.tsx
> +  const POWER_MGMT_ALERT = () => ({
Can you also inline it together with BMO_DISABLED_ALERT ?

2020-11-30 15:12 UTC, rawagner commented on frontend/packages/metal3-plugin/src/components/modals/PowerOffHostModal.tsx
> +            powerOffMessage: getPowerOffMessage(t, pods),
I think we should not construct sentences anymore

2020-12-01 11:08 UTC, yaacov commented on frontend/packages/metal3-plugin/src/components/baremetal-nodes/table-filters.ts
> +    titleKey: 'Ready',
wow - thanks !

2020-12-01 13:08 UTC, yaacov commented on frontend/packages/metal3-plugin/src/components/baremetal-nodes/CSRStatus.tsx
> +  const CLIENT_CSR_DESC = t(
make cammelcase

2020-12-01 13:09 UTC, yaacov commented on frontend/packages/metal3-plugin/src/components/baremetal-nodes/dashboard/StatusCard.tsx
> +import { TFunction } from 'i18next';
move to top of file

2020-12-01 15:06 UTC, rawagner commented
/lgtm

2020-12-01 15:35 UTC, yaacov commented
/retest

2020-12-01 19:11 UTC, yaacov commented
/retest

2020-12-02 08:09 UTC, rawagner commented
/lgtm

2020-12-02 09:36 UTC, merged