(feat): Enable flexible scaling in storage cluster deployment
openshift/console pull request #7416
Opened 2020-12-04 08:46 UTC by afreen23

- implements https://issues.redhat.com/browse/RHSTOR-1399
 - moves arbiter form group to generic file

2020-12-04 09:04 UTC, afreen23 commented
Merge after https://github.com/openshift/console/pull/7376

2020-12-04 09:50 UTC, bipuladh requested changes

2020-12-04 09:50 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/src/utils/install.ts
> +  if ([...uniqZones].length < 3) return false;
```suggestion
  if (uniqZones.size < 3) return false;
```

2020-12-04 09:50 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/src/utils/install.ts
> +  if ([...uniqSelectedNodesZones].length !== 2) return false;
```suggestion
  if (uniqSelectedNodesZones.size !== 2) return false;
```

2020-12-04 09:50 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/src/utils/common-ocs-install-el.tsx
> +  'BAREMETALFLEXIBLESCALING' = 'BAREMETALFLEXIBLESCALING',
`INTERNAL_FLEXIBLE_SCALING & BAREMETAL_FLEXIBLE_SCALING`
More readable.

2020-12-04 09:50 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/src/components/ocs-install/ocs-request-data.ts
> +
This is for??

2020-12-04 10:50 UTC, bipuladh approved these changes
/lgtm

2020-12-04 13:31 UTC, a2batic commented
/lgtm

2020-12-04 13:51 UTC, afreen23 commented
/test analyze

2020-12-04 16:30 UTC, cloudbehl commented
/hold

 for https://github.com/openshift/console/pull/7376

2020-12-05 05:53 UTC, cloudbehl commented
/hold cancel

@afreen23 can you rebase!

2020-12-05 06:05 UTC, a2batic commented
/lgtm

2020-12-05 08:50 UTC, afreen23 commented
/test backend

2020-12-05 09:21 UTC, afreen23 commented
/test backend

2020-12-05 11:17 UTC, afreen23 commented
/test e2e-gcp-console

2020-12-05 18:42 UTC, a2batic commented
/test analyze

2020-12-05 19:21 UTC, merged