Fix pipelinerun visualization inprogress crash
openshift/console pull request #7438
Opened 2020-12-07 10:15 UTC by karthikjeeyar

**Fixes**: 

**Analysis / Root cause**: 
When starting a Pipeline multiple times the console crashes sometimes with this JavaScript error

**Solution Description**: 
If pipeline run is in progress and doesn't have enough information(pipelineSpec) to form the pipeline, then do not render the visualization graph.

**Screen shots / Gifs for design review**: 
![starting-runs-multiple-times](https://user-images.githubusercontent.com/9964343/101338198-ab9d4400-38a2-11eb-869e-38db7121794f.gif)

**Unit test coverage report**: 

![image](https://user-images.githubusercontent.com/9964343/101338427-f8811a80-38a2-11eb-8b66-a685d6617ff2.png)

**Test setup:**

1. Install Openshift pipelines operator
2. Create a pipeline using a add flow or yaml
3. Start the pipeline run multiple times using `start last run` option.

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

/kind bug
/assign @jerolimov

2020-12-07 11:09 UTC, karthikjeeyar commented
/test analyze

2020-12-07 11:22 UTC, jerolimov approved these changes
Crash is solved. :+1:

The update is visible to the user, so that visualization comes after the data is available.

/lgtm
/assign @andrewballantyne

2020-12-07 19:04 UTC, andrewballantyne requested changes
I think we actually want the solution to be in `frontend/packages/pipelines-plugin/src/components/pipelineruns/detail-page-tabs/PipelineRunVisualization.tsx`... this is a problem with our pulling the Pipeline logic from the Pipeline Run... which is a matter of time.

Making the change in `frontend/packages/pipelines-plugin/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualization.tsx` sets us up for an awkward situation of allowing the creation of a PipelineVisualization without a Pipeline -- and that's not ideal.

The solution should also be a Loading indicator not a null as when I reproduce this scenario and get a `null` back from the Pipeline it removes the graph and then pops back in without warning. Probably a better use experience to spin.

2020-12-07 19:06 UTC, andrewballantyne commented
> Crash is solved. 👍

Definitely solved the crash... so this is an _okay_ solution to the problem, however...

> The update is visible to the user, so that visualization comes after the data is available.

This is probably not the best user experiernce.

/lgtm cancel

2020-12-08 07:48 UTC, karthikjeeyar commented
Moved the check to `pipelineRunVisualization.tsx` and added loader for better UX.

![pipelinerun-loaded](https://user-images.githubusercontent.com/9964343/101454924-bc5bc180-3957-11eb-981c-3380074112f8.gif)

2020-12-09 20:41 UTC, andrewballantyne approved these changes
cc @bgliwa01

2020-12-09 21:02 UTC, bgliwa01 approved these changes
lgtm!

2020-12-09 21:04 UTC, andrewballantyne commented
/lgtm

Slight improvement on the solution @jerolimov lgtm'ed -- we talked about this solution and he was in agreement. Let's get this merged 😄

2020-12-09 23:17 UTC, merged