Gherkin script for improve management for helm ODC 2994
openshift/console pull request #7536
Opened 2020-12-14 07:10 UTC by sanketpathak

Epic: https://issues.redhat.com/browse/ODC-2994
Story:https://issues.redhat.com/browse/ODC-4843

2020-12-14 07:27 UTC, sanketpathak commented
/bugzilla refresh

2020-12-14 07:28 UTC, sanketpathak commented
/bugzilla refresh

2020-12-15 10:03 UTC, gajanan-more requested changes

2020-12-15 10:03 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/helm/helm_feature_flag_ODC-5024.feature
> +    And user can see Helm Charts filter in the Developer Catalog page
Please update Indentation

2020-12-15 10:51 UTC, sanketpathak commented on frontend/packages/dev-console/integration-tests/features/addFlow/developer-Catalog-Details.feature
> +        And user select redhat-helm-repo from the list of Chart Repositories
Updated

2020-12-15 10:52 UTC, sanketpathak commented on frontend/packages/dev-console/integration-tests/features/helm/helm_feature_flag_ODC-5024.feature
> +    And user can see Helm Charts filter in the Developer Catalog page
Updated

2020-12-15 10:57 UTC, gajanan-more approved these changes

2020-12-15 10:57 UTC, gajanan-more commented
/lgtm

2020-12-15 11:34 UTC, rohitkrai03 approved these changes
LGTM

2020-12-15 21:32 UTC, merged