Gherkin Script Scenarios for epic ODC-5057
openshift/console pull request #7554
Opened 2020-12-15 12:12 UTC by gajanan-more

Fixes: https://issues.redhat.com/browse/ODC-4839

Problem: Gherkin Scripts for scenarios for ODC-5057

Solution: These are the gherkin scripts designed covering all the scenarios related to epics ODC-5057

2020-12-15 12:16 UTC, gajanan-more commented
/assign @makambalaji @jerolimov

2020-12-15 13:10 UTC, makambalaji requested changes
Please add @addFlow for all scenarios

2020-12-15 13:10 UTC, makambalaji commented on frontend/packages/dev-console/integration-tests/features/addFlow/developer-Catalog-Details.feature
> +        And user clicks on View Details under spec
```suggestion
        When user clicks on View Details under spec in sidebar
```

2020-12-15 13:10 UTC, makambalaji commented on frontend/packages/dev-console/integration-tests/features/addFlow/developer-Catalog-Details.feature
> +        And user clicks on View Details under developerCatalog
```suggestion
        And user clicks on View Details under customization section in sidebar
        And user clicks on View Details under developerCatalog section in sidebar
```

2020-12-15 13:10 UTC, makambalaji commented on frontend/packages/dev-console/integration-tests/features/addFlow/developer-Catalog-Details.feature
> +        And user clicks on View Details under catagories
```suggestion
        And user clicks on View Details under categories
```

2020-12-15 13:10 UTC, makambalaji commented on frontend/packages/dev-console/integration-tests/features/addFlow/developer-Catalog-Details.feature
> +        And user clicks on Reload button when asked to
```suggestion
        And user clicks on Reload button
```

2020-12-15 13:10 UTC, makambalaji commented on frontend/packages/dev-console/integration-tests/features/addFlow/developer-Catalog-Details.feature
> +        Then user will see all the catagories except Languages added under spec.customization.developerCatalog.catagories
```suggestion
        Then user will see all the categories except Languages added under spec.customization.developerCatalog.catagories
```

2020-12-15 13:10 UTC, makambalaji commented on frontend/packages/dev-console/integration-tests/features/addFlow/developer-Catalog-Details.feature
> +        And user will see all the catagories except Languages on Developer Catalog page
```suggestion
        And user will see all the categories except Languages on Developer Catalog page
```

2020-12-15 13:26 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/addFlow/developer-Catalog-Details.feature
> +    Scenario: Developer Catalog Customization - Edit Catagories
Updated

2020-12-15 13:26 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/addFlow/developer-Catalog-Details.feature
> +    Scenario: Developer Catalog Customization - Catagories
Updated

2020-12-15 13:26 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/addFlow/developer-Catalog-Details.feature
> +        Then user will not see Catagories
Updated

2020-12-15 13:26 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/addFlow/developer-Catalog-Details.feature
> +    Scenario: Developer Catalog Customization - Add empty Catagories
Updated

2020-12-15 13:26 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/addFlow/developer-Catalog-Details.feature
> +        And user goes to YAML tab
Updated

2020-12-15 13:27 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/addFlow/developer-Catalog-Details.feature
> +        And user clicks on Reload button when asked to
Updated

2020-12-15 13:27 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/addFlow/developer-Catalog-Details.feature
> +        And user clicks on View Details under spec
Updated

2020-12-15 13:27 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/addFlow/developer-Catalog-Details.feature
> +        And user clicks on View Details under developerCatalog
Updated

2020-12-15 13:27 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/addFlow/developer-Catalog-Details.feature
> +        And user clicks on View Details under catagories
Updated

2020-12-15 13:27 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/addFlow/developer-Catalog-Details.feature
> +        And user clicks on Reload button when asked to
Updated

2020-12-15 13:27 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/addFlow/developer-Catalog-Details.feature
> +        Then user will see all the catagories except Languages added under spec.customization.developerCatalog.catagories
Updated

2020-12-15 13:27 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/addFlow/developer-Catalog-Details.feature
> +        And user will see all the catagories except Languages on Developer Catalog page
Updated

2020-12-15 13:29 UTC, makambalaji commented
/approve

2020-12-15 13:31 UTC, jerolimov commented
looks like it tests all required cases :+1:

/lgtm

2020-12-16 05:36 UTC, sanketpathak commented
/lgtm

2020-12-16 08:30 UTC, merged