Add noobaa sso test migration to cypress
openshift/console pull request #7570
Opened 2020-12-16 13:41 UTC by TimothyAsirJeyasing

Signed-off-by: Timothy Asir Jeyasingh <tjeyasin@redhat.com>

2020-12-16 13:42 UTC, TimothyAsirJeyasing commented
@bipuladh , @afreen23 Please review

2020-12-16 14:41 UTC, bipuladh approved these changes
One minor change.
Everything else looks good
/ok-to-test

2020-12-16 14:41 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/noobaa-sso.spec.ts
> +  before(() => {
```suggestion
  before(() => {
      cy.install();
```

2020-12-16 14:45 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/noobaa-sso.spec.ts
> +    cy.byLegacyTestID('system-name-mcg').eq(0)
Let's update the UI to make sure `data-test-id` is not reused inside the same space.
```suggestion
    cy.byLegacyTestID('system-name-mcg')
```

2020-12-21 06:07 UTC, a2batic commented
@TimothyAsirJeyasing please squash the commits.

2020-12-21 06:09 UTC, a2batic commented
/retest

2020-12-21 10:56 UTC, afreen23 requested changes

2020-12-21 10:56 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/noobaa-sso.spec.ts
> +    cy.login();
You should have login() first and then install()
```suggestion
    cy.login();
    cy.install();
```

2020-12-21 10:56 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/noobaa-sso.spec.ts
> +  it('Test admin user login for noobaa', () => {
We dont want to modify existing test cases but migrate them to cypress.
https://github.com/openshift/console/blob/36558f21ee5161b36e6da6d19ef0da2adaf8cf28/frontend/packages/ceph-storage-plugin/integration-tests/tests/2-tests/noobaa-sso-scenario.ts#L1

2020-12-22 12:22 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/noobaa-sso.spec.ts
> +    checkErrors();
```suggestion
    cy.checkErrors();
```

2020-12-22 12:22 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/noobaa-sso.spec.ts
> +import { checkErrors } from '../../../integration-tests-cypress/support';
```suggestion
```

2020-12-22 12:39 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/noobaa-sso.spec.ts
> +          });
```suggestion
            expect(response.status).toEqual(200)
            expect(response.body).contains(
              'NooBaa Management Console')
          });
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console/7570/pull-ci-openshift-console-master-frontend/1340992172702306304#1:build-log.txt%3A1485

2021-01-29 16:00 UTC, bipuladh commented
/retest

2021-01-29 16:13 UTC, bipuladh commented
@TimothyAsirJeyasing please squash the commits. Rest of the PR looks good.
/retest

2021-01-29 17:05 UTC, bipuladh commented
/retest

2021-02-02 12:14 UTC, bipuladh commented
/lgtm

2021-02-03 01:34 UTC, merged