Add missing tooltips for KMS advanced modal
openshift/console pull request #7582
Opened 2020-12-16 18:33 UTC by a2batic

Signed-off-by: Kanika Murarka <kmurarka@redhat.com>

2020-12-16 18:33 UTC, a2batic commented
/assign @Madhu-1 @nixpanic @GowthamShanmugam @cloudbehl

2020-12-16 18:49 UTC, a2batic commented
/retest

2020-12-16 20:14 UTC, afreen23 commented
Please run yarn i18n to update the keys.

2020-12-17 05:21 UTC, afreen23 requested changes

2020-12-17 05:21 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/components/ocs-storage-class-form/ocs-storage-class-form.tsx
> +            <span className="help-block ocs-storageClass-encryption__help-block">Vault</span>
externalize this string - 'Vault'

2020-12-17 08:08 UTC, nixpanic approved these changes

2020-12-17 08:08 UTC, nixpanic commented on frontend/packages/ceph-storage-plugin/src/components/modals/advanced-kms-modal/advanced-kms-modal.tsx
> +    'ceph-storage-plugin~The Vault namespace to use for the OpenShift Container Storage communication with the Vault server. Using relative paths is allowed. Mainly used for KMS tenants.',
This reads a little difficult. The previous contents made more sense to me.

Note that this is not about OpenShift Namespaces, but Namespaces inside the Vault service (only available with Hashicorps Vault Enterprise product). More details are at https://www.vaultproject.io/docs/enterprise/namespaces

I do not know about the request to change this text, so you do not need to see this as a _needs to change_ review.

2020-12-17 08:08 UTC, nixpanic commented on frontend/packages/ceph-storage-plugin/src/components/modals/advanced-kms-modal/advanced-kms-modal.tsx
> +    `ceph-storage-plugin~A PEM-encoded CA certificate file used to verify the Vault server's SSL certificate. This value, if exists, takes precedence over VAULT_CAPATH.`,
Do we support setting `VAULT_CAPATH`? That would mean the PATH is inside the Ceph-CSI provisioner and node-plugin, and we normally do not add additional files to our containers. Maybe drop _This value, if exists, takes precedence over VAULT_CAPATH._?

2020-12-21 21:04 UTC, a2batic commented
/test analyze

2020-12-21 21:13 UTC, a2batic commented
/test analyze

2020-12-22 08:22 UTC, nixpanic approved these changes
Text and Secret look good to me. Thanks!

2020-12-22 09:37 UTC, afreen23 commented
/lgtm

2020-12-22 11:39 UTC, merged