fix pipeline yaml edit flow
openshift/console pull request #7618
Opened 2020-12-21 16:16 UTC by debsmita1

**Fixes:**
https://issues.redhat.com/browse/ODC-5270

**Analysis / Root cause:** 
The new pipeline obj has no resourceVersion property

**Solution Description:**
Merged the new pipeline and existing pipeline objects

**GIF:**
![pipeline-yaml-edit](https://user-images.githubusercontent.com/22490998/102797520-ce1c7a80-43d5-11eb-9c28-2611088cf4b6.gif)

**Unit test coverage report:**

**Browser conformance:**
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2020-12-21 16:16 UTC, debsmita1 commented
/kind bug

2020-12-22 09:11 UTC, debsmita1 commented
/cc @rottencandy @karthikjeeyar

2020-12-22 09:54 UTC, rottencandy commented on frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineBuilderPage.tsx
> -          pipeline.metadata.namespace = ns;
I think we should keep the `namespace` check, or it would cause [ODC-5251](https://issues.redhat.com/browse/ODC-5251) to appear again.

2020-12-22 11:03 UTC, rottencandy commented
Not able to delete an individual task or a param from the pipeline:
![tmp_pl](https://user-images.githubusercontent.com/20013884/102881785-5dc43680-4473-11eb-99ff-48fc4e16cde3.gif)

2020-12-22 15:52 UTC, rottencandy approved these changes
/lgtm

2021-01-07 07:07 UTC, debsmita1 commented
/assign @andrewballantyne

2021-01-12 13:29 UTC, rohitkrai03 commented
/assign

2021-01-12 13:36 UTC, rohitkrai03 requested changes

2021-01-12 13:36 UTC, rohitkrai03 commented on frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/PipelineBuilderPage.tsx
> +        pipeline =
Why can't we do something similar to how edit-yaml component handles updates?

2021-01-12 15:42 UTC, karthikjeeyar commented
@debsmita1
While editing the pipeline in the yaml view extra properties like `resourceVersion`, `managedFields` etc are not shown in the pipeline yaml view.  IMO we should show all the fields in the yaml view without hiding any fields.

The problem is here is in `PipelineBuilderForm.tsx`,  `sanitizeToYaml` function converts the form to yaml using `convertBuilderFormToPipeline` (missing the third argument `existingPipeline`). This should fix the issue and also show all the missing  fields in the yaml editor. Please revert the current fix and add the third argument to make it work.

2021-01-12 15:44 UTC, karthikjeeyar commented
/lgtm cancel

2021-01-12 17:01 UTC, karthikjeeyar commented
Thanks @debsmita1 
/lgtm

2021-01-12 20:01 UTC, andrewballantyne approved these changes

2021-01-12 22:34 UTC, merged