add translation for pipeline status
openshift/console pull request #7657
Opened 2020-12-24 18:18 UTC by vikram-raj

**Fixes**: 
https://issues.redhat.com/browse/ODC-5292

**Analysis / Root cause**: 
Translation for Pipeline status and breadcrumb text is missing.

**Solution Description**: 
Add translation for Pipeline status and breadcrumb text.

2020-12-29 17:00 UTC, debsmita1 commented
The dropdown items are not translated
![items](https://user-images.githubusercontent.com/22490998/103300028-ef0f4c00-4a23-11eb-8330-278d21355890.png)

2021-01-05 15:47 UTC, debsmita1 commented
![t3](https://user-images.githubusercontent.com/22490998/103666987-59336e00-4f9b-11eb-83fa-eb493d466940.png)
![t1](https://user-images.githubusercontent.com/22490998/103666990-5afd3180-4f9b-11eb-83c3-87e43cf1608f.png)
![t](https://user-images.githubusercontent.com/22490998/103666993-5b95c800-4f9b-11eb-9c01-12140172e446.png)

these are missed

2021-01-05 15:47 UTC, debsmita1 commented on frontend/packages/console-shared/src/hooks/useTabbedTableBreadcrumb.ts
>        name: kindObj.labelPlural,
oh right! my bad

2021-01-05 16:10 UTC, vikram-raj commented
Added the translation for pipelines create options.

2021-01-06 23:05 UTC, jerolimov requested changes
@vikram-raj Also with this PR the pipeline status fields are not translated. On the Pipeline list, PipelineRun list as well on the TaskRun list:

![image](https://user-images.githubusercontent.com/139310/103829748-45f7cf80-507b-11eb-9184-3183b10c4ffb.png)

In the breadcrumb the word "Pipelines" is not translated on the overview page and on the pipeline detail page. But it is translated in the navigation. We do this also for Build Configs and Helm Release, so I think we should do this also for Pipelines:

![image](https://user-images.githubusercontent.com/139310/103830772-8c4d2e80-507b-11eb-848c-16aab9ac27fb.png)

![image](https://user-images.githubusercontent.com/139310/103830989-9b33e100-507b-11eb-86d4-f2f20a7b9e1b.png)

2021-01-07 16:44 UTC, vikram-raj commented
@jerolimov Added the translation for the `Pipeline` page title. And for the status and breadcrumbs, we are using the component from the public and console-shared. So, adding the translation for status and breadcrumb requires works in other packages as well.

2021-01-12 16:28 UTC, andrewballantyne commented
@vikram-raj Isn't it explicitly in your ticket to support the status values? Am I missing something or misunderstanding something?

![Screen Shot 2021-01-12 at 11 26 17 AM](https://user-images.githubusercontent.com/8126518/104342799-3a683680-54c9-11eb-92ce-6d9af1aced39.png)
![Screen Shot 2021-01-12 at 11 26 28 AM](https://user-images.githubusercontent.com/8126518/104342801-3b00cd00-54c9-11eb-9ffc-7cfafcc49de9.png)

2021-01-13 10:13 UTC, vikram-raj commented
@jerolimov @andrewballantyne Added translation for status as well.

2021-01-13 11:02 UTC, jerolimov commented on frontend/packages/pipelines-plugin/src/components/pipelines/modals/triggers/TriggerBindingSection.tsx
> +              <code>{`$(${paramPrefix}parameter)`}</code>
:+1:

2021-01-13 11:05 UTC, jerolimov approved these changes
Tested this locally, pipeline status fields are now translated.

/lgtm

2021-01-13 11:07 UTC, jerolimov commented
/assign @andrewballantyne 

Andrew, FYI, we discussed that we do not translate the status in the header field at the moment because this needs a unnecessary big refactoring. This field is also not translated for Pods etc. So there are still many small things to-do for 4.7.z or 4.8. Are you fine with this?

![image](https://user-images.githubusercontent.com/139310/104444317-e8daad00-5597-11eb-8e8d-a939cc4c6b86.png)

2021-01-13 12:09 UTC, andrewballantyne commented
> /assign @andrewballantyne
> 
> Andrew, FYI, we discussed that we do not translate the status in the header field at the moment because this needs a unnecessary big refactoring. This field is also not translated for Pods etc. So there are still many small things to-do for 4.7.z or 4.8. Are you fine with this?
> 
> ![image](https://user-images.githubusercontent.com/139310/104444317-e8daad00-5597-11eb-8e8d-a939cc4c6b86.png)

That's not ideal but can be done separately of this PR. Please open up a forum to discuss with the Admin team in #tmp-i18n slack room. See if they are aware of / already addressing the status in the header.

2021-01-13 19:33 UTC, andrewballantyne approved these changes

2021-01-13 23:22 UTC, merged