Bug 1890731: Migration status title is now showing state of migration
openshift/console pull request #7664
Opened 2020-12-28 12:05 UTC by metalice

Signed-off-by: Matan Schatzman <mschatzm@redhat.com>

**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1890731

**Analysis / Root cause**: 
The title wasn't taken from migration status but from machine status.

**Solution Description**: 
The title is now constructed from migration status or machine status.

**Screen shots / Gifs for design review**: 
![bug 1890731](https://user-images.githubusercontent.com/14824964/103213234-bd0fc400-4915-11eb-83d5-df28620ea480.gif)

2020-12-28 12:29 UTC, glekner requested changes

2020-12-28 12:29 UTC, glekner commented on frontend/packages/kubevirt-plugin/src/selectors/vmi-migration/selectors.ts
> +  return migrationPhase ? `${migrationPhase} Migration` : title || VMStatus.UNKNOWN.toString();
Maybe do 
```suggestion
  return migrationPhase ? `Migration - ${migrationPhase}` : title || VMStatus.UNKNOWN.toString();
```

2020-12-28 12:36 UTC, glekner commented
/lgtm

2020-12-28 13:02 UTC, yaacov commented on frontend/packages/kubevirt-plugin/src/selectors/vmi-migration/selectors.ts
> +  return migrationPhase ? `${migrationPhase} Migration` : title || VMStatus.UNKNOWN.toString();
```suggestion
  return migrationPhase ? t('{{migrationPhase}} Migration', {migrationPhase}) : title || VMStatus.UNKNOWN.toString();
```

2020-12-28 13:03 UTC, yaacov commented on frontend/packages/kubevirt-plugin/src/components/vm-status/vm-status.tsx
> +    <GenericStatus title={migrationTitle} Icon={icon} popoverTitle={popoverTitle}>
this is only for migrations ?

2020-12-28 14:02 UTC, yaacov commented
/retest

2020-12-28 14:42 UTC, metalice commented
/hold

2020-12-28 18:13 UTC, metalice commented
/hold cancel

2020-12-29 05:23 UTC, yaacov commented on frontend/packages/kubevirt-plugin/src/components/vm-status/vm-status.tsx
> +  const title = t(status.getLabelKey()) || status.toString(); // TODO status.toVerboseString() should be called to pass to popup header
```suggestion
  const title = t(status.getLabelKey()) || status.toString() || t('kubevirt-plugin~Unknown'); 
```

2020-12-29 05:30 UTC, yaacov commented on frontend/packages/kubevirt-plugin/src/constants/vm/vm-status.ts
> +  static readonly MIGRATING_STATUS = (status = 'Pending') =>
```suggestion
  static readonly getMigrationStatus = (phase = 'Pending') =>
```

2020-12-29 05:30 UTC, yaacov commented on frontend/packages/kubevirt-plugin/src/constants/vm/vm-status.ts
> +export const VMStatusMigrationOptions = {
```suggestion
export const VMStatusMigrationPhases = {
```

2020-12-29 05:33 UTC, yaacov commented on frontend/packages/kubevirt-plugin/src/statuses/vm/vm-status.ts
>      return {
```suggestion
    const phase = getMigrationStatusPhase(migration);
    return {
```

2020-12-29 08:46 UTC, yaacov commented
/lgtm

2020-12-29 12:20 UTC, yaacov commented
/hold 
for translations

2020-12-29 12:29 UTC, yaacov commented
/hold cancel
/lgtm

2020-12-29 16:03 UTC, merged