updated add-flow-scenarios automation scripts
openshift/console pull request #7740
Opened 2021-01-07 07:46 UTC by makambalaji

Cypress scripts related to Database, Yaml, Operator-Backed and Page-Details and tag names
Please Note: This scripts are not integrated with CI
If need to verify, execute the below command "npm run test-cypress-devconsole" on fronted

Test Results:
No. of smoke test cases in this pr : 0 [Execution Time: - sec]
No. of regression test cases in this pr: [Execution Time: - sec]
No. of test cases in this pr: [Execution Time: - sec]

2021-01-07 10:05 UTC, gajanan-more requested changes
Can you please update the files with suggested changes?

2021-01-07 10:05 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/getting-started/getting_started _to_dev_perspective.feature
> +        Then user redirects to developer perspective
Can you please add new line?

2021-01-07 11:49 UTC, makambalaji commented on frontend/packages/dev-console/integration-tests/features/getting-started/getting_started _to_dev_perspective.feature
> +        Then user redirects to developer perspective
updated

2021-01-25 10:12 UTC, makambalaji commented
/retest

2021-01-26 12:21 UTC, andrewballantyne commented
@makambalaji Would appear you have some type errors. Please look to fix those asap so we can see this merge before the end of the sprint.

2021-01-31 18:54 UTC, makambalaji commented
closing this pr, due to merge and labels issue. Creating a fresh pr: https://github.com/openshift/console/pull/7989

2021-01-31 18:54 UTC, closed without merging