Bug 1914941: VM Template rootdisk is not deleted after fetching default disk bus
openshift/console pull request #7793
Opened 2021-01-11 14:36 UTC by glekner

2021-01-11 14:45 UTC, metalice commented
/lgtm

2021-01-11 16:00 UTC, suomiy requested changes

2021-01-11 16:00 UTC, suomiy commented on frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/initial-state/storage-tab-initial-state.ts
> -  const diskBus = tmpDiskBus || new DiskWrapper(rootStorage?.disk).getDiskBus();
what is wrong with this part?

2021-01-11 16:01 UTC, suomiy commented
/hold

@metalice can you please wait with the lgtms a bit in new PRs?

2021-01-11 16:21 UTC, suomiy commented on frontend/packages/kubevirt-plugin/src/hooks/use-update-data-volume.ts
> +    removeStorage(templateDisk);
Also, as I noted [here](https://github.com/openshift/console/pull/7749) we probably shouldn't have the decision logic scattered everywhere but just in updaters. We can open a discussion regarding this topic if you want (cc @metalice )

+1 for moving this from storage-tab - which doesn't have to be even rendered.

2021-01-13 11:21 UTC, glekner commented
@suomiy I think I fixed it

2021-01-13 11:21 UTC, glekner commented on frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/initial-state/storage-tab-initial-state.ts
> -  const diskBus = tmpDiskBus || new DiskWrapper(rootStorage?.disk).getDiskBus();
reverted

2021-01-13 11:29 UTC, suomiy commented
+1 simpler and cleaner
/lgtm

2021-01-13 11:32 UTC, glekner commented on frontend/packages/kubevirt-plugin/src/components/create-vm-wizard/redux/state-update/prefill-vm-template-state-update.ts
> +      ? getDisks(vm).filter((d) => d.name !== VM_TEMPLATE_NAME_PARAMETER)
@yaacov @metalice please note this is the correct fix, we should stick to updaters.

2021-01-13 12:05 UTC, yaacov commented
/hold cancel

2021-01-13 12:16 UTC, yaacov commented
/bugzilla refresh

2021-01-13 23:24 UTC, merged