Bug 1866331: Add field level help at various OCS pages
openshift/console pull request #7804
Opened 2021-01-12 13:26 UTC by bipuladh

- Adds help text in dashboards.
 - Adds help text in installation flow.
![Screenshot from 2021-01-12 18-55-24](https://user-images.githubusercontent.com/54092533/104320031-ca2cd580-5507-11eb-9010-b00c5a19cdca.png)
![Screenshot from 2021-01-12 18-14-08](https://user-images.githubusercontent.com/54092533/104320036-cbf69900-5507-11eb-852e-beaf46843e8e.png)
![Screenshot from 2021-01-12 18-13-57](https://user-images.githubusercontent.com/54092533/104320037-cc8f2f80-5507-11eb-87e9-bccece86f674.png)
![Screenshot from 2021-01-12 18-09-13](https://user-images.githubusercontent.com/54092533/104320039-cd27c600-5507-11eb-99eb-daf56a271f7d.png)

2021-01-13 16:43 UTC, afreen23 commented on frontend/packages/noobaa-storage-plugin/src/components/data-consumption-card/data-consumption-card.tsx
> +              'noobaa-storage-plugin~Shows an overview of the data consumption per provider or account collected from the day of the entity creation.',
```suggestion
              'noobaa-storage-plugin~Shows an overview of the data consumption per provider or per account from the day of the entity creation.',
```

2021-01-29 15:03 UTC, bipuladh commented
/retest

2021-01-29 15:03 UTC, bipuladh commented
/test ceph-storage-plugin

2021-01-29 15:30 UTC, droslean commented
/test ceph-storage-plugin

2021-01-29 15:32 UTC, droslean commented
/test ceph-storage-plugin

2021-01-29 15:43 UTC, droslean commented
/test ceph-storage-plugin

2021-01-29 15:56 UTC, bipuladh commented
/test ceph-storage-plugin

2021-02-03 10:36 UTC, cloudbehl commented
frontend tests are failing.

2021-03-23 19:03 UTC, afreen23 requested changes
Please rebase

2021-03-23 19:03 UTC, afreen23 commented on frontend/packages/noobaa-storage-plugin/src/components/capacity-breakdown/capacity-breakdown-card.tsx
> +            )}
Lets be consistent, We are not mentioning card anywhere.
```suggestion
              'noobaa-storage-plugin~Shows used capacity by different resources. The available capacity is based on cloud services therefore it cannot be shown.',
            )}
```

2021-04-29 12:07 UTC, bipuladh commented
/close

2021-04-29 12:07 UTC, closed without merging