[WIP] Migrates object service dashboard tests to cypress
openshift/console pull request #7815
Opened 2021-01-13 06:38 UTC by vbnrh

Signed-off-by: Vineet Badrinath <vbadrina@redhat.com>

2021-02-22 05:35 UTC, bipuladh requested changes
skimmed through it, needs a more indepth review.

2021-02-22 05:35 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/object-service-dashboards.spec.ts
> +    cy.get('div:nth-child(1) > div.co-inventory-card__item-title')
Use `data-test`

2021-02-22 05:35 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/object-service-dashboards.spec.ts
> +    cy.get('div:nth-child(3) > div.co-inventory-card__item-title')
Use data-test

2021-02-22 05:35 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/object-service-dashboards.spec.ts
> +        cy.get('div:nth-child(3) > div.co-inventory-card__item-title')
use data-test

2021-02-22 05:35 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/object-service-dashboards.spec.ts
> +  };
Move it to utils.

2021-02-22 05:35 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/object-service-dashboards.spec.ts
> +  };
We are always running this test on cloud at this current point so we don't really need this. We can introduce this once we need it.

2021-02-22 05:35 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/object-service-dashboards.spec.ts
> +      cy.get('div > div > div:nth-child(1) > div > div.co-dashboard-icon > svg').should(
data-test

2021-02-22 05:35 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/object-service-dashboards.spec.ts
> +    }
```suggestion
```
RGW is not going to be present.

2021-02-22 05:35 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/object-service-dashboards.spec.ts
> +    cy.get('div:nth-child(1) > div.ceph-storage-efficiency-card__item-status > span')
data-test

2021-02-22 05:35 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/object-service-dashboards.spec.ts
> +    cy.get('div:nth-child(2) > div.ceph-storage-efficiency-card__item-status > span')
data-test

2021-02-22 05:35 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/integration-tests-cypress/tests/object-service-dashboards.spec.ts
> +    cy.get('.nb-resource-providers-card__row-title')
data-test

2021-03-01 11:01 UTC, rexagod commented
/retest

2021-03-01 11:02 UTC, rexagod commented
^^ Wanted to look at CI's artifacts and whether they differ from my local results.

2021-03-01 21:13 UTC, rexagod commented
Continued @ #8270 since I don't have permissions to push here.

2021-03-17 12:41 UTC, closed without merging