Bug 1907660: Render pod list cell height correctly when pod names are long
openshift/console pull request #7821
Opened 2021-01-13 11:16 UTC by debsmita1

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1907660

**Solution Description:**
- replaced the `withUserSettingsCompatibility` HOC with the `useUserSettingsCompatibility` hook

**GIF:** 
![fix-cell-height](https://user-images.githubusercontent.com/22490998/104443930-19810d80-55bd-11eb-8a07-47968999a6e6.gif)

**Browser conformance:**
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2021-01-13 11:16 UTC, debsmita1 commented
/kind bug

2021-01-13 11:19 UTC, debsmita1 commented
/bugzilla refresh

2021-01-13 11:20 UTC, debsmita1 commented
/cc @jerolimov @rhamilto

2021-01-13 11:48 UTC, jerolimov requested changes
WOW. Impressed that this solves this issue, but it works great. Small request to keep the old default value.

2021-01-13 11:48 UTC, jerolimov commented on frontend/packages/console-app/src/components/nodes/NodesPage.tsx
> +      null,
Please keep the default as undefined so that this value are not stored in user settings configmap until the user changes the table config.

2021-01-13 11:48 UTC, jerolimov commented on frontend/public/components/namespace.jsx
> +      null,
Please keep the default as undefined so that this value are not stored in user settings configmap until the user changes the table config.

2021-01-13 11:48 UTC, jerolimov commented on frontend/public/components/pod.tsx
> +      null,
Please keep the default as undefined so that this value are not stored in user settings configmap until the user changes the table config.

2021-01-13 11:48 UTC, jerolimov commented on frontend/public/components/namespace.jsx
> +      null,
Please keep the default as undefined so that this value are not stored in user settings configmap until the user changes the table config.

2021-01-13 18:30 UTC, debsmita1 commented
/retest

2021-01-13 18:50 UTC, jerolimov approved these changes
Works fine. Tested resizing the window, changing the columns and switching between pages. Doesn't see the rendering-height-lag anymore. :+1: 

/lgtm

2021-01-13 18:52 UTC, jerolimov commented
/assign @rhamilto @christianvogt

2021-01-13 18:59 UTC, rhamilto reviewed
LGTM, but will wait on Christian for final approval.

2021-01-14 17:47 UTC, christianvogt commented
/lgtm

2021-01-14 19:55 UTC, merged