Bug 1917239: fix devconsole monitoring dashboard toolbar
openshift/console pull request #7855
Opened 2021-01-18 07:26 UTC by vikram-raj

**Fixes**: 
https://issues.redhat.com/browse/ODC-5293

**Analysis / Root cause**: 
Monitoring time options overlap monitoring tab navigation when Quickstart panel is opened

**Solution Description**: 
Fix the layout as per the [UX](https://docs.google.com/document/d/1N3YHCOrN69TR6TjCbsM1bui0cfbZtDsShdDqL_j1YcQ/edit?ts=5ede105d#heading=h.pw0zyzcincru) 
![image](https://user-images.githubusercontent.com/2561818/104884462-6897bb80-598c-11eb-83d5-ab42caba8bce.png)

**Screen shots / Gifs for design review**: 
![Kapture 2021-01-18 at 12 13 38](https://user-images.githubusercontent.com/2561818/104884507-7b11f500-598c-11eb-8d40-e4c53b9b6b0c.gif)

**Browser conformance**: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2021-01-19 18:52 UTC, debsmita1 commented
The alignment here looks a bit odd
![Screenshot from 2021-01-20 00-12-27](https://user-images.githubusercontent.com/22490998/105079453-739a3b00-5ab5-11eb-97ea-512a66b6361e.png)

2021-01-22 13:41 UTC, vikram-raj commented
> The alignment here looks a bit odd
> ![Screenshot from 2021-01-20 00-12-27](https://user-images.githubusercontent.com/22490998/105079453-739a3b00-5ab5-11eb-97ea-512a66b6361e.png)

Added top margin `--pf-global--spacer--sm` to Time Range and Refresh interval.

![image](https://user-images.githubusercontent.com/2561818/105497819-606db200-5ce5-11eb-8fb2-65478ddd60dd.png)

cc: @cshinn

2021-01-22 13:44 UTC, cshinn commented
Looks good with that spacer @vikram-raj!

2021-01-22 14:46 UTC, vikram-raj commented
/kind bug

2021-01-22 16:29 UTC, jerolimov commented
@vikram-raj @cshinn @debsmita1 I think the spacing is still a little bit unbalanced and could be improved.

a) The tabs and the dashboard content uses the same padding on a small and large viewport. But the workload / time uses always the same padding. Can you add the same padding for the small viewport similar to the the other components?

Small viewport:
![Screenshot from 2021-01-22 16-55-38](https://user-images.githubusercontent.com/139310/105513987-4a56f600-5cd3-11eb-9b2b-8761610844a2.png)

Large viewport:
![Screenshot from 2021-01-22 16-56-15](https://user-images.githubusercontent.com/139310/105514007-4fb44080-5cd3-11eb-889a-ca2f96dc844f.png)

b) The vertical spacing above and below the workload / time looks a little bit unhappy, or?

Current screen:
![Screenshot from 2021-01-22 17-00-47](https://user-images.githubusercontent.com/139310/105514521-da953b00-5cd3-11eb-8791-83666a7e15e6.png)

I go to the browser debug tools and removed extra padding below the input fields and for me this looks better. Fyi: removed the `form-group` class which only exists on the time fields.
![Screenshot from 2021-01-22 17-01-18](https://user-images.githubusercontent.com/139310/105514705-1af4b900-5cd4-11eb-89e0-e3931a9af3da.png)

Looks a little bit more like the UX design, or? Wdyt?

2021-01-22 17:28 UTC, jerolimov requested changes
See comment above

2021-01-22 18:23 UTC, debsmita1 commented
> @vikram-raj @cshinn @debsmita1 I think the spacing is still a little bit unbalanced and could be improved.
> 
> a) The tabs and the dashboard content uses the same padding on a small and large viewport. But the workload / time uses always the same padding. Can you add the same padding for the small viewport similar to the the other components?
> 
> Small viewport:
> ![Screenshot from 2021-01-22 16-55-38](https://user-images.githubusercontent.com/139310/105513987-4a56f600-5cd3-11eb-9b2b-8761610844a2.png)
> 
> Large viewport:
> ![Screenshot from 2021-01-22 16-56-15](https://user-images.githubusercontent.com/139310/105514007-4fb44080-5cd3-11eb-889a-ca2f96dc844f.png)
> 
> b) The vertical spacing above and below the workload / time looks a little bit unhappy, or?
> 
> Current screen:
> ![Screenshot from 2021-01-22 17-00-47](https://user-images.githubusercontent.com/139310/105514521-da953b00-5cd3-11eb-8791-83666a7e15e6.png)
> 
> I go to the browser debug tools and removed extra padding below the input fields and for me this looks better. Fyi: removed the `form-group` class which only exists on the time fields.
> ![Screenshot from 2021-01-22 17-01-18](https://user-images.githubusercontent.com/139310/105514705-1af4b900-5cd4-11eb-89e0-e3931a9af3da.png)
> 
> Looks a little bit more like the UX design, or? Wdyt?

I agree

2021-01-22 18:29 UTC, cshinn commented
@jerolimov yep, that makes sense

2021-01-25 05:07 UTC, vikram-raj commented
@jerolimov @cshinn @debsmita1 Updated the spacing. PTAL again.
![image](https://user-images.githubusercontent.com/2561818/105663827-3c82ba00-5ef9-11eb-9ae8-1a00304d7e43.png)
![image](https://user-images.githubusercontent.com/2561818/105663867-4efcf380-5ef9-11eb-8865-7f00ee132ce2.png)

2021-01-25 07:30 UTC, debsmita1 commented
tested this locally
/lgtm

2021-01-26 14:09 UTC, jerolimov approved these changes
Looks good now, thanks

2021-01-26 14:32 UTC, jerolimov commented
/assign @andrewballantyne

2021-01-26 14:44 UTC, andrewballantyne approved these changes
Nits. I feel we can still improve this layout and trim down on our homegrown effort here, but I don't see it's hugely important.

2021-01-26 14:44 UTC, andrewballantyne commented on frontend/packages/dev-console/src/components/monitoring/dashboard/MonitoringDashboard.tsx
> +        <div className="odc-monitoring-dashboard__resource-toolbar">
There is definitely a way to improve this with PF Flex components... ideally we should avoid rolling our own classes and styles.

2021-01-26 17:14 UTC, merged