adding reducer extension types to dynamic-plugin-sdk
openshift/console pull request #7860
Opened 2021-01-18 16:44 UTC by glekner

2021-01-18 16:45 UTC, glekner commented
@vojtechszocs @christianvogt please review

2021-01-18 20:29 UTC, vojtechszocs requested changes

2021-01-18 20:29 UTC, vojtechszocs commented on frontend/packages/console-dynamic-plugin-sdk/src/extensions/reducers.ts
> +    /** The key to represent reducer-managed substate within the Redux state object. */
```suggestion
    /** The key to represent the reducer-managed substate within the Redux state object. */
```

2021-01-18 20:29 UTC, vojtechszocs commented on frontend/packages/console-dynamic-plugin-sdk/src/extensions/reducers.ts
> +    namespace: string;
```suggestion
    scope: string;
```

2021-01-18 20:29 UTC, vojtechszocs commented on frontend/packages/console-dynamic-plugin-sdk/src/extensions/reducers.ts
> +    /** The reducer handler, resolved to a reducer. */
```suggestion
    /** The reducer function, operating on the reducer-managed substate. */
```

2021-01-18 20:29 UTC, vojtechszocs commented on frontend/packages/console-dynamic-plugin-sdk/src/extensions/reducers.ts
> +    handler: EncodedCodeRef;
```suggestion
    reducer: EncodedCodeRef;
```

2021-01-18 20:29 UTC, vojtechszocs commented on frontend/packages/console-dynamic-plugin-sdk/src/extensions/reducers.ts
> +  export type ReduxReducerCodeRef = {
```suggestion

  export type ReduxReducerCodeRefs = {
```

2021-01-18 20:29 UTC, vojtechszocs commented on frontend/packages/console-dynamic-plugin-sdk/src/extensions/reducers.ts
> +    /** The reducer handler, resolved to a reducer. */
```suggestion
```

2021-01-18 20:29 UTC, vojtechszocs commented on frontend/packages/console-dynamic-plugin-sdk/src/extensions/reducers.ts
> +    handler: CodeRef<Reducer>;
```suggestion
    reducer: CodeRef<Reducer>;
```

2021-01-18 20:29 UTC, vojtechszocs commented on frontend/packages/console-dynamic-plugin-sdk/src/extensions/reducers.ts
> +  type: 'console.reducer';
```suggestion
  type: 'console.redux-reducer';
```

2021-01-18 20:29 UTC, vojtechszocs commented on frontend/packages/console-dynamic-plugin-sdk/src/extensions/reducers.ts
> +  e.type === 'console.reducer';
```suggestion
  e.type === 'console.redux-reducer';
```

2021-01-18 20:29 UTC, vojtechszocs commented on frontend/packages/console-dynamic-plugin-sdk/src/schema/console-extensions.ts
> +import { ReduxReducer } from '../extensions/reducers';
```suggestion
import { ReduxReducer } from '../extensions/redux';
```

2021-01-18 20:32 UTC, vojtechszocs commented
Looks great, just a couple of comments.

If an extension supports code refs, there should be two extension properties types:
- `<ExtName>` e.g. `ReduxReducer` - contains _all the properties_, with code refs represented as `EncodedCodeRef` (object literals, suitable for JSON usage)
- `<ExtName>CodeRefs` e.g. `ReduxReducerCodeRefs` - contains _only code ref properties_, typed as `CodeRef<T>` where `T` is the actual object being referenced

For such extensions, there should also be two extension types:
- `<ExtName>` e.g. `ReduxReducer`
- `Resolved<ExtName>` e.g. `ResolvedReduxReducer` - using `UpdateExtensionProperties` helper to replace all encoded code refs with their actual runtime types

When documenting such extension's properties, just document the base type. The `<ExtName>CodeRefs` type is a subset of the base type, so no need to document that.

Also, type guards (`is<ExtName>` e.g. `isReduxReducer`) for such extensions should work with the _resolved_ type, since we assume that code refs will be resolved _before_ the extension instance is interpreted (preferably via `useResolvedExtensions` hook).

2021-01-29 17:15 UTC, spadgett commented
/override ci/prow/ceph-storage-plugin

The ceph-storage-plugin job should only have run on PRs with changes to `frontend/packages/ceph-storage-plugin`. It failed due to an unrelated CI config change. Overriding status on this PR.

2021-01-31 18:34 UTC, glekner commented
can you lgtm @vojtechszocs

2021-02-03 17:44 UTC, vojtechszocs commented
/hold
/lgtm

2021-02-09 17:31 UTC, vojtechszocs commented
/hold cancel

2021-02-09 23:21 UTC, merged