support rendering markdown inline instead of iframe
openshift/console pull request #7872
Opened 2021-01-19 20:22 UTC by christianvogt

**Fixes**: 
https://issues.redhat.com/browse/ODC-5338

**Analysis / Root cause**: 
Markdown renders inside an iframe and when the view resizes, the markdown view doesn't get resized with it.
Another side effect of the iframe is the slow loading of the text areas in the quick start views.

**Solution Description**: 
The approach I took is to render the markdown inline without the iframe. In doing so we no longer get scroll bars around the markdown.

**Screen shots / Gifs for design review**: 
The UI looks the same. No more scroll bars around the individual markdown text components.

![quick-start-md-iframe](https://user-images.githubusercontent.com/14068621/105088577-14fb9f80-5a6a-11eb-9ddc-66c88b62134c.gif)

@openshift/team-devconsole-ux

**Unit test coverage report**: 
Added new unit tests for the markdown view to test rendering inside and outside of iframes, as well as rendering markdown extensions.

**Browser conformance**: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [x] Edge

2021-01-19 20:38 UTC, christianvogt commented
/bugzilla refresh

2021-01-21 14:21 UTC, christianvogt commented
/bugzilla refresh

2021-01-21 15:30 UTC, spadgett commented
I'm a little hesitant about this since the markdown is no longer sandboxed, which is the reason we used an `iframe`. I see a call to `sanitize-html` in `markdownConvert`, but are we absolutely sure there is no way to run JavaScript? (For example, through an event listener on one of the elements in the allowlist?)

2021-01-21 15:45 UTC, rohitkrai03 commented
/assign

2021-01-21 16:30 UTC, christianvogt commented
@spadgett it's a valid concern.
I've looked over the docs and sanitize-html does address this but like anything, if there's a bug or exploit found it does open up for attacks. I did some testing and between the markdown -> html conversion plus the sanitizing, it didn't allow me to execute javascript. However my tests were simple. I'm going to additionally update the sanitize-html to the latest version.

2021-01-21 17:19 UTC, christianvogt commented
@spadgett updated the sanitize-html library

Tested several areas that have markdown and everything seems to continue to render fine.

Since the quick starts render several markdown areas at once, this definitely is a better experience.

2021-01-21 18:13 UTC, christianvogt commented
/bugzilla refresh

2021-01-22 11:00 UTC, rohitkrai03 approved these changes
/lgtm

Code looks good to me. Tested it locally in various scenarios. Works fine.

2021-01-22 17:33 UTC, christianvogt commented
@rohitkrai03 rebased and fixed merge conflict

2021-01-22 18:56 UTC, rohitkrai03 commented
Seems like some tests are failing.

2021-01-25 16:17 UTC, christianvogt commented
I'll regenerate the `yarn.lock` file...

2021-01-26 12:53 UTC, andrewballantyne commented
@christianvogt Looks as if you still have a yarn issue. What's your version of yarn? Looks as if the CI is using `yarn v1.22.10`

2021-01-26 13:15 UTC, andrewballantyne requested changes
LGTM, I was not able to inject anything dangerous. Script tags are removed as non approved tags, anchor hrefs that have `javascript:` are removed as they don't meet `http:` / `https:` / `mailto:`. OnClicks are not approved attributes on anything so they are removed. 

Looks pretty sane on the surface. Not sure what one could do to inject runnable JavaScript into it. 

Once the yarn stuff is fixed, this is a 👍  from me. 

@spadgett Do you have any objections to this merging?
/hold

Waiting for Sam to finish his review.

2021-01-26 13:15 UTC, andrewballantyne commented
/hold

2021-01-26 14:40 UTC, spadgett commented
No objections, thanks guys.

/hold cancel

2021-01-26 15:10 UTC, andrewballantyne commented
pre-emptive LGTM... trust that Christian won't make me come back and see another `yarn.lock` issue 😜 

/lgtm

2021-01-26 15:58 UTC, andrewballantyne commented
/retest

2021-01-26 16:05 UTC, christianvogt commented
yay. yarn file fixed. Now to get through the e2e tests.

2021-01-26 19:32 UTC, merged