[WIP] updated knative-automation framework setup
openshift/console pull request #7875
Opened 2021-01-20 07:22 UTC by makambalaji

This PR is mainly created to setup the framework in knaitve-plugin folder
Jira Id: https://issues.redhat.com/browse/ODC-5076

2021-02-09 12:07 UTC, gajanan-more requested changes
There are few file names with underscore and epic number. Can you please update them as well?

2021-02-09 12:07 UTC, gajanan-more commented on frontend/packages/knative-plugin/integration-tests/features/Knative/event-sources-sink-to-URI.feature
> +        And user is at developer perspective
```suggestion
        And user is at Developer perspective
```

2021-02-09 13:30 UTC, makambalaji commented on frontend/packages/dev-console/integration-tests/features/getting-started/sample-card_Add_page.feature
>      And open project namespace
updated the statement, but this pr is not meant for reviewing this feature files

2021-02-09 13:32 UTC, makambalaji commented on frontend/packages/dev-console/integration-tests/features/helm/helm_feature_flag_ODC-5024.feature
updated

2021-02-10 09:48 UTC, gajanan-more requested changes

2021-02-10 09:48 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/getting-started/getting-started -to-dev-perspective.feature
> +Feature: Login to developer perspective
Do we still require this scenario? 
Also there is an extra space in the file name.

2021-02-10 09:48 UTC, gajanan-more commented on frontend/packages/dev-console/integration-tests/features/getting-started/getting-started -to-dev-perspective.feature
> +        Scenario: Developer perspective display on login to open shift application using developer credentials
```suggestion
        Scenario: Developer perspective display on login to OpenShift application using developer credentials
```

2021-02-10 10:33 UTC, gajanan-more approved these changes
![Screenshot from 2021-02-10 15-36-24](https://user-images.githubusercontent.com/17041173/107498150-67d3fd00-6bb9-11eb-85d6-4dd3dacc2b0f.png)

It's working as expected. 

/lgtm

2021-02-10 14:46 UTC, merged