Bug 1920367: When creating localvolumeset instance from the web console, the title for setting volumeMode is `Disk Mode`
openshift/console pull request #7954
Opened 2021-01-27 19:41 UTC by rexagod

Rename 'Disk Mode' to 'Volume Mode'.

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1920367

2021-01-27 19:42 UTC, rexagod commented
/bugzilla refresh

2021-01-27 21:04 UTC, rexagod commented
/retest

2021-01-29 17:06 UTC, spadgett commented
/override ci/prow/ceph-storage-plugin

The ceph-storage-plugin job should only have run on PRs with changes to `frontend/packages/ceph-storage-plugin`. It failed due to an unrelated CI config change. Overriding status on this PR.

2021-02-05 03:51 UTC, afreen23 requested changes

2021-02-05 03:51 UTC, afreen23 commented on frontend/packages/local-storage-operator-plugin/locales/ja/lso-plugin.json
> +  "Volume Mode": "ボリュームモード",
We dont need to change in language-specific localization file

2021-02-05 03:51 UTC, afreen23 commented on frontend/packages/local-storage-operator-plugin/locales/zh/lso-plugin.json
> +  "Volume Mode": "音量模式",
```suggestion
"Disk Mode": "音量模式",
```


We dont need to change in language-specific localization file

2021-02-05 07:26 UTC, afreen23 commented
Please run `yarn i18n` inside your frontend folder to update the keys.

2021-02-05 08:38 UTC, afreen23 commented
/lgtm

2021-02-05 19:54 UTC, merged