Bug 1899587: Fix RGW Total Used Query
openshift/console pull request #8050
Opened 2021-02-04 07:42 UTC by bipuladh

Stop subtracting NooBaa usage from RGW usage

2021-02-04 07:43 UTC, bipuladh commented
/bugzilla refresh

2021-02-04 08:43 UTC, kyoto commented
FYI @openshift/openshift-team-monitoring

2021-02-04 09:07 UTC, simonpasquier reviewed
/lgtm

2021-02-04 09:09 UTC, bipuladh commented
/hold
need ack from Storage team before we can get this merged.

2021-02-17 04:59 UTC, bipuladh commented
/hold cancel

2021-02-17 05:13 UTC, anmolsachan requested changes

2021-02-17 05:13 UTC, anmolsachan commented on frontend/packages/noobaa-storage-plugin/src/queries.ts
> +    'sum(NooBaa_providers_physical_size{type!="S3_COMPATIBLE"})',
```suggestion
    'sum(NooBaa_providers_physical_size)',
```

2021-02-17 05:13 UTC, anmolsachan commented on frontend/packages/noobaa-storage-plugin/src/queries.ts
> +      'sum(ceph_pool_metadata{name=~"<%= name %>rgw.*"} *on (job, namesapce, pool_id) group_right(name) ceph_pool_stored_raw) - max(NooBaa_providers_physical_size{type="S3_COMPATIBLE"}) + sum(NooBaa_
```suggestion
      'sum(ceph_pool_metadata{name=~"<%= name %>rgw.*"} *on (job, namesapce, pool_id) group_right(name) ceph_pool_stored_raw) + sum(NooBaa_providers_physical_size{type!="S3_COMPATIBLE"})',
```

2021-02-19 11:51 UTC, anmolsachan requested changes

2021-02-19 11:51 UTC, anmolsachan commented on frontend/packages/noobaa-storage-plugin/src/queries.ts
> +      'sum(ceph_pool_metadata{name=~"<%= name %>rgw.*"} *on (job, namesapce, pool_id) group_right(name) ceph_pool_stored_raw) - max(NooBaa_providers_physical_size{type="S3_COMPATIBLE"})',
```suggestion
      'sum(ceph_pool_metadata{name=~"<%= name %>rgw.buckets.data"} *on (job, namesapce, pool_id) group_right(name) ceph_pool_stored) - max(NooBaa_providers_physical_size{type="S3_COMPATIBLE"} or vector(0))',
```

2021-02-19 11:51 UTC, anmolsachan commented on frontend/packages/noobaa-storage-plugin/src/queries.ts
> +      'sum(ceph_pool_metadata{name=~"<%= name %>rgw.*"} *on (job, namesapce, pool_id) group_right(name) ceph_pool_stored_raw) + sum(NooBaa_providers_physical_size{type!="S3_COMPATIBLE"})',
```suggestion
      'sum(ceph_pool_metadata{name=~"<%= name %>rgw.buckets.data"} *on (job, namesapce, pool_id) group_right(name) ceph_pool_stored) + max(sum(NooBaa_providers_physical_size{type!="S3_COMPATIBLE"}) or vector(0))',
```

2021-02-22 05:46 UTC, anmolsachan commented
/lgtm

2021-02-22 08:30 UTC, merged

2021-05-25 12:10 UTC, bipuladh commented
/cherrypick release-4.7