Bug 1891766: Disable submit button for incorrect validations (LSO/OCS local volume set)
openshift/console pull request #8092
Opened 2021-02-08 12:59 UTC by SanjalKatiyar

Before:
"Next" button is enabled even if user has entered a wrong disk size/limit value.
![Screenshot from 2021-02-08 18-23-17](https://user-images.githubusercontent.com/39404641/107222724-4b11bb00-6a3b-11eb-951b-e602aa8b4ba3.png)

After:
"Next" button will be disabled if user enters a incorrect disk size/limit value.
![Screenshot from 2021-02-08 18-19-18](https://user-images.githubusercontent.com/39404641/107222743-506f0580-6a3b-11eb-8620-3d706a09a8b9.png)

2021-02-08 16:06 UTC, afreen23 commented
/ok-to-test
/assign @afreen23

2021-02-09 05:06 UTC, afreen23 requested changes
You don't need to create another state.
We have the disablement control here : https://github.com/openshift/console/blob/db9138bca35526459516f36c7300a450ed3a1aaf/frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices/create-sc/create-sc.tsx#L222

We might want to add more here.

2021-02-12 10:12 UTC, afreen23 approved these changes
looks good just nits

2021-02-12 14:08 UTC, SanjalKatiyar commented
> looks good just nits

thanks for the review... I have made the changes...

2021-02-12 14:32 UTC, afreen23 commented
/lgtm

2021-02-12 15:47 UTC, merged