[WIP] add hide/reveal button for kms token
openshift/console pull request #8196
Opened 2021-02-19 14:56 UTC by SanjalKatiyar

2021-03-01 15:58 UTC, afreen23 requested changes

2021-03-01 15:58 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/components/kms-config/kms-config.tsx
> +          </div>
Instead of wrapping in div , you should consider `InputGroup` that shows a semantic connection of text input and button

2021-03-01 15:58 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/components/kms-config/kms-config.tsx
> +  const [reveal, setReveal] = React.useState(false);
lets be specific.
```suggestion
  const [revealToken, setRevealToken] = React.useState(false);
```

2021-03-01 17:15 UTC, afreen23 commented
/ok-to-test

2021-03-04 05:54 UTC, bipuladh commented
/retest

2021-03-04 13:25 UTC, afreen23 commented
/test ceph-storage-plugin
/test e2e-gcp-console
/lgtm

2021-03-05 06:33 UTC, bipuladh commented
/hold
Tests are failing

2021-03-05 18:13 UTC, spadgett commented
/hold cancel

2021-03-06 08:28 UTC, merged

2021-04-12 11:52 UTC, bipuladh commented
/cherrypick release-4.7