[WIP] Install workflows - textual updates based on doc review
openshift/console pull request #8197
Opened 2021-02-19 15:01 UTC by SanjalKatiyar

URL: https://issues.redhat.com/browse/RHSTOR-1670

2021-02-25 09:08 UTC, cloudbehl commented
/ok-to-test

2021-02-25 09:09 UTC, cloudbehl commented
please add a screenshot of before and after so that the UX team can review it.

2021-02-25 09:10 UTC, SanjalKatiyar commented
> please add a screenshot of before and after so that the UX team can review it.

2021-02-25 09:12 UTC, SanjalKatiyar commented
> please add a screenshot of before and after so that the UX team can review it.

okay... got it...

2021-04-12 08:55 UTC, SanjalKatiyar commented
/test ceph-storage-plugin

2021-05-31 06:24 UTC, bipuladh requested changes

2021-05-31 06:24 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/install-wizard.tsx
> +          {t('ceph-storage-plugin~Create storage class')}{' '}
```suggestion
          {t('ceph-storage-plugin~Create StorageClass')}{' '}
```

2021-05-31 06:24 UTC, bipuladh commented on frontend/packages/local-storage-operator-plugin/src/components/local-volume-set/body.tsx
> +        {t('lso-plugin~Filter Disks By')}
```suggestion
        {t('lso-plugin~Filter Disks by')}
```

2021-06-07 08:43 UTC, yuvalgalanti commented
It looks good, I wouldn't change the way we writing "Storage Class" for now. lets do a revisit for all textual alignments in a new PR

2021-06-08 05:21 UTC, olivelakra commented
/label docs-approved

2021-06-08 05:41 UTC, SanjalKatiyar commented
> It looks good, I wouldn't change the way we writing "Storage Class" for now. lets do a revisit for all textual alignments in a new PR

@yuvalgalanti @bipuladh ... FYI, several string related updates (for example: "storage class" --> "StorageClass") were handled in this: https://github.com/openshift/console/pull/9017 (already merged)...

2021-06-11 04:18 UTC, bipuladh commented
/lgtm

2021-06-11 06:39 UTC, merged