Fix builder image version dropdown value in pipeline edit flow
openshift/console pull request #8215
Opened 2021-02-22 17:20 UTC by karthikjeeyar

**Fixes**: 

https://issues.redhat.com/browse/ODC-5536

**Analysis / Root cause**: 

In pipeline add/edit git flow, builder image version was not tracked in the newly created pipeline, hence the previously selected version was getting lost while going through the edit flow.

**Solution Description**: 

Added a label `pipeline.openshift.io/runtime-version` to get and set the builder image version and used it in the edit flow.

**Screen shots / Gifs for design review**: 

![version-edit-flow](https://user-images.githubusercontent.com/9964343/108744102-8d6ce900-755f-11eb-8fdc-fe48759b25be.gif)

**Unit test coverage report**: 

  ```
updatePipelineForImportFlow
    ✓ should dissociate pipeline if template is not available (1ms)
    ✓ should update params if template is of same type
    ✓ should update VERSION params if image tag is changed (1ms)
    ✓ should update pipeline if template is of different type (1ms)
  isDockerPipeline
    ✓ should return false for a non docker based pipelines
    ✓ should return true for a docker based pipeline template
  pipelineRuntimOrVersionChanged
    ✓ should return false if runtime and version is same for two given pipelines
    ✓ should return false if runtime or version is different for two given pipelines
```
**Test setup:**

1. In git add flow, choose a builder image and version
2. check `Add pipeline` option
3. create the resource and choose edit option from topology page.
4. edit form should have pre-selected the correct builder image version in the dropdown 

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

2021-02-23 04:53 UTC, karthikjeeyar commented
/kind bug

2021-02-23 13:18 UTC, debsmita1 requested changes

2021-02-23 16:57 UTC, karthikjeeyar commented on frontend/packages/pipelines-plugin/src/components/import/pipeline/pipeline-template-utils.ts
> +      ...(template?.metadata?.labels?.[PIPELINE_STRATEGY_LABEL] !== 'docker' && {
I missed it there. Updated :+1:

2021-02-24 05:08 UTC, debsmita1 requested changes

2021-02-24 05:08 UTC, debsmita1 commented on frontend/packages/pipelines-plugin/src/components/import/pipeline/pipeline-template-utils.ts
> +export const pipelineRuntimOrVersionChanged = (
```suggestion
export const pipelineRuntimeOrVersionChanged = (
```

2021-02-24 05:08 UTC, debsmita1 commented
@karthikjeeyar 5 tests are failing

2021-02-24 05:23 UTC, karthikjeeyar commented
@debsmita1 fixed it

2021-02-24 06:41 UTC, debsmita1 commented
Try:
Import from catalog (DONOT check the pipeline) -> Edit the app -> change the BI version & check the pipeline & submit the form
 -> Edit the form --- I do not see the updated version selected

2021-02-24 06:59 UTC, karthikjeeyar commented
> Try:
> Import from catalog (DONOT check the pipeline) -> Edit the app -> change the BI version & check the pipeline & submit the form
> -> Edit the form --- I do not see the updated version selected

@debsmita1  Ah I see what is happening, first time creation (without Pipeline) creates Buildconfig, then while editing the application if you check pipeline even then it takes buildconfig's selected version over the pipelines. The precedence should be Pipelines -> Buildconfig -> default fallback.

2021-02-24 11:33 UTC, karthikjeeyar commented
/retest

2021-02-25 07:33 UTC, karthikjeeyar commented
> Seems to work fine, but I noticed something in the edit flow as well, is this desired?

Not sure what you are referring here, I tried using a `php` image it detected with right builder image and version.

2021-02-25 08:45 UTC, abhinandan13jan commented
> > Seems to work fine, but I noticed something in the edit flow as well, is this desired?
> 
> Not sure what you are referring here, I tried using a `php` image it detected with right builder image and version.

I understand this is separate from the Bug, but the above warning `unable to detect the builder image` in Edit flow, is it desired?

2021-02-25 09:49 UTC, abhinandan13jan commented
PR is fine on its own. Checked locally.
/LGTM
@karthikjeeyar could you please log a tracker for the warning issue we see.

2021-02-25 09:50 UTC, karthikjeeyar commented
> > > Seems to work fine, but I noticed something in the edit flow as well, is this desired?
> > 
> > 
> > Not sure what you are referring here, I tried using a `php` image it detected with right builder image and version.
> 
> I understand this is separate from the Bug, but the above warning `unable to detect the builder image` in Edit flow, is it desired?

I can reproduce this using dotnet image `https://github.com/redhat-developer/s2i-dotnetcore-ex.git`, this one is NOT desired it shouldn't show warning if the builder image is selected in edit flow.

2021-02-25 09:57 UTC, abhinandan13jan commented
https://issues.redhat.com/browse/ODC-5568 cc: @karthikjeeyar

2021-02-25 11:21 UTC, jerolimov approved these changes
Tested it locally. Works fine. :+1: 

/approve

2021-02-25 11:21 UTC, jerolimov commented
/retest

2021-02-25 15:24 UTC, merged

2021-03-03 12:19 UTC, karthikjeeyar commented
cherry-pick release-4.7

2021-03-03 13:18 UTC, karthikjeeyar commented
/cherry-pick release-4.7