Bug 1928937: Bump lodash-es to latest v4.17.21, to remove security vulnerabilities
openshift/console pull request #8247
Opened 2021-02-25 08:49 UTC by jhadvig

Fixes both:
- https://bugzilla.redhat.com/show_bug.cgi?id=1931279
- https://bugzilla.redhat.com/show_bug.cgi?id=1931272

since both of these issues fixes include bumping `lodash-es` to version `4.17.21`

@spadgett PTAL

2021-02-25 08:50 UTC, jhadvig commented
/bugzilla refresh

2021-02-25 19:23 UTC, spadgett requested changes

2021-02-25 19:23 UTC, spadgett commented on frontend/package.json
> +    "lodash-es": "4.17.21",
We should use 4.7.21 or newer

```suggestion
    "lodash-es": "^4.17.21",
```

2021-03-01 10:34 UTC, jhadvig commented
@spadgett comment addressed

2021-03-01 17:28 UTC, spadgett reviewed
It looks like we have an earlier version of lodash coming from Victory charts via Patternfly as well that we might need to override. Might be easiest to add it to the `resolutions` in package.json.

2021-03-02 07:56 UTC, jhadvig commented
@spadgett done :)

2021-03-02 09:28 UTC, jhadvig commented
/test e2e-gcp-console

2021-03-08 08:47 UTC, jhadvig commented
/test e2e-gcp-console

2021-03-18 16:22 UTC, spadgett approved these changes
/lgtm

2021-03-19 09:17 UTC, jhadvig commented
/test e2e-gcp-console

2021-03-21 10:43 UTC, merged