Bug 1931543: Watch noProvSC and invoke hasNoProvSC accordingly
openshift/console pull request #8259
Opened 2021-03-01 10:12 UTC by rexagod

Mentioning here that I was able to replicate this issue only a couple
of times (as is mentioned in the BZ issue body), so this patch fix
addresses some parts of the codebase that I inferred to be the cause
of this issue from that observation.

It'd be nice if someone (who can replicate the issue successfully) can
apply this patch and provide their feedback on it.

2021-03-01 10:13 UTC, rexagod commented
Pasting this in for reference: https://bugzilla.redhat.com/show_bug.cgi?id=1931543

2021-03-01 10:18 UTC, rexagod commented
To add to the aforementioned information, I can confirm that this patch basically checks when the provSC gets filtered in the storage classes dropdown, for the noProv storage class, and invokes the noProv [detection and updation process](https://github.com/rexagod/console/blob/f12891f445c73f0041c397813e9dedbeb36b8fe8/frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/install.tsx#L62).

2021-03-01 11:12 UTC, rexagod commented
PS. To apply this, do `curl https://github.com/openshift/console/commit/f12891f445c73f0041c397813e9dedbeb36b8fe8.patch | git apply`.

2021-03-01 11:40 UTC, afreen23 requested changes
> Mentioning here that I was able to replicate this issue only a couple
> of times (as is mentioned in the BZ issue body), so this patch fix
> addresses some parts of the codebase that I inferred to be the cause
> of this issue from that observation.
> 
> It'd be nice if someone (who can replicate the issue successfully) can
> apply this patch and provide their feedback on it.
> 
> To apply this, do `curl https://github.com/openshift/console/commit/f12891f445c73f0041c397813e9dedbeb36b8fe8.patch | git apply`.

The issue is due to the fact that when we create storage class, we dont fetch results again to update that.
On a new mount this is not the case and storage class is found and hence the correct display.
We need to fix this issue by fetching storage class in wizard and looking if a no  provsc is there, that means moving no Prov sc to wizard component.

2021-03-08 16:17 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/src/components/ocs-install/attached-devices-mode/create-sc/wizard-pages/create-local-volume-set.tsx
> +                }}
move it out toa function maybe call it `onCreate`

2021-03-10 17:33 UTC, rexagod commented
Here a visual of the changes.

https://user-images.githubusercontent.com/33557095/110671526-9d89f700-81f4-11eb-9b66-c78dba97f4a2.mp4

2021-03-24 15:38 UTC, rexagod commented
/bugzilla refresh

2021-03-24 15:43 UTC, afreen23 requested changes
Run `yarn i18n` and update texts

2021-03-24 15:43 UTC, rexagod commented
Updating the i18n files.

2021-03-24 15:52 UTC, rexagod commented
Found a bug, updating this ASAP.

2021-03-24 16:05 UTC, rexagod commented
I've removed hasNoProvSC and setHasNoProvSC entirely from the codebase since we aren't using those anywhere.

2021-03-24 16:06 UTC, rexagod commented
Fixing conflicts.

2021-03-24 17:10 UTC, afreen23 approved these changes
/lgtm

2021-03-25 02:17 UTC, merged