Bug 1928319: Stretch cluster installed on 6 storage node cluster with 2 LSO devices on each storage node fails to utilize 8 LSO devices
openshift/console pull request #8326
Opened 2021-03-08 17:00 UTC by SanjalKatiyar

**Earlier:**
Irrespective of the number of available-storage-devices (attached to the nodes), storage cluster after the creation was only utilising: 
4 devices (in case of arbiter), 
3 devices (in case of flexible scaling) and 
3 devices (in case of normal deployment).

**After:**
For all attached-device mode deployments, created storage cluster will utilise all possible available-storage-devices.
For example: 
storage devices available = 10; then, storage cluster after the creation will utilise: 
8 devices (in case of arbiter), 
10 devices (in case of flexible scaling) and 
9 devices (in case of normal deployment).

The same functionality/behaviour will be used for add capacity as well.

2021-03-16 08:23 UTC, cloudbehl commented
/bugzilla refresh
/ok-to-test

2021-03-16 11:09 UTC, SanjalKatiyar commented on frontend/packages/ceph-storage-plugin/src/components/modals/add-capacity-modal/add-capacity-modal.tsx
> +  if (!pvLoadError && pvData.length && pvLoaded) {
I am only passing `availablePvsCount` to the `getCount` function. This function will return same value (i.e., `1`) for either `availablePvsCount=0` or `availablePvsCount=undefined`. This is why I did not change this condition earlier.

Should I change the condition and make it from `if (!pvLoadError && pvData.length && pvLoaded)` to `if (!pvLoadError && pvLoaded)` ??

2021-04-05 11:44 UTC, cloudbehl commented
@afreen23 can you do a round of testing for this?

2021-04-09 05:28 UTC, afreen23 requested changes

2021-04-09 05:28 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/components/ocs-install/ocs-request-data.ts
> +  deviceSetCount = getCount(availablePvsCount, deviceSetReplica);
```suggestion
 const deviceSetCount = getCount(availablePvsCount, deviceSetReplica);
```

2021-04-14 06:14 UTC, afreen23 approved these changes
LGTM

2021-04-14 08:17 UTC, SanjalKatiyar commented on frontend/packages/ceph-storage-plugin/src/components/ocs-install/ocs-request-data.ts
> +  const deviceSetCount = getDeviceSetCount(availablePvsCount, deviceSetReplica);
I have made some changes (L143-L149)... PTAL...

2021-04-14 09:27 UTC, SanjalKatiyar commented
/test ceph-storage-plugin

2021-04-14 10:16 UTC, SanjalKatiyar commented
/test ceph-storage-plugin

2021-04-14 13:51 UTC, SanjalKatiyar commented
/test ceph-storage-plugin

2021-04-23 05:29 UTC, afreen23 approved these changes
/lgtm

2021-04-23 09:06 UTC, merged