Monitoring dashboards: Support grouping of panels into rows
openshift/console pull request #8364
Opened 2021-03-11 03:57 UTC by kyoto

Group panels according to the rows specified in the dashboard
definition. Also allow expanding / collapsing of rows and support
defaulting to collapsed.

2021-03-11 20:00 UTC, TheRealJon requested changes
Looks like this might not be working as expected. I pulled your branch and took a look at the 
'Kubernetes / Compute Resources / Cluster' dashboard. Looks like all of the rows titled "Network" are showing up in individual collapsible sections instead being collected into one. I assume that the intention would be for panels with the same title to be aggregated?

![image](https://user-images.githubusercontent.com/22625502/110846042-509c3400-8279-11eb-87ab-5615cc1085e5.png)

Also, there is an issue with the key prop being passed  to each row:

```
react_devtools_backend.js:2430 Warning: Encountered two children with the same key, `35`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in div (created by PanelsRow)
    in div (created by PanelsRow)
    in PanelsRow (created by Board)
    in Board (created by MonitoringDashboardsPage_)
    in div (created by Dashboard)
    in Dashboard (created by MonitoringDashboardsPage_)
    in MonitoringDashboardsPage_ (created by ConnectFunction)
    in ConnectFunction
    in ErrorBoundary
    in Unknown (created by Context.Consumer)
    in Route (created by MonitoringUI)
    in Switch (created by MonitoringUI)
    in MonitoringUI (created by AsyncComponent)
    ...
```

2021-03-16 07:50 UTC, kyoto commented on frontend/public/components/monitoring/dashboards/index.tsx
> +  }
Yes, I think this is a little better using `reduce` 👍

2021-03-16 07:54 UTC, kyoto commented
Thanks @TheRealJon

I changed the `key` prop to use the row's panel `id`s, which should ensure uniqueness.

The repeating "Network" groups is actually correct behavior because that is what the dashboard definition says. (Grafana renders it in the same way.)

2021-03-16 18:01 UTC, TheRealJon approved these changes
/lgtm

2021-03-17 02:53 UTC, kyoto commented
/retest

2021-03-17 04:54 UTC, merged