Bug 1940905: [release-4.6] Remove master as default branch and use only when ref is given
openshift/console pull request #8424
Opened 2021-03-19 15:26 UTC by sahil143

This PR is manual cherry-pick of https://github.com/openshift/console/pull/7730

2021-03-22 14:12 UTC, rottencandy approved these changes
/lgtm

2021-03-22 18:23 UTC, rohitkrai03 requested changes
Apart from moving from using `master` as default branch, this PR also introduces support for contextDir in builder image detection but it only does that for github service and not for gitlab or bitbucket services. That fix was added as part of this https://github.com/openshift/console/pull/7470 originally and its a much bigger change including all the tests and test files. The current PR includes part of the changes from https://github.com/openshift/console/pull/7470 and https://github.com/openshift/console/pull/7730. Not sure if all of the changes should be part of this backport. If it's not critical enough we can just push the changes around `master` -> `main` branch issue and keep the PR footprint smaller. Or we include all the changes from both the PRs and backport the whole fix to 4.6. @christianvogt WDYT?

2021-03-25 14:59 UTC, rohitkrai03 requested changes

2021-03-25 14:59 UTC, rohitkrai03 commented on frontend/packages/git-service/src/types/git.ts
> +  contextDir?: string;
Do we need these type changes?

2021-03-25 14:59 UTC, rohitkrai03 commented on frontend/packages/git-service/src/types/repo.ts
> +  contextDir?: string;
Do we need these type changes?

2021-03-25 15:03 UTC, rottencandy commented on frontend/packages/git-service/src/services/github-service.ts
> +        path: '',
The API doc says: 
>If you omit :path, you will receive the contents of the repository's root directory.

https://octokit.github.io/rest.js/v18#repos-get-contents
Would it be possible to leave out the path?

2021-03-25 15:13 UTC, rottencandy commented on frontend/packages/git-service/src/services/github-service.ts
> +        path: '',
Just checked. There is a lint error on removing, so not possible.

2021-03-26 15:13 UTC, rohitkrai03 approved these changes
/approve

2021-03-31 15:51 UTC, rottencandy approved these changes
/lgtm

2021-03-31 16:09 UTC, rottencandy commented
/lgtm cancel

Go builder image is detected for Java sample repository.
![asdfasdf](https://user-images.githubusercontent.com/20013884/113175915-94c39880-9269-11eb-8041-55fd40cddba0.png)

2021-03-31 16:10 UTC, sahil143 commented
> Go builder image is detected for Java sample repository.

The same issue happens on master as well. May need another issue to track it.

2021-03-31 16:11 UTC, rottencandy commented
/lgtm

2021-04-09 20:37 UTC, merged