converting navigation extensions to dynamic-plugin-sdk
openshift/console pull request #8438
Opened 2021-03-22 16:27 UTC by glekner

2021-03-25 10:32 UTC, glekner commented
@christianvogt @vojtechszocs please review.

I added the field 
```js
    /** if true, adds /k8s/ns/active-namespace to the begining */
    addResourcePrefix?: boolean;
```
to `HrefNavItem`.

Kubevirt VM/VMT `/virtualization` uses it, and this page doesn't handle namespaces like the dev perspective views.
since there is no model for `virtualization` but it is namespaced, we need this field.

2021-03-25 10:45 UTC, rohitkrai03 commented
> @christianvogt @vojtechszocs @rawagner please review.
> 
> I added the field
> 
> ```js
>     /** if true, adds /k8s/ns/active-namespace to the begining */
>     addResourcePrefix?: boolean;
> ```
> 
> to `HrefNavItem`.
> 
> Kubevirt VM/VMT `/virtualization` uses it, and this page doesn't handle namespaces like the dev perspective views.
> since there is no model for `virtualization` but it is namespaced, we need this field.

https://github.com/openshift/console/pull/8249 seems to be solving the same problem.

2021-03-25 11:36 UTC, glekner commented
Took changes from #8249 @jerolimov 
updated to `namespaced` and `isResource` for `HrevNavLink`

2021-04-19 04:28 UTC, christianvogt commented
@glekner please rebase and let's get this reviewed as we held up https://github.com/openshift/console/pull/8249 for this

2021-05-02 12:07 UTC, glekner commented
/retest

2021-05-03 08:42 UTC, glekner commented
/retest

2021-05-03 11:17 UTC, glekner commented
/retest

2021-05-03 11:17 UTC, rawagner requested changes

2021-05-03 11:17 UTC, rawagner commented on frontend/public/components/nav/items.tsx
> +        return <RootNavLink name={name} id={id} key={name} component={Component} {...props} />;
as a `key` we should use `item.properties.uid`.

we actually pass LoadedExtension<GenericNavItem> to `createLink` so `uid` prop is accessible

2021-05-04 07:05 UTC, glekner commented
/retest

2021-05-04 09:42 UTC, rawagner requested changes

2021-05-04 09:42 UTC, rawagner commented on frontend/public/components/nav/section.tsx
> +            const pluginChild = this.mapChild(createLink(item as LoadedExtension<NavItem>));
if you change `sortExtensionItems` to
```js
export const sortExtensionItems = <E extends NavItem>(
  extensionItems: LoadedExtension<E>[],
): LoadedExtension<E>[] => {
...
};
```

you will not have to cast to `LoadedExtension<NavItem>` anymore

2021-05-04 09:42 UTC, rawagner commented on frontend/public/module/k8s/k8s.ts
> -
lets remove this change :)

2021-05-04 09:42 UTC, rawagner commented on frontend/packages/metal3-plugin/src/plugin.tsx
> +// import { formatNamespacedRouteForResource } from '@console/shared/src/utils/namespace';
can be removed

2021-05-04 13:22 UTC, rawagner commented
/lgtm

2021-05-04 13:24 UTC, merged