Implement externalLink option for the org.w3 alm x-descriptor
openshift/console pull request #8546
Opened 2021-04-02 11:04 UTC by dmvolod

It would be prefer to open link configured with following OLM descriptor in new window/tab as users always lives Console application in case of click on the provide link
However, changing default behavior for the standard configuration, i.e. `x-descriptors:urn:alm:descriptor:org.w3:link` could have an impact on other applications and configurations
Implement functionality for support `x-descriptors:urn:alm:descriptor:org.w3:externalLink` option

fixes #8477

2021-04-05 15:41 UTC, spadgett commented
/assign @TheRealJon 
/cc @tlwu2013

2021-05-01 07:19 UTC, dmvolod commented
@TheRealJon could you please to have a look at this PR
Thanks in advance

2021-06-07 16:16 UTC, TheRealJon requested changes
We should reuse our existing ExternalLink component and not remove the url scheme:

https://github.com/openshift/console/blob/67128172502d43de3ece30e7b11818006ec9d752/frontend/public/components/utils/link.tsx#L68

2021-06-07 16:16 UTC, TheRealJon commented on frontend/packages/operator-lifecycle-manager/src/components/descriptors/status/index.tsx
> +        </a>
Reuse existing ExternalLink component. as it has specific styling. Also, don't remove scheme from URL. https://github.com/openshift/console/blob/67128172502d43de3ece30e7b11818006ec9d752/frontend/public/components/utils/link.tsx#L68

```suggestion
        <ExternalLink href={value}>
          {value}
        </a>
```

2021-06-07 16:16 UTC, TheRealJon commented on frontend/packages/operator-lifecycle-manager/src/components/descriptors/status/index.tsx
> +const ExternalLink: React.FC<StatusCapabilityProps> = ({
You'll either need to rename this or the imported ExternalLink component

2021-06-07 16:16 UTC, TheRealJon commented on frontend/packages/operator-lifecycle-manager/src/components/descriptors/status/index.spec.tsx
> +    expect(wrapper.find('dd').text()).toEqual('example.com');
You'll need to update this to look for the full URL with scheme once you've made the other updates I suggested.

2021-06-07 16:16 UTC, TheRealJon commented on frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md
> +</table>
We'll need to update these with new screenshots after the other suggested updates. ExternalLinks are styled differently.

2021-06-07 16:18 UTC, TheRealJon commented
/ok-to-test

2021-07-07 19:36 UTC, TheRealJon commented
@dmvolod Looks like there is a merge conflict on this. Could you rebase on master and force push?

2021-12-11 04:10 UTC, closed without merging

2023-03-08 17:21 UTC, kberkos-public commented
Hi, has this feature been implemented? It is an issue that is causing some headache for us also.