Adds description in bucket class dropdown for OBC page
openshift/console pull request #8589
Opened 2021-04-08 06:55 UTC by vbnrh

Design: https://marvelapp.com/prototype/fa616je/screen/74583172

![Screenshot from 2021-04-08 12-09-01](https://user-images.githubusercontent.com/57935785/113981540-6a736b80-9865-11eb-8cad-6466289f59e3.png)

2021-04-08 07:51 UTC, afreen23 requested changes

2021-04-08 07:51 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/components/object-bucket-claim-page/create-obc.tsx
> +  };
```suggestion
onst transformLabel = (resource: K8sResourceKind) => (
      <span className="co-resource-item__resource-name">
        {getName(resource)}
        <div className="text-muted small">{getBucketClassDescription(resource)}</div>
      </span>
    );
```

2021-04-08 07:51 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/components/object-bucket-claim-page/create-obc.tsx
> +  };
externalize the strings

2021-04-08 08:21 UTC, vbnrh commented on frontend/packages/ceph-storage-plugin/src/components/object-bucket-claim-page/create-obc.tsx
> +  };
done

2021-04-08 08:21 UTC, vbnrh commented on frontend/packages/ceph-storage-plugin/src/components/object-bucket-claim-page/create-obc.tsx
> +  };
done

2021-04-08 08:23 UTC, afreen23 approved these changes

2021-04-09 05:37 UTC, afreen23 commented
/lgtm

2021-04-09 07:09 UTC, merged