build phases i18n miss
openshift/console pull request #8659
Opened 2021-04-14 17:59 UTC by debsmita1

**Fixes:**
https://issues.redhat.com/browse/ODC-5765

**Solution description:**
Add i18n support to  filter dropdown items present in the builds list page

**Screenshot:**
![build-i18n](https://user-images.githubusercontent.com/22490998/114756151-117d6900-9d78-11eb-951e-d67a3a8287e1.png)

2021-04-14 17:59 UTC, debsmita1 commented
/kind bug

2021-04-16 16:59 UTC, andrewballantyne requested changes
I'm not entirely sure we wanted to translate Build Phases.

/cc @rebeccaalpert could you help out here?

2021-04-16 16:59 UTC, andrewballantyne commented on frontend/public/components/build-config.tsx
>  ];
Need to move this into `BuildConfigsPage` -- don't want to be doing `i18n.t` in the root of a file. If we do that, the i18n logic fires once at the first import and gets cached. The user changing their language would then see the old language here as it was cached.

2021-04-16 16:59 UTC, andrewballantyne commented on frontend/public/components/build.tsx
> +];
Same issue here. Please move into `BuildsPage`

2021-04-19 05:24 UTC, debsmita1 commented
/cc @rebeccaalpert

2021-04-19 15:20 UTC, rebeccaalpert commented
I'm not sure about the Build phase; Sam would know. I tagged him on Slack here: https://coreos.slack.com/archives/C0176H51F8V/p1618845621055200.

2021-04-19 15:21 UTC, rebeccaalpert approved these changes
Looks good to me. Just need to hear back from Sam about the Build phase question.

2021-04-19 15:31 UTC, spadgett commented
Hi, @debsmita1. Typically we don't attempt to translate data coming from resources like build phases. I don't think we translate pod phases today as an example. Even if build phases are well defined, it doesn't seem practical to go through and translate all known values for all resources. I also wouldn't translate the dropdown if values in the table are not translated (as in your screenshot). I'd leave the build filter as-is.

2021-04-19 18:26 UTC, andrewballantyne approved these changes

2021-04-19 18:30 UTC, andrewballantyne commented
/lgtm

You made the change Sam wanted and Rebecca agreed with the rest of it. Adding the other label.

2021-04-20 07:56 UTC, debsmita1 commented
/test e2e-gcp-console

2021-04-20 22:55 UTC, merged