Fix noobaa-namespace-store and noobaa-backing-store dropdown
openshift/console pull request #8675
Opened 2021-04-15 16:24 UTC by SanjalKatiyar

URL: https://issues.redhat.com/browse/RHSTOR-1792

**Earlier:**
The namespace-store dropdown and backing-store dropdown component does not update immediately when the store is created through the "Create new NamespaceStore" and  "Create new BackingStore" modal respectively.

**After:**
Now they get updated and are working correctly.

2021-04-16 00:38 UTC, vbnrh commented
We don't have to modify the global state to achieve this. Can you try making the changes more self-contained within the dropdown itself ? 
Tip: you can try using useK8sWatchResource rather than useK8sGet for polling  the resource

2021-04-16 00:38 UTC, vbnrh requested changes
We don't have to modify the global state to achieve this. Can you try making the changes more self-contained within the dropdown itself ?
Tip: you can try using useK8sWatchResource rather than useK8sGet for polling the resource

2021-04-19 12:41 UTC, vbnrh commented
Please add screenshots. even better if you could add a recording

2021-04-23 05:29 UTC, afreen23 commented
/ok-to-test

2021-04-26 11:34 UTC, GowthamShanmugam commented on frontend/packages/ceph-storage-plugin/src/components/create-backingstore-page/create-bs.tsx
> +  }
you can move this inside useEffect so you don't need extra const isPhaseDefined

const backingStoreObject:  BackingStoreKind[] = useDeepCompareMemoize(newNbsObj, true);

```
React.useEffect(() => {
  if(isSubmit && !isPage){
   if(backingStoreObject && backingStoreObject?.status?.phase ===  'Ready')
      close()
  else if (backingStoreObject && backingStoreObject?.status?.phase ===  'Failed')
    // doSomething
  else:
      <EmptyState>
          <EmptyStateIcon icon={LoadingComponent} />
        </EmptyState>
 }
}, [backingStoreObject, isSubmit, newNbsLoaded, newNbsErr ]);
```

2021-04-26 11:34 UTC, GowthamShanmugam commented on frontend/packages/ceph-storage-plugin/src/components/create-backingstore-page/create-bs.tsx
> +        </EmptyState>
```suggestion
     
        
```

2021-04-26 11:34 UTC, GowthamShanmugam commented on frontend/packages/ceph-storage-plugin/src/components/namespace-store/namespace-store-dropdown.tsx
> +  const [nnsList, setNnsList] = React.useState([]);
it will be more clear use someother names instead nnsList, setNnsList

2021-04-26 11:34 UTC, GowthamShanmugam commented on frontend/packages/ceph-storage-plugin/src/components/namespace-store/namespace-store-dropdown.tsx
> +  const [dropdownItems, setDropdownItems] = React.useState([]);
```suggestion
  const [dropdownItems, setDropdownItems] = React.useState<JSX.Element[]>([]);
```

2021-04-26 11:34 UTC, GowthamShanmugam commented on frontend/packages/ceph-storage-plugin/src/components/namespace-store/namespace-store-form.tsx
> +
Sam issue what i saw in create-bs.tsx

1. When I use the already existing backing store name, the modal won't throw any error. Line 98 will assume a new pool is created and close the modal. User may assume this backing store is created with new inputs.

2. Any failure that happened while creating a backing store and backing store is not created, this page will keep Invoke LoadingComponent. 
    * Resolve this by onError parameter of handlePromise or errorMessage  (Either you need to display error message or invoke close :) )

3. If the backing store is created but if it is not ready (e.g ReconcileFailed), the module will close without any intimation to the user.

2021-04-26 11:34 UTC, GowthamShanmugam commented on frontend/packages/ceph-storage-plugin/src/components/namespace-store/namespace-store-form.tsx
> +
for more info please check 
https://github.com/openshift/console/blob/master/frontend/packages/ceph-storage-plugin/src/components/modals/block-pool-modal/create-block-pool-modal.tsx#L90

https://github.com/openshift/console/blob/master/frontend/packages/ceph-storage-plugin/src/components/modals/block-pool-modal/create-block-pool-modal.tsx#L66

2021-04-26 11:35 UTC, GowthamShanmugam commented on frontend/packages/ceph-storage-plugin/src/components/create-backingstore-page/create-bs.tsx
> +  }
https://github.com/openshift/console/blob/master/frontend/packages/ceph-storage-plugin/src/components/modals/block-pool-modal/create-block-pool-modal.tsx#L66

2021-04-30 16:51 UTC, SanjalKatiyar commented on frontend/packages/ceph-storage-plugin/src/components/create-backingstore-page/backing-store-dropdown.tsx
> +  }, [backingStoresData, isLoaded, LoadErr]);
I have added it in case `backingStoresData` is ever `undefined` ... that case `noobaBackingStores` will be `[]`

2021-05-01 12:51 UTC, GowthamShanmugam commented
/lgtm

2021-05-01 12:53 UTC, GowthamShanmugam approved these changes

2021-05-04 19:46 UTC, afreen23 requested changes

2021-05-04 19:46 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/components/create-backingstore-page/backing-store-dropdown.tsx
> +  const nooBaaBsResource = {
Move it to `resource.ts`
```suggestion
  const backingStoreResource = {
```

2021-05-04 19:46 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/components/create-backingstore-page/backing-store-dropdown.tsx
> +  const [backingStoresData, , LoadErr] = useK8sWatchResource<BackingStoreKind[]>(nooBaaBsResource);
```suggestion
  const [bsData, , bsLoading, bsLoadError] = useK8sWatchResource<BackingStoreKind[]>(nooBaaBsResource);
```

2021-05-04 19:46 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/components/namespace-store/namespace-store-dropdown.tsx
> +    isList: true,
move it to resource.ts
```suggestion  
  const namespaceStoreResource = {
    kind: referenceForModel(NooBaaNamespaceStoreModel),
    name: null,
    isList: true,
```

2021-05-04 19:46 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/components/namespace-store/namespace-store-dropdown.tsx
> +    nooBaaNsResource,
We name variables in camel case - `nsLoadError`

2021-05-04 19:46 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/components/namespace-store/namespace-store-dropdown.tsx
> +      {LoadErr && (
We use came case for naming variables.

2021-05-05 18:03 UTC, SanjalKatiyar commented
/test e2e-gcp-console

2021-05-06 04:44 UTC, SanjalKatiyar commented
/test e2e-gcp-console

2021-05-06 08:48 UTC, afreen23 approved these changes
/lgtm

2021-05-06 13:41 UTC, SanjalKatiyar commented
/test e2e-gcp-console

2021-05-06 14:57 UTC, SanjalKatiyar commented
/test e2e-gcp-console

2021-05-07 03:41 UTC, merged