Bug 1949889: Enables text input for volume count in backingstore page
openshift/console pull request #8748
Opened 2021-04-22 15:02 UTC by vbnrh

Signed-off-by: Vineet Badrinath <vbadrina@redhat.com>

2021-04-22 15:04 UTC, vbnrh commented
/bugzilla refresh

2021-04-26 05:15 UTC, bipuladh requested changes

2021-04-26 05:15 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/src/components/noobaa-provider-endpoints/pvc-endpoint-type.tsx
>            />
Use `NumberInput` PF component.

2021-05-18 06:01 UTC, vbnrh commented on frontend/packages/ceph-storage-plugin/src/components/noobaa-provider-endpoints/pvc-endpoint-type.tsx
>            />
done

2021-05-18 06:01 UTC, vbnrh commented on frontend/packages/ceph-storage-plugin/src/components/noobaa-provider-endpoints/pvc-endpoint-type.tsx
>            />
good call

2021-05-18 09:08 UTC, bipuladh requested changes

2021-05-18 09:08 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/src/components/noobaa-provider-endpoints/pvc-endpoint-type.tsx
> +          plusBtnAriaLabel="plus"
```suggestion
          plusBtnAriaLabel="plus"
          min={1}
```

2021-05-18 09:53 UTC, vbnrh commented on frontend/packages/ceph-storage-plugin/src/components/noobaa-provider-endpoints/pvc-endpoint-type.tsx
> +          plusBtnAriaLabel="plus"
done

2021-05-18 11:44 UTC, bipuladh commented
Tested working as expected.
/lgtm

2021-05-19 07:25 UTC, bipuladh approved these changes
/lgtm

2021-05-19 19:17 UTC, merged