adds devfile provider for dev catalog
openshift/console pull request #8812
Opened 2021-04-28 10:37 UTC by invincibleJai

**Fixes**: 
https://issues.redhat.com/browse/ODC-5729

**Analysis / Root cause**: 

**Solution Description**: 
adds devfile provider for dev catalog so that user can see type `devfiles` in the catalog and create one

**Screen shots / Gifs for design review**: 
@openshift/team-devconsole-ux @lwrigh 

![image](https://user-images.githubusercontent.com/5129024/116390172-679fe100-a83b-11eb-86e1-1d3017d13e2d.png)

![image](https://user-images.githubusercontent.com/5129024/116390257-7be3de00-a83b-11eb-9114-7bc1be5055e9.png)

![image](https://user-images.githubusercontent.com/5129024/116390311-87cfa000-a83b-11eb-9e1c-9d999dedffaa.png)

![image](https://user-images.githubusercontent.com/5129024/116390421-a0d85100-a83b-11eb-93d4-8e71379b2418.png)

**Review commit**: https://github.com/openshift/console/commit/9c1b913b9d2bc9ab74f3d02497dc8ff29cab0f9a

**Depends on**:  https://github.com/openshift/console/pull/8794

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2021-04-28 10:41 UTC, invincibleJai commented
/cc @rottencandy 
/assign @rohitkrai03

2021-04-28 10:41 UTC, invincibleJai commented
/hold 

adding hold as depends on https://github.com/openshift/console/pull/8794

2021-04-28 12:49 UTC, lwrigh commented
This looks good to me!

2021-04-28 15:42 UTC, rohitkrai03 requested changes

2021-04-28 15:42 UTC, rohitkrai03 commented on frontend/packages/dev-console/src/components/catalog/providers/useDevfile.tsx
> +      .then(setDevfileSamples)
Should check if component is still mounted before setting state.

2021-04-28 17:09 UTC, beaumorley commented
Hi @invincibleJai. One question. On the Developer Catalog there is a (?) next to Type. This is a popover with a definition of all the types. Do you know if this issue includes adding Devfiles to this? I did not see it in the Epic.

2021-04-29 05:33 UTC, invincibleJai commented
> Hi @invincibleJai. One question. On the Developer Catalog there is a (?) next to Type. This is a popover with a definition of all the types. Do you know if this issue includes adding Devfiles to this? I did not see it in the Epic.

yes @beaumorley, have handled it as part of the same PR. If you think there is a need to change the text for devFile LMK or can log a ticket to update it.

![image](https://user-images.githubusercontent.com/5129024/116506226-7b4e5480-a8da-11eb-9492-6ff51320846a.png)

2021-04-30 20:02 UTC, christianvogt commented
We had a discussion on this scenario in the devfile cabal. Please connect with @rohitkrai03. As the scenario for changing the git url and using the sample as a stack wasn't considered by the devfile team.

2021-05-12 12:46 UTC, rohitkrai03 commented
/hold cancel

2021-05-13 01:15 UTC, merged