Make multus public network optional
openshift/console pull request #8834
Opened 2021-05-03 05:19 UTC by bipuladh

Allow user to select NADs from default Namespace
Screeshots:
1) Allow User to move forward after only selecting Cluster Network
![Screenshot from 2021-05-03 10-09-19](https://user-images.githubusercontent.com/54092533/116841769-cc6e8900-abf7-11eb-80b2-c4f74825ba1e.png)
2)Disable if none is selected
![Screenshot from 2021-05-03 10-09-28](https://user-images.githubusercontent.com/54092533/116843340-48b79b00-abfd-11eb-8a7c-84c494445afb.png)
cc @leseb

2021-05-04 19:08 UTC, afreen23 requested changes

2021-05-04 19:08 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/components/ocs-install/install-wizard/configure.tsx
>      namespace: 'openshift-storage',
USe CEPH_STORAGE_NAMESPACE

2021-05-04 19:08 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json
> +  "To use Multus networking either the public or cluster Network Attachment Definition must be selected.": "To use Multus networking either the public or cluster Network Attachment Definition must be
```suggestion
  "A public or cluster network attachment definition must be selected for multus networking."
```

2021-05-05 04:39 UTC, bipuladh commented on frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard-steps/configure.tsx
> +      payload: `${getNamespace(resource)}/${getName(resource)}`,
I don't want to refactor actions.

2021-05-05 05:04 UTC, afreen23 requested changes

2021-05-05 05:04 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/utils/common-ocs-install-el.tsx
> +          'ceph-storage-plugin~To use Multus networking either the public or cluster Network Attachment Definition must be selected.',
We need to change the title -  `Public Network Attachment Definition cannot be empty`.

2021-05-10 06:03 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/components/ocs-install/internal-mode/install-wizard-steps/configure.tsx
> +      payload: `${getNamespace(resource)}/${getName(resource)}`,
I am okay with this in another PR as well.

2021-05-10 06:15 UTC, afreen23 approved these changes
/lgtm

2021-05-10 06:23 UTC, afreen23 requested changes
/lgtm cancel
If we are using title then lets enhance the description more with details.

2021-05-10 06:24 UTC, afreen23 requested changes

2021-05-10 06:24 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/utils/common-ocs-install-el.tsx
> +          'ceph-storage-plugin~A public or cluster network attachment definition must be selected.',
```suggestion
          'ceph-storage-plugin~A public or cluster network attachment definition must be selected to use multus netowrking.',
```

2021-05-10 06:24 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/utils/common-ocs-install-el.tsx
> +          'ceph-storage-plugin~A public or cluster network attachment definition must be selected.',
Lets enhance the description if we need title, otherwise omit the title.

2021-05-10 11:57 UTC, afreen23 approved these changes
/lgtm

2021-05-10 15:05 UTC, merged

2021-05-11 09:41 UTC, bipuladh commented
/bugzilla refresh