give feedback when modal submit is clicked
openshift/console pull request #8855
Opened 2021-05-04 15:29 UTC by debsmita1

**Fixes:**
https://issues.redhat.com/browse/ODC-5799

**Root analysis:**
The submit status information is not sent to the modal submit footer

**Solution description:**
The submit status information is sent to the `submitDisabled` & `inProgress` props of the ModalSubmitFooter

**GIF:**
![modal-submit](https://user-images.githubusercontent.com/22490998/117028673-8f031c00-ad1b-11eb-93f8-90d5bd956b3b.gif)

**Browser conformance:**
- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

2021-05-04 15:42 UTC, debsmita1 commented
/assign @christianvogt

2021-05-04 16:15 UTC, rohitkrai03 requested changes

2021-05-04 16:15 UTC, rohitkrai03 commented on frontend/packages/console-shared/src/components/modals/DeleteResourceModal.tsx
> +    actions.setStatus({ isSubmitting: true });
This is just a hack to make this work and not a good way to set submitting status. Formik handles submitting status for you automatically if the submit handler is async and returns a promise. You can read more about why this doesn't work right now in this [code comment](https://github.com/formium/formik/blob/master/packages/formik/src/Formik.tsx#L748)

2021-05-04 16:15 UTC, rohitkrai03 commented on frontend/packages/console-shared/src/components/modals/DeleteResourceModal.tsx
> +        inProgress={status?.isSubmitting || isSubmitting}
This change won't be needed if formik's status handling works correctly.

2021-05-04 16:40 UTC, christianvogt commented
gif looks good!

2021-05-10 18:40 UTC, rohitkrai03 requested changes

2021-05-10 18:40 UTC, rohitkrai03 commented on frontend/packages/console-shared/src/components/modals/DeleteResourceModal.tsx
>            actions.setSubmitting(false);
Same here.

2021-05-11 14:36 UTC, debsmita1 commented
/kind bug

2021-05-11 14:53 UTC, rohitkrai03 requested changes
In progress loading animation is shown but the submit button is not disabled. Can you also add the logic to disable the submit button while form is submitting?

2021-05-11 19:10 UTC, rohitkrai03 approved these changes
/approve
/lgtm

2021-05-11 22:55 UTC, merged