Fix tooltip on pipelineRunCount and TaskRunDuration graphs based of P…
openshift/console pull request #8868
Opened 2021-05-07 07:25 UTC by karthikjeeyar

**Fixes**: 

https://issues.redhat.com/browse/ODC-5763

**Analysis / Root cause**: 

Follow the PF guidelines and include the design change outlined in the JIRA ticket.

**Solution Description**: 

1.  Included the `PipelineRuns: ` label for the second row in the pipeline Run count graph.
2.  Included the `chartLegendTooltip` to show all the data points in a single tooltip based on the cursor movement in the chart.

**Screen shots / Gifs for design review**: 

1. Pipeline Run count graph:

![image](https://user-images.githubusercontent.com/9964343/117412276-39548c80-af32-11eb-81b9-436dd4798d97.png)

2. TaskRun Duration graph:
![image](https://user-images.githubusercontent.com/9964343/117412475-7587ed00-af32-11eb-88cb-5ca1830be8c7.png)

![metrics-tooltips](https://user-images.githubusercontent.com/9964343/117413186-4920a080-af33-11eb-9b2c-fda1e7f89e65.gif)

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

/kind bug
cc: @bgliwa01 @andrewballantyne

2021-05-07 07:27 UTC, karthikjeeyar commented on frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineRunCount.tsx
> +  React.useEffect(() => {
to avoid react warnings for bad setState calls, used useEffect in all chart components.

2021-05-07 08:57 UTC, karthikjeeyar commented
/retest

2021-05-17 18:54 UTC, andrewballantyne requested changes
Think we need to wrap or truncate or something the name:
![image](https://user-images.githubusercontent.com/8126518/118541543-d035fb80-b71f-11eb-95fa-fd04891fa899.png)

2021-05-17 18:54 UTC, andrewballantyne commented on frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineRunCount.tsx
> +      onInitialLoad &&
Merge the two checks?

2021-05-17 18:54 UTC, andrewballantyne commented on frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineRunDurationGraph.tsx
> +      onInitialLoad &&
Same here

2021-05-17 18:54 UTC, andrewballantyne commented on frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineRunTaskRunGraph.tsx
> +      onInitialLoad &&
Same here

2021-05-17 18:54 UTC, andrewballantyne commented on frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineSuccessRatioDonut.tsx
> +      onInitialLoad &&
Same here

2021-05-18 10:54 UTC, karthikjeeyar commented
Truncating the pipelinerun name now.
![image](https://user-images.githubusercontent.com/9964343/118639289-5c662280-b7f5-11eb-8c59-da8808d345f1.png)

2021-05-18 14:07 UTC, andrewballantyne commented on frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/PipelineRunTaskRunGraph.tsx
> +import { CursorVoronoiContainer } from '@console/internal/components/graphs';
nit, sort imports.

2021-05-18 20:04 UTC, debsmita1 commented
tried this out and it works fine
/lgtm

2021-05-18 22:18 UTC, merged