Fix pipelinerun and taskrun log snippet message for timeout issue
openshift/console pull request #8907
Opened 2021-05-12 14:34 UTC by karthikjeeyar

**Fixes**: 

https://issues.redhat.com/browse/ODC-5702

**Analysis / Root cause**: 

When a pipelinerun/taskrun fails due to a timeout issue, then the reason for failure is not shown in the pipelinerun/taskrun details page

**Solution Description**: 

Show the message for the know reasons like PipelineRunTimeout and TaskRunTimeout
known reasons are mentioned in the docs:
https://tekton.dev/vault/pipelines-v0.21.0/pipelineruns/#monitoring-execution-status
https://tekton.dev/vault/pipelines-v0.21.0/taskruns/#monitoring-execution-status

**Screen shots / Gifs for design review**: 

**PipelineRun Details page:**
Before fix:
![image](https://user-images.githubusercontent.com/9964343/117991797-02301200-b35c-11eb-9cba-449a17c76803.png)
After fix:
![image](https://user-images.githubusercontent.com/9964343/117991851-0e1bd400-b35c-11eb-871b-5dfa3aab825c.png)

**Taskruns Details page**
![image](https://user-images.githubusercontent.com/9964343/117992176-563af680-b35c-11eb-9da1-b0f054711868.png)

**Unit test coverage report**: 

PipelineRunLogSnippet test
```
✓ should return a Log message for PLR with PipelineRunTimeout reason
```
  TaskRunLogSnippet test
  ```
    ✓ should return null for successful TaskRun (2ms)
    ✓ should return a Log message for failed TaskRun with task container (1ms)
    ✓ should return a Log message for TaskRun with TaskRunTimeout reason
    ✓ should return a static message (1ms)
   ```

**Test setup:**

Create the following resources:
**pipeline:**
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: new-pipeline
spec:
  tasks:
    - name: kn
      params:
        - name: kn-image
          value: >-
            registry.redhat.io/openshift-serverless-1/client-kn-rhel8@sha256:efb51d4a337566ca8532073cd598cc2cfbbec260f037ce4de19d4c67ee411358
        - name: ARGS
          value:
            - help
      taskRef:
        kind: ClusterTask
        name: kn
```
**PipelineRun:**
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: new-pipelinerun-
  labels:
    tekton.dev/pipeline: new-pipeline
spec:
  pipelineRef:
    name: new-pipeline
  serviceAccountName: pipeline
  timeout: 4s
 ```

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

/kind bug
cc: @andrewballantyne @VeereshAradhya

2021-05-17 15:17 UTC, andrewballantyne requested changes
Runs good, a few small things we can improve / help you merge (hopefully it actually breaks the tests when it tries to merge)

2021-05-18 08:49 UTC, karthikjeeyar commented on frontend/packages/pipelines-plugin/src/test-data/pipeline-data.ts
> +        spec: {
The other(spec) structure group is to maintain `Pipeline`'s spec,  so here in this `pipelineRun` I have reference it inside status.pipelineSpec now.

2021-05-18 08:50 UTC, karthikjeeyar commented on frontend/packages/pipelines-plugin/src/components/taskruns/logs/__tests__/taskRunLogSnippet.spec.ts
> +describe('TaskRunLogSnippet test', () => {
Added in both the tests.

2021-05-18 14:00 UTC, andrewballantyne commented on frontend/packages/pipelines-plugin/src/test-data/pipeline-data.ts
> +        spec: {
Oops! You are so right. Apologizes for that!

2021-05-18 14:05 UTC, andrewballantyne approved these changes
/lgtm

2021-05-18 14:05 UTC, andrewballantyne commented
/retest

2021-05-18 22:18 UTC, merged