Fix isSubmitting logic of formik forms
openshift/console pull request #8984
Opened 2021-05-19 18:39 UTC by rohitkrai03

**Fixes**: https://issues.redhat.com/browse/ODC-3617

**Analysis / Root cause**: In our use of Formik we are always manually calling actions.setSubmitting(true | false) for our async submit handlers. But this is not needed because formik handles that logic internally if a promise is returned from the submit handler.

**Solution Description**: Cleanup the use of `setSubmitting` to manually handle the submitting state.

**Screen shots / Gifs for design review**: No design changes.

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [x] Edge

2021-05-19 18:56 UTC, rohitkrai03 commented
/cc @invincibleJai @andrewballantyne

2021-05-19 18:58 UTC, andrewballantyne commented
Did we not want to wait for 4.9 for this? 🤔

2021-05-19 19:10 UTC, rohitkrai03 commented
I thought we were doing our tech debt stories in 4.8 only.

2021-05-19 19:12 UTC, andrewballantyne commented
Epic is marked 4.9 and we haven't pointed any yet.

2021-05-19 19:12 UTC, andrewballantyne commented
Here is the current objectives we are working on [ODC-5828 (comment)](https://issues.redhat.com/browse/ODC-5829?focusedCommentId=16164629&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16164629) @rohitkrai03

2021-05-19 19:18 UTC, rohitkrai03 commented
> Here is the current objectives we are working on [ODC-5828 (comment)](https://issues.redhat.com/browse/ODC-5829?focusedCommentId=16164629&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16164629) @rohitkrai03

Yeah, well I don't think this particular ticket needed anymore explanations, information or clarifications. We've had several conversations around trying to complete the tech debt epic in 4.8 time frame but I am perfectly fine to push this to 4.9 if we decide otherwise.

2021-05-19 19:24 UTC, andrewballantyne commented
> > Here is the current objectives we are working on [ODC-5828 (comment)](https://issues.redhat.com/browse/ODC-5829?focusedCommentId=16164629&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16164629) @rohitkrai03
> 
> Yeah, well I don't think this particular ticket needed anymore explanations, information or clarifications. We've had several [conversations](https://coreos.slack.com/archives/CHGU4P8UU/p1621256269351900) around trying to complete the tech debt epic in 4.8 time frame but I am perfectly fine to push this to 4.9 if we decide otherwise.

I'm not against seeing this in 4.8 (I also don't really have a say in what we do at a large like this)... but it's in the wrong Epic for that. It needs to be a task or somehow find another Epic targeted for 4.8. Would send the wrong image if it stays in the 4.9 Epic and is merged in 4.8.

2021-05-19 19:31 UTC, rohitkrai03 commented
> > > Here is the current objectives we are working on [ODC-5828 (comment)](https://issues.redhat.com/browse/ODC-5829?focusedCommentId=16164629&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16164629) @rohitkrai03
> > 
> > 
> > Yeah, well I don't think this particular ticket needed anymore explanations, information or clarifications. We've had several [conversations](https://coreos.slack.com/archives/CHGU4P8UU/p1621256269351900) around trying to complete the tech debt epic in 4.8 time frame but I am perfectly fine to push this to 4.9 if we decide otherwise.
> 
> I'm not against seeing this in 4.8 (I also don't really have a say in what we do at a large like this)... but it's in the wrong Epic for that. It needs to be a task or somehow find another Epic targeted for 4.8. Would send the wrong image if it stays in the 4.9 Epic and is merged in 4.8.

I agree that the ticket should be in an epic targeted for 4.8 but my assumption was that we'll change the target of this epic from 4.9 to 4.8 as a conclusion to the earlier conversations. I guess our goal for tomorrow's meeting should be to decide on that.

2021-06-04 14:17 UTC, debsmita1 requested changes

2021-06-04 14:17 UTC, debsmita1 commented on frontend/packages/knative-plugin/src/components/traffic-splitting/TrafficSplitting.tsx
>          action.setSubmitting(false);
missed removing this ?

2021-06-04 14:17 UTC, debsmita1 commented on frontend/packages/dev-console/src/components/hpa/HPAFormikForm.tsx
>      helpers.setSubmitting(true);
any reason for not removing this ?

2021-06-04 14:18 UTC, debsmita1 commented
missed few instances in the below files:
CloudShellDeveloperSetup.tsx
ProjectAccess.tsx

2021-06-07 08:03 UTC, rohitkrai03 commented on frontend/packages/knative-plugin/src/components/traffic-splitting/TrafficSplitting.tsx
>          action.setSubmitting(false);
Done.

2021-06-07 08:04 UTC, rohitkrai03 commented on frontend/packages/dev-console/src/components/hpa/HPAFormikForm.tsx
>      helpers.setSubmitting(true);
Missed it. Done.

2021-06-07 10:19 UTC, invincibleJai commented
/lgtm

/label qe-approved
Tested the PR with cluster bot. Everything works as expected.

/label px-approved
added on behalf of px as being a tech debt epic it's not needed

/label docs-approved
added on behalf of docs team as being a tech debt epic it's not needed.

2021-06-07 12:20 UTC, merged

2021-08-03 16:21 UTC, andrewballantyne commented on frontend/packages/dev-console/src/components/hpa/HPAFormikForm.tsx
> +      return Promise.reject();
This appears to have caused https://issues.redhat.com/browse/ODC-6188