Bug 1935087: Align Arbiter text with the new behaviour introduced by BZ #1928319
openshift/console pull request #9019
Opened 2021-05-24 10:41 UTC by SanjalKatiyar

**Earlier:**
![Screenshot_20210517_193909](https://user-images.githubusercontent.com/39404641/119335919-97ab9a00-bcaa-11eb-83f5-1c19105cddf9.png)

**After:**
![Screenshot from 2021-05-24 16-03-51](https://user-images.githubusercontent.com/39404641/119335950-a003d500-bcaa-11eb-92f9-ee429d9d9a9d.png)

2021-05-24 10:50 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json
> +  "Selected nodes are based on the selected storage class. Minimum 4 nodes in 2 different zones will be selected with a recommended requirement of 14 CPU and 34 GiB RAM per node.": "Selected nodes ar
```suggestion
  "Selected nodes are based on the selected storage class. Minimum 4 nodes in 2 different zones will be selected with a recommended requirement of 14 CPU and 34 GiB RAM per node.": "Selected nodes are based on the selected storage class and the arbiter configuration requirements."
  thoughts ??

2021-05-24 11:01 UTC, SanjalKatiyar commented on frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json
> +  "Selected nodes are based on the selected storage class. Minimum 4 nodes in 2 different zones will be selected with a recommended requirement of 14 CPU and 34 GiB RAM per node.": "Selected nodes ar
Looks good, let me confirm it with UX.

2021-05-24 11:14 UTC, afreen23 commented
/ok-to-test

2021-05-25 17:49 UTC, afreen23 approved these changes
/lgtm

2021-06-01 09:42 UTC, afreen23 requested changes

2021-06-01 09:42 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/constants/tooltips.ts
> +    { storageClassName: scName },
If you are getting missing i18n key errors in console logs then use `<Trans/>`
```suggestion
    'ceph-storage-plugin~Selected nodes are based on the storage class <em>{{storageClassName}}</em> and fulfill the stretch cluster requirements with a recommended requirement of 14 CPU and 34 GiB RAM per node.',
    { storageClassName: scName },
```

2021-06-01 09:42 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/constants/tooltips.ts
> +    { storageClassName: scName },
Same here, make storage class name emphasized

2021-06-01 21:10 UTC, afreen23 approved these changes
/lgtm

2021-06-02 02:55 UTC, merged