Add Codeready Workspaces feature files.
openshift/console pull request #9113
Opened 2021-06-02 09:35 UTC by rhopp

Signed-off-by: Radim Hopp <rhopp@redhat.com>

2021-06-02 09:35 UTC, rhopp commented
@makambalaji  PTAL ;-)

2021-06-07 08:12 UTC, makambalaji requested changes
Unable to execute this scenarios on the cluster, Please add if any other setup is required

2021-06-07 08:12 UTC, makambalaji commented on frontend/packages/dev-console/integration-tests/features/codeready-workspaces/crw-basic.feature
> +        Then Codeready Workspace entry is present
Logged in as basic user 
Unable to view application launcher itself
![image](https://user-images.githubusercontent.com/61005404/120981952-d014a300-c795-11eb-9671-07c0bf931204.png)
Do we need any other actions to perform before this scenario?

2021-06-07 08:22 UTC, rhopp commented on frontend/packages/dev-console/integration-tests/features/codeready-workspaces/crw-basic.feature
> +        Then Codeready Workspace entry is present
@makambalaji Yes. It's defined in "Background section" - `Given Red Hat CodeReady Workspaces operator is installed on the cluster`
If you want to try it yourself, you need to install CRW operator from OperatorHub and then create CheCluster CR (default is OK). Then wait fo CRW instance to be properly installed (can take few minutes).

2021-06-07 08:23 UTC, rhopp commented on frontend/packages/dev-console/integration-tests/features/codeready-workspaces/crw-basic.feature
> +Feature: Basic Codeready Workspaces usage
Will do.

2021-06-07 09:22 UTC, makambalaji commented on frontend/packages/dev-console/integration-tests/features/codeready-workspaces/crw-basic.feature
> +        Then Codeready Workspace entry is present
yeah, I installed and logged in with 2 different users

2021-06-07 13:09 UTC, makambalaji requested changes
Please add @crw tag, Remaining everything looks good to me

2021-06-07 14:17 UTC, makambalaji commented
/lgtm
/approve

2021-06-07 19:26 UTC, merged

2021-06-08 05:08 UTC, crw commented on frontend/packages/dev-console/integration-tests/features/codeready-workspaces/crw-basic.feature
> +Feature: Basic Codeready Workspaces usage
To be clear, that's my github user name you're mentioning.

2021-06-08 05:09 UTC, crw commented on frontend/packages/dev-console/integration-tests/features/codeready-workspaces/open-app-in-crw.feature
> +Feature: Opening Codeready Workspaces from Topology view for existing app
You know you can use backticks like `@crw` right?