No color change on Add card hover
openshift/console pull request #9159
Opened 2021-06-07 12:57 UTC by abhinandan13jan

# Addresses
https://issues.redhat.com/browse/ODC-5887

# Issue
Add card items change color on hover, active 

# Screenshot
![addcardhover (1)](https://user-images.githubusercontent.com/24852534/121020370-f1898500-c7bd-11eb-80bb-47fe9ac44f91.gif)

# Tests
No change

# Briwser conformance
Chrome

2021-06-07 13:12 UTC, jerolimov commented
/cc @jerolimov @gdoyle1 

Gina, FYI

2021-06-07 13:37 UTC, gdoyle1 commented
@jerolimov based on this PR https://github.com/patternfly/patternfly/pull/4099#issuecomment-848274068 , the getting started card styling will also be updated to match this once PF puts out the next release.

2021-06-07 13:37 UTC, gdoyle1 approved these changes

2021-06-07 18:35 UTC, jerolimov requested changes
see above

2021-06-11 11:28 UTC, jerolimov approved these changes
Thanks. Works now as expected also for the getting started section.

![Peek 2021-06-11 13-27](https://user-images.githubusercontent.com/139310/121679662-e2098500-cab8-11eb-921a-116939d5015f.gif)

/lgtm
/approve

2021-06-11 13:05 UTC, jerolimov commented
/retest

2021-06-12 12:35 UTC, merged