Add git URL help text so that other sections doesn't jump down
openshift/console pull request #9290
Opened 2021-06-17 13:59 UTC by jerolimov

**Fixes**: 
https://issues.redhat.com/browse/ODC-5955
https://issues.redhat.com/browse/ODC-6016

**Analysis / Root cause**: 
With 4.8 we automatically focus the Git URL (the first input field) when the user imports from Git, Dockerfile or Devfile.

When the user clicks then on "Try sample" or "Show advanced Git options" the url field losts his focus. The `onBlur` method then marks the input field as `touched` (in formik) and show an error if the url field is empty.

This "Required!" error was shown faster then the mentioned buttons handles their event. And because the "Required!" was added as a new label below the input field all buttons and input fields jumps a little but down and the user click on these buttons is ignored.

A second click works fine. Also if the user first lost the focus of the input field, and then select it again.

**Solution Description**: 
Add a help text to the "Git Repo URL" field. This help text was replaced with the error message when the form field is empty (or invalid).

Also fixed a small flicking because `git.isUrlValidating` was set to false before the validation status was set.

The help text for the different cases are:

1. Repository URL to built and deploy your code from source.
2. Repository URL to built and deploy your code from a Dockerfile.
3. Repository URL to built and deploy your code from a Devfile.

**Screen shots / Gifs for design review**: 
Before:
![Peek 2021-06-17 15-56](https://user-images.githubusercontent.com/139310/122410907-9eb18980-cf84-11eb-919a-936f69783ec0.gif)

After:
![Peek 2021-06-17 15-57](https://user-images.githubusercontent.com/139310/122411134-cbfe3780-cf84-11eb-87da-1b0e10a5475b.gif)

**Unit test coverage report**: 

**Test setup:**
Just added a new help text. Tests not changed

**Browser conformance**: 
- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge

2021-06-17 14:07 UTC, jerolimov commented
/kind bug
/assign @debsmita1

2021-06-18 18:33 UTC, debsmita1 requested changes
Tried out the changes and it looks good. Left a few comments related to the help texts. Will wait for UX to approve the changes

2021-06-18 18:33 UTC, debsmita1 commented on frontend/packages/dev-console/src/components/import/git/GitSection.tsx
> +      return t('devconsole~Repository URL to built and deploy your code from source.');
```suggestion
      return t('devconsole~Repository URL to build and deploy your code from source.');
```

same for the remaining 2 help texts

2021-06-18 18:33 UTC, debsmita1 commented on frontend/packages/dev-console/src/components/import/git/GitSection.tsx
> +      return t('devconsole~No Devfile present, unable to continue');
```suggestion
      return t('devconsole~No Devfile present, unable to continue.');
```

2021-06-21 21:57 UTC, jerolimov commented on frontend/packages/dev-console/src/components/import/git/GitSection.tsx
> +      return t('devconsole~Repository URL to built and deploy your code from source.');
Thanks. Updated.

2021-06-21 21:57 UTC, jerolimov commented on frontend/packages/dev-console/src/components/import/git/GitSection.tsx
> +      return t('devconsole~No Devfile present, unable to continue');
Updated.

2021-06-22 09:20 UTC, jerolimov commented
> Will wait for UX to approve the changes

It is approved by @beaumorley and @parvathyvr in this [slack thread](https://app.slack.com/client/T027F3GAJ/CHC2R6AGG/thread/CHC2R6AGG-1623436371.040500), but maybe one of you both could add a comment to this PR as well. Thanks :)

2021-06-22 12:07 UTC, debsmita1 commented
/lgtm

2021-06-22 18:38 UTC, merged