fix invalid runafter breaking pipeline builder issue
openshift/console pull request #9293
Opened 2021-06-17 19:30 UTC by karthikjeeyar

**Fixes**: 

https://issues.redhat.com/browse/ODC-5991

**Analysis / Root cause**: 

In yaml view, adding an non existent task name as a value to any task's `runafter` field and switching back to pipeline builder view forms an incorrect edge and topology layout fails to find the non existent node in the data model. 

**Solution Description**: 

Filter out the invalid/non-existent node name from runAfter field and also surface the invalid runAfter error to the user so they can correct their mistake by going back to yaml view.

**Screen shots / Gifs for design review**: 

![Invalid_runAfter](https://user-images.githubusercontent.com/9964343/122460513-d265d100-cfcf-11eb-9293-d6ec85b2ddaa.png)

**Unit test coverage report**: 

```
 getEdgesFromNodes
    ✓ should contain correct number of edges based on the runAfters (1ms)
    ✓ should exclude the invalid runAfter names
 ```

**Test setup:**

1. In create pipelines page, switch to pipeline builder
2. Try out `docker-build-and-deploy-pipeline` sample and change the name the `fetch-reposistory` task **or** add any invalid in `build` tasks's runAfter value
3. Switch back to pipeline builder view

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

cc: @bgliwa01 
/assign @andrewballantyne

2021-06-17 20:08 UTC, andrewballantyne requested changes

2021-06-18 02:53 UTC, karthikjeeyar commented on frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-builder/const.ts
> +  INVALID_RUNAFTER = 'invalidRunAfter',
Yes, Agreed. A `Message` and an `Action` is needed here to proceed with submission of the pipeline builder, Until this error is fixed the submit button stays disabled.

2021-06-23 12:27 UTC, karthikjeeyar commented
@rohitkrai03 @andrewballantyne 
In this [commit](4a27196), I have added the form validation before switching to form view using `sanitizeTo` function in syncedEditorField. I have used the existing pipeline form schema to validate the errors. There could be some form errors which may not be necessary for yaml content eg `Must define at least one task` is a form validation error, so we should not show alert in this case, so we need to have a separate yaml schema(not as strict as form view) cc: @nemesis09 


![invalid-form-or-invalid-structure](https://user-images.githubusercontent.com/9964343/123094553-a07ac180-d44a-11eb-8307-7689236a5b8b.gif)

2021-06-23 13:48 UTC, nemesis09 commented
> @rohitkrai03 @andrewballantyne
> In this [commit](https://github.com/openshift/console/pull/9293/commits/4a27196ade84de03522998b3230b1712a32fa928), I have added the form validation before switching to form view using `sanitizeTo` function in syncedEditorField. I have used the existing pipeline form schema to validate the errors. There could be some form errors which may not be necessary for yaml content eg `Must define at least one task` is a form validation error, so we should not show alert in this case, so we need to have a separate yaml schema(not as strict as form view) cc: @nemesis09
> 
> ![invalid-form-or-invalid-structure](https://user-images.githubusercontent.com/9964343/123094553-a07ac180-d44a-11eb-8307-7689236a5b8b.gif)

Thanks! @karthikjeeyar 
I agree, we should allow switch with any invalid value that can be corrected in the form. Maybe we can add a separate schema. I believe we have had similar discussion around this issue of invalid yaml switch requiring a second minimalized validation schema.
I have a implemented a similar schema as a part of https://github.com/openshift/console/pull/9282. I am still testing and refining it.
This PR already addresses much of the issue. Maybe I can update my PR to just add the min validation schema.

2021-07-05 13:07 UTC, andrewballantyne commented
/close 

Will be included in #9282

2021-07-05 13:07 UTC, closed without merging