Fix HealthCheckProbeData type
openshift/console pull request #9300
Opened 2021-06-18 18:03 UTC by debsmita1

**Fixes:**
https://issues.redhat.com/browse/ODC-6037

**Solution description:**
Created types:
- `HealthCheckFormProbeData` : which contains properties required to populate the Health checks form
- `HealthCheckProbeData` : which contains properties required to update the k8s resource

**GIF:**
No UI changes

**Unit Tests:**
Update the unit tests

2021-06-18 18:03 UTC, debsmita1 commented
/cc @andrewballantyne 
/cc @jerolimov

2021-06-21 13:26 UTC, andrewballantyne requested changes
Looking good. It's a pity we don't have Deployment and Deployment Config defined more strictly so we can use your type within' 🤔 

One change to do because we really need to be typing both ends of a utility (I think there are other utilities in your files that are not double-ended typed, but we can fix those each time we touch the area rather than make this PR a hunt-and-fix PR -- because that may not have an easy end).

2021-06-21 19:40 UTC, andrewballantyne approved these changes

2021-06-22 15:35 UTC, vikram-raj reviewed
/lgtm

2021-06-22 23:52 UTC, merged