Fix to persist YAML Editor success message
openshift/console pull request #9320
Opened 2021-06-22 18:36 UTC by dtaylor113

**[Recent change](https://github.com/openshift/console/commit/ac18fec217edbf0307067402d961e1a306b619b3#diff-68f9741fec50dc79b50d2de1ece38b9a78fb54154c683c8be276d2a104e62cdbL143) was causing YAML Editor success message to be removed upon re-render:**

https://user-images.githubusercontent.com/12733153/122980263-72bc4c80-d366-11eb-9186-97a6758759fc.mov

**This was causing CI flakes in the CRD extensions test suite.**

2021-06-22 18:38 UTC, jcaianirh approved these changes
lgtm

2021-06-22 18:38 UTC, dtaylor113 commented on frontend/public/components/edit-yaml.jsx
> +            this.handleError(nextProps.error);
handleError sets success to null:
```
handleError(error) {
   this.setState({ errors: _.isEmpty(error) ? null : [error], success: null });
}
```

2021-06-22 18:39 UTC, rhamilto commented
LGTM, but will wait to @jcaianirh to weigh in.

2021-06-22 18:42 UTC, jcaianirh requested changes
@dtaylor113 on second look, this was specifically removed so that fixed errors would be cleared...is there another way to resolve this success message issue? Do you want me to look into it?

2021-06-22 18:44 UTC, dtaylor113 commented
> @dtaylor113 on second look, this was specifically removed so that fixed errors would be cleared...is there another way to resolve this success message issue? Do you want me to look into it?

@jcaianirh  s'maybe :-)  I have another approach if it doesn't pan out, I might need some help -thanks

2021-06-22 19:16 UTC, dtaylor113 commented
> @jcaianirh s'maybe :-) I have another approach if it doesn't pan out, I might need some help -thanks

Hi @jcaianirh, ok latest code is up and it basically passes `state.success` to `handleError`.  The success message persists with this change, but I'm not sure how/if it impacts your other work in this area.  -thanks

2021-06-22 20:16 UTC, dtaylor113 commented
/retest

2021-06-23 18:28 UTC, rhamilto commented
/bugzilla refresh

2021-06-23 20:20 UTC, jcaianirh commented
@dtaylor113 tested this with some error cases, and it looks good. thanks!

2021-06-23 20:20 UTC, jcaianirh approved these changes
lgtm

2021-06-23 20:23 UTC, rhamilto commented
/lgtm

2021-06-23 22:28 UTC, merged

2021-07-28 15:15 UTC, spadgett commented
/cherry-pick release-4.8