Bug 1975696: compareOwnerReference should not accept a reference
openshift/console pull request #9336
Opened 2021-06-24 08:43 UTC by glekner

cc @spadgett @vojtechszocs

2021-06-24 12:05 UTC, spadgett requested changes

2021-06-24 12:05 UTC, spadgett commented on frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/combined-disk.ts
> +                  kind: DataVolumeModel,
Shouldn't this be...?

```suggestion
                  kind: DataVolumeModel.kind,
```

2021-06-24 15:04 UTC, glekner commented
/retest

2021-06-24 15:04 UTC, glekner commented on frontend/packages/kubevirt-plugin/src/k8s/wrapper/vm/combined-disk.ts
> +                  kind: DataVolumeModel,
oops

2021-06-25 16:08 UTC, spadgett approved these changes
/lgtm

2021-06-26 01:41 UTC, merged