Add compression savings to pool list page
openshift/console pull request #9457
Opened 2021-07-09 12:38 UTC by aruniiird

This PR is on top of @GowthamShanmugam 's PR#9252, just adding the compression savings details to the list page.

2021-07-09 14:13 UTC, aruniiird commented
@cloudbehl , @afreen23 , @bipuladh  please take a look...

2021-07-18 19:08 UTC, GowthamShanmugam commented
Please resolve conflicts and share some screen shot for this

2021-07-20 17:03 UTC, afreen23 requested changes

2021-07-22 14:39 UTC, aruniiird commented on frontend/packages/ceph-storage-plugin/src/components/block-pool/block-pool-list-page.tsx
> +    .string;
Right @afreen23 , updated the code...
@GowthamShanmugam , @afreen23 , screenshot attached, please take a look.

![Screenshot from 2021-07-22 20-07-17](https://user-images.githubusercontent.com/895234/126657847-672aaf3b-5eb0-4426-ad8f-5ebaec0fb41b.png)

2021-07-23 08:47 UTC, aruniiird commented
Rebased to latest upstream/master. @afreen23 , @GowthamShanmugam , please take a look

2021-07-23 11:08 UTC, GowthamShanmugam approved these changes

2021-07-23 11:09 UTC, GowthamShanmugam commented
/assign @cloudbehl

2021-07-23 11:10 UTC, GowthamShanmugam commented
Changes are fine, LGTM

2021-07-23 13:12 UTC, afreen23 approved these changes
/lgtm

2021-07-24 10:23 UTC, aruniiird commented
Rebased to latest upstream/master.

2021-07-24 10:49 UTC, GowthamShanmugam approved these changes

2021-07-24 12:51 UTC, afreen23 commented
/ok-to-test

2021-07-24 12:56 UTC, afreen23 approved these changes
/lgtm

2021-07-24 14:50 UTC, merged