Bug 1978421: String updates (typos, etc.)
openshift/console pull request #9480
Opened 2021-07-13 13:20 UTC by SanjalKatiyar

2021-07-13 18:06 UTC, afreen23 requested changes

2021-07-13 18:06 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/locales/en/ceph-storage-plugin.json
> +  "Before we can create a StorageCluster, the local storage operator needs to be installed. When installation is finished come back to OpenShift Container Storage to create a StorageCluster.<1><0>Ins
The name of an operator is a proper noun so we can use title case.
```suggestion
  "Before we can create a StorageCluster, the Local Storage operator needs to be installed. When installation is finished come back to OpenShift Container Storage to create a StorageCluster.<1><0>Install</0></1>": "Before we can create a StorageCluster, the Local Storage operator needs to be installed. When installation is finished come back to OpenShift Container Storage to create a StorageCluster.<1><0>Install</0></1>",
```

2021-07-15 05:21 UTC, SanjalKatiyar commented
/test ceph-storage-plugin

2021-07-19 20:13 UTC, GowthamShanmugam commented
@SanjalKatiyar can you ask QE to verify this

2021-07-20 15:07 UTC, afreen23 commented
/lgtm

2021-07-21 01:54 UTC, merged