Fix to hide rollback action from action menu when there is only 1 helm-release revision
openshift/console pull request #9625
Opened 2021-07-26 11:42 UTC by divyanshiGupta

**Fixes:** https://issues.redhat.com/browse/ODC-6107

**Root Cause:**
Rollback action was shown for a helm-release that has only 1 revision and hence allowed rolling back to the same version.

**Solution:**
Show the rollback action only when there are more than 1 revisons.

**Screen-recording:**

https://user-images.githubusercontent.com/20724543/126983110-3ac7380f-81b3-42fe-a8e3-e8ca64ad7650.mov

https://user-images.githubusercontent.com/20724543/126983141-6381c023-42b8-4761-843e-b2b02baeccb7.mov

/kind bug

2021-07-26 12:35 UTC, rohitkrai03 reviewed
Also need to update helm history page action.

2021-07-26 12:35 UTC, rohitkrai03 commented on frontend/packages/helm-plugin/src/actions/useRollbackAction.tsx
> +        releases = await fetchHelmReleaseHistory(scope.releaseName, scope.namespace);
You don't actually need to fetch history. Helm release has data about revision. If revision is `1` then you don't need to show a rollback option.

2021-07-26 14:56 UTC, rohitkrai03 requested changes

2021-07-26 14:56 UTC, rohitkrai03 commented on frontend/packages/helm-plugin/src/actions/providers.ts
> +      ...(scope.revisions > 1 ? [getHelmRollbackAction(scope, t)] : []),
Probably better to handle this in the `getHelmRollbackAction`.

2021-07-26 14:56 UTC, rohitkrai03 commented on frontend/packages/helm-plugin/src/actions/types.ts
> +  revisions?: string | number;
I think now it makes sense to just send the `HelmRelease` object as context. The provider can pull whatever data it needs out of it.

2021-07-26 14:56 UTC, rohitkrai03 commented on frontend/packages/helm-plugin/src/components/details-page/history/HelmReleaseHistory.tsx
> +    if (parseInt(memoizedObj.metadata.labels.version, 10) > 1) {
We should still show the history list. Just the kebab action should not be shown if it only has one revision.

2021-07-27 16:28 UTC, rohitkrai03 requested changes

2021-07-27 16:28 UTC, rohitkrai03 commented on frontend/packages/helm-plugin/src/actions/types.ts
> +  obj: { [key: string]: any };
```suggestion
  release: HelmRelease;
```

2021-07-27 16:33 UTC, rohitkrai03 requested changes

2021-07-27 16:33 UTC, rohitkrai03 commented on frontend/packages/helm-plugin/src/components/details-page/history/HelmReleaseHistoryRow.tsx
> +    )}
```suggestion
      <TableData className={tableColumnClasses.kebab}>
         {customData?.totalRevisions > 1 && <HelmReleaseHistoryKebab obj={obj} />}
      </TableData>
```

2021-07-29 12:51 UTC, divyanshiGupta commented
/retest

2021-07-29 13:24 UTC, nemesis09 commented
This is weird. The tests pass locally.

2021-07-29 13:41 UTC, nemesis09 commented
/retest

2021-07-29 13:41 UTC, nemesis09 commented
/retest

2021-07-29 17:14 UTC, christianvogt commented on frontend/packages/helm-plugin/src/actions/creators.ts
> +  { obj: { name: releaseName, namespace }, redirect }: HelmActionsScope,
Can we use a better name than `obj`. This represents a helm release? Maybe just call it `release` even if it is a partial.

2021-07-29 17:14 UTC, christianvogt commented on frontend/packages/helm-plugin/src/actions/types.ts
> +type HelmActionObj = { name: string; namespace: string; version?: number | string };
`version` is not optional in the `HelmRelease` why is it optional here? won't a helm release always contain a version?

2021-07-29 17:14 UTC, christianvogt commented on frontend/packages/helm-plugin/src/components/details-page/HelmReleaseDetails.tsx
> +  }, [helmReleaseName, namespace, secret.data]);
`secret.data` isn't used in this effect. Can you explain why this is here and if necessary add a comment in the code.

2021-07-29 20:25 UTC, rohitkrai03 requested changes

2021-07-29 20:25 UTC, rohitkrai03 commented on frontend/packages/helm-plugin/src/components/details-page/HelmReleaseDetails.tsx
> +  }, [helmReleaseName, namespace, secret.data]);
if a new secret is created every time a release is rolled back or upgraded then it would be better to use `secret.data.length`.

2021-07-29 20:56 UTC, rohitkrai03 commented on frontend/packages/helm-plugin/src/components/details-page/HelmReleaseDetails.tsx
> +  }, [helmReleaseName, namespace, secret.data]);
Okay, just tried this locally. It seems there's some issue where the page gets stuck while doing a rollback if we use `secret.data.length`. So its okay as it is now.

2021-07-29 21:01 UTC, rohitkrai03 approved these changes
/lgtm
/approve

Tested it locally. Everything works fine.

2021-07-29 22:02 UTC, merged