[WIP] create component to show bindables resources as trapezoid shape and add support for relationship provider
openshift/console pull request #9698
Opened 2021-08-02 12:28 UTC by invincibleJai

**Fixes**: 
https://issues.redhat.com/browse/ODC-6123

**Solution Description**: 
- create component to show bindables resources as trapezoid shape
- add support for relationship provider

**Screen shots / Gifs for design review**: 

**Unit test coverage report**: 

**Test setup:**

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2021-08-02 13:05 UTC, invincibleJai commented on frontend/packages/dev-console/console-extensions.json
> +      },
This is done only to test resources as bindable so one we have is Kafka connection resouce conributes with Rhoas operator and i add `IntegrationPlatform` once CR for `IntegrationPlatform` is created pls add a label 

```
app.kubernetes.io/component: external-service
```

the actual contribution of resources will happen with https://issues.redhat.com/browse/ODC-6160

2021-08-02 13:19 UTC, invincibleJai commented on frontend/packages/dev-console/src/components/topology/createConnector.ts
> +import { Node } from '@patternfly/react-topology';
do we need this ??

2021-08-04 14:33 UTC, invincibleJai commented
/cc @sahil143 @rohitkrai03

2021-08-04 15:59 UTC, invincibleJai commented
/retest

2021-08-05 03:51 UTC, karthikjeeyar commented
/retest

2021-08-05 05:33 UTC, invincibleJai commented
/retest

2021-08-05 08:38 UTC, wtrocki commented
Verifying

2021-08-05 11:21 UTC, wtrocki approved these changes

2021-08-05 11:39 UTC, wtrocki commented
Verified end to end:

- Creation of the resource 
- Binding
- Credentials injection
- Kafka

2021-08-05 16:28 UTC, sahil143 approved these changes
/lgtm

2021-08-05 16:28 UTC, sahil143 commented
/hold

cc @rohitkrai03

2021-08-06 14:35 UTC, rohitkrai03 requested changes

2021-08-06 14:35 UTC, rohitkrai03 commented on frontend/packages/dev-console/src/components/topology/components/devConsoleComponetFactory.ts
> +import * as React from 'react';
Nit: we follow kebab case for naming non component files generally.

2021-08-06 14:35 UTC, rohitkrai03 commented on frontend/packages/dev-console/src/components/topology/index.ts
> +export { default as getBindableDevConsoleTopologyDataModel } from './dev-console-data-transformer';
Probably better to export utils as named exports instead of default.

2021-08-06 14:35 UTC, rohitkrai03 commented on frontend/packages/rhoas-plugin/src/topology/components/rhoasComponentFactory.ts
> +import BindableNode from '@console/dev-console/src/components/topology/components/BindableNode';
Should this be part of topology itself if its being used in multiple places? We don't want to create a dependency on dev-console. Topology is going to be a core package and contribute utils and components to the SDK.

2021-08-09 04:02 UTC, invincibleJai commented
/retest

2021-08-09 15:55 UTC, rohitkrai03 requested changes

2021-08-09 15:55 UTC, rohitkrai03 commented on frontend/packages/topology/src/components/graph-view/components/nodes/trapezoidNode/BindableNode.tsx
> +// import { getTopologyResourceObject } from '@console/topology/src/utils';
Do we need to keep the comments?

2021-08-09 19:02 UTC, invincibleJai commented on frontend/packages/topology/src/components/graph-view/components/nodes/trapezoidNode/BindableNode.tsx
> +// import { getTopologyResourceObject } from '@console/topology/src/utils';
missed this, have updated

2021-08-10 10:24 UTC, rohitkrai03 approved these changes
/lgtm

Changes looks good to me.

2021-08-10 11:05 UTC, sanketpathak commented
Working as expected
![Screenshot from 2021-08-09 21-07-07](https://user-images.githubusercontent.com/10252230/128855917-ec9815b2-2e60-4f57-9ac3-f226947e2da7.png)

/label qe-approved

2021-08-11 08:58 UTC, sahil143 commented
/label px-approved
/label docs-approved

Since the epic acceptance criteria of [ODC-5722](https://issues.redhat.com/browse/ODC-5722) have not changed and the epic has a px-ack and doc-ack, we approve this on behalf of PX and doc.

2021-08-11 08:58 UTC, sahil143 approved these changes
/lgtm

2021-08-11 11:54 UTC, invincibleJai commented
/hold cancel

2021-08-11 11:54 UTC, invincibleJai commented
/retest

2021-08-12 01:37 UTC, merged