fixes styles for revision and route list
openshift/console pull request #9792
Opened 2021-08-12 06:51 UTC by invincibleJai

**Fixes**: 
https://issues.redhat.com/browse/ODC-6243

**Solution Description**: 
fixes styles for revision and route list

**Screen shots / Gifs for design review**: 

![image](https://user-images.githubusercontent.com/5129024/129150999-23b94237-3ba3-4c82-8837-2312cdf53336.png)

![image](https://user-images.githubusercontent.com/5129024/129151043-95a7fcae-016f-41c8-b82a-888dccca0123.png)

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2021-08-12 15:23 UTC, invincibleJai commented
/kind bug

2021-08-12 16:48 UTC, rohitkrai03 requested changes

2021-08-12 16:48 UTC, rohitkrai03 commented on frontend/packages/knative-plugin/src/components/revisions/revision-table.ts
> +  classNames('pf-m-hidden', 'pf-m-visible-on-sm'), // service
You don't actually need `classNames` if there's no conditional class.

2021-08-18 07:45 UTC, debsmita1 commented
verified the changes
/lgtm

2021-08-18 10:10 UTC, merged