fix: add volume mode selection in storage creation
openshift/console pull request #9971
Opened 2021-09-02 08:57 UTC by shdn-ibm

2021-09-02 10:25 UTC, afreen23 requested changes

2021-09-02 10:25 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/components/create-storage-system/external-storage/ibm-flashsystem/index.tsx
> +          onSelect={onModeSelect}
```suggestion
          onSelect={onModeSelect}
          id="volume-mode-input"
```

2021-09-02 10:25 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/components/create-storage-system/external-storage/ibm-flashsystem/index.tsx
> +      <FormGroup label={t('ceph-storage-plugin~Volume Mode')} fieldId="volmode-input">
```suggestion
      <FormGroup label={t('ceph-storage-plugin~Volume Mode')} fieldId="volume-mode-input">
```

2021-09-02 10:25 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/components/create-storage-system/external-storage/ibm-flashsystem/index.tsx
> +  });
```suggestion
  const volModeOptions = VOLUME_MODES.map((mode) => <SelectOption key={mode} value={mode} />;
```

2021-09-02 10:25 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/components/create-storage-system/external-storage/ibm-flashsystem/index.tsx
> +  const volModeList = ['thick', 'thin'];
```suggestion
  const  VOLUME_MODES = ['thick', 'thin'];
```
Define it outside the component

2021-09-02 10:25 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/components/create-storage-system/external-storage/ibm-flashsystem/index.tsx
> +  const [isOpen, setIsOpen] = React.useState(false);
Move it above with rest of the hooks.
Hoosk should always be at the top

2021-09-02 10:25 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/components/create-storage-system/external-storage/ibm-flashsystem/index.tsx
> +  const onModeSelect = (event, value) => {
Add a space
```suggestion
  const onToggle = () => setIsOpen(!isOpen);
  
  const onModeSelect = (event, value) => {
```

2021-09-02 10:25 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/components/create-storage-system/external-storage/ibm-flashsystem/type.ts
> +  volmode?: string;
```suggestion
  volmode: string;
```
state should not have optional types

2021-09-02 10:27 UTC, afreen23 commented
/ok-to-test

2021-09-03 06:22 UTC, afreen23 requested changes
Just some minors

2021-09-03 06:22 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/components/create-storage-system/external-storage/ibm-flashsystem/index.tsx
> +  const VOLUME_MODES = ['thick', 'thin'];
define this outside the component

2021-09-03 06:22 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/components/create-storage-system/external-storage/ibm-flashsystem/index.tsx
> +          {volModeOptions}
```suggestion
          {VOLUME_MODES.map((mode) => <SelectOption key={mode} value={mode} />)}
```

2021-09-03 06:22 UTC, afreen23 commented on frontend/packages/ceph-storage-plugin/src/components/create-storage-system/external-storage/ibm-flashsystem/index.tsx
> +  const volModeOptions = VOLUME_MODES.map((mode) => <SelectOption key={mode} value={mode} />);
```suggestion
  const volModeOptions = VOLUME_MODES.map((mode) => <SelectOption key={mode} value={mode} />);
```
```suggestion

```

2021-09-03 09:33 UTC, afreen23 approved these changes
/lgtm

2021-09-03 10:27 UTC, SanjalKatiyar commented on frontend/packages/ceph-storage-plugin/src/components/create-storage-system/external-storage/ibm-flashsystem/index.tsx
> +      <FormGroup label={t('ceph-storage-plugin~Volume Mode')} fieldId="volume-mode-input">
```suggestion
      <FormGroup label={t('ceph-storage-plugin~Volume mode')} fieldId="volume-mode-input">
```

2021-09-03 10:32 UTC, SanjalKatiyar commented
/retitle Bug 2000935: add volume mode selection in storage creation

2021-09-03 11:16 UTC, SanjalKatiyar commented
/lgtm

2021-09-03 13:19 UTC, shdn-ibm commented
/retest

2021-09-03 18:23 UTC, merged