Bug 2000590: Warning on topology context menu right click
openshift/console pull request #9975
Opened 2021-09-02 13:01 UTC by yozaam

**Fixes**: 

https://issues.redhat.com/browse/ODC-6105

**Analysis / Root cause**: 

- ref was getting added to `KebabItem` function component

**Solution Description**: 

- wrapped the function component with a React Fragment `<> </>`

**Screen shots / Gifs for design review**: 

No warning is seen anymore
![image](https://user-images.githubusercontent.com/20089340/131847412-de266f5e-dc82-479f-90d6-5cde2280198d.png)

**Unit test coverage report**: 

**Test setup:**

Open topology.
Right click on any workload.

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2021-09-02 13:01 UTC, yozaam commented
/cc @rottencandy

2021-09-03 05:31 UTC, rottencandy approved these changes
/lgtm

2021-09-03 05:49 UTC, yozaam commented
/assign @rohitkrai03 
requesting approval

2021-09-03 09:39 UTC, rohitkrai03 requested changes

2021-09-03 09:39 UTC, rohitkrai03 commented on frontend/packages/topology/src/components/graph-view/components/nodeContextMenu.tsx
> +          <>
Can you add a comment here why we need to wrap this in fragments?

2021-09-03 10:35 UTC, rohitkrai03 approved these changes
/lgtm
/approve

2021-09-03 13:18 UTC, yozaam commented
/retest

2021-09-03 18:23 UTC, merged